### ISSUE TITLE
Formatting not work with relative PATH

### ISSUE THREAD

**Issue by fannheyward** [fannheyward/coc-pyright#100]
Hi, @fannheyward @Maswor 

I also tried the format feature ported from coc-python or vscode-python.

Relative PATH was also possible when setting `python.formatting.blackPath` in "coc-python".

In "coc-pyright", you had to specify it in the absolute PATH.

If you set up "coc-pyright" with a relative PATH, it seems to show only the echo message, not the actual formatting.

## Relative PATH (NG)

```
{
  // ...snip
  "python.formatting.blackPath": "~/.local/bin/black",
  // ...snip
}
```

**DEMO**

![01_coc-pyright-black-path-relative-path](https://user-images.githubusercontent.com/188642/95707805-81117f00-0c95-11eb-99a1-aa3e8e9eaaba.gif)

## Absolute PATH (OK)

```
{
  // ...snip
  "python.formatting.blackPath": "/Users/yaegassy/.local/bin/black",
  // ...snip
}
```

**DEMO**

![02_coc-pyright-black-path-absolute-path](https://user-images.githubusercontent.com/188642/95707824-925a8b80-0c95-11eb-9793-5f13e35b65dc.gif)

_Originally posted by @yaegassy in https://github.com/fannheyward/coc-pyright/issues/81#issuecomment-706867291_

**Comment by yaegassy** [comment]
Hi, @fannheyward 

Thank you for putting up a new issue.

The above symptoms were confirmed by `nvim`.

An additional report.

`Vim8` seems to give me an error message if I set it up with a relative PATH.

`Vim8` will also format correctly if you set it up with absolute PATH.

**Message:**

vim8.

```
[coc.nvim] Formatting with black failed.black module is not installed.
```

**DEMO**

![vim8-coc-pyright-format](https://user-images.githubusercontent.com/188642/95723919-ab246a80-0cb0-11eb-8d8a-118d29279ea8.gif)
