### ISSUE TITLE
`pipenv --py` might introduce newlines

### ISSUE THREAD

**Issue by notEvil** [fannheyward/coc-pyright#1005]
Just fyi: https://github.com/pypa/pipenv/issues/5969
This leads to "Unable to get Python version from interpreter" and therefore broken experience

https://github.com/fannheyward/coc-pyright/blob/8789fcc25cd055a0cc1e70fc83bfcca90720c384/src/configSettings.ts#L77

**Comment by fannheyward** [comment]
What's your `pipenv` version? Tested with version 2023.10.3, no newlines.

<img width="764" alt="image" src="https://github.com/fannheyward/coc-pyright/assets/345274/9651557b-0c41-4944-85b2-6d7ce97a046b">

**Comment by fannheyward** [comment]
`python -c "import subprocess; print(subprocess.Popen(['pipenv', '--py'], stdout=subprocess.PIPE).stdout.read())"` outputs:

`b'/Users/fannheyward/src/hello-sonar/.venv/bin/python\n'`

**Comment by notEvil** [comment]
As noted in "Steps to replicate": make the console small enough so the path doesn't fit on one line

**Comment by fannheyward** [comment]
But this won't affect to coc-pyright's result, doesn't it?

**Comment by notEvil** [comment]
The newline ends up in `pythonPath` which leads to issues later on like ENOENT (path doesn't exist) in

https://github.com/microsoft/pyright/blob/f4e309a84cbc12e91063d93dc1ede54d84d54485/packages/pyright-internal/src/common/fullAccessHost.ts#L110C22-L110C22

So the issue is affecting coc-pyright but probably needs to be fixed in Pipenv.

**Comment by fannheyward** [comment]
> The newline ends up in pythonPath which leads to issues later on like ENOENT

I still can't get the point.

coc-pyright runs `pipenv --py` by spawning a child process, trims the output, uses the result as pythonPath. The size of the console window, no matter small or big enough, won't affect the child process result.

<img width="141" alt="image" src="https://github.com/fannheyward/coc-pyright/assets/345274/8c4736ae-98b4-41e7-a189-0010d6062761">

**Comment by notEvil** [comment]
I see, node unlike python seems to create a barrier so rich, used by Pipenv and responsible for splitting the lines, assumes a width of 80. So use a long dictionary name to reproduce with node.

**Comment by fannheyward** [comment]
> use a long dictionary name to reproduce with node

What's this?

**Comment by notEvil** [comment]
I meant directory, sry!

**Comment by fannheyward** [comment]
Closing for now. Thank you for your report.

**Comment by notEvil** [comment]
Just for reference: https://github.com/pypa/pipenv/pull/5971
