### ISSUE TITLE
Run mypy in daemon mode

### ISSUE THREAD

**Issue by danjones1618** [fannheyward/coc-pyright#1007]
In order to help with running on larger projects, should coc-pyright run [mypy as a daemon](https://mypy.readthedocs.io/en/stable/mypy_daemon.html) instead of as a command line tool?
I think this shouldn't be too big of a change as it just requires some setup/shutdown logic and then `dmypy` just outputs the same as running mypy normally.

**Comment by fannheyward** [comment]
Use https://github.com/yaegassy/coc-mypy, with `dmypy` by default.
