### ISSUE TITLE
is pyright supposed to show me ref counts?

### ISSUE THREAD

**Issue by amirongit** [fannheyward/coc-pyright#1020]
**output of `:CocCommand pyright.version`** 
coc-pyright 1.1.335 with Pyright 1.1.335

**output of `nvim --version`**
NVIM v0.10.0-dev-e9b9a86
Build type: RelWithDebInfo
LuaJIT 2.1.1699524327
Run "nvim -V1 -v" for more info

**output of `:CocCommand workspace.showOutput Pyright`**
```
Workspace: - - -
Using python from /home/- - -/.local/share/virtualenvs/- - -/bin/python

[Info  - 09:00:50.525] Pyright language server 1.1.335 starting
[Info  - 09:00:50.525] Server root directory: /home/- - -/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist
[Info  - 09:00:50.531] Starting service instance "- - -"
[Info  - 09:00:50.546] Setting pythonPath for service "- - -": "/home/- - -/.local/share/virtualenvs/- - -/bin/python"
[Info  - 09:00:50.576] Assuming Python version 3.11
[Info  - 09:00:50.657] Found 57 source files
```

in the readme page, there is a virtual text for the unittest being show cased. is there something like that for references counts?!
(I can see all the references with `nmap <silent><leader>ref  <Plug>(coc-references)`).

**Comment by amirongit** [comment]
coc settings

```
  "pyright.inlayHints.variableTypes": false,
  "pyright.inlayHints.functionReturnTypes": false,
  "codeLens.enable": true,
  "codeLens.position": "right_align"
```
it is more, these are settings that I think are relevant.

**Comment by fannheyward** [comment]
No such feature yet.

**Comment by amirongit** [comment]
ok then
