### ISSUE TITLE
Disable "reportGeneralTypeIssues" 

### ISSUE THREAD

**Issue by foozzi** [fannheyward/coc-pyright#1021]
` coc-pyright 1.1.336 with Pyright 1.1.336`
<img width="995" alt="Снимок экрана 2023-11-16 в 22 23 18" src="https://github.com/fannheyward/coc-pyright/assets/1178208/390f504b-03c5-47a9-bc57-8c4dc2c77274">

**Comment by fannheyward** [comment]
What's the issue/problem?

**Comment by foozzi** [comment]
> What's the issue/problem?

There is no issue. 
How to disable that message?

**Comment by fannheyward** [comment]
```json
  "python.analysis.diagnosticSeverityOverrides": {
    "reportGeneralTypeIssues": "none"
  },
```
