### ISSUE TITLE
Question: implementation provider

### ISSUE THREAD

**Issue by foozzi** [fannheyward/coc-pyright#1023]
Hi,
I have an error when `gi` in `.py` file:
<img width="1204" alt="Снимок экрана 2023-11-22 в 19 17 20" src="https://github.com/fannheyward/coc-pyright/assets/1178208/6091a50d-4fdb-4e73-810d-585699c8ef0b">

my coc-settings.json:
```json
{
    "python.linting.ruffEnabled": true,
    "python.linting.mypyEnabled": true,
    "pyright.organizeimports.provider": "ruff",
    "python.formatting.provider": "ruff",
    "pyright.inlayHints.variableTypes": false,
    "pyright.inlayHints.functionReturnTypes": false,
    "python.analysis.diagnosticSeverityOverrides": {
        "reportGeneralTypeIssues": "warning",
        "reportOptionalMemberAccess": "warning"
    }
}
```
and 
<img width="971" alt="Снимок экрана 2023-11-22 в 19 49 28" src="https://github.com/fannheyward/coc-pyright/assets/1178208/bd6eae56-ec00-4977-b425-685c913b419f">

What do I need to do to use that feature?

**Comment by fannheyward** [comment]
Pyright doesn't provide implementation and foldingRange support.
