### ISSUE TITLE
how to write `pyrightconfig.json` to get info from specific dirs.

### ISSUE THREAD

**Issue by hyaray** [fannheyward/coc-pyright#1024]
Hi there, I want tell pyright where to get function info when I edit python at specific dirs.
root dir is `apps`,
module file path: `apps/aaa/aaa/utils.py`,
created config file at `apps/pyrightconfig.json`, 
When I edit python file in `apps/xxx` or `d:\other`, I want pyright to get infos from `apps/aaa/*.py`,
how to deal this? Thanks a lot!!!
Best Wishes.

**Comment by fannheyward** [comment]
```sh
pwd
/Users/fannheyward/src/test

❯ fd
bbb/
bbb/bbb/
bbb/bbb/x.py
frappe/
frappe/frappe/
frappe/frappe/utils.py

cat frappe/frappe/utils.py

def foo():
    print("foo")

cat bbb/bbb/x.py

from frappe.frappe.utils import *
foo()
```

`gd` on `foo` will jump to utils.py, no `pyrightconfig.json` configuration.
