### ISSUE TITLE
uncaughtException Error: write EPIPE

### ISSUE THREAD

**Issue by meangrape** [fannheyward/coc-pyright#1033]
**What's the output of `:CocCommand pyright.version`**
coc-pyright 1.1.339 with Pyright 1.1.339

**What's the output of `:CocCommand workspace.showOutput Pyright`**
  Workspace: /Users/jayed/repos/fdb_exporter
  Using python from /Users/jayed/.pyenv/shims/python

  [Info  - 13:45:42.323] Pyright language server 1.1.339 starting
  [Info  - 13:45:42.323] Server root directory: /Users/jayed/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist
  [Info  - 13:45:42.326] Starting service instance "fdb_exporter"
  [Info  - 13:45:42.334] Setting pythonPath for service "fdb_exporter": "/Users/jayed/.pyenv/shims/python"
  [Info  - 13:45:42.423] Assuming Python version 3.11
  [Info  - 13:45:42.604] No source files found.

**`:CocOpenLog`**
  2023-12-07T13:45:42.177 INFO (pid:99402) [plugin] - coc.nvim initialized with node: v21.2.0 after ^[[33m518^[[39m
  2023-12-07T13:45:42.178 INFO (pid:99402) [services] - LanguageClient Pyright Server state change: stopped => starting
  2023-12-07T13:45:42.182 INFO (pid:99402) [language-client-index] - Language server "pyright" started with 99509
  2023-12-07T13:45:42.232 INFO (pid:99402) [core-watchman] - watchman watching project: /Users/jayed/repos/fdb_exporter
  2023-12-07T13:45:42.327 INFO (pid:99402) [services] - LanguageClient Pyright Server state change: starting => running
  2023-12-07T13:45:42.330 INFO (pid:99402) [services] - service pyright started
  2023-12-07T13:45:42.644 INFO (pid:99402) [core-watchman] - watchman watching project: /Users/jayed/.pyenv/versions/3.11.4/lib/python3.11
  2023-12-07T13:45:43.700 ERROR (pid:99402) [server] - uncaughtException Error: write EPIPE
    | at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)
  2023-12-07T13:45:46.513 INFO (pid:99402) [attach] - receive notification: runCommand [ ^[[32m'workspace.showOutput'^[[39m, ^[[32m'Pyright'^[[39m ]
  2023-12-07T13:47:26.092 INFO (pid:99402) [attach] - receive notification: openLog []

When initially opening a python file from the command line or in a new buffer or when saving a buffer, I receive the following error:
`uncaughtException Error: write EPIPE`

**Comment by fannheyward** [comment]
Thank you for your report, but I can't reproduce this. What's your coc.nvim version? You can get it from `:CocInfo`.

The `write EPIPE` means write date to a closed connection, maybe something broken between the client and server.

**Comment by meangrape** [comment]
I just updated the plugin and have the same error.

`coc.nvim version: 0.0.82-d1568d56 2023-09-29 19:43:34 +0800`

**Comment by fannheyward** [comment]
> [Info - 13:45:42.604] No source files found.

Strange log, pyright didn't find any Python files in your project.

Do you have some root patterns files, for example `.git/`, `pyproject.toml`, `pyrightconfig.json` file in your project root?

**Comment by meangrape** [comment]
pyright is running `/opt/homebrew/Cellar/node/21.2.0/bin/node --max-old-space-size=3072 /Users/jayed/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/langserver.index.js --node-ipc --clientProcessId=45713`

I understand the "no source files found" error now. The file doesn't have a `.py` extension. When I rename it to include the extension, 1 source file is found, however the `[coc.nvim]: Uncaught exception: write EPIPE` error still exists.

I have a number of root patterns
```
['.git', '.env', 'venv', '.venv', 'setup.cfg', 'setup.py', 'pyproject.toml', 'pyrightconfig.json']
```
however this is an incredibly simple project with one text file, one python file, one tags file, and a `.git` directory

**Comment by fannheyward** [comment]
Do you have any other extensions? Make a minimal test, maybe the error isn't came from coc-pyright.

**Comment by meangrape** [comment]
I receive the error with only pyright

![CleanShot 2023-12-10 at 13 01 46](https://github.com/fannheyward/coc-pyright/assets/9083/e631f0c0-d123-4180-b0c8-dfc30670dae3)
 installed

**Comment by meangrape** [comment]
It also happens with a minimal vimrc
```
let mapleader = ";"

map <leader>e :e ./init.vim<CR><C-W>
map <silent><leader>E :source ./init.vim<CR>:filetype detect<CR>:exe ":echo 'init.vim reloaded'"<CR>

set runtimepath+=$HOME/.vim/

call plug#begin('$HOME/.vim/plugged')
Plug 'neoclide/coc.nvim', { 'branch': 'release' }
call plug#end()


filetype plugin indent on
au FileType python let b:coc_root_patterns = ['.git', '.env', 'venv', '.venv', 'setup.cfg', 'setup.py', 'pyproject.toml', 'pyrightconfig.json']
syntax on
```

**Comment by meangrape** [comment]
If, however, I change from `iTerm2` to the macOS `Terminal` the error goes away

**Comment by fannheyward** [comment]
It's not coc.nvim or coc-pyright issue, but something broken in your env.

**Comment by xanderdunn** [comment]
I'm also experiencing this issue in iTerm2 on macOS.
