### ISSUE TITLE
coc throws error whenever I try to accept any suggestion from pyright

### ISSUE THREAD

**Issue by h-sifat** [fannheyward/coc-pyright#1034]
Hi there! First of all thank you so much for your amazing work and I'm really sorry for bothering you.

I'm trying to use coc-pyright but it's always throwing the following error. But other LSPs are working fine.

```
[coc.nvim]: UnhandledRejection: Cannot read properties of undefined (reading 'match')
```

[pyright.webm](https://github.com/fannheyward/coc-pyright/assets/80267830/823bf33e-984b-4f73-afcf-805532eae980)

I'm really sorry I can't provide a minimal reproducible configuration right now because my config is rather large. But I've tried to find the source of the bug.

The error is being thrown from the coc [fixIndent](https://github.com/neoclide/coc.nvim/blob/f82e420efdb6291d1c3fcac1e20790a7f10f1a78/src/completion/source-language.ts#L194) function and it's being used [here](https://github.com/neoclide/coc.nvim/blob/f82e420efdb6291d1c3fcac1e20790a7f10f1a78/src/completion/source-language.ts#L158).

The error occurs because at line **144** the de-structured `line` variable is undefined.

```js
let { character, line } = this.triggerContext
```
Sadly, I couldn't do anything more than that as I don't know how coc and it's plugin system work. If you have some time kindly take a look at the issue and let me know if you need any other information.

Here are some helpful attachments:

[coc-info.txt](https://github.com/fannheyward/coc-pyright/files/13759914/coc-info.txt)
[health-check.txt](https://github.com/fannheyward/coc-pyright/files/13759915/health-check.txt)

Thank you.

**Comment by fannheyward** [comment]
Thank you for your report, glad to hear coc-pyright can help you!

I can't reproduce this with same sample code, the `fixIndent` function is used to compute indent size for new inputed text. Do you use `tab` for indent in Python? Can you reproduce this error with no-indent codes?

**Comment by h-sifat** [comment]
Hello @fannheyward, thanks for getting back to me. Yes, the error still occurs with no-indent codes.

But luckily I somehow fixed the problem myself. I went to the `~/.local/share/nvim/lazy/coc.nvim/build/index.js` file and located where the [applyTextEdit](https://github.com/neoclide/coc.nvim/blob/f82e420efdb6291d1c3fcac1e20790a7f10f1a78/src/completion/source-language.ts#L158) function is defined and made the following modifications:

```ts
private async applyTextEdit(doc: Document, additionalEdits: boolean, item: CompletionItem, option: CompleteDoneOption): Promise<boolean> {
  let { linenr, col } = option
  let { character, line } = this.triggerContext

  // I just added the next line
  if(!line) return;

  // rest of the function ...
}
```
Now, it doesn't throw error anymore :smile:

**Comment by fannheyward** [comment]
Yes, the `!line` checking will prevent the error throwing, but this didn't fix the issue.

After you input something, trigger coc.nvim to fetch completion suggestions from Pyright, then coc.nvim will apply it to the document. The `fixIndent` needs the current `line` string to compute indent size with new added/changed text, here the `line` was came from vim by `getline('.')`, this shouldn't be empty or undefined.

There's still something wrong with your configuration for Python. I suggest you to bisect your configurations.

**Comment by fannheyward** [comment]
Close for now.
