### ISSUE TITLE
new module isn't recognized until I re-open nvim

### ISSUE THREAD

**Issue by amirongit** [fannheyward/coc-pyright#1043]
**What's the output of `:CocCommand pyright.version`**
coc-pyright 1.1.342 with Pyright 1.1.344

**What's the output of `:CocCommand workspace.showOutput Pyright`**
Workspace: /home/amir/Development/*
Using python from /home/amir/.local/share/virtualenvs/*/bin/python

[Info  - 14:14:29.276] Pyright language server 1.1.344 starting
[Info  - 14:14:29.276] Server root directory: file:///home/amir/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist
[Info  - 14:14:29.281] Starting service instance "*"
[Info  - 14:14:29.302] Setting pythonPath for service "*": "/home/amir/.local/share/virtualenvs/*/bin/python"
[Info  - 14:14:29.339] Assuming Python version 3.11
[Info  - 14:14:29.452] Found 50 source files
[Error - 14:14:30.953] Sending request textDocument/documentHighlight failed.
  Message: request cancelled
  Code: -32800 

I have this problem on two PCs, so it is probably caused by my configurations.
this is how you can reproduce my situation

have a python workspace which is correctly working (with local auto imports and all that)
create a new python module locally somewhere in the project
import it in one of the buffers which was already open
pyright gives you an error saying that it can't resolve the imported module!
oddly enough, I have the auto import feature working for the new module which imports it correctly, but the diagnose about the wrong import path remains until I close nvim and open it again!

CocConfig
```json
{
  "coc.preferences.jumpCommand": "tab drop",
  "diagnostic.messageTarget": "float",
  "diagnostic.floatConfig": {
    "border": true,
    "maxWidth": 90,
    "maxHeight": 90
  },
  "diagnostic.showUnused": false,
  "diagnostic.warningSign": ">",
  "diagnostic.errorSign": "*",
  "diagnostic.infoSign": ">",
  "diagnostic.hintSign": ">",
  "git.changeRemovedSign.text":"-",
  "git.conflictedDecorator": "*",
  "git.topRemovedSign.text": "-",
  "git.untrackedDecorator": "?",
  "git.changedDecorator": "~",
  "git.changedSign.text": "~",
  "git.removedSign.text": "-",
  "git.branchCharacter": "b",
  "git.stagedDecorator": "+",
  "git.addedSign.text": "+",
  "hover.target": "float",
  "hover.floatConfig": {
    "border": true,
    "maxWidth": 90,
    "maxHeight": 90
  },
  "hover.autoHide": false,
  "pyright.organizeimports.provider": "pyright",
  "pyright.inlayHints.variableTypes": false,
  "pyright.inlayHints.functionReturnTypes": false,
  "python.sortImports.args": ["--up", "-l 120"],
  "python.analysis.autoImportCompletions": true,
  "python.analysis.typeCheckingMode": "off",
  "python.analysis.diagnosticMode": "workspace",
  "python.linting.flake8Enabled": false,
  "python.linting.enabled": true,
  "python.linting.flake8Args": ["--max-line-length=120"],
  "python.linting.mypyEnabled": true,
  "python.linting.mypyPath": "mypy",
  "python.linting.mypyArgs": [
      "--no-pretty",
      "--ignore-missing-imports",
      "--follow-imports=silent",
      "--show-column-numbers"
  ],
  "lua.enable": true,
  "Lua.codeLens.enable": true,
  "Lua.completion.showWord": "Disable",
  "signature.hideOnTextChange": false,
  "signature.target": "float",
  "signature.floatConfig": {
    "border": true,
    "maxWidth": 90,
    "maxHeight": 90
  },
  "inlayHint.display": true,
  "inlayHint.enable": true,
  "inlayHint.enableParameter": true,
  "inlayHint.refreshOnInsertMode": true,
  "codeLens.enable": true,
  "codeLens.position": "right_align",
}
```

**Comment by fannheyward** [comment]
Install https://facebook.github.io/watchman/ , coc.nvim will use this to watch project files change and send to language server.
