### ISSUE TITLE
pyright is not working on LocalConfig on windows

### ISSUE THREAD

**Issue by harol97** [fannheyward/coc-pyright#1044]
Hello @fannheyward 

First , thanks for this excelent tool, I have used coc-pyright on distributions based on linux without problems.
 however actually I'm using Windows S.O, and I have some problems, principal I found errors in 

"python.formatting.provider" and "pyright.organizeimports.provider" in CocLocal config.

It looks always take values of CocConfig and never take values of CocLocalConfig

![image](https://github.com/fannheyward/coc-pyright/assets/49042862/12299a91-504a-4d8d-9ada-72c8e7b85f18)

How you could appreciate on image, i set formatting provider = ruff but when use it so pyright search autopep8

Do I lost something?

Any help is welcome. 

Best regards

**Comment by fannheyward** [comment]
What's the output of `:echo CocAction('getConfig', 'python.formatting')` in your Linux and Windows env? Looks like `.vim/coc-settings.json` on Windows wasn't loaded.

**Comment by fannheyward** [comment]
coc.nvim uses the hard-coded path `.vim/coc-settings.json` to resolve the local configuration file, should be fixed with the PR.

**Comment by harol97** [comment]
> What's the output of `:echo CocAction('getConfig', 'python.formatting')` in your Linux and Windows env? Looks like `.vim/coc-settings.json` on Windows wasn't loaded.



> What's the output of `:echo CocAction('getConfig', 'python.formatting')` in your Linux and Windows env? Looks like `.vim/coc-settings.json` on Windows wasn't loaded.

output is

![image](https://github.com/fannheyward/coc-pyright/assets/49042862/7d8a9946-71b4-40ca-9f89-1e2fe70e6c6a)

pyright.enable config is working wll.

but "python.formatting.provider" and "pyright.organizeimports.provider"  no

**Comment by harol97** [comment]
Now "pyright.organizeimports.provider" is working,  but python.formatting.provide is not working.
When execute formatOnSave command It is searching autopep8  when I set provider = ruff in my local config on windows.

Do I lost something?

Any help is welcome.

Best regards

**Comment by fannheyward** [comment]
It's `python.formatting.provider`, not `python.formatting.provide`.

And provide `:echo CocAction('getConfig', 'python.formatting'` in your windows project.

**Comment by harol97** [comment]
> It's `python.formatting.provider`, not `python.formatting.provide`.
> 
> And provide `:echo CocAction('getConfig', 'python.formatting'` in your windows project.

It's my workspace and result of command

![image](https://github.com/fannheyward/coc-pyright/assets/49042862/e9c7cd6f-732e-4837-a389-a9a82b182de1)

and It's my global config

![image](https://github.com/fannheyward/coc-pyright/assets/49042862/596f422e-3b68-47e2-93ea-b0cad1e425bc)


when i set python.formatting.provider = ruff in global settings. It works well but not in local config when I format on save

**Comment by fannheyward** [comment]
Sorry for the delay, from the screenshot, the `python.formatting.provider` is set to ruff.

Run `:CocCommand editor.action.formatDocument`, then `:CocCommand workspace.showOutput coc-pyright-formatting` to check the logs.
