### ISSUE TITLE
Python extraPaths

### ISSUE THREAD

**Issue by tdejager** [fannheyward/coc-pyright#105]
Hi!

Would it be possible to be able to set the `python.analysis.extraPaths` option, it seems to be available in pyright? The option is also available in coc-python, but is listed under `autoComplete` instead of `analysis`.

This is useful when your projects are not on the pythonpath per se.

**Comment by fannheyward** [comment]
It's already supported https://github.com/fannheyward/coc-pyright/blob/8dead6ff49e2fc70f97746565ae4c0af4d8b44ff/package.json#L71.
