### ISSUE TITLE
关于 Python 虚拟环境以及 PYTHONPATH 的问题

### ISSUE THREAD

**Issue by rmGFW** [fannheyward/coc-pyright#106]
我发现我项目中写了某写模块，必须手动export PYTHONPATH到那个包的地址才行，否则import 就会提示错误。
而且还有一个问题，虚拟环境可以配置相对地址嘛。一般都是项目根路径下的某个文件夹

**Comment by fannheyward** [comment]
> 手动export PYTHONPATH到那个包的地址才行，否则import 就会提示错误

无法重现。

虚拟环境可以用相对位置，比如 `"python.venvPath": ".venv"`.

**Comment by chenyidao110** [comment]
> 
> 
> > 手动export PYTHONPATH到那个包的地址才行，否则import 就会提示错误
> 
> 无法重现。
> 
> 虚拟环境可以用相对位置，比如 `"python.venvPath": ".venv"`.

是把上面的配置写到vim的配置文件中吗，然后coc-pyright就能正常解析虚拟环境中的python了吧？
