### ISSUE TITLE
Inlay Hints stopped working

### ISSUE THREAD

**Issue by ironhacker** [fannheyward/coc-pyright#1062]
Really like the inlay hints feature, but it quit working recently and I don't know why.  I'm using it with NeoVIM:

vim version: NVIM v0.9.5
node version: v20.11.1
coc.nvim version: 0.0.82-84ce0312 2024-03-11 10:52:28 +0800

I tried upgrading everything include node, NeoVIM, coc, and coc-pyright.  I also tried disabling all the other plugins in my nvim config, but no luck.   Any suggestions would be appreciated.

**What's the output of `:CocCommand pyright.version`**

coc-pyright 1.1.351 with Pyright 1.1.354

**What's the output of `:CocCommand workspace.showOutput Pyright`**

Workspace: /home/randall/programs/workspace
Using python from /home/randall/programs/workspace/pyenv/bin/python

[Info  - 19:01:55.793] Pyright language server 1.1.354 starting
[Info  - 19:01:55.794] Server root directory: file:///home/randall/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist
[Info  - 19:01:55.797] Starting service instance "workspace"
[Info  - 19:01:55.810] Setting pythonPath for service "workspace": "/home/randall/programs/workspace/pyenv/bin/python"
[Info  - 19:01:55.831] Assuming Python version 3.9
[Info  - 19:01:55.885] Auto-excluding /home/randall/programs/workspace/pyenv
[Info  - 19:01:55.887] Found 1 source file

**Comment by fannheyward** [comment]
coc.nvim has added inline inlayHint support for nvim, similar to Vim 9, https://github.com/neoclide/coc.nvim/pull/4648, this requires nvim 0.10+.

Yes, this is a breaking change for stable (0.9.5) users, two solutions:

1. using nvim 0.10.0 nightly
2. or downgrade your coc.nvim to https://github.com/neoclide/coc.nvim/commit/3dc6153a85ed0f185abec1deb972a66af3fbbfb4
