### ISSUE TITLE
Installing spawn EINVAL

### ISSUE THREAD

**Issue by MaskDuck** [fannheyward/coc-pyright#1071]
![image](https://github.com/fannheyward/coc-pyright/assets/70831061/22710265-cb57-4600-941e-aa7763489f6a)
Installing coc-pyright returns EINVAL

**What's the output of `:CocCommand pyright.version`**
![image](https://github.com/fannheyward/coc-pyright/assets/70831061/e4766f0a-0d3c-48b7-97d0-c5dc2d220a32)

**What's the output of `:CocCommand workspace.showOutput Pyright`**

**Comment by fannheyward** [comment]
Upgrade your coc.nvim please https://github.com/neoclide/coc.nvim/pull/4985
