### ISSUE TITLE
Error when I use organize imports

### ISSUE THREAD

**Issue by harol97** [fannheyward/coc-pyright#1095]
First , thanks for this excelent tool.
Recently I see an error when I'm trying organize imports . The message error is: 
![image](https://github.com/fannheyward/coc-pyright/assets/49042862/b0531d0f-0778-466f-9659-5a0be6d15496)

**What's the output of `:CocCommand pyright.version`**
![image](https://github.com/fannheyward/coc-pyright/assets/49042862/982a672d-c0f6-4844-9a86-b8e778ea495a)

**What's the output of `:CocCommand workspace.showOutput Pyright`**
![image](https://github.com/fannheyward/coc-pyright/assets/49042862/268a6f92-14ae-4b6f-8d87-6317ceb8bf49)

**Comment by fannheyward** [comment]
`CocUpdate` to coc-pyright v1.1.371
