### ISSUE TITLE
[question] VSCode support

### ISSUE THREAD

**Issue by ethanc8** [fannheyward/coc-pyright#1097]
What would it take to make coc-pyright work on VSCode? It provides some features that Pyright extension doesn't provide, so it would be useful for the open-source VSCode forks such as VSCodium and Theia so that they can have better Python support.

**Comment by ethanc8** [comment]
Also, how many of the features such as:

- semanticTokens highlighting!
- inlayHints supports
- codeActions to add imports, ignore typing check, run tests and more
- linting with `bandit`, `flake8`, `mypy`, `ruff`, `prospector`, `pycodestyle`, `pydocstyle`, `pyflakes`, `pylama`, `pylint`, `pytype`
- formatting with `ruff`, `yapf`, `black`, `autopep8`, `darker`, `blackd`, `pyink`
- testing with `unittest` or `pytest`, supports codeLens
- sort imports with `ruff`, `isort` and `pyright`
- extract method and variables with `rope`

could be provided by the language server instead of by the extension? Then these features could be used by any LSP client, not just coc-pyright.

**Comment by ethanc8** [comment]
Now that I look at it, it looks like [basedpyright](https://github.com/DetachHead/basedpyright) is the way to go, especially since Pyright is openly hostile towards bug reports and improvements now. They provide a VSCode extension and a better language server with some Pylance features.

**Comment by fannheyward** [comment]
No plan for this.

**Comment by ethanc8** [comment]
This was not exactly a feature request, this was a question about how feasible it would be for others to do it.

**Comment by fannheyward** [comment]
> how feasible it would be for others to do it.

It's possible to add features to language server itself, [basedpyright](https://github.com/DetachHead/basedpyright) has done in this way.
