### ISSUE TITLE
GObject.Property and setter decorator mistakenly issue reportRedeclaration

### ISSUE THREAD

**Issue by ltsdw** [fannheyward/coc-pyright#1107]
**What's the output of `:CocCommand pyright.version`**
```
[coc-nvim] coc-pyright 1.1.377 with Pyright 1.1.378
```

**What's the output of `:CocCommand workspace.showOutput Pyright`**
```
Workspace: /tmp/GTK4
Using python from /tmp/GTK4/venv/bin/python

[Info  - 02:49:10.025] Pyright language server 1.1.378 starting
[Info  - 02:49:10.025] Server root directory: file:///home/dev_user/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist
[Info  - 02:49:10.027] Starting service instance "GTK4"
[Info  - 02:49:10.040] Loading configuration file at /tmp/GTK4/pyrightconfig.json
[Info  - 02:49:10.041] Setting pythonPath for service "GTK4": "/tmp/GTK4/venv/bin/python"
[Info  - 02:49:10.041] No include entries specified; assuming /tmp/GTK4
[Info  - 02:49:10.042] Auto-excluding **/node_modules
[Info  - 02:49:10.042] Auto-excluding **/__pycache__
[Info  - 02:49:10.042] Auto-excluding **/.*
[Info  - 02:49:10.072] Assuming Python version 3.12.5.final.0
[Info  - 02:49:10.142] Auto-excluding /tmp/GTK4/env/asts-env
[Info  - 02:49:10.143] Auto-excluding /tmp/GTK4/venv
[Info  - 02:49:10.148] Found 74 source files
```

I have the pygobject stubs installed, but it still wrongly issuing reportRedeclaration.

```python
    @property
    def index(self):
        return self._index


    @index.setter
    def index(self, value): # normal, no report here
        self._index = value


    @Property(type=str, default="")
    def end_time(self): # issue reportRedeclaration here
        return self._end_time


    @end_time.setter
    def end_time(self, value: str) -> None:
        self._end_time = value

        self.notify("end_time")
```

**Comment by fannheyward** [comment]
Can you reproduce this with VSCode+Pyright/Pylance? The error message was reported by Pyright, coc-pyright just displayed it.

**Comment by ltsdw** [comment]
> Can you reproduce this with VSCode+Pyright/Pylance?

I'm unable to test it right now, but I can try test it later with pylance and or vscode too.

> The error message was reported by Pyright, coc-pyright just displayed it.

Yeah, thought of that too... do you think it would be better to report to ms' pyright instead?

**Comment by fannheyward** [comment]
> report to ms' pyright instead

Try to reproduce with VSCode+Pylance/Pyright first.

**Comment by ltsdw** [comment]
Yeah, I tried vscode, tried for hours to make pylance work, but heh, no luck.

But it was really easy to use pyright there, just installed the extension and good to go.
I can confirm it's reproducible using vscode+pyright.
