### ISSUE TITLE
Specifying a pyright setting in coc-settings.json

### ISSUE THREAD

**Issue by hiphamster** [fannheyward/coc-pyright#1122]
**What's the output of `:CocCommand pyright.version`**
coc-pyright 1.1.385 with Pyright 1.1.389

Setting **"reportOptionalIterable": false** in coc-settings.json produces an error:
"Property pyright.reportOptionalIterable is not allowed"

I can set it in pyrightconfig.json, but i don't understand why it can't be placed in coc-seetings.json

Thank you!

**Comment by fannheyward** [comment]
```json
  "python.analysis.diagnosticSeverityOverrides": {
    "reportOptionalIterable": false
  },
```

**Comment by hiphamster** [comment]
Thank you!
