### ISSUE TITLE
pyright.version not found

### ISSUE THREAD

**Issue by ssz29** [fannheyward/coc-pyright#1128]
**What's the output of `:CocCommand pyright.version`**
Error on notification "runCommand": Command: pyright.version not found

**CocInfo**
![image](https://github.com/user-attachments/assets/114df313-a8d0-4d66-a7f9-123fce49cf52)

**Comment by fannheyward** [comment]
> 0.0.82-7a50d4d9

You're using outdated version of coc.nvim, please use the latest `release` branch.

**Comment by ssz29** [comment]
> > 0.0.82-7a50d4d9
> 
> You're using outdated version of coc.nvim, please use the latest `release` branch.

Thanks, but if I want to use this version of coc.nvim, which version of coc-pyright could be compatible?

**Comment by fannheyward** [comment]
Maybe v1.1.336 or earlier.
