### ISSUE TITLE
coc-python -> coc-pyright

### ISSUE THREAD

**Issue by fannheyward** [fannheyward/coc-pyright#116]
## Background

- coc-python forks from [vscode-python](https://github.com/microsoft/vscode-python/commit/16899f6b13477786212f29eb3cb7a459b5ebf0a4), provides Python supports with Jedi/[MSPL](https://github.com/microsoft/python-language-server) for code completions, ctags for workspaceSymbols, Black/X for code formatting, pylint/X for code linting, and more
- [MSPL will be deprecated](https://devblogs.microsoft.com/python/announcing-pylance-fast-feature-rich-language-support-for-python-in-visual-studio-code/#the-future-of-the-microsoft-python-language-server) instead of [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance).
- Pylance is powered by [Pyright](https://github.com/microsoft/pyright), static type checker for Python, with some closed-source IntelliCode functions.
- Pyright has LSP supports, but lacks some feature, for example code formatting.

I've ported some features from coc-python to coc-pyright:

- code formatting from black/yapf/autopep8
- code listing from flake8/mypy/pep8/prospector/pydocstyle/pylama/pylint/bandit, and Pytype

## Commands

| coc-python | coc-pyright | Support? |
| --- | --- | --- |
| python.sortImports | - | Use `pyright.organizeimports` |
| python.startREPL | - | No |
| python.createTerminal | - | No |
| python.execInTerminal | - | No |
| python.buildWorkspaceSymbols | - | No |
| python.upgradePythonLanguageServer | - | No |
| python.viewOutput | - | No |
| python.goToPythonObject | - | No |
| python.setLinter | - | No |
| python.enableLinting | - | No |
| python.setInterpreter | - | No #99 |
| python.runLinting | python.runLinting | √ |
| - | pyright.restartserver | √ |
| - | pyright.createtypestub | √ |

## Configurations

| coc-python | coc-pyright | Will support? |
| --- | --- | --- |
| python.autoComplete.* | - | No |
| python.jedi* | - | No |
| python.autoUpdateLanguageServer | - | No |
| python.disableInstallationCheck | - | No |
| python.trace.server | - | No |
| python.globalModuleInstallation | - | No |
| python.analysis.downloadChannel | - | No |
| python.analysis.diagnosticEnabled | - | No |
| python.analysis.diagnosticPublishDelay | - | No |
| python.analysis.errors | - | No |
| python.analysis.warnings | - | No |
| python.analysis.information | - | No |
| python.analysis.disabled | - | No |
| python.analysis.symbolsHierarchyDepthLimit | - | No |
| python.condaPath | - | No |
| python.pipenvPath | - | No |
| python.poetryPath | - | No |
| python.venvFolders | - | No |
| python.workspaceSymbols.* | - | No |
| python.sortImports.* | - | No |
| python.terminal.* | - | No |
| python.venvPath | python.venvPath | √ |
| python.pythonPath | python.pythonPath | √ |
| python.formatting.* | python.formatting.* | √ |
| python.linting.* | python.linting.* | √ |
| - | python.linting.pytypeEnabled | √ |
| - | python.linting.pytypePath | √ |
| - | python.linting.pytypeArgs | √ |
| python.analysis.typeshedPaths | python.analysis.typeshedPaths | √ |
| python.analysis.openFilesOnly | python.analysis.diagnosticMode | √ |
| python.analysis.logLevel | python.analysis.logLevel | √ |
| - | python.analysis.extraPaths | √ |
| - | python.analysis.typeshedPaths | √ |
| - | python.analysis.autoImportCompletions | √ |
| - | python.analysis.autoSearchPaths | √ |
| - | python.analysis.stubPath | √ |
| - | python.analysis.diagnosticSeverityOverrides | √ |
| - | python.analysis.typeCheckingMode | √ |
| - | python.analysis.useLibraryCodeForTypes | √ |
| - | pyright.disableCompletion | √ |
| - | pyright.disableLanguageServices | √ |
| - | pyright.disableOrganizeImports | √ |

**Comment by mike-lloyd03** [comment]
Thanks for all your work on coc-python. Is coc-pyright a direct replacement for coc-python? Are there any features I'm going to missing by switching over, and if so, should I wait a while before doing so?

Migrating from coc-python to coc-pyright should just be a matter of COC commands right?

```
:CocUninstall coc-python
:CocInstall coc-pyright
```

**Comment by fannheyward** [comment]
> Is coc-pyright a direct replacement for coc-python

Yes or No, it depends on your usage. coc-pyright uses Pyright as language server, it's completely different with MPLS or Jedi used by coc-python. You can test with your code.

**Comment by elleven11** [comment]
I really need something that works with both python3 and 2... Pyright works wonderfully with python3 but does not work at all with python2. Is there any way I could disable automatically the extension while editing python2 files?
