### ISSUE TITLE
How to get different diagnostic colours

### ISSUE THREAD

**Issue by esn89** [fannheyward/coc-pyright#141]
Hi, 

I noticed that in this [image](https://user-images.githubusercontent.com/345274/64470245-bda9a780-d172-11e9-9fda-48af0617a2ee.png) from your README has different colours for [E] and [H].  I was wondering how you achieved that.

**Comment by fannheyward** [comment]
Checkout `:h CocErrorHighlight@en` and `:h CocHintHighlight@en`.
