### ISSUE TITLE
doc comments have extra new lines

### ISSUE THREAD

**Issue by ludwj61** [fannheyward/coc-pyright#145]
I have the following function (which is simply from the "default" coc config)
```vim
function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  elseif (coc#rpc#ready())
    call CocActionAsync('doHover')
  else
    execute '!' . &keywordprg . " " . expand('<cword>')
  endif
endfunction
```
I have noticed that doc comments which are multiple lines include extra new lines when displayed with this function.
Take this multi-line doc comment for example:

![image](https://user-images.githubusercontent.com/42984254/99110248-1adf8b00-25b8-11eb-81d5-abb2e92e5577.png)

when using the function, I see:
![image](https://user-images.githubusercontent.com/42984254/99110742-dbfe0500-25b8-11eb-8cde-ed75ac4543ca.png)

As you can see, it is making newlines to make sure the doc stays within the bounds of the popup, but also including the new lines from the doc comment itself, resulting in weird breaks in the comment. 

Apologies if this is not the plugin's fault but instead coc, vim, pyright, etc.

Thanks for the extension!

**Comment by oblitum** [comment]
@ludwj61 I think that's pyright to blame. It should provide correct data for client to display. The client should not apply additional formatting, like removing chars, etc.
