### ISSUE TITLE
`python.analysis.extraPaths` setting not working

### ISSUE THREAD

**Issue by thibthib18** [fannheyward/coc-pyright#149]
CocConfig:
```json
{
"python.autoComplete.extraPaths": [
    "/home/thib/catkin_ws/devel/lib/python3/dist-packages",
    "/home/thib/main/svpy",
  ],
"python.analysis.extraPaths": [
    "/home/thib/catkin_ws/devel/lib/python3/dist-packages",
    "/home/thib/main/svpy",
  ]
}
```

When importing modules from outside the working project, the following import error shows up:
```python
from sv_msgs.msg import PickupZoneArray, PickupZone
                                          [Pyright (reportGeneralTypeIssues)] [E] "PickupZoneArray" is unknown import symbol    
```

When importing modules from within the working project, the following error import shows up:
```python
from pymongo.database import Database
                   [Pyright (reportMissingImports)] [E] Import "pymongo.database" could not be resolved
```

`coc-python` works without issue with the right `python.autoComplete.extraPaths`. But somehow `coc-pyright` ignore those extra paths.

**Comment by fannheyward** [comment]
Pyright doesn't follow `python.autoComplete.extraPaths`. You can test whether VSCode+Pyright works or not.

> [Pyright (reportMissingImports)] [E] Import "pymongo.database" could not be resolved

I can't reproduce this error.

**Comment by thibthib18** [comment]
Yes, `python.autoComplete.extraPaths` is to indicate extra paths for `coc-python`. 

Am I right to assume that `python.analysis.extraPaths` is its `coc-pyright` counterpart?

Or what should be the proper way to add extra paths to `coc-pyright` then?

**Comment by thibthib18** [comment]
> You can test whether VSCode+Pyright works or not.

This also happens on VSCode, I will open an issue there.
Thanks.
