### ISSUE TITLE
Coc-pyright removes sourcery's quickfixes

### ISSUE THREAD

**Issue by anstadnik** [fannheyward/coc-pyright#172]
Sourcery is an AI tool that refactors code [link](https://github.com/sourcery-ai/sourcery/wiki/Vim-Usage#installation). It adds items to `:CocFix`, when it finds any ways to improve the code. When coc-pyright is installed, it somehow overwrites those fixes.

e.g.
![image](https://user-images.githubusercontent.com/40110937/101130397-1719b400-360c-11eb-8489-f003f7cffcd4.png)
When coc-pyright is not installed, `:CocFix` changes `dict()` to `{}`. With coc-pyright installed, nvim prints `[coc.nvim] No quickfix action available`.
<details>
<summary>Code from the image</summary>

```python
class choises_printer:
    def __init__(self):
        self.choise = dict()

    def set_choise(l: int, i: int):
        self.choise[l] = i
```

</details>
Please tell me if you need any additional information.

**Comment by fannheyward** [comment]
Try `<Plug>(coc-codeaction-line)`.

**Comment by anstadnik** [comment]
Hm, for me it doesn't work. I tried this as well as `<Plug>(coc-codeaction)`. Does it work for you?

**Comment by fannheyward** [comment]
Sorry, I don't use Sourcery, can not to test or debug this.

**Comment by marcoaaguiar** [comment]
I use both Sourcery and PyRight. Could you post a code example so that we are talking about the same thing?
I can try to reproduce it.

**Comment by anstadnik** [comment]
Hi @marcoaaguiar. The code is in the first comment, you just need to open the fold

**Comment by marcoaaguiar** [comment]
My bad didn't notice. 

Anyway, it works just fine for me. I used the method that I explained in https://github.com/sourcery-ai/sourcery/issues/43#issuecomment-708864836 to setup Sourcery (Downloading the release from their Github page)
In your screenshot, I noticed that PyRight is not complaining about the lack o self on the second method (which is in mine).
I will try to upgrade Sourcery to see if it is an issue with their side.

**Comment by marcoaaguiar** [comment]
With the latest version of everything (coc.nvim, pyright, sourcery), I cannot reproduce the error you posted. That is, quickfix works just fine.

**Comment by marcoaaguiar** [comment]
@anstadnik, are you running all the latest versions?

**Comment by anstadnik** [comment]
Yes, I can confirm that the issue is gone

**Comment by fvdnabee** [comment]
I'm experiencing a similar issue with the following snippet (from [the sourcery tutorial](https://github.com/sourcery-ai/sourcery/wiki/Sourcery-Tutorial)):
```python
def dictionary_get():
    dictionary = {}
    data = ""
    if "message" in dictionary:
        data = dictionary["message"]
```

CocDiagnostics output:
```
test.py|3 col 1 info| [sourcery refactoring/diagnostic] Sourcery - Replace if statement with if expression, Simplify dictionary access using default get [I]
test.py|3 col 5 H| [Pyright] "data" is not accessed [H]
test.py|5 col 9 H| [Pyright] "data" is not accessed [H]
```
![image](https://user-images.githubusercontent.com/1157936/135587225-3ca57d97-6999-4e6e-8605-e5b8c3e35688.png)

With the pyright error present, `<Plug>(coc-codeaction)` with the cursor on any line in the buffer does not offer the sourcery suggestion. When I move the cursor to L2 or L4 (one line above/below where vim highlights the sourcery suggestion and the pyright error) and execute <Plug>(coc-codeaction-line) I get the sourcery suggestion for the line below/above:
![image](https://user-images.githubusercontent.com/1157936/135586094-18ec4519-2959-42d7-8a48-d850b41b5658.png)

Then when I update the snippet to fix the pyright error to:
```python
def dictionary_get():
    dictionary = {}
    data = ""
    if "message" in dictionary:
        data = dictionary["message"]
   return data
```
CocDiagnostics lists no more pyright errors, only the same sourcery suggestion:
```
test.py|3 col 1 info| [sourcery refactoring/diagnostic] Sourcery - Replace if statement with if expression, Simplify dictionary access using default get, Inline variable that is immediately returned [I]
```
And <Plug>(coc-codeaction) shows the sourcery suggestion with the cursor on any line in the buffer and  <Plug>(coc-codeaction-line) shows the suggestion on L2, L3 and L4, as you would expect.

It appears the pyright error is swallowing the coc-codeaction sourcery suggestion for the entire buffer and the coc-codeaction-line sourcery suggestion on the line where the pyright error occurs. Whether this is an issue with pyright, coc-nvim or sourcery I can't say...

Finally, note that doHover does work on the line with the pyright error (for the original snippet):
![image](https://user-images.githubusercontent.com/1157936/135586971-ae11291c-b4e5-4d70-b964-c229b96e7a20.png)
It's just the codeaction that doesn't work (annoyingly).
