### ISSUE TITLE
No code action available when calling :CocAction

### ISSUE THREAD

**Issue by dob9601** [fannheyward/coc-pyright#173]
Whenever I call :CocAction, I get told that there are no code actions available - not even general ones such as sorting imports or formatting. Is this intended? I've tried reinstalling several times but with no change. I'm in the process of switching from coc-python to coc-pyright - so far I've found it to be great, aside from this

**Comment by fannheyward** [comment]
Yes. You can use `:CocCommand pyright.organizeimports` to sort imports.
