### ISSUE TITLE
What is the equivalent configuration of `venv` property?

### ISSUE THREAD

**Issue by TonalidadeHidrica** [fannheyward/coc-pyright#176]
I can use `venv` property in `pyrightconfig.json` .  Is there an equivalent Coc configurations, like `python.venv` or something?

**Comment by fannheyward** [comment]
Yes, it's `python.venvPath`.

**Comment by TonalidadeHidrica** [comment]
In pyright, there are two configurations concerned with virtual environment: `venv` and `venvPath`.  ([link](https://github.com/microsoft/pyright/blob/master/docs/configuration.md))  If you want to use specific virtual environment, you should set both `venv` and `venvPath` in `pyrightconfig.json`, as described [here](https://github.com/microsoft/pyright/blob/master/docs/import-resolution.md#configuring-your-python-environment).  However, in `coc-pyright` there are only one property `python.venvPath`.  I specified the path to the virtual environment to `pyrhon.venvPath`, but it didn't work.  So I suspect I need some way to specify both of them.

**Comment by fannheyward** [comment]
coc-pyright uses the same configurations as vscode-pyright, https://github.com/microsoft/pyright/blob/master/packages/vscode-pyright/package.json#L669.

**Comment by TonalidadeHidrica** [comment]
I see, so I'd better send a question to `vscode-pyright`.  Thanks
