### ISSUE TITLE
Signature help fails on method defined below current line

### ISSUE THREAD

**Issue by SvanT** [fannheyward/coc-pyright#177]
```
class Test:
    def method1(self, param1):
        pass

    def method2(self, param1):
        pass
```

If you write `self.method2(` in method1 it will show autocomplete up until the parenthesis, but the signature help won't show up and this shows in CocOpenLog:
2020-12-07T20:53:48.491 WARN (pid:51074) [Handler] - signature help provider not found!

However if you go to method2 and write `self.method1(` the signature help works just fine, and in vscode with pylance both cases work (which I guess is using the same pyright backend for this).

**Comment by fannheyward** [comment]
Tested with VSCode + Pyright, same issue. You should use https://marketplace.visualstudio.com/items?itemName=ms-pyright.pyright to do testing, not Pylance, since Pylance needs VSCode Python.
