### ISSUE TITLE
could not be resolved if use pyenv local 

### ISSUE THREAD

**Issue by Junnplus** [fannheyward/coc-pyright#184]
I use pyenv for manage virtualenv of python, but if use `pyenv local`(.python-version file in local dir) in coc-pyright, raise reportMissingImports error on import something.
![image](https://user-images.githubusercontent.com/8097526/101623445-6b30f800-3a53-11eb-969d-23cb2aa68a2c.png)

`pyenv shell` is working. PYENV_VERSION environment variable can be accepted.

**Comment by psacawa** [comment]
I'm also encountering this.

**Comment by fannheyward** [comment]
Do you have set `python.pythonPath` in coc-settings.json? What's the value?

**Comment by Junnplus** [comment]
@fannheyward I try to set `python.pythonPath` as `/Users/jun/.pyenv/shims/python` is invalid, now I unset `python.pythonPath`

**Comment by yaegassy** [comment]
@Junnplus 

Setting the `venvPath` correctly may solve the problem.

- Place `pyrightconfig.json` in the project root and set the `venvPath` correctly
- Or set `python.venvPath` correctly in `coc-settings.json`

**Comment by Junnplus** [comment]
@yaegassy `pyrightconfig.json` is working, but is not optimal, everyone project maybe place a file.
In addition, I try to use `python.venvPath`, not working

**Comment by nacknime-official** [comment]
I'm also encountering this, but with pipenv.
It'll be very nice if this awesome plugin will able to search environment by itself, just like coc-python.

**Comment by fannheyward** [comment]
@Junnplus sorry for the delay. Can you test your case with VSCode + https://marketplace.visualstudio.com/items?itemName=ms-pyright.pyright, note: you should not enable VSCode Python or Pylance.

**Comment by ryanbyon** [comment]
Hi, I am also having the same problem but I am using pipenv instead. Should I create another issue? All of the installed packages are okay but all of the django apps that I created are being unable to be resolved. Thank you for your help :)

**Comment by Junnplus** [comment]
@fannheyward i don't know how to set `pyenv local` about ms-pyright in VSCode. `pyrightconfig.json` in project root dir is working, but it's not my expected.

**Comment by fannheyward** [comment]
I'll test pyenv/pipenv later, trying to make it works with Pyright.

**Comment by rbpatt2019** [comment]
Some further diagnostic information that might be useful...running `pyright` from the command line in a directory that contains a `.python-version` file works as expected. I've tried this with both a globally installed version (`sudo npm install -g pyright`) and the version installed by coc-pyright (`~/.config/coc/extensions/node_modules/coc-pyright/node_modules/.bin/pyright`), both on the most recent version, 1.1.95. 

This suggests the error is somehow tied to the way the plugin is looking for the environment with `pyright`, though I haven't figured out where it might be. I'll keep looking! Thanks for the awesome plugin!

**Comment by rid-32** [comment]
Hi! I have the same problem. I install venv using: python -m venv env. In the folder with my project: /home/user/src/python/project.

After that I install pymongo using: pip install pymongo. The package is placed now in the /home/user/src/python/project/env/lib/python3.9/site-packages/. I have an error: Import "pymongo" could not be resolved, when I try to import it via: from pymongo import MongoClient.

I added the pyrightconfig.json with the following content:
{
  "venvPath": "/home/user/src/python/project",
  "venv": "env",

  "pythonVersion": "3.9",
  "pythonPlatform": "Linux"
}

But it didn't solve the problem. Can anyone help me with this, please?

**Comment by yaegassy** [comment]
@rid-32 

Is the "workspace folder" resolved with the correct directory name?

Try to do `:echo WorkspaceFolders` or `CocCommand workspace.workspaceFolders`

Does the output show the name of the directory where `pyrightconfig.json` is located?

If nothing is displayed or the correct directory is not displayed, you may want to put the following settings in `.vimrc` or `init.vim`.

```
au FileType python let b:coc_root_patterns = ['.git', '.env', 'venv', '.venv', 'setup.cfg', 'setup.py', 'pyrightconfig.json', 'env']
```

----

Ref: Resolve workspace folder https://github.com/neoclide/coc.nvim/wiki/Using-workspaceFolders

**Comment by laixintao** [comment]
> Also bumping into this issue. I've tried setting `python.pythonPath` to both `python` and `/home/rbpatt2019/.pyenv/shims/python`. both to no avail. As all my virtualenvs with pyenv live in a single directory, I've tried specifying `python.venvPath` as `/home/rbpatt2019/.pvenv/versions`, also to no avail. The only solution I've found that delivers a working system is to specify both `venvPath` and `venv` in a local `pyrightconfig.json`. Specifying `python.venvPath` in the coc-settings.json had no effect, even if I specified `venv`in a local `pyrightconfig.json`.
> 
> As long as the environment variable "PYENV_VERSION" gets set, then pyright detects everything correctly. For some reason, `pyenv local` does not set this variable, while `pyenv shell` does. I was actually able to force this by deleting my `.python-version` file and manually exporting the "PYENV_VERSION" variable! Not sure what's happening under the hood with pyright or pyenv, but the fact that `pyenv local` does not set "PYENV_VERSION" is documented [here](https://github.com/pyenv/pyenv) under "Choosing the pyhton version".

The message that `PYENV_VERSION` will work is very helpful, thanks!

My solution is settings this variable in `.envrc` which controlled by https://direnv.net/ . It works perfect.

**Comment by PatrickMassot** [comment]
For information: experiments here suggest that coc-pyright is using the python version that pyenv decides to use when sitting inside the folder containing the pyright executable (`$HOME/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/` on my system). Setting the environment variable `PYENV_VERSION` (for instance using `pyenv shell`) works here (but it somehow defeats the purpose of pyenv).

**Comment by fannheyward** [comment]
coc-pyright v1.1.106 adds support for `pyenv local`, please give it a try.

**Comment by pauloalem** [comment]
@fannheyward there's one problem with the fix in that pyenv local allows for setting more than one python with it: https://github.com/pyenv/pyenv/blob/master/COMMANDS.md#pyenv-local-advanced.
So I've been hit with an error message such as:
```
[coc.nvim]: pyenv: version `venv-foo
another-python-venv' is not installed (set by PYENV_VERSION environment variable)
```
I'm not sure how we could fix this edge case.

**Comment by kevr** [comment]
Do we specifically **have** to use a pyrightconfig.json? I'd like to set it up in coc-settings.json...

**Comment by fannheyward** [comment]
@kevr the `pyrightconfig.json` is used in Pyright https://github.com/microsoft/pyright/blob/main/docs/configuration.md
