### ISSUE TITLE
Built-in docstrings

### ISSUE THREAD

**Issue by YodaEmbedding** [fannheyward/coc-pyright#187]
Docstrings for third-party libraries and custom functions work. Would it be possible to reallow builtin functions (e.g. `print`) to also display docstrings?

See here for more information: https://github.com/microsoft/pylance-release/issues/49

**EDIT:** Whoops, I meant to raise this issue in the pyright repository. Please close if it's not relevant.

**Comment by fannheyward** [comment]
https://github.com/microsoft/pylance-release/issues/49#issuecomment-740131435

> the functionality to do this is implemented in Pylance

Pyright doesn't support this.
