### ISSUE TITLE
workspaceSymbols very slow

### ISSUE THREAD

**Issue by ashb** [fannheyward/coc-pyright#188]
I work with a large code base (apache/airflow) and workspaceSymbols `:CocList -I symbols` is very slow, and I pay that cost each time I have to use it.

I'm not sure if this is issue belongs here or in pyright itself, but I was wondering if there is some option so this could be cached?

**Comment by fannheyward** [comment]
Pyright's issue, AFAIK there is no configuration to do caching.

**Comment by ashb** [comment]
Pyright said "not out responsiblity -- we do that in Pylance" (issue 1997 in pyright -- making a url to avoid linking issues unnecessarily)

**Comment by ashb** [comment]
It looks like pyright _does_ have support for indexing, but it's not exposed vIa the LSP, only to node js

https://github.com/microsoft/pyright/blob/c64baa0f02a97d11280bfb06a5393e7b3590fc2e/packages/pyright-internal/src/languageService/documentSymbolProvider.ts#L138-L156

**Comment by fannheyward** [comment]
Checked the 1997 issue, if Pyright has no plan to to this, it's hard for coc-pyright to do this.

> it's not exposed vIa the LSP, only to node js

What do you mean this?

**Comment by ashb** [comment]
I have to admit I get a bit lost looking through the pyright code, and haven't worked out how the LSP messages map to functions. (Does LSP even matter here, or does COC speak to coc-pyright which runs pyright code directly?)

But: it does look like there is _some_ support in pyright for caching, which we might be able to use here?

**Comment by fannheyward** [comment]
> Does LSP even matter here

LSP defines [Workspace Symbols Request](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#workspace_symbol), when you do `:CocList -I symbols`, coc sends `workspace/symbols` request to LS, here is Pyright, and Pyright sends results back. We can't run Pyright code directly.

> there is some support in pyright for caching

How did you confirm this?

**Comment by ashb** [comment]
I.... can't. I thought when I looked the other day I saw something but looking at the code again I can no longer see anything like it.

I must have mis-parsed the code in my haste :/

**Comment by ashb** [comment]
Ah, I might have been thinking of this bit of code https://github.com/microsoft/pyright/blob/c64baa0f02a97d11280bfb06a5393e7b3590fc2e/packages/pyright-internal/src/analyzer/program.ts#L1356-L1359

**Comment by fannheyward** [comment]
If Pyright supports caching, coc-pyright already used it.
