### ISSUE TITLE
python.venvPath config setting does not expand variables

### ISSUE THREAD

**Issue by ashb** [fannheyward/coc-pyright#189]
I'm migrating from coc-python, and I have this in my global config file

```
  "python.venvPath":"~/.virtualenvs",
```

Previously this worked, but now I see the following message in the pyright output:

```
[Error  - 12:17:32] venvPath /home/ash/code/airflow/airflow/~/.virtualenvs is not a valid directory.
```

I also tried with `$HOME`, neither worked.

Please could one of these expansion mechanisms work before the config is passed on to pyright?

**Comment by fannheyward** [comment]
No, Pyright server gets configurations by sending `workspace/configuration` to client, coc responses contents from package.json, so expansion does nothing.

**Comment by ashb** [comment]
Expansion used to work for the previous provider.

I'd really like to not have to have a custom config per machine I run on (where my username is different).

Are you saying this isn't possible and we can't fix it? Should I open this as a feature request against pyright?

**Comment by fannheyward** [comment]
> Expansion used to work for the previous provider.

What do you mean previous provider?

**Comment by ashb** [comment]
coc-python, sorry.

Anyway your comment was enough to point me in the right direction, and I have opened https://github.com/microsoft/pyright/pull/1267

**Comment by ashb** [comment]
For anyone coming across this issue, the fix is (or will be when next pyright release happens) is to use `${env: HOME}`

**Comment by ashb** [comment]
@fannheyward A question about developing this extension/pyright itself using this: is there any easy way I can point at a custom pyright install? I'm trying to debug the above linked issue and would like to do so in by running it "as I normally do" -- from within nvim.

Is this possible?

**Comment by fannheyward** [comment]
Replace your build with `~/.config/coc/extensions/coc-pyright/node_modules/pytight`

**Comment by g6ai** [comment]
> For anyone coming across this issue, the fix is (or will be when next pyright release happens) is to use `${env: HOME}`

Could you elaborate how to make this work? I tried to set it to:

```json
"python.venvPath": "${env: HOME}/.pyenv/versions"
```

but no luck. (The absolute path, for me its `/Users/gbai/.pyenv/versions`, is working)

**Comment by ashb** [comment]
@g6ai This is what I have in my global coc-settings.json

```json
  "python.venvPath":"${env:HOME}/.virtualenvs",
```

Probably no space after the `:`

**Comment by g6ai** [comment]
@ashb You are right, it works!

**Comment by ashb** [comment]
Updated my original comment.

**Comment by Dhruv-mak** [comment]
I have ```virtualenv``` already installed. But I can't find any ```~/.pyenv```, ```~/Envs```, ```~/.virtualenvs```. I am using windows. What should be the value of ```pyhton.venvPath``` in my ```coc-settings.json```.
