### ISSUE TITLE
"python.linting.enabled": false Do not work

### ISSUE THREAD

**Issue by zhouyangnk** [fannheyward/coc-pyright#210]
I just use pyright's goto definition and goto reference, so I try to set "python.linting.enabled": false in coc-settings.json, but this setting do not work
`
{
    "python.linting.enabled": false,
}
`

**Comment by fannheyward** [comment]
`"python.linting.enabled": false` will disable Pylint/flake8/xxx linting, but not Pyright's lint.

**Comment by yaegassy** [comment]
@zhouyangnk It is possible to stop the lint of pyright by setting the diagnostic of coc.nvim itself to false.

```
{
  "diagnostic.enable": false
}
```

**Comment by zhouyangnk** [comment]
> @zhouyangnk It is possible to stop the lint of pyright by setting the diagnostic of coc.nvim itself to false.
> 
> ```
> {
>   "diagnostic.enable": false
> }
> ```

Thanks! 
This worked
