### ISSUE TITLE
Separate virtualenv for nvim + coc-pyright and project.

### ISSUE THREAD

**Issue by karolius** [fannheyward/coc-pyright#216]
I want to use two different virtualenvs, one for pyright utils like formatting, linting etc. and different for each project, so i in `init.vim` i `set let g:python3_host_prog = '/home/user/.virtualenvs/nvim/bin/python'` as base env named **nvim**, activate it, then add a `pyrightconfig.json` with `{"venvPath": "/home/user/.virtualenvs", "venv": "proj-venv"}`. When open project files pylint shows import errors on third party libs, but all pyright functionality works. If mix both virtualenvs and install all project requirements on **nvim** virtualenv the problem is solved, but it's not a clean solution.

**Comment by FalseDev** [comment]
Linting is not really possible from a different venv. They work based upon typedefs based on your packages, if the packages aren't visible, then you'll only get import-errors from the linter
