### ISSUE TITLE
venv black is not used for formatting

### ISSUE THREAD

**Issue by maxcountryman** [fannheyward/coc-pyright#220]
It seems that even though black is installed into the relevant virtualenv, coc-pyright is not utilizing it. There doesn't seem to be an error, instead when the formatter runs nothing appears to happen. However if I run the formatter directly, i.e. in the activated virtualenv, then it works as expected.

**Comment by willir** [comment]
I think I have similar behavior, I have black installed through my system package manager (`aptitude`), but it doesn't seem to call it, just reports - `Formatted with black`

**Comment by fannheyward** [comment]
coc-pyright v1.1.97 adds more formatting logs, you can get it by: `:CocCommand workspace.showOutput` - `coc-pyright-formatting`.
