### ISSUE TITLE
pyright reportMissingImports and setting project root directory

### ISSUE THREAD

**Issue by ryanbyon** [fannheyward/coc-pyright#221]
Hi, as I mentioned in [this issue](https://github.com/fannheyward/coc-pyright/issues/184#issue-760242610), the pyright is producing reportMissingImports warning  when I am trying to import anything from my own django apps. 
I believe the issue is related to where my project root is set.
below is my working directory.

```
project  (this is what pyright thinks the cwd is)
| -- django_project   (this should be the cwd)
|    | -- manage.py
|    | -- Pipfile
|    | -- my_app
|    | --  ....rest of files and folders
|
|-- .git
|-- ... rest of files and folders
```

The lsp should think of the `django_project` as the root of working directory but instead thinking `project` as the working directory since the `.git` lives there. Therefore, when I try to use the auto import feature, it imports as `from django_project.my_app.models import ....`.

I tried to set `autocmd FileType python let b:coc_root_patterns = ["Pipfile"]` on my nvim config file to override the working directory to be where the `Pipfile` is, and it works for coc-explorer but coc-pyright still does not work properly.

Is there any way to set cwd correctly to remove the warnings?

Thank you for your help in advance, and happy holidays!

**Comment by fannheyward** [comment]
Put a `pyrightconfig.json` under django_project and try again, you can set it to empty JSON, `{}`.

https://github.com/microsoft/pyright/blob/master/docs/configuration.md
