### ISSUE TITLE
Configure signature help for readability

### ISSUE THREAD

**Issue by ApolloBian** [fannheyward/coc-pyright#224]
The signature help provided by pyright is too overwhealming and complicated for quick help. It is cluttered with type suggestions etc. Is there a way to configure the signature help formatting to be more like python-language-server?

pyright:
![image](https://user-images.githubusercontent.com/13659369/103191246-2b9d5380-490f-11eb-82a0-a42af18dfa77.png)

python-language-server:
![image](https://user-images.githubusercontent.com/13659369/103191280-525b8a00-490f-11eb-8c0b-27d929397143.png)

**Comment by fannheyward** [comment]
Do you mean hover document? The screenshot you posted is not signature help.

The function document is came from Pyright, it's difficult for us to extract useful information from documents, because they are just strings.
