### ISSUE TITLE
Support shebang-only Python file

### ISSUE THREAD

**Issue by fannheyward** [fannheyward/coc-pyright#228]
#202

**Comment by yaegassy** [comment]
@fannheyward @gasull

Shebang-only python files are now supported in pyright 1.1.98.

> Behavior Change: Eliminated restriction that prevented the analysis of text files that don't end in ".py" or ".pyi".

I tried it in my environment, and it worked fine.

**Related:**

- https://github.com/microsoft/pyright/releases
- https://github.com/microsoft/pyright/commit/c03e8c309e936d970d2df7f4ba858ff438772bc5
