### ISSUE TITLE
Failed to install on windows

### ISSUE THREAD

**Issue by dianlujitao** [fannheyward/coc-pyright#230]
Looks like a dependency issue of coc, but other plugins install fine and the error does NOT occur on Linux with the same npm/node version.
```
124 error code ERESOLVE
125 error ERESOLVE unable to resolve dependency tree
126 error
127 error Found: @types/node@14.14.16
127 error node_modules/@types/node
127 error   dev @types/node@"^14.11.8" from the root project
127 error   @types/node@"*" from @types/fs-extra@9.0.6
127 error   node_modules/@types/fs-extra
127 error     dev @types/fs-extra@"^9.0.2" from the root project
127 error   1 more (@types/md5)
127 error
127 error Could not resolve dependency:
127 error dev coc.nvim@"^0.0.80" from the root project
127 error
127 error Conflicting peer dependency: @types/node@10.12.0
127 error node_modules/@types/node
127 error   peer @types/node@"10.12.0" from coc.nvim@0.0.80
127 error   node_modules/coc.nvim
127 error
127 error Fix the upstream dependency conflict, or retry
127 error this command with --force, or --legacy-peer-deps
127 error to accept an incorrect (and potentially broken) dependency resolution.
```
[full log](https://fars.ee/FXpM)
[eresolve-report.txt](https://fars.ee/WmrO)

**Comment by fannheyward** [comment]
I don't have a Windows env to debug this issue.

**Comment by grimgort** [comment]
i have same error

**Comment by dianlujitao** [comment]
FYI this could be a bug of npm 7.3.0, coc-explorer failed to install as well yet a completely different error https://github.com/weirongxu/coc-explorer/issues/351

**Comment by fannheyward** [comment]
@dianlujitao  Can you test the latest master?

**Comment by dianlujitao** [comment]
> @dianlujitao Can you test the latest coc release and coc-pyright?

It works now, thanks for the fix!

**Comment by dianlujitao** [comment]
@fannheyward I'm not sure if this is the right place to report, but can u apply the fix to https://github.com/neoclide/coc-html ? It suffers from the same problem.
