### ISSUE TITLE
can't seem to resolve reportMissingImports with coc-pyright on my python3.9 venv on neovim

### ISSUE THREAD

**Issue by siu3334** [fannheyward/coc-pyright#235]
Hi, I recently switched to neovim from vim yesterday and installed coc-pyright with it since coc-python's README recommended it, I have a python3.9 venv at /opt/, I have extensively searched through issues here and found #87 similar to my issue. I have even installed `pynvim` in my venv with `python -m pip install pynvim` and added this line in my neovim init.vim:
```
let g:python3_host_prog = '/opt/bin/python'
```

Here is my output of `CocInfo`:
```
## versions
    
vim version: NVIM v0.4.3   
node version: v15.5.0
coc.nvim version: 0.0.80-cf0e8400a4
coc.nvim directory: /home/ubuntu/.config/nvim/plugged/coc.nvim
term: xterm-256color
platform: linux 
        
## Log of coc.nvim

2021-01-01T06:53:11.766 INFO (pid:4799) [services] - registered service "eslint"
2021-01-01T06:53:11.841 INFO (pid:4799) [services] - registered service "pyright"
2021-01-01T06:59:31.454 INFO (pid:4907) [services] - Pyright Server state change: stopped => starting
2021-01-01T06:53:11.926 INFO (pid:4799) [plugin] - coc.nvim 0.0.80-cf0e8400a4 initialized with node: v15.5.0 after 316ms
2021-01-01T06:53:11.945 INFO (pid:4799) [language-client-index] - pyright started with 4920
2021-01-01T06:53:12.251 INFO (pid:4799) [services] - Pyright language server state change: starting => running
2021-01-01T06:53:12.260 INFO (pid:4799) [services] - service pyright started
2021-01-01T06:53:15.585 INFO (pid:4799) [attach] - receive notification: showInfo []
```

I have added `pyrightconfig.json` on my venv root folder at `/opt/`:
```json
{
    "include": [
        "**/site-packages",
        "**/cogs",
        "**/core"
    ],

    "exclude": [
        "**/__pycache__"
    ],

    "executionEnvironments": [
        {
            "root": "lib/python3.9/site-packages",
            "pythonVersion": "3.9",
            "pythonPlatform": "Linux"
        }
    ],

    "venvPath": "/opt",
    "reportMissingImports": true,
    "pythonVersion": "3.9",
    "pythonPlatform": "Linux"
}
```

and here is my `coc-settings.json` stored at `~/.config/nvim/`:
```json
{
    "python.pythonPath": "/usr/bin/python3.9",
    "python.venvPath": "/opt/"
}
```
even with these settings, whenever I open any `*.py` file, I get pyright showing warning about missing imports althought those packages are already present in my venv site-packages: `/opt/lib/python3.9/site-packages`

Is there anything I did wrong or I missed in these settings? I apologise for any inconvenience I'm still new with pyright, if someone can help me out I would be really grateful. 🙏🏼

**Comment by fannheyward** [comment]
The `pyrightconfig.json` file should be put at your project root, not venv root.

**Comment by siu3334** [comment]
hi, I did what you suggested but pyright still not able to resolve missing imports.
my venv root is at /opt/
my project root is at /opt/cogs/CogManager/cogs/
and all pip packages are installed at /opt/lib/python3.9/site-packages/

I'm probably doing something wrong but I can't seem to figure out what it is haha. 😄

**Comment by morsecodist** [comment]
I am having the exact same issue on neovim. I added `pyrightconfig.json` at the project root but it won't recognize any of my local imports.

**Comment by jeeeem** [comment]
> I am having the exact same issue on neovim. I added `pyrightconfig.json` at the project root but it won't recognize any of my local imports.
> 
> Update: Just solved my issue. It seems the coc extension recognizes the root of your git repo as the root not the directory you open. I was using a subdirectory of a monorepo as my root and opening that with neovim on it's own. I just moved the `pyrightconfig.json` to the correct root and added the prefix of my sub-directory to the root path in an execution environment and it worked.

Can you type here exactly what you input in the `pyrightconfig.json` Im new to configuring this Im not sure if I'm doing this right.

**Comment by morsecodist** [comment]
So I have a big monorepo that looks kind of like:
```
- some-parent/
  - my-module/
  - some-other-stuff/
- some-other-parent
```

and my `pyrightconfig.json`:

```
{
    "executionEnvironments": [
        {
            "root": "some-parent/my-module"
        }
    ]
}
```

**Comment by HansPinckaers** [comment]
I just upgraded my coc-pyright, and thus I guess pyright too. It does not seem to find my pyrightconfig.json anymore. The linked website on the README is mine (https://hanspinckaers.com/fixing-coc-pyright-and-anaconda-import-errors), but this method thus doesn't work anymore for me.

Do you know if anything changed recently @fannheyward ?

I can try to pinpoint which version of pyright worked for me. Using older version of coc-pyright didn't do the trick, so pretty sure it's pyright itself.

**Comment by yaegassy** [comment]
@HansPinckaers Is the "workspace folder" resolved with the correct directory name?

How about trying this issue comment once? https://github.com/fannheyward/coc-pyright/issues/184#issuecomment-759878973

**Comment by fannheyward** [comment]
@HansPinckaers goto `~/.config/coc/extensions/node_modules/coc-pyright`, change Pyright version in package.json to older version and try again.

coc-pyright has not changed anything about module imports lately.

**Comment by HansPinckaers** [comment]
Hi all, thanks for the help, turned out trying a new conda environment worked. The environment I used had some package "inconsistencies", not sure if related, but it works perfectly with a new environment (unrelated: I used [mamba](https://github.com/mamba-org/mamba) this time, which I did not know, but is amazing).

**Comment by felippemr** [comment]
I am having a similar problem. Just migrated from coc-python and the `setInterpreter` command is not appearing on `CocCommand`(even when I have a python file opened). All my imports from the virtual env are currently broken.

**Comment by yaegassy** [comment]
@felippemr There is no setInterpreter command in coc-pyright.

It is recommended that you activate the virtual environment, then go to the project root and launch Vim/Neovim.

If you still cannot import correctly, place `pyrightconfig.json` in the project root and settting `venvPath` and `venv` appropriately.

----

**Example: pyrightconfig.json**

If the location of your virtual environment is `/path/to/projectroot/.venv`.

```
{
  "venvPath": "/path/to/projectroot"
  "venv": ".venv"
}
```

**Comment by felippemr** [comment]
Thanks @yaegassy. I tried that, but it didn't work. Here is how I configured it.
```
{
   2   │   "venvPath": "/Users/felippe.raposo/.pyenv",
   3   │   "venv": ".python-version"
   4   │ 
}
```

**Comment by yaegassy** [comment]
Are any of the people listed in this issue still having trouble with reportMissingImports?

The latest version of coc-pyright (v1.1.106) adds support for pyenv, pipenv, and poetry, which may further alleviate the import problem.

You all might want to give it a try.

**Comment by fannheyward** [comment]
I'm going to close this issue, open a new issue if you still has this error.

**Comment by keevee09** [comment]
yaegassy's solution works for me --- neovim v5.0, coc-pyright, pyenv.

`{` 
`    "venvPath": "pyn",`
`    "venv": "/home/chris/.pyenv/versions/3.9.0/envs" `
`}`
