### ISSUE TITLE
`gd` command goes to .pyi file instead of source file

### ISSUE THREAD

**Issue by sify21** [fannheyward/coc-pyright#245]
When I run `gd` on built-in function or class, it goes to the .pyi file, which isn't very helpful. Can it go to the source file?

**Comment by fannheyward** [comment]
It's expected, as Pyright directs to the `.pyi` file.

**Comment by sify21** [comment]
Hi @fannheyward , it seems currently pyright will display both the .pyi files and py files, see https://github.com/microsoft/pylance-release/issues/65 and https://github.com/microsoft/pyright/issues/795. But when I run gd it only goes to the pyi file, do I have the option to go to the source file?

**Comment by sify21** [comment]
It seems some will show available options, for example dataclasses.dataclass;  but some will just go to .pyi, for example typing.ContextManager

**Comment by fannheyward** [comment]
> but some will just go to .pyi

Looks like Pyright can't find the py file for it.

**Comment by meandmymind** [comment]
@fannheyward seems pylance [fixed ](https://github.com/microsoft/pylance-release/issues/65#issuecomment-776354122)the issue by somehow separating go-to-definition and go-to-declaration, first going to .py files, second going to .pyi. Can coc-pyright do something similar?
