### ISSUE TITLE
always uses autopep8

### ISSUE THREAD

**Issue by kaldown** [fannheyward/coc-pyright#247]
1) it won't work for me if you use `python.*` as a key:
```
{
        "venvPath": "/home/kaldown/.cache/pypoetry/virtualenvs",
        "venv": "api-ohFkNBde-py3.9",
        "formatting.provider": "black"
        "python.formatting.provider": "black"
}
```

2) this doesn't work for *black*
```
:Format
[coc.nvim] Formatting with autopep8 failed. autopep8 module is not installed.
[coc.nvim] Formatted with autopep8
```

Logs from *pyright-formatting*
```
########## active formattor: autopep8
execPath:   autopep8
moduleName: autopep8
args:       --diff,/home/kaldown/projects/api/api/user.py.637c8314dedc40677769355f0c7e1395.py
########## Formatting with autopep8 failed
Formatting with autopep8 failed. autopep8 module is not installed.
Module 'autopep8' not installed.
```

**Comment by fannheyward** [comment]
> active formattor: autopep8

coc-pyright gets the configuration from coc-settings.json, are you using local coc-settings.json? What's your `:CocConfig` and `:CocLocalConfig`?

**Comment by kaldown** [comment]
No, I use `pyrightconfig.json` looking through issues.
There is no info about `pyrightconfig.json` nor `coc-settings.json`. Which one is the right one?

**Comment by kaldown** [comment]
`:CocConfig` is opening an empty `~/.config/nvim/coc-settings.json`
`:CocLocalConfig` asking me to create `.vim` folder inside current directory, which I don't need actually.

**Comment by fannheyward** [comment]
`"python.formatting.provider": "black"` should be set in your `:CocConfig`.

**Comment by kaldown** [comment]
whats `pyrightconfig.json` then? You've mentioned this as a reference to store configs for a particular project.

**Comment by fannheyward** [comment]
`pyrightconfig.json` is used by Pyright, https://github.com/microsoft/pyright/blob/master/docs/configuration.md

The `python.*` configurations listed in README is used by coc-pyright, which are set and read by coc.nvim, you need to set them in `coc-settings.json`. I'll update the README to describe it clearly.

**Comment by kaldown** [comment]
what's the point of setting `venvPath` if you sourcing it anyway? https://github.com/fannheyward/coc-pyright#my-workflow-with-pyright

**Comment by kaldown** [comment]
With the approach of sourcing venv you have to install staff that can be outside of a project scope.
Like `neovim`:
```
:checkhealth

## Python 3 provider (optional)
    - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
    - ERROR: Python provider error:
      - ADVICE:
        - provider/pythonx: Could not load Python 3:
            /home/kaldown/.cache/pypoetry/virtualenvs/dorm-api-ohFkNBde-py3.9/bin/python3 does not have the "neovim" module. :help provider-python
            python3.7 not found in search path or not executable.
            python3.6 not found in search path or not executable.
            python3.5 not found in search path or not executable.
            python3.4 not found in search path or not executable.
            python3.3 not found in search path or not executable.
            /home/kaldown/.cache/pypoetry/virtualenvs/dorm-api-ohFkNBde-py3.9/bin/python does not have the "neovim" module. :help provider-python
    - INFO: Executable: Not found
```

**Comment by kaldown** [comment]
`let g:python3_host_prog="/usr/bin/python" solved a problem with `:checkhealth`
