### ISSUE TITLE
jumping outside of current virtualenv

### ISSUE THREAD

**Issue by kaldown** [fannheyward/coc-pyright#249]
I have my project with 
```
cat .vim/coc-settings.json
{
        "python.venvPath": "/home/kaldown/.cache/pypoetry/virtualenvs",
        "python.formatting.provider": "black"
}
```

and a file with:
```
# application.py
from flask.json import JSONEncoder
```

trying to follow definition of a `JSONEncoder` class it opens:
```
1)  /home/kaldown/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/typeshed-fallback/third_party/2and3/flask/json/__init__.pyi |6 col 7| class JSONEncoder(_json.JSONEncoder):
2)  /home/kaldown/.cache/pypoetry/virtualenvs/api-ohFkNBde-py3.9/lib/python3.9/site-packages/flask/json/__init__.py |61 col 7| class JSONEncoder(_json.JSONEncoder):
```

which is outside of my current `virtualenv` created via `poetry`.

Ho to restrict usage withing my my virtualenv?

**Comment by fannheyward** [comment]
The first line is `pyi` file which provides by Pyright, the second line is source file.

**Comment by kaldown** [comment]
> The first line is `pyi` file which provides by Pyright, the second line is source file.

Sure thing.
But I don't wont to mess my project with the tools being used outside of it.

I don't think this issue should be closed.
What do you think?

**Comment by fannheyward** [comment]
It's Pyright's behavior https://github.com/microsoft/pyright/issues/795#issuecomment-654277605
