### ISSUE TITLE
venvPath doesn't follow the environment

### ISSUE THREAD

**Issue by kaldown** [fannheyward/coc-pyright#250]
.vim/coc-settings.json
```
{
	"python.venvPath": "/home/kaldown/.cache/pypoetry/virtualenvs",
        "python.venv": "dorm-worker-qqMHwzdW-py3.9",
	"python.formatting.provider": "black"
}
```
everything looks correct according to this example:
https://github.com/fannheyward/coc-pyright/blob/c6d29cda7b1091e6b007aa21473b8beaab0753eb/schemas/pyrightconfig.schema.json#L428-L444

But I receive:
`[coc.nvim] definition not found` trying to access package being installed.

This directory is present.
```
$ pwd
/home/kaldown/.cache/pypoetry/virtualenvs/dorm-worker-qqMHwzdW-py3.9
```
![2021-01-11_659x137_scrot](https://user-images.githubusercontent.com/3754017/104153151-a4fa7300-53f2-11eb-86c6-4ca9dac1e46e.png)

I have to activate python shell in order to "see" installed packages.
But what's the point of `python.venvPath` if I still have to source?

**Comment by yaegassy** [comment]
Is it `coc-settings.json` that you are configuring? Or is it `pyrightconfig.json`?

There are some differences in the settings between `coc-settings.json` and `pyrightconfig.json`.

For `coc-settings.json`, please refer to here. https://github.com/microsoft/pyright/blob/master/docs/settings.md

For `pyrightconfig.json`, please refer to here. https://github.com/microsoft/pyright/blob/master/docs/configuration.md

**Comment by kaldown** [comment]
Thanks.
It's just weird for me to have local `coc-settings.json` and local `pyrightconfig.json`.
Why should I have both if they are related?
