### ISSUE TITLE
Change status line

### ISSUE THREAD

**Issue by kaldown** [fannheyward/coc-pyright#257]
On this example **E36** is not a part of a path, appears after `pyright` is loaded.
How to disable or move this from file path row?

![2021-01-14_295x16_scrot](https://user-images.githubusercontent.com/3754017/104547806-7a9df500-5640-11eb-9938-bb14f26ef9e9.png)

**Comment by fannheyward** [comment]
Can't reproduce, please check your statusline plugin.

**Comment by kaldown** [comment]
Have no plugin for statusline.

**Comment by fannheyward** [comment]
Do you have any other Python linter ?

**Comment by kaldown** [comment]
Nope. I was using Ale + ycm. Now only pyright with blake + pylint

**Comment by fannheyward** [comment]
coc will not change your statusline directly, most likely you've set some statusline function. Please test with minimal vimrc.
