### ISSUE TITLE
 Coc.nvim and coc.pyright require different node versions to work!

### ISSUE THREAD

**Issue by SubhamBurnwal** [fannheyward/coc-pyright#260]
I am on Ubuntu LTS 10.04, and I installed coc.nvim with vim-plug.
coc.nvim asks for v10.12 or something while the coc.pyright extension requires v12+. Whenever I install either of those, the previous one gets uninstalled.. I know this is the case because the warning pops up whenever I open Vim or whenever I open a python file(which turns on coc.pyright) What do I do?? I googled about this and asked it elsewhere and only resorted to open an issue since it was taking too many days to get help. Also, I would have asked this question in the "Discussions" area but I can't find that tab here in this repository..

**Comment by fannheyward** [comment]
coc needs node >= v10.12, not just v10.12, you can use v12 or above.
