### ISSUE TITLE
Disable hint-level diagnostics

### ISSUE THREAD

**Issue by patricknraanes** [fannheyward/coc-pyright#271]
Thanks for all the great work!

Is there any way to get rid of "hint" type diagnostics? See attached screenshot:
![hints](https://user-images.githubusercontent.com/7222967/105190039-e3e8a100-5b35-11eb-87c3-fb7181f3d131.png)

I've tried all of these with no luck:
```python
# pyright: reportGeneralTypeIssues=false
# pyright: reportUnusedVariable=false
# pyright: off
```

**Comment by yaegassy** [comment]
@patricknraanes  `[H]` (Hint) messages cannot be disabled by pyright.

If you change the `diagnostic.showUnused` or `diagnostic.level` setting in "coc-settings.json", it will not be displayed.

```
{
  // ...snip
  "diagnostic.showUnused": false,
  // ...snip
}
```

or

```
{
  // ...snip
  // Set level to information or higher
  "diagnostic.level": "information",
  // ...snip
}
```

**Comment by fannheyward** [comment]
https://github.com/microsoft/pyright/issues/982#issuecomment-684045241

> Pyright is using the "Unnecessary" tag, and VS Code uses that to determine which ranges to display in gray.

coc-pyright will remove the `Unnecessary` tag.

**Comment by fannheyward** [comment]
Releases with v1.1.103, `CocUpdate` and give it a try.

**Comment by fannheyward** [comment]
Maybe we should not remove `Unnecessary` support directly.

**Comment by fannheyward** [comment]
The latest coc-pyright, v1.1.103, has removed the `Unnecessary` tag support, Pyright will not return `Unnecessary` diagnostics, there is no conflict with `diagnostic.showUnused`.

I'll leave this issue open to see whether this will cause other unexpected problems.

**Comment by fannheyward** [comment]
https://github.com/neoclide/coc.nvim/blob/master/src/diagnostic/buffer.ts#L200

**Comment by HudsonMC16** [comment]
I'm not sure if this is related, but I am not receiving any unused notifications now. I can see unused import warnings with the appropriate diagnostic overrides set, but no unused variable diagnostics. Is this still under investigation? I'm using this config:
```
// vim: set filetype=jsonc
{
    "python.analysis.typeCheckingMode": "basic",
    "diagnostic.warningSign": "",
    "diagnostic.errorSign": "",
    "diagnostic.infoSign": "",
    "diagnostic.hintSign": "",
    "diagnostic.level": "information",
    "diagnostic.showUnused": true,
    "python.linting.enabled": true,
    "python.linting.pylintEnabled": true
    // "python.analysis.diagnosticSeverityOverrides": {
    //    "reportUnusedImport": "warning",
    //    "reportUnusedClass": "warning",
    //    "reportUnusedFunction": "warning",
    //    "reportUnusedVariable": "warning"
    // }
}
```
It does not appear any combination of diagnostic overrides or coc options produces the diagnostics. They do show up when using nvim lsp, however.

**Comment by HudsonMC16** [comment]
A bit of clarification:

I am receiving diagnostic warnings for variables declared but not used within that function's scope, but not for parameters included in the signature but not used within that function's scope. Perhaps this is handled by some other option?

**Comment by haoyun** [comment]
> A bit of clarification:
> 
> I am receiving diagnostic warnings for variables declared but not used within that function's scope, but not for parameters included in the signature but not used within that function's scope. Perhaps this is handled by some other option?

I'm having the same issue. The defaut behavior seems to have been changed and this change was introduced recently. I do benefit from those hints. So I rolled back to an previous version of coc-pyright.

`coc-pyright@1.1.101` works fine, but `coc-pyright@1.1.103` breaks.

**Comment by fannheyward** [comment]
@haoyun @HudsonMC16 try v1.1.113.

**Comment by HudsonMC16** [comment]
Still no dice: 
![image](https://user-images.githubusercontent.com/34110053/108774307-1b77ae00-7525-11eb-9ddf-13095ea8c880.png)

Only the `unused` variable is flagged, but not the unused `testing` function argument.

**Comment by yaegassy** [comment]
@HudsonMC16 In my environment, "v1.1.113" shows up fine.

<img width="391" alt="coc-pyirght-271-1" src="https://user-images.githubusercontent.com/188642/108782480-fcbdf980-75ae-11eb-98f0-839bb545d8cf.png">

Has your coc-pyright been updated to v1.1.113?

I checked your `coc-settings.json` in this comment. https://github.com/fannheyward/coc-pyright/issues/271#issuecomment-782259066

You have customized the `diagnostic.level`, so I think that is affecting it, Does it work correctly if you set your "diagnostic.level" to `hint` (default value) instead of `information`?

**Comment by lsaint** [comment]
> @patricknraanes `[H]` (Hint) level messages cannot be disabled by pyright.
> 
> If you change the `diagnostic.showUnused` or `diagnostic.level` setting in "coc-settings.json", it will not be displayed.
> 
> ```
> {
>   // ...snip
>   "diagnostic.showUnused": false,
>   // ...snip
> }
> ```
> 
> or
> 
> ```
> {
>   // ...snip
>   // Set level to information or higher
>   "diagnostic.level": "information",
>   // ...snip
> }
> ```

# pyright language server 1.1.113

```
@classmethod
def func(cls, a, unuse1):
    unuse2 = 2
    return a
```

in this case, cls and unuse1 are act the same.
how to turn ("cls" is not accessed) off and keep the message about unuse1 ?

**Comment by yaegassy** [comment]
@lsaint In that case, make sure to show the Hint level message. (`"diagnostic.showUnused": true`, or `"diagnostic.level": "hint"`)

Add `del cls` to your code and try it.

<img width="554" alt="coc-pyirght-271-2" src="https://user-images.githubusercontent.com/188642/108814073-8d1f2d00-75f5-11eb-8b95-bcd352a018f2.png">

**Comment by lsaint** [comment]
@yaegassy
I know that add `del cls` to function will disable the ("cls" is not accessed) message, but that's not i wanted.
Sometimes, It's normal for `self` or `cls` not in use in Python, i don't want it to be treated as a warning or error or hint.
But if other args such as `unuse1` should always be treated like a warning.

**Comment by yaegassy** [comment]
@lsaint Check the documentation of pyright itself to see if there are any control settings for diagnostic messages that you expect, and try them out. <https://github.com/microsoft/pyright/blob/master/docs/configuration.md#type-check-diagnostics-settings>

If the configuration you expect does not exist, you may want to suggest it in `pyright`'s itself GitHub issue or on gitter.

**Comment by alejo90** [comment]
Sorry, I'm a little confused. Is there a setting combination that would lead to `self` and `cls` not being marked as unused while other arguments that are unused remain marked as such?

**Comment by fannheyward** [comment]
You can disable the self not accessed hint from coc-pyright v1.1.129, set `pyright.disableSelfClsNotAccessed` in your coc-settings.json.

**Comment by lsaint** [comment]
https://github.com/fannheyward/coc-pyright/commit/89fe02ba15e7fc863ffcb86640ca075d31f84484

hmm, hard code, but it work well.
