### ISSUE TITLE
Add option to use isort for organizing imports

### ISSUE THREAD

**Issue by languitar** [fannheyward/coc-pyright#272]
The pyright configuration for organizing imports is pretty limited and isort is quite accepted in the Python community. Therefore, it would be nice if there was an option to use isort for organizing imports instead of or in addition to pyright itself. The old coc-python plugin did have isort support. Maybe this can be ported.

**Comment by fannheyward** [comment]
> organizing imports is pretty limited

What's the limit?

**Comment by yaegassy** [comment]
@languitar This is not directly related to the question of whether `coc-pyright` supports "isort", but coc-diagnostic can work with "isort".

https://github.com/iamcco/coc-diagnostic/pull/73

**Comment by languitar** [comment]
> What's the limit?

First, I have an existing isort configuration and compliance to that is built into my linting setup using flake8-isort.. I would have to rebuild this config with the available pyright options and getting two tools to agree onto the exact same thing is not that easy. Moreover, I can't even find a single configuration option regarding organize imports feature in [the config documentation](https://github.com/microsoft/pyright/blob/master/docs/configuration.md) and there is also [this issue](https://github.com/microsoft/pyright/issues/240) which states that this feature should never have made it into pyright.

> This is not directly related to the question of whether coc-pyright supports "isort", but coc-diagnostic can work with "isort".

Can I make a distinct action only for calling isort with coc-diagnostics that doesn't also include black etc.?

**Comment by languitar** [comment]
Nice, that was quick!

**Comment by yaegassy** [comment]
@languitar Is `python.sortImports.path` working correctly?

**Comment by fannheyward** [comment]
@yaegassy there is a bug with `python.sortImports.path`

**Comment by fannheyward** [comment]
@yaegassy fixed on master 14369d3f6ba244413ae667d6a60e151544d8893d

**Comment by yaegassy** [comment]
I had added console.log in isortProvider.ts and checked it, but could not see the value.

Here is my isort configuration.

```
{
  // ...snip
  "python.sortImports.path": "/Users/yaegassy/.local/bin/isort",
  // ...snip
}
```

It worked in coc-python.

As an additional note, `~/.local/bin/isort` cannot be executed in "coc-python".

You may be even happier if you can run it in `~/`.

**Comment by yaegassy** [comment]
@fannheyward I have checked with this setting.

```
  "python.sortImports.path": "/Users/yaegassy/.local/bin/isort",
```

or

```
  "python.sortImports.path": "~/.local/bin/isort",
```

Both worked fine!

**Comment by fannheyward** [comment]
@yaegassy you can use `python.isort.path` for now, I'll publish another release after Pyright release. I don't want to break the version number :D.

**Comment by yaegassy** [comment]
@fannheyward Of course. I think the next release of pyright (v1.1.106) will be perfectly fine.

**Comment by languitar** [comment]
For me everything works as expected. But I didn't have to set the path by hand so far.

**Comment by Clish254** [comment]
I've added 
`☰  ℅:1
[coc.nvim] Failed to format import by isort`
to my config but i'm still getting this error "[coc.nvim] Failed to format import by isort"

**Comment by yaegassy** [comment]
@Clish254 I have tried with this configuration and isort works fine. I can't reproduce it.

```vim
"python.sortImports.path": "~/.local/bin/isort",
```

Your configuration does not have a leading `"`, is this a typo?

Does `isort` exist in the path you set? try, `~/.local/bin/isort --version`
