### ISSUE TITLE
OOTB support for Pipfile / pipenv

### ISSUE THREAD

**Issue by ddnomad** [fannheyward/coc-pyright#273]
Hey, first of all, thanks for this project. So far it catches more issues comparing to `coc-python` and this is good.

However, one feature of `coc-python` I really liked is an out of the box support for Pipfile. From what I understand, `coc-python` was checking for `Pipfile*` (i.e. `Pipfile` and `Pipfile.lock`) inside the project root and then automatically "activating" the virtual environment, which makes it possible to resolve import errors for packages that are installed only inside the `pipenv` and not on the host.

As all projects I'm working on use `pipenv` as a standard to handle development environments, it is rather inconvenient to not have that supported by `coc-pyright`.

Any chance you can add `pipenv` support? I'd be happy to help as well, though my TS/JS skills are definitely lacking.

**Comment by betaboon** [comment]
I'm interested in something similar but using poetry.
I tried using https://github.com/petobens/poet-v which properly creates and activates the virtualenv but i cant figure out how to have pyright pick it up.

**Comment by fannheyward** [comment]
coc-pyright v1.1.106 adds support for pipenv and poetry, please give it a try.

**Comment by betaboon** [comment]
@fannheyward i don't understand how the provided changes would add support for poetry?
