### ISSUE TITLE
can't resolve numpy, scipy, etc

### ISSUE THREAD

**Issue by LXYYY** [fannheyward/coc-pyright#276]
Hi, I found coc-pyright can't resolve some of basic package like numpy and scipy. For example, I am using ros, and there is a package named ros_numpy, and I install ros_numpy through apt, which will install python-numpy as a dependency. But pyright can find ros_numpy, but not numpy. Do you guys have any idea?
And I am using python2, because thats what you get with ROS, and I saw somewhere before, pyright is trying to look for packages' stub file, and it's said old version of numpy doesn't provide this stub file. Is this the possible reason, version too old?

**Comment by fannheyward** [comment]
Pyright doesn't support Python 2. 

> Pyright provides support for Python 3.0 and newer. There is currently no plan to support older versions.

https://github.com/microsoft/pyright#limitations
