### ISSUE TITLE
FEATURE: add "python.autoComplete.addBrackets"

### ISSUE THREAD

**Issue by nacknime-official** [fannheyward/coc-pyright#277]
Automatically add brackets if suggesting element is a function or a method, like in `coc-rust-analyzer`.

Is it possible from your side or it's a task of Pyright?

**Comment by fannheyward** [comment]
It's completion snippet feature, should be provided by Pyright.

**Comment by walkert** [comment]
Realize this is closed but thought I'd comment that I've [asked](https://github.com/microsoft/pyright/issues/1450) about this over on the pyright repo. 🤞

**Comment by fannheyward** [comment]
coc-pyright has added this support, will be released later.
