### ISSUE TITLE
Is there any shortcuts to close the diagnostics/Location List

### ISSUE THREAD

**Issue by zhangchi0104** [fannheyward/coc-pyright#283]
Hi,

I'm new to `coc` and `coc-pyright`. I'm wondering if there is any keyboard shortcut to close the location list.
![image](https://user-images.githubusercontent.com/39239965/105947838-d470d700-60a4-11eb-9e37-e9671e311889.png)

**Comment by fannheyward** [comment]
`esc`, check `:h coc-list-mappings` and `:h coc-list-mappings-custom`.
