### ISSUE TITLE
Pyright reports issue type in popup box

### ISSUE THREAD

**Issue by roblevy** [fannheyward/coc-pyright#286]
In the screenshot in the README, coc-pyright reports its errors with:

```
[pyright] [E] ...
```

On my installation it reports errors with:

```
[Pyright reportGeneralTypeIssues] [E]
```

![very verbose](https://user-images.githubusercontent.com/4764631/106181490-8f789d80-6195-11eb-8bd2-c25634c5dca8.png)

This leads to a very wide popup box and looks a bit unattractive.

(I've also noticed that `'age' is not accessed'` doesn't come up for me. I wonder why that is?)

What in my config is different to yours?

## CocConfig

```
{
  "diagnostic-languageserver.filetypes": {
    "sh": "shellcheck",
    "python": "flake8"
  },
  "sql.database": "postgresql",
	"languageserver": {
		"terraform": {
			"command": "terraform-ls",
			"args": ["serve"],
			"filetypes": [
				"terraform",
				"tf"
			],
			"initializationOptions": {},
			"settings": {}
		}
	}
}
```

**Comment by yaegassy** [comment]
@roblevy A few days ago, the `[H]` diagnostics message was changed to not be displayed. See: https://github.com/fannheyward/coc-pyright/issues/271

**Comment by fannheyward** [comment]
For your first question, you can change the `diagnostic.format`.
