### ISSUE TITLE
Improve the signature help readability of the current parameter.

### ISSUE THREAD

**Issue by WachaDev** [fannheyward/coc-pyright#293]
On many other language servers, such as jedi, rust-analyzer, tsserver, etc.  When we type`(` triggers the signature help and highlight or underline the parameter that we are currently on. In Pyright this feature is not available.

And yes, I have this in my init.vim:

`autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')`

**Comment by fannheyward** [comment]
Try v1.1.108
