### ISSUE TITLE
FEATURE: Enable linting updates for unsaved buffers

### ISSUE THREAD

**Issue by walkert** [fannheyward/coc-pyright#301]
I'm wondering if there's any way for the linting updates to occur on unsaved buffers (or essentially 'live') vs the current state where updates are only visible after the current buffer is saved. This makes it feel more 'realtime'.

**Comment by walkert** [comment]
Interestingly, I just enabled `mypy` linting and notice that this updates 'live' in the current buffer as soon as you switch from insert to command mode. Both flake8 and pep8 don't exhibit this behaviour. Do you know why they appear to work differently?

**Comment by dirn** [comment]
@walkert are you sure mypy works on unsaved buffers? The only diagnostics I'm able to get are pyright's type checks. Linting on save seems to be a limitation of coc, not any particular extension. cic-python has the same limitation: https://github.com/neoclide/coc-python#faq.

**Comment by tsiq-walkert** [comment]
@dirn to be clear as I might be using the wrong terminology mypy works for me when I switch from input to command modes (no saving required). I read that in the coc-python faq but always assumed it was a limitation of that plugin, not coc itself.

**Comment by dirn** [comment]
@tsiq-walkert I assume you’re talking about using mypy through coc-pyright. I have that enabled myself and don’t receive any warnings from mypy until I save the buffer. That’s been my experience with coc-Python, coc-go, and now coc-pyright, that’s what leads me to believe it’s a limitation of coc itself, but I can’t say that with any degree of authority.

**Comment by tsiq-walkert** [comment]
Yup this is direct from coc-pyright. I can only assume I'm benefiting from a newer version of vim than you or I have some other setting enabled. The messages from coc-pyright don't require a save either so I just figured tools that it calls could do the same.

**Comment by fannheyward** [comment]
The _live_ linting is only supported by Pyright, all other linters, mypy/pylint/x, can only lint on save. The is not a limitation of coc or coc-pyright, it's limitation of language server.

Pyright support LSP, coc and coc-pyright, as a LSP client, sends the changes to Pyright, received the diagnostics and display. For mypy/pylint, coc-pyright does linting like `pylint main.py`, parses stdout/stderr and display them.

@tsiq-walkert 

> this is direct from coc-pyright

Does the diagnostics message contains something like `[Pyright]`? It's came from coc-pyright, provided by Pyright.
