### ISSUE TITLE
Using pipenv with coc-pyright?

### ISSUE THREAD

**Issue by gozes** [fannheyward/coc-pyright#308]
I'm still in the process of moving from coc-python to coc-pyrigth but I have a few question around pipnev and coc-pyright.

Is there any plans to support pipenv in coc-pyright?

if there is not planned the will coc-pyright do the the right thing/work properly if you have PIPENV_VENV_IN_PROJECT set for pipenv?

if that won't work ether then what will be the best way to integrate pipenv with coc-pyrigth?

**Comment by fannheyward** [comment]
coc-pyright already has pipenv support, please upgrade to latest release.

**Comment by gozes** [comment]
Then maybe update the docs on how to use it?

**Comment by fannheyward** [comment]
coc-pyright will try to detect pipenv Python by `pipenv --py` if a `Pipfile` file in project root, then use this Python.
