### ISSUE TITLE
Can't jump to definition

### ISSUE THREAD

**Issue by Thrasymachus01** [fannheyward/coc-pyright#310]
"Error on notification "jumpImplementation": your language server doesnt support it"

When doing "gi" in vim i get this error:
<img width="1025" alt="Screenshot 2021-02-11 at 19 40 46" src="https://user-images.githubusercontent.com/71150099/107689737-2028a080-6ca1-11eb-9d15-8595150d979d.png">

**Comment by yaegassy** [comment]
@Thrasymachus01 Use `<Plug>(coc-definition)` to jump to the definition.

For example, in the README mapping of coc.nvim, use gd.

```
" GoTo code navigation.
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)
```

**Comment by Folaht** [comment]
I have the same issue.

**Comment by fannheyward** [comment]
@Thrasymachus01 your issue is not `jump to definition`, but `jump to implementation`, which is fired by your `gi` mapping to `<Plug>(coc-implementation)`.

Pyright doesn't support goto implementation by now.

**Comment by adamwojt** [comment]
For those missing `jump to implementation` i found sane replacement: https://github.com/fannheyward/coc-pyright/issues/420#issuecomment-1347943845
