### ISSUE TITLE
Ingnoring pylintArgs

### ISSUE THREAD

**Issue by kaldown** [fannheyward/coc-pyright#312]
1)
```
    "python.linting.pylintArgs": [
        "--load-plugins",
        "pylint_flask_sqlalchemy",
        "pylint_flask"
    ]

```
won't make any effect. Still got an error
![2021-02-12_943x64_scrot](https://user-images.githubusercontent.com/3754017/107703858-53812480-6ccd-11eb-8953-90a03ab25a2c.png)

2) Creating `.pylintrc` won't make any difference too.

But with `.pylintrc`, manually calling `pylint afile.py` on a file, Shows no warnings.
Which makes me think **CoC-Pyright** is inoring **pylintArgs**.
There is no description in documentation either.

**Comment by yaegassy** [comment]
The error warning is coming from `pyright`, not `pylint`, as you can see in your capture.

In the case of a "pylint" error warning, the output will be `[pylint ...]`.

<img width="787" alt="coc-pyright-pylint" src="https://user-images.githubusercontent.com/188642/107718305-fb700f80-6d18-11eb-9f82-ea9e3372ac3b.png">

If you want to control errors with pyright, you should check the documentation of pyright itself.

**For example:**

- Use `# type: ignore`.
- Use `pyrightconfig.json`
- Setting `python.analysis.diagnosticSeverityOverrides` in `coc-settings.json`

**Comment by kaldown** [comment]
Tanks for clarification.

Only now I realized Pyright isn't a language server but a type checker.

**Comment by fannheyward** [comment]
> Pyright isn't a language server but a type checker

No, Pyright is a language server. You can use `pyrightconfig.json` to config Pyright https://github.com/microsoft/pyright/blob/master/docs/configuration.md#type-check-diagnostics-settings.
