### ISSUE TITLE
"randn" is not a known member of module

### ISSUE THREAD

**Issue by njse22** [fannheyward/coc-pyright#314]
Hi, first thanks for you great job in this project, I have a little ... 'bug' with numpy, Pyright marks like a error the method 'randn()' say:  ' "randn is not a know member of module"'

this is the code to reproduce: 
```python
import numpy as np
x = np.random.randn(1000)*15+100
```

sorry for my english ...

**Comment by yaegassy** [comment]
@njse22 This is **not** a coc-pyright problem, but a numpy problem.

Please upgrade numpy.

If you are using numpy v1.20.0 or later, you will not see that error.

If you are using a lower version of numpy, install a third party stubs package such as `data-science-types`.

There is a related issue, which you can also check here. https://github.com/fannheyward/coc-pyright/issues/163

**Comment by njse22** [comment]
yep .. you right is the error by my numpy version, thanks for asking
