### ISSUE TITLE
White spaces in docstrings shown as HTML characters

### ISSUE THREAD

**Issue by dianlujitao** [fannheyward/coc-pyright#320]
```python
def foo():
    """
    foo
        bar bar
        bar bar
    foo
    """
    pass
```
![image](https://user-images.githubusercontent.com/5774651/108011653-82d3c080-7042-11eb-8dc2-57c76e0fc6fd.png)

**Comment by yaegassy** [comment]
@dianlujitao If you are concerned about `&nbsp;`, please set `"coc.preferences.enableMarkdown": false` in "coc-settings.json"

**Comment by dianlujitao** [comment]
> @dianlujitao If you are concerned about `&nbsp;`, please set `"coc.preferences.enableMarkdown": false` in "coc-settings.json"

Is it possible to support markdown and translate nbsp at the same time? The old coc-python properly renders both iirc.

**Comment by yaegassy** [comment]
The language server used by coc-python is `microsoft/python-language-server`. I think it's a specification of "microsoft/python-language-server".

The language server of coc-pyright is pyright (`pyright-langserver`). I think that behavior is not supported by the pyright-langserver itself.

The behavior is the same when using pyright with other LSP client plugins.

### vim-lsp (pyright-langserver):

<img width="692" alt="_vim-lsp" src="https://user-images.githubusercontent.com/188642/108014884-47d98900-7052-11eb-9f00-ee053574c20a.png">

### Neovim built-in lsp (pyright-langserver):

<img width="695" alt="_neovim_lsp" src="https://user-images.githubusercontent.com/188642/108014921-617ad080-7052-11eb-927e-d152ac87899f.png">

**Comment by dianlujitao** [comment]
It's properly rendered in vscode with the Pylance language server:
![image](https://user-images.githubusercontent.com/5774651/108016426-75700380-704d-11eb-950b-a2d3b919799c.png)

I'm not sure but the issue in vim seems to be "expected" and caused by [a vscode-specific hack](https://github.com/microsoft/pyright/blob/231565f273c6c8547f4e94c2bce8a3498e55ff35/packages/pyright-internal/src/analyzer/docStringConversion.ts#L565). There's even [a unit test](https://github.com/microsoft/pyright/blob/231565f273c6c8547f4e94c2bce8a3498e55ff35/packages/pyright-internal/src/tests/docStringConversion.test.ts#L102) for this.

**Comment by fannheyward** [comment]
```python
class Foo:
    """Foo:

    Args:
        foo (Foo): Foo!
        *args: These are positional args.
        **kwargs: These are named args.
    """

    pass
```

<img width="483" alt="截屏2021-02-18 15 30 58" src="https://user-images.githubusercontent.com/345274/108320854-4e0c6880-71fe-11eb-84ec-a68f4fcb4285.png">

Tests code from https://github.com/microsoft/pyright/blob/231565f273c6c8547f4e94c2bce8a3498e55ff35/packages/pyright-internal/src/tests/docStringConversion.test.ts#L102


```python
def foo():
    """
    foo
        bar bar
        bar bar
    foo
    """
    pass
```

<img width="401" alt="截屏2021-02-18 15 32 10" src="https://user-images.githubusercontent.com/345274/108320980-78f6bc80-71fe-11eb-8ede-670d835e2312.png">

This has been improved, but still doesn't same as Pylance. `foo.__doc__` is:

```
    foo
        bar bar
        bar bar
    foo
```

Pyright returns docs:

```
contents: {
    kind: 'markdown',
    value: '```python\n' +
      '(function) foo: () -> None\n' +
      '```\n' +
      'foo\\\n' +
      '&nbsp;&nbsp;&nbsp;&nbsp;bar bar\n' +
      'bar bar\\\n' +
      'foo'
  },
```
