### ISSUE TITLE
reportMissingModuleSource using poetv + pyenv + poetry + mypy

### ISSUE THREAD

**Issue by Lilja** [fannheyward/coc-pyright#324]
I'm getting errors that I assume the plugin can't find my virtualenv created by poetry.

Related shell configuration
```fish
# ~/.config/fish/config.fish
pyenv init - | source
which python3 | read -l answer
set -gx PYTHONPATH "$answer/site-packages" $PYTHONPATH
set -gx PYENV_ROOT $HOME/.pyenv
set -gx PIPENV_PYTHON "$PYENV_ROOT/shims/python"
```

```
# :CocInfo
## versions
vim version: VIM - Vi IMproved 8.2 8022450
node version: v12.14.1
coc.nvim version: 0.0.80-6e5a2aaeb5
```

`vim src/file.py`

![image](https://user-images.githubusercontent.com/6134511/108189063-9baaa780-7110-11eb-8786-464f64044ad8.png)

`:PoetvActivate`
`:call CocAction('reloadExtension', 'coc-pyright')` I guess this is needed?

![image](https://user-images.githubusercontent.com/6134511/108189731-5cc92180-7111-11eb-84ad-1a85a88da080.png)

Doesn't seem to work? (Also note my statusline's `backend-dmp...` which denotes `poetv` has activated the environment)

Packages:

<details>
<summary>Click to expand</summary>

`:!pip list`

```

Package                   Version
------------------------- ------------
aiofiles                  0.6.0
aiohttp                   3.7.3
async-timeout             3.0.1
asyncio                   3.4.3
attrs                     20.3.0
boto3                     1.16.24
botocore                  1.19.24
cachetools                4.1.1
certifi                   2020.11.8
chardet                   3.0.4
h11                       0.9.0
httpcore                  0.11.1
httptools                 0.1.1
httpx                     0.15.4
idna                      2.10
jmespath                  0.10.0
multidict                 5.0.0
mypy                      0.800
mypy-boto3-secretsmanager 1.17.9.0
mypy-extensions           0.4.3
pip                       19.2.3
python-dateutil           2.8.1
requests                  2.25.0
rfc3986                   1.4.0
s3transfer                0.3.3
sanic                     20.9.1
Sanic-Cors                0.10.0.post3
Sanic-Plugins-Framework   0.9.4.post1
sentry-sdk                0.19.4
setuptools                41.2.0
six                       1.15.0
sniffio                   1.2.0
typed-ast                 1.4.2
typing-extensions         3.7.4.3
ujson                     4.0.1
urllib3                   1.26.2
uvloop                    0.14.0
websockets                8.1
yarl                      1.6.3
```

</details>

the reverse order doesn't work either: `vim`, `:PoetvActivate`, `:e src/file.py`.

However, `poetry shell`, `vim src/file.py` seems to work. What could be the issue here?

**Comment by fannheyward** [comment]
> can't find my virtualenv created by poetry

what do you mean `virtualenv created by poetry`? AFAIK, poetry does dependency management, it can't create venv.

coc-pyright will try to detect venv from `poetry env info --path` if there is a `poetry.lock` file in project workspace root.

**Comment by Lilja** [comment]
I do think poetry creates virtualenvs actually, I wouldn't think some other tool creates it.

![image](https://user-images.githubusercontent.com/6134511/108342676-5acb9500-71db-11eb-8fe2-99e047e6ffa5.png)

`$ vim`
* `:!which python`
* `:PoetvActivate`
* `:!which python`

![image](https://user-images.githubusercontent.com/6134511/108342862-91a1ab00-71db-11eb-924e-cbac5e7f03e4.png)

**Comment by fannheyward** [comment]
Do you have `poetry.lock` file in your project root? coc-pyright will try to detect python with `poetry env info --path` if `poetry.lock` is found.

**Comment by fannheyward** [comment]
coc-pyright v1.1.112 has improved poetry support, will detect python from `poetry env list --full-path`, please give it a try.

**Comment by Lilja** [comment]
Sadly the update did not do anything for me. I saw [that this code](https://github.com/fannheyward/coc-pyright/commit/39d64dcbd0731bc75af25672c9d1272376766a09#diff-a7c472e6e48d3adae9be979e4a4e3175f3354c2979a2279122f22ea078f40a43R51) referenced a `.python-version`. I added it also, but no effect(it wasn't there before).

```
$ tree -a -I '.mypy_cache|*.swp|__pycache__' .
.
├── .gitignore
├── .python-version
├── Makefile
├── package-lock.json
├── package.json
├── poetry.lock
├── pyproject.toml
├── serverless.yml
├── source.env
└── src
    ├── data_request_form_api
    │   ├── __init__.py
    │   ├── auth.py
    │   ├── client.py
    │   ├── lambda_handler.py
    │   └── runner.py
    └── run

2 directories, 15 files
```

`vim`
*  `PoetvActivate`
* `:e src/data_request_form_api/auth.py`

![image](https://user-images.githubusercontent.com/6134511/108637012-19601180-7489-11eb-8af7-9bfadd006385.png)

**Comment by Lilja** [comment]
Poetry info:

![image](https://user-images.githubusercontent.com/6134511/108637308-75776580-748a-11eb-93e9-f71c015da4f6.png)

**Comment by Lilja** [comment]
Deleted earlier comment since it was inaccurate. 

I'm not sure this has to do with `poetry` as I use the `PoetvActivate` to activate the virtualenv. It's like Coc-Pyright doesn't find it? Don't get me wrong, if I don't have to run `PoetvActivate` in order to use Coc-Pyright, then great!

**Comment by yaegassy** [comment]
@Lilja Is there any change in behavior if I run the `poetry shell` before starting Vim in the project root without using the Vim plugin (`:PoetvActivate`) to activate the virtual environment?

Is the project root the directory where `pyproject.toml` is located? Or is it the `src` directory?

Is there any change in behavior if I put `pyrightconfig.json` in the project root?

**Comment by Lilja** [comment]
> Is there any change in behavior if you run the poetry shell before starting Vim in the project root without using the Vim plugin (:PoetvActivate) to activate the virtual environment?

Yes, that makes it work. But my point being is that `:PoetvActivate` ought to do the same thing as `$ poetry shell`.

> Is the project root the directory where pyproject.toml is located? Or is it the src directory?

Yes, the project root is where the `pyproject.toml` is located.

> Is there any change in behavior if you put pyrightconfig.json in the project root?

No, `$ touch pyrightconfig.json` and then `vim`, `:PoetvActivate`, `:e src/<file>.py` doesn't change anything.

**Comment by yaegassy** [comment]
`pyrightconfig.json` should be in valid json format, This is the minimum content.

```json
{}
```

**Comment by yaegassy** [comment]
In my experience, enabling python virtual environment at Vim plugin or vimrc level or adding it to "sys.path" does not detect pyright well.

I don't know the cause.

I believe this is also true for other LSP client plugins that use pyright. (e.g. vim-lsp, Neovim built-in lsp)

**Comment by fannheyward** [comment]
>  I use the PoetvActivate to activate the virtualenv. It's like Coc-Pyright doesn't find it

coc-pyright doesn't care `PoetvActivate`. The problem is when you enter vim, Pyright will try to detect Python and start, after you run `PoetvActivate`, Pyright doesn't change anything. Maybe you can run `:CocRestart` after `:PoetvActivate`, (I don't try this works or not)

> referenced a .python-version

`.python-version` is created and used by pyenv, you shouldn't create it if you use poetry to manage your venvs. coc-pyright will try to run `poetry env list --full-path` if there is a `poetry.lock` found.

What's `poetry env list --full-path` output in your project?

**Comment by Lilja** [comment]
> What's poetry env list --full-path output in your project?
```
lilja in ~/c/u/c/backend on master λ poetry env list --full-path
/Users/lilja/Library/Caches/pypoetry/virtualenvs/backend-dmp__8h8-py3.8 (Activated)
```

**Comment by fannheyward** [comment]
@Lilja your poetry env is OK, remove `.python-version` and try again, coc-pyright will find and use python venv from poetry.

**Comment by Lilja** [comment]
I removed `.python-version`, but it didn't do anything. 

No `poetry shell`, just `vim <file>.py` 

![image](https://user-images.githubusercontent.com/6134511/109290653-2df52e80-7828-11eb-8a0b-cfd301412356.png)

`:CocList extensions`

![image](https://user-images.githubusercontent.com/6134511/109290708-406f6800-7828-11eb-8d29-93bf646b738d.png)

`:!poetry env list --full-path`

![image](https://user-images.githubusercontent.com/6134511/109290750-4ebd8400-7828-11eb-8870-ccf0181bb741.png)

Is there a way to display more debug information on what python environment this plugin/extension picks/decides to pick?

**Comment by fannheyward** [comment]
@Lilja coc-pyright v1.1.115 will log what's python is using in `:CocCommand workspace.showOutput` - Pyright/coc-pyright-formatting/coc-pyright-linting.

**Comment by Lilja** [comment]
`:CocCommand workspace.showOutput` and then picking `pyright` in the prompted menu.

![image](https://user-images.githubusercontent.com/6134511/109657979-61a4c100-7b66-11eb-9947-317e4493a68d.png)

What's interesting is that the `/umbrella/` directory is two parent directories above the project directory(backend).

`~/code/umbrella/<parent-directory>/backend`.

I wonder if there is some mechanism inside pyright/coc-pyright that doesn't see a `.venv` and walks ups the directory tree until it finds one?

**Comment by Lilja** [comment]
What's also interesting is that I just deleted that directory venv directory. I then exited vim and it looks like it's still using that python? `:CocRestart` doesn't change that either.

![image](https://user-images.githubusercontent.com/6134511/109660559-4dae8e80-7b69-11eb-8136-0aa521c011fa.png)

![image](https://user-images.githubusercontent.com/6134511/109660601-57d08d00-7b69-11eb-8908-771d62496a15.png)

`:CocRestart`
![image](https://user-images.githubusercontent.com/6134511/109660674-6c148a00-7b69-11eb-81e7-42ac47f7eb04.png)
![image](https://user-images.githubusercontent.com/6134511/109660692-70d93e00-7b69-11eb-9a02-cd542a9fb672.png)
![image](https://user-images.githubusercontent.com/6134511/109660706-746cc500-7b69-11eb-9c07-a6f961a6b5ac.png)

**Comment by yaegassy** [comment]
Is there any change in behavior if I start vim in the project root? Is the project root in this case the "backend" directory?

The information in this wiki may be helpful to ensure that project root (workspaceFolders) are detected properly. https://github.com/neoclide/coc.nvim/wiki/Using-workspaceFolders

For reference, this is how I set it up when the file type is python.

```vim
" ...snip
  au FileType python let b:coc_root_patterns = ['.git', '.env', 'venv', '.venv', 'setup.cfg', 'setup.py', 'pyrightconfig.json']
" ...snip
```

**Comment by Lilja** [comment]
@yaegassy Boom! There it is.

We use the `umbrella` directory as an "umbrella"-directory for all of our projects at my work. So it has a `.git` folder.

Perhaps Coc detects that it's the workspace folder while it's incorrect.

I added your snippet into my vimrc and voila! 

![image](https://user-images.githubusercontent.com/6134511/109663698-ae8b9600-7b6c-11eb-9d9d-332e569efe35.png)

For future readers, make sure to set `b:coc_root_patterns`!
