### ISSUE TITLE
Go to definition always to module source insted of stub

### ISSUE THREAD

**Issue by luisiacc** [fannheyward/coc-pyright#326]
I recommend to, whenever exists a module that have stubs (*.pyi), when triggering Go to Definition, don't ask me if I want to go to the stub file, just go straight to module source file. This feature was implemented in latest python extension of vscode, there, in order to go the the stub file you would have to trigger Go to Implementation, it's not a bad solution. Great extension btw! 👍

**Comment by yaegassy** [comment]
This behavior has been changed in pyright `v1.1.110`. 

> Behavior Change (from Pylance): Separated behavior of "go to definition" and "got to declaration". The former tries to take you to the source, whereas the latter takes you to the stub file.

I think that the expected behavior will be achieved by upgrading the version of pyright used in coc-pyright.

**Related:**

- https://github.com/microsoft/pyright/releases/tag/1.1.110
- https://github.com/microsoft/pylance-release/issues/65#issuecomment-776354122

**Comment by luisiacc** [comment]
@yaegassy I think the bump bot bumped the version to v1.1.111, however when I install coc-pyright it installs the v1.1.109.

**Comment by fannheyward** [comment]
You can `:CocUninstall coc-pyright` and `:CocInstall coc-pyright` to upgrade Pyright to latest release. I'll publish a new release of coc-pyright later, with some other fixes.

**Comment by AntoineD** [comment]
With last coc-pyright and pyright 1.1.115, the behavior has not changed for me and it still goes to the stub file instead of the source code.
Am I missing something to get it right?

**Comment by meandmymind** [comment]
@fannheyward I'm not able to go to source files either.

For example, with `pandas`. When I don't use type stubs, and do GoToDefinition on `DataFrame().sample()`, I can go to source file.

However, when I use type stubs (from `data-science-types`) I can only go to type stubs definitions.
![Annotation 2021-06-25 155043](https://user-images.githubusercontent.com/24773652/123398127-62f27180-d5cd-11eb-8ecf-bba2b010835c.png)

**Comment by fannheyward** [comment]
@meandmymind what's your Pyright version? Checkout `:CocCommand pyright.version`

**Comment by meandmymind** [comment]
@fannheyward  coc-pyright 1.1.159 with Pyright 1.1.159
