### ISSUE TITLE
Pass parameters to isort command

### ISSUE THREAD

**Issue by luisiacc** [fannheyward/coc-pyright#327]
I would like to have an option to pass some arguments to te isort command, perhaps via local `coc-settings.json` ? My problem actually is that my project root is not the python project root, so I was going to ask for a way to set the python project root, but why not go bigger ?
Ex:
```
{
	...
    "python.isort.args": "--sp ./python-src --ca"
}
```

PD: 
```
  --sp SETTINGS_PATH, --settings-path SETTINGS_PATH, --settings-file SETTINGS_PATH, --settings SETTINGS_PATH
                        Explicitly set the settings path or file instead of
                        auto determining based on file location.
```

**Comment by fannheyward** [comment]
You can create a custom isort python script, something like https://github.com/fannheyward/coc-pyright/blob/master/pythonFiles/sortImports.py, set it to `python.sortImports.path`.
