### ISSUE TITLE
"python.formatting.provider" leaves "^M" characters at the end of lines on :Format

### ISSUE THREAD

**Issue by kglundgren** [fannheyward/coc-pyright#329]
![image](https://user-images.githubusercontent.com/56938604/108537248-b2522980-72dd-11eb-8897-3096fd3a28e2.png)

It looks like that. This is using Neovim on Windows.
**EDIT:** It happens regardless of which formatting provider is used. autopep8 or black makes no difference.

**Comment by fannheyward** [comment]
Have no idea about this. coc-pyright runs a formatter, for example black, to get diffs, then use <https://github.com/google/diff-match-patch> to parse the diff text to textEdits and apply.

The parse logic is same as vscode-python:

- https://github.com/microsoft/vscode-python/blob/f884383c577d5f1b9bc68c301f1a3e2c8bb0294f/src/client/common/editor.ts#L68
- https://github.com/fannheyward/coc-pyright/blob/92b214eca199aac947d6d43066fd568a9958915f/src/common.ts#L211
