### ISSUE TITLE
No flake8 linting shown

### ISSUE THREAD

**Issue by AntoineD** [fannheyward/coc-pyright#331]
Hello,

The linting messages from flake8 are not shown, only pyright messages are displayed.

Flake8 is found and executed, output of `CocCommand workspace.showOutput coc-pyright-linting`:
```
########## active linter: flake8
########## Linting Output - flake8##########
/path/file.py:22:1: D205 1 blank line required between summary line and description
/path/file.py:22:1: D212 Multi-line docstring summary should start at the first line
```

Output of `CocCommand workspace.showOutput Pyright`:
```
[Info  - 7:23:32 AM] Pyright language server 1.1.113 starting
[Info  - 7:23:32 AM] Server root directory: /home/AntoineD/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/
[Info  - 7:23:32 AM] Loading configuration file at /path/pyrightconfig.json
[Info  - 7:23:32 AM] Assuming Python version 3.8
[Info  - 7:23:32 AM] Assuming Python platform Linux
[Info  - 7:23:32 AM] No include entries specified; assuming /path
[Info  - 7:23:32 AM] Auto-excluding **/node_modules
[Info  - 7:23:32 AM] Auto-excluding **/__pycache__
[Info  - 7:23:32 AM] Auto-excluding .git
[Error  - 7:23:32 AM] stubPath /path/typings is not a valid directory.
[Info  - 7:23:32 AM] Searching for source files
[Info  - 7:23:32 AM] Auto-excluding /path/.tox/.tox
[Info  - 7:23:32 AM] Auto-excluding /path/.tox/anaconda-package
[Info  - 7:23:33 AM] Auto-excluding /path/.tox/conda-build
[Info  - 7:23:35 AM] Found 74237 source files
[Info  - 7:23:38 AM] [FG] Long operation: checking: /path/file.py (2567ms)
[Info  - 7:23:38 AM] [FG] Long operation: analyzing: /path/file.py (2752ms)
```

Contents of `pyrightconfig.json `:
```
{
    "venvPath": ".tox",
    "venv": "dev"
}
```

Contents of `.vim/coc-settings.json`:
```
{
  "python.linting.enabled": true,
  "python.linting.flake8Enabled": true,
  "python.linting.flake8Path": ".tox/dev/bin/flake8"
}
```

**Comment by fannheyward** [comment]
The output of `CocCommand workspace.showOutput coc-pyright-linting` shows flake8 is working.

**Comment by AntoineD** [comment]
Hi @fannheyward.
Yes flake8 is working, would you mind help me figure out the problem please?

**Comment by fannheyward** [comment]
Properly is the message format, mine is:

```
########## active linter: flake8
########## Linting Output - flake8##########
5,1,F,F401:'dataclasses' imported but unused
6,1,F,F401:'os' imported but unused
```

**Comment by AntoineD** [comment]
Do you mean that coc-pyright cannot parse the output from flake8 because it is not properly formatted?

**Comment by fannheyward** [comment]
Yes, coc-pyright runs flake8 and parses the output, your flake8's output is different for coc-pyright to parse. What's your flake8 version? 

```
flake8 --version
3.8.4 (mccabe: 0.6.1, pycodestyle: 2.6.0, pyflakes: 2.2.0) CPython 3.8.8 on Darwin
```

**Comment by AntoineD** [comment]
flake8 --version                                        
3.8.4 (flake8-bugbear: 20.11.1, flake8-colors: 0.1.9, flake8-docstrings: 1.5.0, pydocstyle: 5.1.1, flake8-print: 4.0.0, logging-format: 0.6.0, mccabe: 0.6.1, naming: 0.11.1, pycodestyle: 2.6.0, pyflakes: 2.2.0) CPython 3.8.6 on Linux

**Comment by fannheyward** [comment]
Does `flake8 --format="%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s" main.py` work for you?

**Comment by AntoineD** [comment]
```
flake8 /path/file.py  --format="%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s"
22,1,D,D205:1 blank line required between summary line and description
22,1,D,D212:Multi-line docstring summary should start at the first line
```

**Comment by AntoineD** [comment]
FYI, these are my settings for flake8 in `setup.cfg`:
```
[flake8]
# See http://www.pydocstyle.org/en/latest/error_codes.html for more details.
# https://github.com/PyCQA/flake8-bugbear#how-to-enable-opinionated-warnings
ignore = E501
select = B,C,D,E,F,G,N,T,W,B950
# settings for compatibility with black, see
# https://github.com/psf/black/blob/master/docs/compatible_configs.md#flake8
# https://black.readthedocs.io/en/stable/the_black_code_style.html?highlight=bugbear#line-length
max-line-length = 80
extend-ignore = E203, W503
per-file-ignores =
    # ignore print statements violations in the examples and tutorials
    doc_src/**/*.py:T
docstring-convention=google
```

**Comment by fannheyward** [comment]
Have no idea about this.

**Comment by AntoineD** [comment]
Removing the settings from `setup.cfg` does not help.

I don't know typescript but I'd like to debug this. Would you mind to help me run this after inserting some print statements for instance in `BaseLinter.run`?

**Comment by yaegassy** [comment]
@AntoineD The format of your flake8 lint message seems to be the same as what you see if you don't pass anything to args.

**Comment by AntoineD** [comment]
Hi @yaegassy,

thanks for helping!

There's no `python.linting.flake8Args` setting in my local `coc-settings.json` (see my first message) and the global one is empty.
My flake8 settings are only in `setup.cfg`.

Strangely, if I add the format settings to the `setup.cfg` then I get the expected output from the command line:
```
flake8 /path/file.py"
22,1,D,D205:1 blank line required between summary line and description
22,1,D,D212:Multi-line docstring summary should start at the first line
```
But still the output of `CocCommand workspace.showOutput coc-pyright-linting`:
```
########## active linter: flake8
########## Linting Output - flake8##########
/path/file.py:22:1: D205 1 blank line required between summary line and description
/path/file.py:22:1: D212 Multi-line docstring summary should start at the first line
```

**Comment by AntoineD** [comment]
I just found this is due to the flake8-colors plugin, though the issue does not happen when flake8 is run from the command line.
