### ISSUE TITLE
How to configure the environment to detect packages?

### ISSUE THREAD

**Issue by dycw** [fannheyward/coc-pyright#332]
I am a long-time `conda`, `poetry` and `pipenv` user, but I still cannot figure out how to set up `vim`/`python`. This is in contrast to PyCharm where one can readily set the interpreter to your environment, regardless of the manager, and then get both autocompletions and auto-imports. For example, with `conda` say, I have a number of environments containing `pyvnim`:

```
❯ conda env list
# conda environments:
#
base                  *  /home/derek/miniconda3
neovim                   /home/derek/miniconda3/envs/neovim
```

Then in my `init.vim` I then point dynamically to the `python` depending on the project I'm in:

```
let conda_default_env = $CONDA_DEFAULT_ENV
if conda_default_env == 'base'
  let env_name = 'neovim'
else
  let env_name = conda_default_env
endif
let bin_python = expand('~') . '/miniconda3/envs/' . env_name . '/bin/python'
if filereadable(bin_python)
  let g:python3_host_prog = bin_python
endif                                            
```

Of course, I also have

```
Plug 'neoclide/coc.nvim', {
  \ 'do': { -> coc#util#install() },
  \ 'branch': 'release',
  \ 'tag': '*',
  \ }

let g:coc_global_extensions = [
  \ 'coc-pyright',
  \ ]
```

along with the rest of the stuff from [here](https://github.com/neoclide/coc.nvim#example-vim-configuration).

Furthermore, I also have configured a local `coc-settings.json` to be

```json
{
  "python.pythonPath": "/home/derek/miniconda3/envs/test/bin/python"
}
```

Lastly, for good measure, I have followed [this](https://hanspinckaers.com/fixing-coc-pyright-and-anaconda-import-errors) too.

Well when it comes to editing, I'm not getting autocompletions from these modules. For example, if I add `numpy` to my brand new environment:

```python
from numpy import <CURSOR>
```

I expect to be able to get some module members like `arange`, `ones`, etc. I don't though. Any help please?

**Comment by yaegassy** [comment]
@dycw If you try the steps in this link instead of setting up the python environment in vimrc/init.vim, does it work correctly? https://github.com/fannheyward/coc-pyright#links

<https://hanspinckaers.com/fixing-coc-pyright-and-anaconda-import-errors>

**Comment by dycw** [comment]
Hi @yaegassy thanks for dropping by. In my OP I in fact already mentioned the same 2 links you shared. It appears there are many places to set "interpreter path" (using PyCharm terminology):

1. `~/.config/nvim/init.vim` which has `python3_host_prog`,
2. `~/.config/nvim/coc-settings.json` which has both `python.pythonPath` and `python.venvPath`, and
3. `~/myrepo/pyrightconfig.json` which has both `venvPath` and `venv`.

Can you shed some light on which exactly is meant to be set? 

To clarify, whilst I use `conda` mostly, I am happy to use something else to create venvs (e.g. `poetry`). Thus, whichever I can get plugged into `coc.nvim` easiest is the one I'll use.

**Comment by yaegassy** [comment]
In my experience, the simplest way to do this is to "activate" the virtual environment in "shell" and then start Vim/Neovim in the "project root".

1. A situation where the expected python interpreter is running.
2. A situation where the package can be imported correctly using the REPL
3. Start Vim in the project root

Under these conditions, I believe that pyright can be used correctly without any configuration.

**Comment by dycw** [comment]
Well, I do this more or less automatically with [direnv](https://direnv.net/).

But if I was a brand new `neovim` user I'm going to be complained at regarding `python3_host_prog`, so I presume I need to set that.

But the `coc-settings.json` and `pyrightconfig.json` ask for more information. Do I need to set upwards of 4 more variables?

**Comment by yaegassy** [comment]
`python3_host_prog` is a Neovim setting. My understanding is that if you use plugins that depend on `python3_host_prog`, you need to configure it properly.

I think coc.nvim will work correctly with or without `python3_host_prog` setting. Also, coc.nvim will work with Vim8.

The environment-related settings in `coc-settings.json` and `pyrightconfig.json` are additional settings in case the expected Python interpreter or package directory is not recognized.

For more details, you should check the documentation of pyright itself and try various things by yourself. <https://github.com/microsoft/pyright/blob/master/docs/configuration.md>

**Comment by dycw** [comment]
I see. Well thanks for stopping by. I'll close this now.
