### ISSUE TITLE
I am getting "is not  a known member of module" errors when using pytorch

### ISSUE THREAD

**Issue by joaqo** [fannheyward/coc-pyright#348]
Hi, just started using coc-pyright and I absolutely love the library, thanks a ton for your work!

Everything is working perfectly except for the library having some issues accessing certain pytorch members. I get the error in the title on several (but not all) pytorch lines in my code. Here is a short code snippet to reproduce the bug:

```python
import torch

torch.cuda  # [Pyright reportGeneralTypeIssues] [E] "cuda" is not a known member of module
```

Whats funny is that 'go to definition' works perfectly on `cuda`.

Is there anyway to fix this? And if there is no current way to fix this, is there an easy way to hide the red vim sign column error `>>` characters and the hover error messages so I can ignore this issue for the time being?

Thanks a ton!

Edit: Tried setting `"python.analysis.useLibraryCodeForTypes": false` but the problem persists.

**Comment by fannheyward** [comment]
That's because Pyright can't find the `cuda` in pytorch's pyi.

Try put `# type: ignore` at the end of the line, Pyright will ignore this line checking.

**Comment by joaqo** [comment]
@fannheyward Is there a more global way of solving this? I would have to litter my codebase with `# type: ignore` to fix this, which I would have a hard time justifying. Can I just not show the error `>>` things on vim?

**Comment by fannheyward** [comment]
Have not idea about this.

**Comment by joaqo** [comment]
Here is the solution if anyone is interested: https://github.com/microsoft/pyright/issues/1542
