### ISSUE TITLE
Is there a way for coc-pyright to just use the current virtual environment?

### ISSUE THREAD

**Issue by joaqo** [fannheyward/coc-pyright#349]
Currently I have to set `"python.pythonPath": "/venv/path/bin/python"` manually for each session I have active. Isn't there a way for coc-pyright to do something like `which python` see which path the current python interpreter is using, and set that as the current python path?

**Comment by yaegassy** [comment]
I don't know what "active session" indicates.

If you "activate" the virtual environment for each project and then launch Vim, it will be detected properly without having to set "python.pythonPath" every time.

**Comment by fannheyward** [comment]
Set `python.pythonPath` to `python`, coc-pyright will try to detect python in your venv.

**Comment by joaqo** [comment]
Thats great! Thanks a ton!
