### ISSUE TITLE
Pyright fails on pandas classes

### ISSUE THREAD

**Issue by DKozl50** [fannheyward/coc-pyright#350]
coc-pyright version 1.1.114; pandas version 1.2.2; Python 3.9.1

MVE:
```python
import pandas as pd

def func(df: pd.DataFrame):
    for i in df.index:
        print(i)
```
Here, pyright notifies me that `df.index`'s (`Index` type) `__iter__` method does not return an object. 
Index is defined [here](https://github.com/pandas-dev/pandas/blob/v1.2.2/pandas/core/indexes/base.py#L150-L5793), it inherits `__iter__` method from `IndexOpsMixin` [here](https://github.com/pandas-dev/pandas/blob/479a7f601897a804b5a712fd0ce1fd97378b02a6/pandas/core/base.py#L351). So the code should work okay (and it does), but pyright behaves weird.

I tried to narrow down the problem and look at 
```python
import pandas as pd

def func(iom: pd.IndexOpsMixin):
    for i in iom:
        print(i)
```
For me it says `[Pyright reportGeneralTypeIssues] [E] "Module("numpy")" is not iterable`, and `[Pyright reportGeneralTypeIssues] [E] "datetime" is not iterable "__iter__" method not defined` and I do not understand what is happening here. 

Tested on a minimal init.vim and in virtual environment (and outside too). I used NVim 0.5.0

**Comment by yaegassy** [comment]
@DKozl50 Try one of these methods.

- Install the pandas stubs file (e.g. `pip3 install pandas-stubs`)
- Or set `python.analysis.useLibraryCodeForTypes": false` in `coc-settings.json`

See: https://github.com/fannheyward/coc-pyright#python-typing-and-stub-files

**Comment by DKozl50** [comment]
Yes, it works, thank you
Closing the issue

**Comment by cshjsc** [comment]
coc-pyright version 1.1.162; pandas version 1.3.2; Python 3.9.6 Nvim 0.5.0
```
import pandas as pd
df = pd.read_csv('admissions_data.csv')
print(type(df))
print(df.head())
features =  df.iloc[:,-1]

```
I get the the error 

> Cannot access member "head" for type "TextFileReader"
> Member "head" is unknown

which is not right because the type of df is `pandas.core.frame.DataFrame` 
I installed like suggested the pandas-stubs but after that I just don't get suggestions for the pandas module.
If I set 
`python.analysis.useLibraryCodeForTypes": false` 

I won't get suggestions at all
