### ISSUE TITLE
Issue with 'go to definition' asking me which file I want, but prompting for the same file each time.

### ISSUE THREAD

**Issue by joaqo** [fannheyward/coc-pyright#352]
Hi, really love the library!

I have a small issue, sometimes, which I try to 'go to definition' coc-pyright asks me which of the possible files hosting the defitinion I want to open. The thing is that all the prompts are to the same file! Here is an example:

<img width="954" alt="image" src="https://user-images.githubusercontent.com/14966348/109428971-37bd9400-79d8-11eb-8917-8611c8db1ed2.png">

And here is my config:

```json
{
  "python.formatting.provider": "black",
  "python.linting.pylintEnabled": true,
  "python.linting.enabled": true,
  "python.jediEnabled": false,
  "python.pythonPath": "/path/to/symlink/which/points/to/python/bin",
  "diagnostic.checkCurrentLine": true,
  "python.analysis.useLibraryCodeForTypes": false,
  "python.analysis.typeCheckingMode": "off"
}
```

Also when I restart vim the error gets fixed! But after using the same vim session for some time it starts happening again.

Thanks!

**Comment by fannheyward** [comment]
The locations are came from Pyright, coc-pyright just display them in list.

> all the prompts are to the same file

They're same file with different lines, look at the line numbers in list. They're different locations.

**Comment by joaqo** [comment]
The 1st and the 3rd options are actually the same file and same line number, but if it's what pyright is outputting to coc-pyright I guess there is nothing you can do about it.

Thanks for the help and for the awesome project!

**Comment by joaqo** [comment]
@fannheyward Small update, I am getting this error when trying to go to a definition made in the file I'm working with:

<img width="859" alt="image" src="https://user-images.githubusercontent.com/14966348/109912139-4501a980-7c8a-11eb-8999-8abc2f8a3069.png">

I this something I should just bring up with the pyright folks as it doesn't depend on coc-pyright?

**Comment by fannheyward** [comment]
@joaqo what's the output of `:CocList services`?

**Comment by joaqo** [comment]
Just a single `* pyright [running] python` line.

**Comment by fannheyward** [comment]
You can test your code with VSCode + https://marketplace.visualstudio.com/items?itemName=ms-pyright.pyright, if there're same two locations, it's Pyright's issue.

**Comment by yaegassy** [comment]
@joaqo What other coc extensions do you use besides coc-pyright? Do you also have "`coc-python`" installed?

Uninstall "`coc-python`" if it is already installed. `:CocUninstall coc-python`

Note: `"python.jediEnabled": false` is a coc-python setting and should be removed.

**Comment by joaqo** [comment]
Thanks @yaegassy, you were completely right! Turns out I had coc-python installed from quite some time ago. I ended up uninstalling coc.nvim that time, but apparently coc-python remained installed and got picked up again when I reinstalled coc.nvim. Thanks again!

**Comment by joaqo** [comment]
@yaegassy Just as a side note, when I uninstalled coc-python some, but not all, go to definitions stopped working. If I install coc-python they start working again.

What is more weird is that if I just have coc-pyright installed, in a line like `from pytorch_metric_learning.utils.accuracy_calculator import AccuracyCalculator`, go to definition fails on AccuracyCalculator. But it works if I previously go to definition on just `pytorch_metric_learning`.

**Comment by yaegassy** [comment]
I'm not sure because I do not use `pytorch_metric_learning` packages on a daily basis.

I installed `pytorch_metric_learning` and tried the `jumpDefinition`. No problem in my environment. `coc-pyright` works very well.

![coc-pyright-issue352](https://user-images.githubusercontent.com/188642/110037491-d273f500-7d81-11eb-94d7-e6c5108ce76a.gif)

This [issue](https://github.com/fannheyward/coc-pyright/issues/352) has been resolved.

**Comment by joaqo** [comment]
Gotcha, it has to be something wrong with my config then. I'll keep on looking and report back if I find anything interesting in case anyone has the same issue I have. Thanks a ton for your help!

**Comment by yaegassy** [comment]
I have no problem with Vim8 in my environment as well.

**Comment by joaqo** [comment]
Oh, thanks for the heads up. Im just gonna start from a fresh vim install then and try to find the culprit.

**Comment by joaqo** [comment]
If anybody ends up here, I ended up solving this by deleting `~/.vim` and `~/.config/coc` folders and reinstalling all my vim plugins and coc servers from scratch. Cheers!

**Comment by joaqo** [comment]
Well final update for this issue. When I re added my old CocConfig things broke down again, so I tried deleting settings until I found the culprit:

```json
"python.analysis.useLibraryCodeForTypes": false
```

Deleted this and now everything is working perfect, no idea why this is, but it might be interesting to you @yaegassy and @fannheyward.

Anyway I am now extremelly happy with how coc-pytright is working, thanks for the awesome library!

**Comment by fannheyward** [comment]
Yes, `python.analysis.useLibraryCodeForTypes` in coc-pyright is `true` by default, but `false` by default in Pyright.

Pyright uses stub pyi files to do jumpDefinition and completions, if `useLibraryCodeForTypes` is true, Pyright will analyze library source code too.

I make this `true` in coc-pyright is because, many Python libraries are working on stubs by now, many libraries doesn't provide stubs by now, user custom library/module don't has stubs, so this configuration make Pyright to do analyze library source code.

This will cause some issues in large library, https://github.com/fannheyward/coc-pyright/issues/287, I'll change to false in later release.

**Comment by joaqo** [comment]
This means that by default 'go to definition' for libraries with no pyi files doesn't work on VSCode? That sounds really bad tbh.

**Comment by fannheyward** [comment]
VSCode has vscode-python , Pylance(based on Pyright) can work with vscode-python together for more features.

**Comment by yaegassy** [comment]
> This will cause some issues in large library, #287, I'll change to false in later release.

@fannheyward This may increase the number of issue reports where "jumpDefinition" does not work properly.

The behavior of [this issue comment](https://github.com/fannheyward/coc-pyright/issues/352#issuecomment-790932644), as reported by @joago, also occurs.

When changing the default values of the settings, it may be a good idea to include a note in the README as well.

**Comment by fannheyward** [comment]
@yaegassy I prefer to keep it `true` in a _long_ period, maybe change it in laaaaater release. Although it may cause issues in large codebase, I think it's better to make Pyright to do analyzes. What do you think?

**Comment by yaegassy** [comment]
Supplementary information. The current default setting for other LSP client plug-ins is true. (pyright lsp related)

- vim-lsp (vim-lsp-settings) https://github.com/mattn/vim-lsp-settings/blob/master/settings/pyright-langserver.vim#L14
- nvim-lspconfig https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/pyright.lua#L30
- emacs-lsp (lsp-pyright) https://github.com/emacs-lsp/lsp-pyright/blob/master/lsp-pyright.el#L205

**Comment by fannheyward** [comment]
Pylance maybe add `partial type stubs` analyze https://github.com/microsoft/pylance-release/issues/946#issuecomment-781961760 , don't know whether this will be added in Pyright or not.

**Comment by yaegassy** [comment]
I find the `true` setting more comfortable. Probably, the same is true for first-time users of coc-pyright.

Thank you for the information on pylance trends.

The pylance is... Hmmm. I can't comment on anything. :(

**Comment by fannheyward** [comment]
Thank you @yaegassy, for your help on coc-pyright issues/tests ❤️

**Comment by joaqo** [comment]
Agree with @yaegassy, I prefer the current default of `true`. For a first time user, 'go to definition' not working is very confusing.

**Comment by yaegassy** [comment]
https://github.com/microsoft/pyright/releases/tag/1.1.118

> Enhancement (from Pylance): Improved support for partial stubs (where py.typed file includes "partial" as per PEP 561).
