### ISSUE TITLE
Can it add interface to disable  Pyright's lint?

### ISSUE THREAD

**Issue by pittcat** [fannheyward/coc-pyright#358]

**Comment by fannheyward** [comment]
No.

**Comment by pittcat** [comment]
I only want to use pyright for completion. Ale for lint seems a nice choice.

**Comment by pittcat** [comment]
coc-clangd can disable diagnostics by setting clangd.disableDiagnostics to true.

**Comment by fannheyward** [comment]
Pyright's linting is the core feature, so I'd prefer to keep it must have.

**Comment by pittcat** [comment]
Pyright's linting has great features, but is still evolving. Flake8 or other more stable python linter are the choice of many python users, i think coc-pyright should add interface to control pyright's linting so that users can use pyright's linting and other linter separately. switch for pyright's linting does't mean neutering the diagnostics function, and it simply provides users with more freedom to configure and choose linter.
