### ISSUE TITLE
pyright.disableLanguageServices seems to get ignored

### ISSUE THREAD

**Issue by HansPinckaers** [fannheyward/coc-pyright#36]
Hi there,

I use coc-python for completion and coc-pyright for linting. I disabled completion for coc-pyright to circumvent duplicate completion items. However, pyright.disableLanguageServices seems to get ignored.

I tested multiple versions, and it breaks at 1.0.82. Version 1.0.81 shows no duplicates and 1.0.82 does.

Cheers,
Hans

**Comment by fannheyward** [comment]
Can't reproduced. I only install `coc-pyright` and set `pyright.disableLanguageServices` to false, no completion and references works.

There is no any difference between 1.0.82 and 1.0.81, except Pyright server.

**Comment by HansPinckaers** [comment]
Hmm this is strange, I update everything and now it is OK again.
