### ISSUE TITLE
Question: how to move an object to a new file?

### ISSUE THREAD

**Issue by dycw** [fannheyward/coc-pyright#360]
Hi, thanks for a great plugin. If I have two files 

```python
# a.py

def foo():
    pass
```

```python
# b.py

from a import foo

def bar():
    return foo()
```

How can I move `foo` to a new file, say, `a2.py` and have the reference update with it to `from a2 import foo`? I suppose `coc-refactor` is something to use, but I need some more examples on how to use it.

**Comment by fannheyward** [comment]
No such feature now.
