### ISSUE TITLE
PYTHONPATH ignored

### ISSUE THREAD

**Issue by hifigraz** [fannheyward/coc-pyright#361]
I have a PYTHONPATH set and exported to another project of mine I want to import from and pyright seems to ignore the PYTHONPATH environment variable so import is marked as cannot be resolved.

**Comment by fannheyward** [comment]
Have no idea about it, can you reproduce this error with VSCode + https://marketplace.visualstudio.com/items?itemName=ms-pyright.pyright ? Note that you should disable vscode-python and Pylance to test it.

**Comment by fannheyward** [comment]
Close for now.
