### ISSUE TITLE
Add pycodestyle linting

### ISSUE THREAD

**Issue by LongerHV** [fannheyward/coc-pyright#362]
Please consider adding support for pycodestyle instead of deprecated pep8. It is a drop in replacement, so setting "python.linting.pep8Path": "pycodestyle" works as a workaround.

**Comment by yaegassy** [comment]
Looking at the currently `vscode-python` configuration, it seems that `pep8` has been removed and replaced with `pycodestyle`.

It seems to be from this commit. https://github.com/microsoft/vscode-python/commit/15756ba62fd78517c45f688763899836d8d5fa82#diff-6b6295567ce9afc6ec4d006c54ec69efde2d31d0e1b6794ed59f3df2bbca2dd0
