### ISSUE TITLE
Are `python.linting.pylintArgs` and `python.linting.pylintCategorySeverity` inactive?

### ISSUE THREAD

**Issue by ahmedsaoudi** [fannheyward/coc-pyright#369]
Hello! 
Thanks for the awesome plugin! 
I just wanted to change some parameters regarding Pylint via the `python.linting.pylintArgs` and `python.linting.pylintCategorySeverity` directives but they don't seem to do anything. 

Despite these two settings were mentioned in the README, they were present in the code itself, so I was wondering if they are not taken into account for the time being. Any confirmation on this?
Thanks!

**Comment by fannheyward** [comment]
Can't reproduce, for example bellow configuration will work as expect (disabled no-member error)

```
"python.linting.pylintArgs": [
    "--disable=E1101"
]
```

**Comment by ahmedsaoudi** [comment]
It must be some sort of error in my installation then. Thanks for your reply!
