### ISSUE TITLE
No parameter named "n_neighbors", but the parameter is actually there

### ISSUE THREAD

**Issue by danielfalbo** [fannheyward/coc-pyright#371]
I have a simple file `foo.py`:

```python3
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=1)
```
. It runs without any error, but while I'm editing, pyright complains
```
No parameter named "n_neighbors"
[Pyright: reportGeneralTypeIssues]
```
.
![Screenshot 2021-03-07 at 10 17 27](https://user-images.githubusercontent.com/39460524/110235064-59fe6700-7f2e-11eb-8b87-3c7a7c79c0f4.png)

**Comment by danielfalbo** [comment]
The package is `scikit-learn`

**Comment by fannheyward** [comment]
Looks like it's Pyright's issue, can you reproduce this with VSCode + https://marketplace.visualstudio.com/items?itemName=ms-pyright.pyright ?

**Comment by danielfalbo** [comment]
![Screenshot 2021-03-08 at 09 22 01](https://user-images.githubusercontent.com/39460524/110294226-defd8500-7fef-11eb-9f7e-05cbe5b97f63.png)

Mmmhh, looks good in VSCode

**Comment by yaegassy** [comment]
@danielfalbo Try setting `python.analysis.useLibraryCodeForTypes` to `true` in VSCode's `settings.json`.

```jsonc
{
  // ...snip
  "python.analysis.useLibraryCodeForTypes": true
  // ...snip
}
```

<img width="1244" alt="coc-pyright-issue371" src="https://user-images.githubusercontent.com/188642/110296303-894bcb80-8035-11eb-8093-b9b96d91d866.png">

----

I have never used `scikit-learn`, but if there is a "stub package" for `scikit-learn`, installing it may help.

**Comment by yaegassy** [comment]
@danielfalbo If you cannot find a stub package for sklearn, you can create one yourself.

Try to run this command in the "project root".

```
pyright --createstub sklearn
```

I think the "stub" will be created with a folder structure like `typings/sklearn/...`.

**Comment by fannheyward** [comment]
There's no error in VSCode, but there's no other results too, for example no hover document on `KNeighborsClassifier`.

This is because `python.analysis.useLibraryCodeForTypes` is false by default in Pyright, Pyright doesn't analyze code source, coc-pyright enable this to make Pyright analyze code, then find the error.

**Comment by fannheyward** [comment]
You can run `:CocCommand pyright.createtypestub sklearn` to create stub.

**Comment by danielfalbo** [comment]
Thank you! It actually works
