### ISSUE TITLE
"imread" is not a known member of module, but that's not true

### ISSUE THREAD

**Issue by danielfalbo** [fannheyward/coc-pyright#378]
I have a simple file `foo.py`:
```python3
import cv2

img = cv2.imread("image.png")
```
. It runs without any error, but while I'm editing, pyright complains
```
"imread" is not a known member of module
[Pyright: reportGeneralTypeIssues]
```
. I had a [similar issue](https://github.com/fannheyward/coc-pyright/issues/371) the other day, which was solved by running `:CocCommand pyright.createtypestub sklearn`. But now even if I run `:CocCommand pyright.createtypestub cv2`, the error persists. Is there something I can do to fix this?  Or is this the type of issue you [mention](https://github.com/fannheyward/coc-pyright#python-typing-and-stub-files) in the readme for which we have to wait for updates from the package developers?

![Screenshot 2021-03-10 at 09 23 07](https://user-images.githubusercontent.com/39460524/110599640-5ca5ca00-8183-11eb-9542-0f09b93f5d9f.png)

`cv2` can be installed by running `pip install opencv-python`, but I guess you already know

**Comment by yaegassy** [comment]
This is not a coc-pyright issue. The reason is that `cv2` is not implemented in python and there is no source code to parse.

There are also many reports of problems with pyright, pylance, and opencv. We recommend that you first check the issue of pyright itself and the package you are using.

- For example
    - <https://github.com/microsoft/pyright/issues/1461>
    - <https://github.com/microsoft/pylance-release/issues/138>
    - <https://github.com/opencv/opencv/issues/14590>
