### ISSUE TITLE
Pylint showing 10/10 inside nvim but 8.4/10 if called manually

### ISSUE THREAD

**Issue by p-gentili** [fannheyward/coc-pyright#379]
Hi,
if I run pylint manually on a file I get 8.4/10 as a score. Usig nvim and coc-pyright I always get 10/10 thus no warnign/errors from pylint are displayed (I checked this result with :CocCommand workspace.showOutput coc-pyright-linting)

I get a similar result setting flake8 enabled.

Any idea?
Thanks

**Comment by fannheyward** [comment]
Set `python.linting.pylintUseMinimalCheckers` to false in coc-settings.json and try again.

**Comment by p-gentili** [comment]
That was easy, thank you.
