### ISSUE TITLE
Remove warning for 'self' not being accessed

### ISSUE THREAD

**Issue by WieeRd** [fannheyward/coc-pyright#381]
`self` is always required in class method parameter, and it is perfectly normal to not use it at all.  
But coc-pyright always shows warning for not accessing self.  
I think it's completely unnecessary and should be removed.

**Comment by yaegassy** [comment]
#271

**Comment by WieeRd** [comment]
Thanks, that solved the annoying warnings for now.  
But I wish I could disable it for only `self`.  
Unused variable hints are sometimes useful.

**Comment by you-n-g** [comment]
@WieeRd 
I have the same issue with you.
Have you found any solution to disable `self` while leaving unused variable hints enabled? 

Thanks.

**Comment by WieeRd** [comment]
@you-n-g 
Sadly I still haven't.  
I found this `reportSelfClsParameterName` option in [pyright](https://github.com/microsoft/pyright/blob/master/docs/configuration.md#type-check-diagnostics-settings)(not coc-pyright, but pyright itself) configuration guide,  
But I haven't figured out how to apply this option in coc.nvim.

**Comment by you-n-g** [comment]
@WieeRd  Thanks for your reply. 

I tried to place a `pyrightconfig.json`  in my project with `reportSelfClsParameterName ` set to `"none"` just now.
Sadly it doesn't work.  :(  
Hope that the maintainers could give us some hints.

**Comment by WieeRd** [comment]
@yaegassy Do you know where to put `pyrightconfig.json` file?

**Comment by yaegassy** [comment]
Place `pyrightconfig.json` in the project root. https://github.com/microsoft/pyright/blob/master/docs/configuration.md

However, the hint message cannot be suppressed by the pyright setting.

**Comment by you-n-g** [comment]
@yaegassy  I think we should leave this issue open.

**Comment by fannheyward** [comment]
You can disable the hint from coc-pyright v1.1.129, set `pyright.disableSelfClsNotAccessed` in your coc-settings.json.
