### ISSUE TITLE
How disable pyright message?

### ISSUE THREAD

**Issue by RastaDill** [fannheyward/coc-pyright#382]
Hello. I enable linting flake8, but how disable message pyroght?
Example:
    import os

Import module os, but not used. Vim show:
1) [Pyright] [H] "os" is not accessed
2) [flake8 F401] [E] 'os' imported but unused

How disabled first message?
I try set "reportUnusedImport" to false in coc-settings.json but this not working.
How jump to message linting?

**Comment by fannheyward** [comment]
Set `pyright.disableDiagnostics` to true to disable diagnostics from Pyright.

**Comment by RastaDill** [comment]
Thanks. My mistake, got confused about the parameters.

**Comment by ranelpadon** [comment]
In my case, this is not enough:
`"pyright.disableDiagnostics": true` 

need to add this also:
`"diagnostic.showUnused": false,`

as per https://github.com/fannheyward/coc-pyright/issues/271#issuecomment-764172559.
