### ISSUE TITLE
How naviaget pyright message?

### ISSUE THREAD

**Issue by RastaDill** [fannheyward/coc-pyright#383]
Hello. How jump to next/previous message pyright?
Maybe also have ability show preview all messages?

**Comment by yaegassy** [comment]
There is an explanation in the README of `coc.nvim` itself.

```vim
" Use `[g` and `]g` to navigate diagnostics
" Use `:CocDiagnostics` to get all diagnostics of current buffer in location list.
nmap <silent> [g <Plug>(coc-diagnostic-prev)
nmap <silent> ]g <Plug>(coc-diagnostic-next)
```

Check the help, README and wiki for basic usage and configuration of `coc.nvim`

- `h: coc-nvim`
- <https://github.com/neoclide/coc.nvim/blob/release/Readme.md>
- <https://github.com/neoclide/coc.nvim/wiki>

**Comment by RastaDill** [comment]
Yes. It's working, thanks!
