### ISSUE TITLE
How can i set a root folder for completion for python project on monorepo

### ISSUE THREAD

**Issue by luisiacc** [fannheyward/coc-pyright#389]
Situation, I have a mono repo with 2 projects, server: python, client: javascript, python project is on folder `server`, js project is on `client` folder, so canonical structure is something like this:

```
cool_project
	.git
	.editorconfig
	> server
		> settings
		> help
		- .venv
		- pyproject.toml
		- manage.py
	> client
		package.json
		...more js stuff
```

So I know that I can add `server` folder to `python.analysis.extraPaths` to local `.vim/coc-settings.json`, and that was recently working fine, but now for some reason, auto imports are attaching `server.` to all imported packages, so if I would like to import something from a local module `help.models`, then auto import would put `server.help.models`, and if I removed `python.analysis.extraPaths` then it does not find local modules at all, so I think it is because is not considering `server` as the root of the python project, so I like to know how hardcode the python root so coc know where it has to look.

**Comment by fannheyward** [comment]
Try `:h b:coc_root_patterns`.
