### ISSUE TITLE
Unknown import symbol

### ISSUE THREAD

**Issue by riazufila** [fannheyward/coc-pyright#392]
![image](https://user-images.githubusercontent.com/46749569/111614832-0556c800-881b-11eb-9334-595447535ea0.png)

I'm not sure how this happened. But this error has never appeared before on the same line.

**Comment by yaegassy** [comment]
@riazufila I installed the discord package and gave it a try. In my environment, there is no problem.

I recommend checking to see if there may be similar solved issues (closed issue). https://github.com/fannheyward/coc-pyright/issues

**Comment by riazufila** [comment]
Somehow when I open while im in virtual environment the error disappeared. It only appears on my environment without venv activated (but i do have discord both in venv and global).

**Comment by riazufila** [comment]
I found the issue only comes when I install the module using Arch package manager. The problem goes away when I installed using pip instead. Closing issue. Thank you.
