### ISSUE TITLE
"int" in set of "str"

### ISSUE THREAD

**Issue by edDask18** [fannheyward/coc-pyright#395]
Hello, I am trying to add an "***int***" to a set of "***str***", python is not return any error.
- **vim version:** 8.1 
- **coc-pyright** version: **1.1.123**
- python version: 3.8.5
![imagen](https://user-images.githubusercontent.com/48848672/111855852-b46fce00-8905-11eb-8ba7-25b08f51fd2c.png)
![imagen](https://user-images.githubusercontent.com/48848672/111855018-31e50f80-8901-11eb-830f-16b8f0f9f407.png)

The same thing happens with the ***update()*** method and python is not return any error too.

![imagen](https://user-images.githubusercontent.com/48848672/111856356-e20a4680-8908-11eb-9153-fe61b852346d.png)
![imagen](https://user-images.githubusercontent.com/48848672/111856346-d6b71b00-8908-11eb-8f36-f7b33151a612.png)

**Comment by yaegassy** [comment]
@edDask18 [pyright](https://github.com/microsoft/pyright) is a static type checker. It will point out the parts of the program that might lead to bugs.
