### ISSUE TITLE
How to use tabs for indentation?

### ISSUE THREAD

**Issue by ProgrammingLife** [fannheyward/coc-pyright#402]
I wanna use tabs for indentation. How to set it in coc-pyright?

**pyright.version: ** 1.1.118

**Comment by yaegassy** [comment]
@ProgrammingLife 

The indentation-related setting is a setting of "Vim8/Neovim" itself, Check the documentation and make the settings you need in `.vimrc/init.vim`.

**e.g.**:

- `:h tabstop`
- `:h shiftwidth`
- `:h softtabstop`
- `:h expandtab`
- `:h indent.txt`

**Comment by fannheyward** [comment]
coc-pyright does nothing for your code indentation.

**Comment by ProgrammingLife** [comment]
@fannheyward I've finally solved this. Neovim has hardcoded rules special just for python files so user settings are ignored.
Solution: https://www.reddit.com/r/neovim/comments/b7te96/vim_completely_ignoring_my_tab_settings_but_only/
