### ISSUE TITLE
No snippets like coc-python

### ISSUE THREAD

**Issue by ilkl** [fannheyward/coc-pyright#410]
There are no snippets like coc-python, except for keywords.

**Comment by fannheyward** [comment]
The vscode-python has already removed the snippets feature, https://github.com/microsoft/vscode-python/pull/15006, check https://github.com/microsoft/pylance-release/issues/629 https://github.com/microsoft/python-language-server/issues/2011 https://github.com/microsoft/vscode-python/issues/14566 and https://github.com/microsoft/vscode-python/issues/15220.

I'll leave this issue open for a while, waiting for more feedbacks.

**Comment by lodagro** [comment]
Can ultisnips be used tother with coc-pyright?
Tried it, but no completions on the snippets unfortunately.

**Comment by fannheyward** [comment]
I'm using coc-snippets with honza/vim-snippets, works as expected.

**Comment by lodagro** [comment]
Do you get the snippet previews in the completion overview?
I have to manually trigger snippet list, the snippets do not show up in the coc* completion.
In coc settings: ``` "pyright.completion.snippetSupport": true```.

Besides the completion&preview ultisnips+vim-snippets is working fine.

**Comment by fannheyward** [comment]
@lodagro yes, snippet preview is working, the snippet item will be labeled `[S]`.

<img width="546" alt="截屏2021-03-30 17 30 15" src="https://user-images.githubusercontent.com/345274/112967207-9748c400-917d-11eb-9117-76077d644e0a.png">

**Comment by lodagro** [comment]
Do i need to configure anything else besides ```"pyright.completion.snippetSupport": true``` to get this?

**Comment by fannheyward** [comment]
@lodagro No, maybe you need to use `coc-snippets`.

**Comment by lodagro** [comment]
I removed ```coc-snippets``` and switched from ```coc-python``` to ```coc-pyright``` at the same time. After this i no longer have the snippet completion and i was thinking this was due to ```coc-pyright```. But it is probably because i removed ```coc-snippets```. I do want to use ```ultisnips``` to process the ```vim-snippets``` instead of ```coc-snippets``` since ```coc-snippets``` is not supporting all ```ultisnips``` features (see also https://github.com/neoclide/coc-snippets#ultisnips-features).

**Comment by fannheyward** [comment]
@lodagro I see. I don't know how to make ultisnips work with coc completions.

**Comment by lodagro** [comment]
Found a solution, i installed ```coc-ultisnips```. The snippets are now in the completion list (without preview unfortunately) and are handled by ultisnips. Hard to get an overview for all these coc-nvim plugins.

See also https://github.com/neoclide/coc-sources

**Comment by fannheyward** [comment]
I'll close this issue, and will not port snippets from vscode-python/coc-python. If you want to use snippets, use coc-snippets.
