### ISSUE TITLE
Autocompletion happens twices

### ISSUE THREAD

**Issue by neerajbadlani** [fannheyward/coc-pyright#418]
**What's the output of `:CocCommand pyright.version`**
[coc.nvim] coc-pyright 1.1.127 with Pyright 1.1.127

![image](https://user-images.githubusercontent.com/3440085/113279613-2cd87680-9298-11eb-8a54-d10100a7348d.png)

![image](https://user-images.githubusercontent.com/3440085/113279711-4974ae80-9298-11eb-8081-5812060c3f33.png)

**Comment by fannheyward** [comment]
Yes, by default, there is no complete suggestion when you input `import `, no module names listed, suggestions will be triggered after you input continue or `coc#refresh()`.

coc-pyright adds a python-import completion source, as you can see it ends with `[PY]`. With python-import source, coc-pyright will list available modules after you input `import ` or `from `.

But this will make suggestion duplicate sometime, for example, `import ` will list modules, they're came from python-import source. Then you continue input `red`, will list `redis` and `readline`, both are from python-import, you delete and input `d` again, this will trigger both python-import and pyright sources, you got two same suggestions.

My purpose of add python-import source is to make import suggestions automatically, I will try to solve this duplicate problem, or add to configuration to disable it.
