### ISSUE TITLE
Quickfix import

### ISSUE THREAD

**Issue by MoronVV** [fannheyward/coc-pyright#419]
**What's the output of `:CocCommand pyright.version`**
`[coc.nvim] coc-pyright 1.1.127 with Pyright 1.1.127`

In coc-python it was quickfix option to import undefined var standing on it by `coc-fix-current` command.
Is there any alternative solution (not using autoimport while typing)?
![image](https://user-images.githubusercontent.com/24293616/113404186-6d2b1800-93b0-11eb-9912-6a1113104162.png)

**Comment by fannheyward** [comment]
Pyright doesn't has import code action support by now, https://github.com/microsoft/pyright/issues/251

**Comment by fannheyward** [comment]
coc-pyright v1.1.152 added import support by rope.

<img width="332" alt="截屏2021-06-25 下午5 58 42" src="https://user-images.githubusercontent.com/345274/123407838-fd0ee580-d5de-11eb-8b04-09ce0f198fa6.png">

**Comment by yaegassy** [comment]
@fannheyward I tried it in my environment.

If there is a "reportUndefinedVariable" in the diagnostics, the code action for auto import was displayed.

<img width="788" alt="coc-pyright-auto-import-action" src="https://user-images.githubusercontent.com/188642/123414255-a14c5880-d5ee-11eb-81ee-d95ca7ef8988.png">

**Comment by adnion** [comment]
Thank you for this great functionality!
I have an idea for an even faster workflow.
The option `2. Add "from _ import FastAPI"` could autocomplete paths for faster input.

What do you think about automatic suggestion of suitable imports? Any idea how it could work?
Even Microsoft's VSCode Pylance Server can't do this!

**Comment by fannheyward** [comment]
> autocomplete paths for faster input

Have no idea about this, because we don't know, and have no way to know where the module from. That's why I leave it blank to input.

**Comment by adnion** [comment]
In a python file we already have working autocompletion for imports. It's triggered automatically by default.
What if we could make the `Module:` popup think it's just a normal python file?

I don't know where `pyright.addImport` is located
https://github.com/fannheyward/coc-pyright/blob/724b7492924164777190de6e75f1c28466281093/src/codeActionsProvider.ts#L106-L112

**Comment by adnion** [comment]
I found that rope has autoimport functionality! Maybe we could pipe the suggestions into the popup
https://github.com/python-rope/rope/blob/master/docs/library.rst#ropecontribautoimport

**Comment by whitelilis** [comment]
![image](https://user-images.githubusercontent.com/1090230/132488985-d6be49ea-ad22-4b96-98c7-d1e34a918586.png)

Why I can‘t see the code action ？

[coc.nvim] coc-pyright 1.1.164 with Pyright 1.1.165

**Comment by fannheyward** [comment]
@whitelilis use `<Plug>(coc-codeaction-cursor)` to fire the code action.

**Comment by SuryaThiru** [comment]
Hi, 
I'm receiving errors using this functionality in vim 9.0.

Pyright version:
```
[coc.nvim] coc- pyright 1.1.325 with Pyright 1.1.327
```
On the cursor position,  I use the `<Plug>(coc-codeaction-cursor)` command, and receive the expected options:

![image](https://github.com/fannheyward/coc-pyright/assets/22935226/77612a83-5c10-4d42-b02a-633a26e8206e)

However, if I select 1, I get the following error:

```
[coc.nvim] Cannot perform addImport using selected element(s).
```

Could you tell me why its not adding in the import when it correctly identifies the missing module?
