### ISSUE TITLE
How to activate auto-import

### ISSUE THREAD

**Issue by jeanlucthumm** [fannheyward/coc-pyright#445]
I see the option in the completion list:

![image](https://user-images.githubusercontent.com/4934853/115788242-383f2f00-a378-11eb-8c8a-1162df3677ed.png)

But if I nagivate to that option, no auto import happens and it keeps the fully qualified symbol. I set the following as suggested in issue #90:

```
"python.analysis.diagnosticMode": "workspace"
```
But I'm not sure if that changed anything.

**Output of `:CocCommand pyright.version`**:
```
coc-pyright 1.1.126 with Pyright 1.1.126
```

**Comment by fannheyward** [comment]
> if I nagivate to that option, no auto import happens

After you `<CR>` to confirm the completion, is there any auto imports?

**Comment by jeanlucthumm** [comment]
There is not, however my `<CR>` is remapped to the following. Maybe I need to change this definition to trigger it somehow?
```
inoremap <expr> <CR>                                                                                                                                                                                        
      \ pumvisible() ? (empty(v:completed_item)?"\<C-n>":"\<C-g>u\<CR>") :                                                                                                                                  
      \ "\<C-g>u\<CR>"  
```

**Comment by fannheyward** [comment]
My `<CR>` mapping:

```
inoremap <silent><expr> <CR> pumvisible() ? coc#_select_confirm()
      \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
```
