### ISSUE TITLE
Trim newlines on completion/hover text

### ISSUE THREAD

**Issue by ehandal** [fannheyward/coc-pyright#446]
Completions/hovers often take up an extra line like so:

![image](https://user-images.githubusercontent.com/23243879/115897879-8872cb80-a422-11eb-8853-2d93ea1d141a.png)
![image](https://user-images.githubusercontent.com/23243879/115898493-3c745680-a423-11eb-816c-d95888fa1edf.png)

Could the trailing newlines be trimmed to keep these from taking up extra space?

Version: `[coc.nvim] coc-pyright 1.1.133 with Pyright 1.1.133`

**Comment by fannheyward** [comment]
Hover for `sys.exit` is

```
contents: {
    kind: 'markdown',
    value: '```python\n(function) exit: (__status: object = ...) -> NoReturn\n```'
  }
```

There's an `\n` in the code block, that's why you see the newline. But I think the client should not touch or modify the code block content.

**Comment by fannheyward** [comment]
Fixed on coc https://github.com/neoclide/coc.nvim/pull/3055
