### ISSUE TITLE
isort always uses saved file, not current buffer state

### ISSUE THREAD

**Issue by languitar** [fannheyward/coc-pyright#448]
**What's the output of `:CocCommand pyright.version`**

[coc.nvim] coc-pyright 1.1.134 with Pyright 1.1.135

When using isort as the import sorting provider, triggering the code action on an unsaved buffer uses the saved file, not the saved buffer.

**Comment by fannheyward** [comment]
It's expected, coc-pyright just runs something like `isort xxx.py`, parses output and applies the diff.

**Comment by languitar** [comment]
That's pretty confusing because reformatting with black uses the actual buffer contents. According to [this issue comment](https://github.com/PyCQA/isort/issues/40#issuecomment-25883821), using stdin should also be possible for isort.

**Comment by fannheyward** [comment]
coc-pyright 1.1.135 has improved isort, use current buffer content.

**Comment by languitar** [comment]
Thanks!
