### ISSUE TITLE
Enable ignoring warnings on an ad hoc basis

### ISSUE THREAD

**Issue by jean** [fannheyward/coc-pyright#453]
**What's the output of `:CocCommand pyright.version`**

[coc.nvim] coc-pyright 1.1.135 with Pyright 1.1.135                                                                                                                                                

PyRight emits warnings for e.g. unused names (https://github.com/microsoft/pyright/issues/1118). 
Nvim with CoC displays this quite obtrusively. With PyLint, it's possible to silence warnings on individual lines using comments like `# pylint: disable=W0612`. 

Is anything similar possible for PyRight?

**Comment by fannheyward** [comment]
Put `# type: ignore` in the end of the line.

**Comment by jean** [comment]
Hmm maybe something else is missing on my side .. 
![Screenshot from 2021-04-30 10-18-57](https://user-images.githubusercontent.com/84800/116644477-acdc2400-a99d-11eb-8fe4-eb6e1d7caf4d.png)

**Comment by yaegassy** [comment]
@jean Please check here and give it a try. https://github.com/fannheyward/coc-pyright/issues/271#issuecomment-764172559

**Comment by jean** [comment]
@yaegassy thanks for the pointer. It's good, but it's global. I would like to normally see this type of hint, and to be able to turn it off on a case-by-case basis.

**Comment by yaegassy** [comment]
@jean It is also possible to change the settings at the "project level". `:CocLocalConfig`

I had previously considered adding a feature that would completely suppress the hint messages themselves, but for various reasons, this feature has been removed. https://github.com/fannheyward/coc-pyright/pull/428#issue-609950918

**Comment by jean** [comment]
@yaegassy project level is better already, but this is really the kind of thing that's relevant on a case by case basis. It looks like https://github.com/fannheyward/coc-pyright/pull/428#issue-609950918 is about a global category of parameters that should not be flagged. 
In my case, it's about warnings that would normally be helpful and desired, e.g. in this case about a variable that's unused but present due to the shape of the data being iterated, that I'd like to silence explicitly after due consideration, so that others who look at the code (including future me) know what we're up to.

**Comment by yaegassy** [comment]
@jean OK, I understand what you want to do. But unfortunately, there is no way to suppress this hint message individually at the moment.

**Comment by ssgosh** [comment]
Does something like this work: https://stackoverflow.com/a/72322304/2109112 ?
