### ISSUE TITLE
linting not working at all

### ISSUE THREAD

**Issue by ipsod** [fannheyward/coc-pyright#465]
**What's the output of `:CocCommand pyright.version`**
[coc.nvim] coc-pyright 1.1.137 with Pyright 1.1.137
nvim version: NVIM v0.5.0-dev+1302-g8a93d1028

Hi.  I can't get linting to work at all.  I load the virtualenv before opening nvim.

I have this in my coc-settings.json:

`  "python.linting.pylintEnabled": true,
  "python.linting.enabled": true,
  "python.pythonPath": "/home/zero/rockbox/bin/coc_nvim_stuff/pyright_fix.bash",
  "python.linting.flake8Enabled": true,
  "python.linting.pylintEnabled": true,
`

**Comment by fannheyward** [comment]
What's the output of `:CocCommand workspace.showOutput` - `coc-pyright-linting` ?

**Comment by ipsod** [comment]
```
Using python from /home/zero/rockbox/bin/coc_nvim_stuff/pyright_fix.bash

########## active linter: bandit
Linting with bandit failed: bandit module is not installed.
Module 'bandit' not installed.

```

That doesn't seem right - I didn't configure it to use bandit.  I double checked and modified my CocConfig, but still get the same result after restarting nvim:

```
    "python.linting.pylintEnabled": true,
    "python.linting.enabled": true,
    "python.pythonPath": "/home/zero/rockbox/bin/coc_nvim_stuff/pyright_fix.bash",
    "python.linting.flake8Enabled": true,
    "python.linting.pylintEnabled": true,
    "python.linting.banditEnabled": false,
```

**Comment by ipsod** [comment]
I found that it was an issue elsewhere in my CocConfig.  I had some bad settings that were breaking Coc in general.
