### ISSUE TITLE
`.vim/coc-settings.json` keeps getting recreated and modified with absolute path for `python.pythonPath`

### ISSUE THREAD

**Issue by Kache** [fannheyward/coc-pyright#477]
**What's the output of `:CocCommand pyright.version`**
`[coc.nvim] coc-pyright 1.1.137 with Pyright 1.1.138`

No matter what I do, `.vim/coc-settings.json` keeps getting automatically recreated/modified to have an absolute path for `python.pythonPath`.

I tried setting `"python.pythonPath": "python"` in `~/.vim/coc-settings.json` and deleting `.vim` in project folders.
I tried setting `"python.pythonPath": "python"` in `PROJ_DIR/.vim/coc-settings.json` and it gets modified to an absolute path -- sometimes to one in a different project.

If `pythonPath` can be determined automatically so, why does it have to keep being written?
If correct configuration actually matters, why does it keep getting changed to different values?

If it's relevant, I'm working in a monorepo environment.

**Comment by yaegassy** [comment]
Me too. For me, it is better if `.vim/coc-settings.json` is not created automatically.

I always have to delete `.vim/coc-settings.json` or add `.vim` to ".gitignore". :(

I will create the `.vim/coc-settings.json` myself if I need it.

However, there are some people who cannot detect the correct "pythonPath" and cannot use coc-pyright correctly. In that case, it may be beneficial for `.vim/coc-settings.json` to be created.

**Comment by Kache** [comment]
Created and _automatically continually modified_?
Also created despite being set in `~/.vim/coc-settings.json`?

And as to the "set to path to a different project", it feels like it's due to the extension getting confused when I open a file in a different project within a monorepo (of multiple projects), and it finds a different `.venv`.

**Comment by fannheyward** [comment]
The `python.pythonPath` setting has been improved, coc-pyright will try to detect the correct python to use, and send to Pyright without set to coc-settings.json.
