### ISSUE TITLE
Linting with Django

### ISSUE THREAD

**Issue by lioaslan** [fannheyward/coc-pyright#480]
Hi,
I'm using Django for API development and `pylint` for linting. However, it needs plugin `pylint-django` for linting Django exactly. Apparently, the authors didn't set `load-plugin` for `pylint` configuration so I met the error below. That's only a query of the model. See example [here](https://docs.djangoproject.com/en/3.2/topics/db/queries/#saving-foreignkey-and-manytomanyfield-fields) in Django's documentation.
https://github.com/fannheyward/coc-pyright/blob/793c0c4cdb8ee897ce20af09714289be3e9ae670/src/linters/pylint.ts#L44-L63
![image](https://user-images.githubusercontent.com/24852182/118531309-e66ba800-b76f-11eb-83a3-008af8f0dbaf.png)
Additionally, I think `python.linting.enabled` didn't work. I set it to `false` to turn off linting but the error still shows.
Thank you for any help!

**Comment by fannheyward** [comment]
You can set `.pylintrc` in your project root like:

```
[MASTER]
load-plugins=pylint_django
```

pylint will load and use the plugins. This will work in coc-pyright next release.

> `python.linting.enabled` didn't work. I set it to `false` to turn off linting but the error still shows.

`python.linting.enabled` only enable/disable lint by pylint/flake8 etc, the errors you got are came from Pyright.

**Comment by lioaslan** [comment]
I tried put it into `.pylintrc` but it didn't work
![image](https://user-images.githubusercontent.com/24852182/118585330-d8934280-b7c2-11eb-8c1e-bed15f634e86.png)

**Comment by lioaslan** [comment]
How to use linting by pylint instead of Pyright? I tried to set `python.linting.pylintEnabled` but I didn't work

**Comment by fannheyward** [comment]
@lioaslan set `pyright.disableDiagnostics` to true.

**Comment by fannheyward** [comment]
@lioaslan try v1.1.141 for pylint plugins support.

**Comment by lioaslan** [comment]
Thanks for the great update!
