### ISSUE TITLE
Passing variable to @classmethod super() triggers invalid "[Pyright reportGeneralTypeIssues] [E]"

### ISSUE THREAD

**Issue by Kache** [fannheyward/coc-pyright#484]
**What's the output of `:CocCommand pyright.version`**
`[coc.nvim] coc-pyright 1.1.137 with Pyright 1.1.138`

```python
class Foo:
    def __init__(self):
        self.x = 'foo'


class Bar(Foo):
    @classmethod
    def from_str(cls, s):
        obj = cls.__new__(cls)
        super(cls, obj).__init__()  # on this line, over `cls`
        # super(Bar, obj).__init__()  # doesn't error, but this line is equivalent
        obj.x += 'bar' + s
        return obj


print(Bar.from_str('hello').x)
```

Getting:

`[Pyright reportGeneralTypeIssues] [E] Expected class type as first argument to "super" call but received "Type[Bar]"`

As I understand it, `from_str` is a [standard way of creating an "alternative" initializer](https://stackoverflow.com/a/38885481/234593) in Python.

**Comment by yaegassy** [comment]
@Kache If you use the pyright extension of "VSCode", or if you use pyright on the command line, the error will be reported in the same way.

**Visual Studio Code (pyright extension)**:

<img width="957" alt="vscode-pyright" src="https://user-images.githubusercontent.com/188642/118595349-dbebf580-b7e5-11eb-97aa-83a6d60443d2.png">

**cli**:

```
(venv) check$ pyright check.py
# ...snip
Found 1 source file
/private/tmp/check/check.py
  /private/tmp/check/check.py:10:15 - error: Expected class type as first argument to "super" call but received "Type[Bar]" (reportGeneralTypeIssues)
1 error, 0 warnings, 0 infos
Completed in 0.581sec
```

If you feel that being error-reported is a problem, you need to report a bug or make a suggestion to "pyright" itself.

**Comment by Kache** [comment]
Ah, I see. I'll report it upstream
