### ISSUE TITLE
Sort imports on save?

### ISSUE THREAD

**Issue by nastynaz** [fannheyward/coc-pyright#489]
Is there a way to automatically sort imports on save using isort?

In my `coc-settings.json` I have:

```
{
  "coc.preferences.formatOnSaveFiletypes": ["python"],
  "python.linting.pylintEnabled": false,
  "python.linting.flake8Enabled": true,
  "python.linting.mypyEnabled": true,
  "python.linting.enabled": true,
  "python.formatting.provider": "black",
  "pyright.organizeimports.provider": "isort"
}
```

but it doesn't seem to work. The only way I can get it working is if I type `CocCommand python.sortImports`. Is there a way to get it so that it does this every time a file is saved?

**Comment by fannheyward** [comment]
Try some autocmd like `autocmd BufWritePre *.py silent! :call CocAction('runCommand', 'python.sortImports')`.

**Comment by yaegassy** [comment]
@nastynaz As a side note, it can also be quickly executed from a "code action".

<img width="543" alt="coc-pyright-isort" src="https://user-images.githubusercontent.com/188642/119096467-99792180-ba4e-11eb-810a-1c54df918338.png">
