### ISSUE TITLE
Document that coc-pyright does not work for scripts that are in home dir

### ISSUE THREAD

**Issue by apirogov** [fannheyward/coc-pyright#492]
I just spent multiple hours trying to understand why Coc autocomplete does not work until I stumbled onto to possibility to see the logs of the language server, which told me where the problem was:
```
[Warn  - 11:11:33] Ignored rootPath /home/admin of client "pyright"
```
It would be great if this woud be somewhere in the readme. I just tried out coc with pyright on simple test.py in my homedir and was almost giving up on it. 

PS: Now that I could finally see it in action - looks really great, thanks for creating it!

**Comment by yaegassy** [comment]
This is not a problem with coc-pyright, but with coc.nvim itself.

- <https://github.com/neoclide/coc.nvim/issues/3102>
- <https://github.com/neoclide/coc.nvim/commit/7904a9e7dff16354ba91644647b4871722879743>

For example, `vim-language-server` need to work in the "HOME" directory as well, so I think this behavior is a "bug".

**Comment by thesimpleboy** [comment]
Yes, I have the same problem on my Linux.but I don’t have this problem on my Mac, Why?

**Comment by arunanshub** [comment]
Can confirm. None of the coc plugins work when neovim is opened in home directory.

**Comment by zuoxinyu** [comment]
> Yes, I have the same problem on my Linux.but I don’t have this problem on my Mac, Why?

Maybe your coc on mac isn't the latest.

**Comment by fannheyward** [comment]
Fixed on latest release branch of coc.nvim.
