### ISSUE TITLE
coc-pyright isn't recognizing new files

### ISSUE THREAD

**Issue by gbrennon** [fannheyward/coc-pyright#493]
coc-pyright version:
`[coc.nvim] coc-pyright 1.1.137 with Pyright 1.1.138 `
---

Hey folks,

If I create a new(or rename one) file in my workspace I need to run `CocCommand pyright.restartServer`(or re-open nvim) so it can notice the new file.

If I don't execute any of those operations the plugin just show this:
`[Pyright reportMissingImports] [E] Import "bus.messages.message_body" could not be resolved`

**Comment by fannheyward** [comment]
Try to install https://github.com/facebook/watchman, coc can watch the project with watchman.
