### ISSUE TITLE
pydocstyle's default --match option should be honored

### ISSUE THREAD

**Issue by koluacik** [fannheyward/coc-pyright#494]
**What's the output of `:CocCommand pyright.version`**
[coc.nvim] coc-pyright 1.1.141 with Pyright 1.1.142

By [default](http://www.pydocstyle.org/en/stable/usage.html#cli-usage) pydocstyle does not check file names starting with `test_` for docstrings. Running `pydocstyle` from shell confirms this. However, I still see missing docstring warnings while working on my test files. I could disable linting altogether for test files, or disable pydocstyle while writing tests, but both are inconvenient. ~~Ideally, there should be a way to specify arguments passed to `pydocstyle`~~ there is.

Is this an issue with the upstream, or can this be handled within coc-pyright?

edit: Appearently, there is an option for that: `"python.linting.pydocstyleArgs": [ "--match='(?!test_).*\\.py" ]` (notice the double \ because coc complained about invalid escape character.) Should this option have a default value that reflects that of the standalone `pydocstyle`?

**Comment by yaegassy** [comment]
@fannheyward It is pydocstyle, but apparently it is not excluded if you pass the file as absolute or relative path.

```
(venv) $ pwd
/private/tmp/pydocstylecheck
(venv) $ cat test_main.py
import unittest

class TestMain(unittest.TestCase):
    def test_name(self):
        pass
(venv) $ # NG (not excluded)
(venv) $ pydocstyle /private/tmp/pydocstylecheck/test_main.py
/private/tmp/pydocstylecheck/test_main.py:1 at module level:
        D100: Missing docstring in public module
/private/tmp/pydocstylecheck/test_main.py:3 in public class `TestMain`:
        D101: Missing docstring in public class
/private/tmp/pydocstylecheck/test_main.py:4 in public method `test_name`:
        D102: Missing docstring in public method
(venv) $ # OK
(venv) $ pydocstyle test_main.py
(venv) $
```

**REF?**:

- <https://github.com/PyCQA/pydocstyle/issues/363>
- <https://github.com/PyCQA/pydocstyle/pull/529>

**Fix?**:

In my environment, I confirmed that it worked fine by passing the file name as is. https://github.com/fannheyward/coc-pyright/blob/master/src/linters/pydocstyle.ts#L12

```typescript
    const messages = await this.run([path.basename(Uri.parse(document.uri).fsPath)], document, cancellation);
```

(If the this issue has already been solved, you can ignore it.)

**Comment by fannheyward** [comment]
@yaegassy yes, you're right, this fix won't work.

**Comment by yaegassy** [comment]
@fannheyward I checked this PR in coc.nvim before it was merged. https://github.com/neoclide/coc.nvim/pull/3106

**Comment by fannheyward** [comment]
https://github.com/microsoft/vscode-python/issues/11728

**Comment by fannheyward** [comment]
Use file name is incorrect, for example:

```sh
main.py
test
test/__init__.py
test/m.py
test/test_m.py
```

`nvim main.py` is working, but `nvim test/m.py` will run something like `pydocstyle m.py`.

**Comment by yaegassy** [comment]
@fannheyward Isn't it a problem that can be solved by passing the "file name" instead of the "file path"?

**Fix it like this**:

```typescript
    const messages = await this.run([path.basename(Uri.parse(document.uri).fsPath)], document, cancellation);
```

**Comment by fannheyward** [comment]
@yaegassy "file name" is not ok. `nvim test/m.py` will become `pydocstyle m.py` that m.py not found to run.

**Comment by yaegassy** [comment]
@fannheyward Oh... that's exactly how it should behave... :(

**Comment by fannheyward** [comment]
@yaegassy my example maybe misleading. For example:

```
main.py
lib/m.py
lib/test_m.py
```

If we use "file name", `nvim lib/m.py` runs `pydocstyle m.py`.

**Comment by yaegassy** [comment]
Unfortunately, vscode-python is not excluded either... It's currently a disappointing specification :(

<img width="739" alt="vscode-pydocstyle" src="https://user-images.githubusercontent.com/188642/119431987-7dc39300-bd4e-11eb-820e-563c0df37b0f.png">

**Comment by fannheyward** [comment]
The key problem is `pydocstyle lib` will ignore `test_m.py` by default, but `pydocstyle lib/test_m.py` will run it.

**Comment by fannheyward** [comment]
Fix: run `pydocstyle` for current document's dir, and file message for current document only.

**Comment by yaegassy** [comment]
@fannheyward I've tried this commit: https://github.com/fannheyward/coc-pyright/commit/d4b3e3b603f4119c70c149a2a95b90232b24a10f

It seems to run recursively when you pass the directory, so it may take too long to complete for large projects.

In some cases, the pydocstyle process might stay up for a very long time.

**Comment by fannheyward** [comment]
@yaegassy good catch.

**Comment by fannheyward** [comment]
Check filename with `^test_.*\.py$`, return empty when matched.

**Comment by aiwalter** [comment]
@fannheyward for me this does not work, it seems it just excludes all.
