### ISSUE TITLE
Jumping to definitions of overloaded operators

### ISSUE THREAD

**Issue by ozars** [fannheyward/coc-pyright#501]
```
[coc.nvim] coc-pyright 1.1.143 with Pyright 1.1.143
```

Some C++ language servers can jump to definition of overloaded operators when requested while hovering on overloaded operators. Is it possible to do similarly for python functions like `__getitem__`, `__call__`, `__add__` etc.? It would be very useful when navigating around in complex libraries.

Example:

```
class A:
    def __call__(self):
        ...

    def __getitem__(self, i):
        ...

a = A()

a()
a[1]
```

Expected behavior: On `<Plug>(coc-definition)` while  hovering on either parentheses of `a()`, it jumps as if it were hovering a `a.__call__` function call. Similarly for square brackets of `a[1]` and `a.__getitem__`.

Current behavior: From the opening parenthesis/bracket, it jumps to `a = A()`, and from closing ones it gives error "definition not found".

**Comment by fannheyward** [comment]
Unfortunately Pyright doesn't provide this feature. Tested with VSCode+Python+Pylance, same results.
