### ISSUE TITLE
Multiple formaters?

### ISSUE THREAD

**Issue by UltiRequiem** [fannheyward/coc-pyright#507]
**What's the output of `:CocCommand pyright.version`**
![image](https://user-images.githubusercontent.com/71897736/120211936-0a5ecd00-c1f7-11eb-9173-438d4cd828b0.png)
It would be posible to insted of:
![image](https://user-images.githubusercontent.com/71897736/120212211-53168600-c1f7-11eb-8128-a611fcc8adfc.png)
Do something like:
![image](https://user-images.githubusercontent.com/71897736/120212253-5f024800-c1f7-11eb-8e0f-b0a973a1bbfd.png)
I mean that after the extension has formatted with black, that it also does it with autopep8 and the rest that I put in the list.
Thank you very much for the work on this extension, it is really cool!

**Comment by fannheyward** [comment]
No such support yet, why do you want multiple formatter for the same project?

**Comment by UltiRequiem** [comment]
It is a feature that I was already used to when I was using [vim-autoformat](https://github.com/vim-autoformat/vim-autoformat).

![image](https://user-images.githubusercontent.com/71897736/120335909-7c96e680-c2b7-11eb-8f5b-7b363bf1eeec.png)

**Comment by fannheyward** [comment]
I don't plan to add multiple formatter in coc-pyright.

1. from vim-autoformat's document, I think the multiple formatters will be useful for single file that contains multiple languages, for example vue contains js and html template and css, runs multiple formatters for the single file one by one to format each part
2. for Python, I think it's better to use one formatter for the file/project
3. the main reason, coc-pyright uses coc's `formatOnSave` to do formatting, there's a time limit to run black/yapf, multiples formatters maybe not all succeed. https://github.com/fannheyward/coc-pyright/issues/229 https://github.com/fannheyward/coc-pyright/issues/424

**Comment by UltiRequiem** [comment]
Oh, Ok
