### ISSUE TITLE
"Rename" does not work with coc-python + coc-pyright

### ISSUE THREAD

**Issue by yaegassy** [fannheyward/coc-pyright#51]
## Describe the bug

I use `coc-python + coc-pyright`.

"Rename" doesn't work if coc-pyright is installed.

An error message `[coc.nvim] Invalid position for rename` is displayed.

"Rename" works when coc-pyright is uninstalled.

## CocInfo versions

```
vim version: NVIM v0.5.0-340-gd3a9d75c0
node version: v12.13.1
coc.nvim version: 0.0.74
term: iTerm.app
platform: darwin
```

## coc-settings.json

```json
  ...snip
  "python.jediEnabled": false,
  ...snip
  "pyright.disableLanguageServices": true,
  "pyright.openFilesOnly": true,
  ...snip
```

## Demo (Animation GIF)

![coc-pyright-rename-issue-1200](https://user-images.githubusercontent.com/188642/73256303-071f8f80-4205-11ea-91e2-cea1b50ddaed.gif)

**Comment by yaegassy** [comment]
`:CocList outline` had the same problem.

":CocList outline" doesn't work if coc-pyright is installed.

**Comment by fannheyward** [comment]
After some dig I found that set`"pyright.disableLanguageServices": false` will fix this error.

This problem is caused because: Pyright's language server is faster than coc-python's, when you do `rename` calls, Pyright will return the results first and change the document, then coc-python found the document changed, `Invalid position for rename`.

I'd prefer to use `coc-python` or `coc-pyright` alone, not both. Maybe we should disable `coc-pyright` if `coc-python` is activated.

**Comment by fannheyward** [comment]
Latest coc.nvim has fixed the range error, now you can use coc-pyright and coc-python together.

**Comment by yaegassy** [comment]
Thank you. I'll try.

**Comment by yaegassy** [comment]
@fannheyward 

I tried the coc-python + coc-pyright.
I found an issue where the completion was duplicated.

<img width="539" alt="dup_example_1" src="https://user-images.githubusercontent.com/188642/78892789-f614b980-7aa4-11ea-8322-f2b47f49c6e2.png">

<img width="470" alt="dup_example_2" src="https://user-images.githubusercontent.com/188642/78892817-0036b800-7aa5-11ea-9889-d3a7f1b858f1.png">

**Comment by fannheyward** [comment]
Set `pyright.disableLanguageServices` to true, this will disable Pyright LS, left only lint.

**Comment by yaegassy** [comment]
When "pyright.disableLanguageServices" is set to true, `Rename` and `:CocList outline` do not work properly.  :(

**Comment by fannheyward** [comment]
@yaegassy I've added `pyright.disableCompletion`, a dirty-hack to disable completion only.

**Comment by yaegassy** [comment]
Thank you.

**Comment by maxnoe** [comment]
I have the same problem (renaming not working) but I only have `coc-pyright` installed, not `coc-python`. Any idea?

**Comment by fannheyward** [comment]
@maxnoe can't reproduce, does other coc-pyright functions, eg code completion, goto definition, work?

**Comment by maxnoe** [comment]
Yes, they do.

**Comment by fannheyward** [comment]
@maxnoe please open a new issue with `:CocInfo`, `:CocOpenLog`.

**Comment by maxnoe** [comment]
I think it was just that I was testing it in my home (lots of stray python scripts) and it somehow tried to identify the variable also in other scripts?

Testing in a Project, it worked nicely.
