### ISSUE TITLE
Virtual enviornment imports not found

### ISSUE THREAD

**Issue by hatzel** [fannheyward/coc-pyright#512]
Version: coc-pyright 1.1.146 with Pyright 1.1.146

I have a virtual environment created using: `python -m virtualenv venv`. I activate it and start vim in the same shell, apparently the correct python path is set in pyright, as the log output (using `:CocCommand workspace.showOutput`) shows the following lines:
```
Using python from /tmp/test_project/venv/bin/python

[Info  - 12:13:31 PM] Pyright language server 1.1.146 starting
[Info  - 12:13:31 PM] Server root directory: /home/hansole/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/
[Info  - 12:13:31 PM] No configuration file found.
[Info  - 12:13:31 PM] No pyproject.toml file found.
[Info  - 12:13:31 PM] Setting pythonPath for service "test_project": "/tmp/test_project/venv/bin/python"
[Warn  - 12:13:31 PM] stubPath /tmp/test_project/typings is not a valid directory.
[Info  - 12:13:31 PM] Assuming Python version 3.9
[Info  - 12:13:31 PM] Assuming Python platform Linux
[Error  - 12:13:32 PM] Exception received when installing recursive file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Error  - 12:13:32 PM] Exception received when installing recursive file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Info  - 12:13:32 PM] Searching for source files
[Info  - 12:13:32 PM] Auto-excluding /tmp/test_project/venv
[Info  - 12:13:32 PM] Found 1 source file
```

For dependencies installed only in the virtual environment, however, I get: `import-error: Unable to import <modulename>` annotations when importing them.

Any ideas what's causing this, could it be the TypeError? From [my understanding this is the recommended workflow.](https://github.com/fannheyward/coc-pyright/issues/67#issuecomment-670292342).

I have no local configuration files (`.vim` and `pyrightconfig.json` don't exist),  My global coc-settings look like this:
```
{
  "diagnostic.virtualText": false,
  "diagnostic.checkCurrentLine": true,
  "diagnostic.messageTarget": "float",
  "diagnostic.level": "information",
  "suggest.autoTrigger": "none",
  "signature.enable": false,
  "rust-analyzer.diagnostics.enable": true,
  "python.linting.flake8Enabled": false,
  "python.linting.pylintEnabled": false,
  "python.formatting.provider": "black",
  "python.formatting.blackPath": "/usr/bin/black"
}
```

**Comment by fannheyward** [comment]
> Using python from /tmp/test_project/venv/bin/python

This means coc-pyright detects the correct Python venv and uses it for Pyright.

The `import-error: Unable to import` error may not came from coc-pyright. Do you have another pylint tools?

**Comment by hatzel** [comment]
Good idea, but as far as I know there should be nothing else producing this ![image](https://user-images.githubusercontent.com/2643354/120631409-2321e980-c468-11eb-88d5-68847e44007c.png)

**Comment by fannheyward** [comment]
The error message is not came from coc-pyright, because we don't use messages to show errors.

**Comment by hatzel** [comment]
Thanks a lot for the quick answers! figured out that ale was still installed.
