### ISSUE TITLE
Third Party modules are not recognised by pyright

### ISSUE THREAD

**Issue by 3301n** [fannheyward/coc-pyright#530]
**What's the output of `:CocCommand pyright.version`**
[coc.nvim] coc-pyright 1.1.150 with Pyright 1.1.150  

**What's the output of `:CocCommand workspace.showOutput Pyright`**
Workspace: /home/kali                                                                                                                                        
  2 Using python from /usr/bin/python                                                                                                                            
  3                                                                                                                                                              
  4 [Warn  - 12:09:38 PM] Ignored rootPath /home/kali of client "pyright"                                                                                        
  5 [Info  - 12:09:39 PM] Pyright language server 1.1.150 starting                                                                                               
  6 [Info  - 12:09:39 PM] Server root directory: /home/kali/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/                           
  7 [Info  - 12:09:39 PM] No pyproject.toml file found.                                                                                                          
  8 [Info  - 12:09:39 PM] Setting pythonPath for service "<default>": "/usr/bin/python"                                                                          
  9 [Warn  - 12:09:39 PM] stubPath typings is not a valid directory.                                                                                             
 10 [Warn  - 12:09:39 PM] Python version 2.7 from interpreter is unsupported                                                                                     
 11 [Info  - 12:09:39 PM] Assuming Python platform Linux                                                                                                         
 12 [Info  - 12:09:39 PM] Searching for source files                                                                                                             
 13 [Info  - 12:09:39 PM] No source files found. 

When i import bs4 module or requests module pyright is showing error
[Pyright reportMissingImports] [E] Import "bs4" could not be resolved 
[Pyright reportMissingModuleSource] [W] Import "requests" could not be resolved from source

![vim](https://user-images.githubusercontent.com/69240615/122718252-55b24b80-d28a-11eb-8b82-867f8016095e.png)

**Comment by fannheyward** [comment]
1. `Workspace: /home/kali`, you should not code your py files in your HOME, put it in a project folder
2. `Python version 2.7 from interpreter is unsupported`, Pyright only works Python 3+

**Comment by 3301n** [comment]
How could i change my interpreter into python3?

**Comment by fannheyward** [comment]
Do you have Python 3 installed? You can set it by `python.pythonPath` in your coc-settings.json.

**Comment by 3301n** [comment]
Thanks for the help I uninstalled python2 and installed python-is-python3 and it worked
