### ISSUE TITLE
Only critical errors are now underlined

### ISSUE THREAD

**Issue by dob9601** [fannheyward/coc-pyright#542]
Issue is due to a breaking change in coc.nvim. See: https://github.com/neoclide/coc.nvim/issues/3185

**What's the output of `:CocCommand pyright.version`**
`coc-pyright 1.1.154 with Pyright 1.1.154`

**Comment by fannheyward** [comment]
In my tests, Error/Warning/Information level diagnostics are underlined, only Hint level diagnostic is not. Can you give a test py file?

**Comment by dob9601** [comment]
My mistake, its specifically linting errors of any severity

**Comment by dob9601** [comment]
This would be fine if, like pyright hints it greyed out the text - but it does not

**Comment by fannheyward** [comment]
Will look into this if it's possible or not.

**Comment by fannheyward** [comment]
> 6,1,F,F401:'os' imported but unused

This is an error message from Flake8, only line(6) and column(1) info are available, no error end is provided, we can't make range for the diagnostic.

**Comment by dob9601** [comment]
@fannheyward the problem is that since it's not underlined or greyed out, there's no easy way to see where you need to hover in order to view the actual error message in a floating window.

**Comment by fannheyward** [comment]
@dob9601 yes, I know your problem, but without the error/warning end position, we can't do _correct_ underline or grey out for the diagnostic.

**Comment by dob9601** [comment]
As a workaround, would it be possible to infer the range by having the end column exactly 1 word (vim word style) to the right? In my experience this would be correct most of the time, and in situations where it's not it gives you a rough ballpark of where the error is located - which is better than having to scan your cursor across the line from left to right until you get a bubble (unless you have diagnostics open)

**Comment by fannheyward** [comment]
@dob9601 coc used to do a simple hack: if LS returns empty range, for example (3, 3, 3, 3), starts with line 3 char 3, ends with line 3 char 3, coc would add one char to the end, made it to (3, 3, 3, 4). This hack has been removed in https://github.com/neoclide/coc.nvim/pull/3147, this is the breaking change.

Maybe we can add this range format in coc-pyright.

**Comment by fannheyward** [comment]
Try coc-pyright v1.1.155.

**Comment by dob9601** [comment]
@fannheyward I still don't seem to be getting any underlining/greying out of linting errors at all. Have double checked, version is reading as v1.1.155 and have tried uninstalling and reinstalling too

**Comment by fannheyward** [comment]
@dob9601 which linter do you use? Can you post an example code for me to test?

**Comment by dob9601** [comment]
Played around with it a bit more. Linting errors are being highlighted, but not those of "Information" severity (from both flake8 and pylint. They're not being greyed out at all either. Unsure if this is intentional behaviour or not @fannheyward

**Comment by dob9601** [comment]
Example code:
```py
def func():
    """This is worded non-imperatively and has no fullstop"""

    return None # Shouldn't be a space before this
```
None of these errors are highlighted. Some are of information level, some are of error (such as the lack of 2 spaces before the inline comment. None are underlined on my end.

**Comment by dob9601** [comment]
Language server output:
```
########## Linting Output - flake8##########
1,1,D,D100:Missing docstring in public module
2,1,D,D202:No blank lines allowed after function docstring
2,1,D,D400:First line should end with a period
2,1,D,D401:First line should be in imperative mood; try rephrasing
4,16,E,E261:at least two spaces before inline comment

########## Linting Output - flake8##########
1,1,D,D100:Missing docstring in public module
2,1,D,D202:No blank lines allowed after function docstring
2,1,D,D400:First line should end with a period
2,1,D,D401:First line should be in imperative mood; try rephrasing
4,16,E,E261:at least two spaces before inline comment

########## Linting Output - pylint##########
************* Module temp
1,0,convention,C0114:Missing module docstring (missing-module-docstring)

------------------------------------------------------------------
Your code has been rated at 5.00/10 (previous run: 5.00/10, +0.00)


########## Linting Output - pylint##########
************* Module temp
1,0,convention,C0114:Missing module docstring (missing-module-docstring)

------------------------------------------------------------------
Your code has been rated at 5.00/10 (previous run: 5.00/10, +0.00)
```
Have checked the output twice, and both times 2 identical outputs were produced for each linter

**Comment by pittcat** [comment]
@dob9601 It seems that after the update I can see the underline .
![image](https://user-images.githubusercontent.com/22888402/124601295-417d6980-de9a-11eb-9586-c332db6d0ef5.png)

**Comment by dob9601** [comment]
> @dob9601 It seems that after the update I can see the underline .
> ![image](https://user-images.githubusercontent.com/22888402/124601295-417d6980-de9a-11eb-9586-c332db6d0ef5.png)
> 

Can you try it with the snippet I sent? I'm getting the underline sometimes but not always

**Comment by pittcat** [comment]
![image](https://user-images.githubusercontent.com/22888402/124601693-b781d080-de9a-11eb-8699-e2f922dd1310.png)

**Comment by dob9601** [comment]
![image](https://user-images.githubusercontent.com/24723950/124603856-46262b80-de62-11eb-9c02-7ff4f0ee1496.png)
I'm getting extra errors because I'm using flake8-docstrings (which used to work fine before this change to coc.nvim). Old behaviour iirc was that the space between `None` and `#` would be underlined

**Comment by fannheyward** [comment]
@dob9601 Yes, the fix in v1.1.155 is not 100% same as before, only error like `11,0,error,E0401:Unable to import 'os' (import-error)` will be parsed and adjusted range. `7,16,E,E261:at least two spaces before inline comment` errors will not be changed.

I'll improve this.

**Comment by dob9601** [comment]
It does seem that end column is possible with Flake8 as per this issue here on ALE: https://github.com/dense-analysis/ale/issues/538. Albeit that may be something for another issue

**Comment by fannheyward** [comment]
@dob9601 you point me a better way to handle error messages from linter, I'll improve it.

**Comment by dob9601** [comment]
@fannheyward apologies, didn't see lines 166-174 - thats a great way of handling it, thanks :).
I've got a few other ideas and might make a PR if any work well if that sounds good.

Thanks for the patch either way
