### ISSUE TITLE
Allow venv path in coc-settings.json

### ISSUE THREAD

**Issue by kevr** [fannheyward/coc-pyright#546]
**What's the output of `:CocCommand pyright.version`**
`coc-pyright 1.1.154 with Pyright 1.1.154`

**What's the output of `:CocCommand workspace.showOutput Pyright`**
`Not applicable`

When using a **virtualenv** to manage dependencies with a project, users may wish to specify one for their `pyright` session. With `pyright` alone, this is quite simple, as a user can configure the following in `pyrightconfig.py`: 

```
{
    "pythonVersion": "3.9",
    "pythonPath": "/home/kevr/.pyenv/versions/3.9.5/envs/venv/bin/python3",
    "venvPath": "/home/kevr/.pyenv/versions/3.9.5/envs",
    "venv": "venv"
}
```

With this configuration, a user can then use `coc-pyright` properly for their project with its virtualenv.

However, this comes with a bit of a problem when paired with `coc-pyright`; Without the `venv` specification and utilizing the virtualenv in `coc-settings.json`, `coc.nvim` has no way to put itself into the environment specified in `pyrightconfig.json`. This means that, if users want to use things like `flake8`, `autopep8` or `isort` in `coc-pyright` configuration, paths to the executables which correlate with the supplied `venv` are required, otherwise `coc-pyright` cannot find the executables in question.

Proposal: Allow `python.venv` to be specified in `coc-settings.json` and use the specification to put the `coc.nvim` user into the virtualenv while running `pyright` (if it exists). At least then, the entire environment would be matched and we'd be working inside of a specified virtualenv. This would make configuration a lot easier and more understandable.

We should be able to just specify to `coc-settings.json` with non-specific paths for python tooling:

```
{
    "python.pythonVersion": "3.9",
    "python.pythonPath": "/home/kevr/.pyenv/versions/3.9.5/envs/venv/bin/python3",
    "python.venvPath": "/home/kevr/.pyenv/versions/3.9.5/envs",
    "python.venv": "venv",
    "python.linting.flake8Path": "flake8",
    "python.formatting.autopep8Path": "autopep8"
}
```

In essence, the actual defaults for `pyright` would be able to properly execute without specifying a custom virtualenv path to its binary.

**Comment by fannheyward** [comment]
We can't, because Pyright language server doesn't use `venv` setting from LSP configuration, here is `coc-settings.json`, https://github.com/microsoft/pyright/blob/c887ef115073598e98e35a7236c943fa68645b41/packages/pyright-internal/src/server.ts#L70.
