### ISSUE TITLE
Disable warnings regarding code formatting and best practices

### ISSUE THREAD

**Issue by vspecky** [fannheyward/coc-pyright#548]
**What's the output of `:CocCommand pyright.version`**
`[coc.nvim] coc-pyright 1.1.152 with Pyright 1.1.153`

coc-pyright always gives me warnings regarding formatting. Stuff like `Expected 2 blank lines, found 1` or `Do not assign a lambda expression, use def`. While these would be very welcome in personal projects, I'm trying to work on a large codebase at work right now and these are a major hindrance to my flow. How can I go about disabling these? I've tried out some stuff as evidenced by my coc config below but none of it works. Thanks in advance for any help. :)
Following is my coc config.  
```
{
      "explorer.width": 38,
      "explorer.icon.enableNerdfont": true,
      "explorer.previewAction.onHover": false,
      "explorer.keyMappings.global": {
        "<cr>": ["expandable?", "expand", "open"],
        "v": "open:vsplit"
      },

      "diagnostic.refreshOnInsertMode": true,
      "diagnostic.warningSign": "",
      "diagnostic.errorSign": "E",
      "diagnostic.hintSign": "H",
      "diagnostic.checkCurrentLine": true,
      "javascript.suggestionActions.enabled": false,
      "python.linting.enabled": false,
      "python.analysis.typeCheckingMode": "off",
      "python.formatting.provider": "none"
}
```

**Comment by fannheyward** [comment]
Looks like you've other plugins, like ALE, that give formatting warnings.

**Comment by vspecky** [comment]
Oh, that is indeed true, and disabling said plugin did the trick. Thanks a lot!
