### ISSUE TITLE
Show python interpreter/environment in statusline

### ISSUE THREAD

**Issue by patricknraanes** [fannheyward/coc-pyright#549]
**What's the output of `:CocCommand pyright.version`**
[coc.nvim] coc-pyright 1.1.148 with Pyright 1.1.149

**What's the output of `:CocCommand workspace.showOutput Pyright`**
```
Workspace: /Users/myuser/myproj
Using python from /Users/myuser/anaconda3/envs/MYENV/bin/python

[Info  - 09:50:26] Pyright language server 1.1.149 starting
[Info  - 09:50:26] Server root directory: /Users/myuser/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/
[Info  - 09:50:26] No configuration file found.
[Info  - 09:50:26] pyproject.toml file found at /Users/myuser/myproj.
[Info  - 09:50:26] Loading pyproject.toml file at /Users/myuser/pyproject.toml
[Error  - 09:50:26] Pyproject file "/Users/myuser/pyproject.toml" is missing "[tool.pyright] section.
[Info  - 09:50:26] Setting pythonPath for service "MYENV": "/Users/myuser/anaconda3/envs/MYENV/bin/python"
[Warn  - 09:50:26] stubPath /Users/myuser/typings is not a valid directory.
[Info  - 09:50:26] Assuming Python version 3.7
[Info  - 09:50:26] Assuming Python platform Darwin
[Info  - 09:50:26] Searching for source files
[Info  - 09:50:26] Found 16 source files
[Info  - 09:50:35] [FG] Long operation: checking: /Users/myuser/script.py (8828ms)
[Info  - 09:50:35] [FG] Long operation: analyzing: /Users/myuser/script.py (9279ms)
[Info  - 09:52:25] [FG] Long operation: checking: /Users/myuser/script.py (3135ms)
[Info  - 09:52:25] [FG] Long operation: analyzing: /Users/myuser/script.py (3216ms)
```

**Feature request:** Would it be possible to display the path of the python environment in the statusline somehow? Maybe including adaptations for vim-airline, similar to what `coc-python` was doing? I find that sometimes the wrong venv is activated, and this way I wouldn't need to run  `:CocCommand workspace.showOutput Pyright` to figure it out.

**Comment by fannheyward** [comment]
There's is no plan to add Python interpreter/environment information to status line, use `:CocCommand workspace.showOutput Pyright` instead.

Because coc-pyright is different from coc-python or vscode-python that has a heavy dependence on Python env to run tools like pylint/black, all these Python tools are optional. I know the core of coc-pyright, Pyright, also needs Python path to work, coc-pyright already supports automaticly resolve/detect Python from project, it works in most cases.
