### ISSUE TITLE
Import part of Tensorflow Package cannot be resolved. Numpy methods are not known members of module

### ISSUE THREAD

**Issue by Wanghongkua** [fannheyward/coc-pyright#561]
**What's the output of `:CocCommand pyright.version`**

[coc.nvim] coc-pyright 1.1.155 with Pyright 1.1.156

**What's the output of `:CocCommand workspace.showOutput Pyright`**

Workspace: /Users/hongkuanwang/Documents/Practice
Using python from /Users/hongkuanwang/anaconda3/envs/tf14/bin/python

[Info  - 2:36:12 pm] Pyright language server 1.1.156 starting
[Info  - 2:36:12 pm] Server root directory: /Users/hongkuanwang/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/
[Info  - 2:36:12 pm] No configuration file found.
[Info  - 2:36:12 pm] No pyproject.toml file found.
[Info  - 2:36:12 pm] Setting pythonPath for service "Practice": "/Users/hongkuanwang/anaconda3/envs/tf14/bin/python"
[Info  - 2:36:12 pm] Assuming Python version 3.7
[Info  - 2:36:12 pm] Assuming Python platform Darwin
[Info  - 2:36:12 pm] Searching for source files
[Info  - 2:36:13 pm] Found 2021 source files
[Info  - 2:36:17 pm] [FG] Long operation: checking: /Users/hongkuanwang/Documents/Practice/Tensorflow/V1/linear_regression.py (3484ms)
[Info  - 2:36:17 pm] [FG] Long operation: analyzing: /Users/hongkuanwang/Documents/Practice/Tensorflow/V1/linear_regression.py (3792ms)

**Problem description**
## Problem 1

`import tensorflow.compat.v1 as tf` cannot be resolved, and no auto-completion info for `tf`. However, `import tensorflow` first and assign `tensorflow.compat.v1` to `tf` would work, and auto-completion info works. Please check pictures bellow for reference.
![Screen Shot 2021-07-12 at 2 39 53 pm](https://user-images.githubusercontent.com/18624821/125232190-73ba1b80-e31f-11eb-8bd7-a1e9dd3ab92f.png)
![Screen Shot 2021-07-12 at 2 54 10 pm](https://user-images.githubusercontent.com/18624821/125232976-0c04d000-e321-11eb-9668-14daad7de358.png)

## Problem 2
`randn` method of `numpy` package can be auto-completed, but an error, `"randn" is not a known member of module`, is reported.
![Screen Shot 2021-07-12 at 2 59 16 pm](https://user-images.githubusercontent.com/18624821/125233846-c3e6ad00-e322-11eb-8b36-3fb36d6b2a0f.png)

## Background:
I've generated type files for both `tensorflow` and `numpy` with the following command, and configured in the coc-settings.json.
`pyright --createstub tensorflow`
`pyright --createstub numpy`
The version of `tensorflow` is 1.14, and `numpy` is 1.16.4.

**Comment by fannheyward** [comment]
Pyright's issue, coc-pyright can do nothing about this.

**Comment by Wanghongkua** [comment]
Thank you for your reply. I'm reporting this problem to Pyright.
