### ISSUE TITLE
How to complete the self egg module of python

### ISSUE THREAD

**Issue by HaomingJu** [fannheyward/coc-pyright#562]
**What's the output of `:CocCommand pyright.version`**

**What's the output of `:CocCommand workspace.showOutput Pyright`**

**Comment by HaomingJu** [comment]
My coc-pyright can't complete the carla egg

**Comment by fannheyward** [comment]
I don't use carla, from my research, carla is a c++ lib with Python API binding. But it doesn't provide any stub type files, so Pyright can't do complete suggestions. coc-pyright can't do anything about this, carla should provide stub type files for Pyright to use.
