### ISSUE TITLE
"<attr>" not acessed warnings

### ISSUE THREAD

**Issue by bellini666** [fannheyward/coc-pyright#566]
Hello,

I keep getting "<attr> not acessed" warnings even if I disable the report in pyright (it I enable it I actually get an error)

![Screenshot from 2021-07-13 12-15-31](https://user-images.githubusercontent.com/134025/125478122-8c7f56b8-1ec0-4a51-925c-b4228fabfde4.png)

There are reasons for why I might not use some variables:

1) Sometimes I'm overloading a method so I need to declare the same function parameters but I might not actually use them
2) When I do something like that split, I need to retrieve those variables that way but I might not use them all
3) Even `**kwargs` gives me those warnings
4) Using `_` solves the issue but it is not a solution for 2 reasons: 4.1) I might need to use the exact name when overloading a keyword argument; 4.2) My modules use have `_` in their namespaces because I use it for gettext
5) Prefixing the names with `_*` doesn't change anything (and is a solution for 4.2 but not for 4.1)

I saw this comment (https://github.com/microsoft/pyright/issues/982#issuecomment-764186708) but don't know if that's something that I should configure myself for coc-pyright.

**Comment by fannheyward** [comment]
<img width="307" alt="截屏2021-07-14 15 21 22" src="https://user-images.githubusercontent.com/345274/125580238-ad8a3aa6-0eec-4ae5-8319-797cfc71e337.png">

Upgrade your coc.nvim to latest release, unused vars will be grayed out.

**Comment by bellini666** [comment]
Hi @fannheyward ,

I'm actually on the latest version... Maybe I'm seeing it like that because I'm using ale to display those errors?

Is there a way to disable that warning?

**Comment by fannheyward** [comment]
Yes, this error is not came from coc-pyright. I don't use ale and have no ideas about it.

**Comment by bellini666** [comment]
@fannheyward I was actually asking how to disable this error in `coc-pyright` itself since it doesn't seem to respect any `report*` config.

But nvm, I just changed some highlights on ale to make them less "annoying".

**Comment by fannheyward** [comment]
The warnings can't be disabled.
