### ISSUE TITLE
[coc.nvim] The "python" server crashed 4 times in the last 3 minutes. The server will not be restarted

### ISSUE THREAD

**Issue by farzadmf** [fannheyward/coc-pyright#569]
Hi, I'm not sure what happened recently, but I don't think I changed anything in my config other than updating everything, and now whenever I open a Python file, I hear the Pyright language server spinning up the CPU usage and after a while, it seems to be crashing and I see the message "... server crashed 4 times ...".

I'd really appreciate if you help me solve this issue because it basically killed my usual workflow of using neovim with Python files :slightly_frowning_face: 

**What's the output of `:CocCommand pyright.version`**
`[coc.nvim] coc-pyright 1.1.156 with Pyright 1.1.156`

**What's the output of `:CocCommand workspace.showOutput Pyright`**
```
Workspace: /data/github/wrk
Using python from /data/github/wrk/.direnv/python-3.9.6/bin/python

[Info  - 12:13:24 p.m.] Pyright language server 1.1.156 starting
[Info  - 12:13:25 p.m.] Server root directory: /home/farzad/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/
```

**Comment by fannheyward** [comment]
Any error message in the output of `:CocOpenLog`? What't the output of `:CocList extensions` and `:CocList services`?

**Comment by farzadmf** [comment]
Thank you for your reply @fannheyward . The path I'm working on is the company code, so if you don't mind, I'll paste the logs as the last resort.

But doing `:CocOpenLog` revealed an error that was indeed specific to my environment, and I fixed that.

Unfortunately, that didn't fix the main issue. Now, when I open a Python file in my project, I see this:
![image](https://user-images.githubusercontent.com/5768792/126251864-a758fda1-11e5-4b39-b97a-3df1ab966bdd.png)

And the spinning thing there just rotates and rotates (the number of "items left" doesn't change either), and finally it shows the message "... crashed 4 times ..."

**Comment by fannheyward** [comment]
Looks like you're using `coc-python`, not `coc-pyright`.

**Comment by farzadmf** [comment]
Oh no, thank you for @fannheyward  noticing. That was unintentional :slightly_frowning_face: and I just noticed I have both.

I know `coc-python` is not maintained anymore, so I think I've forgotten to remove it

Can you please tell me how you found out that I have `coc-python`?

**Comment by fannheyward** [comment]
> how you found out

1. `The "python" server crashed ...`, if Pyright failed, the message should be `Pyright server`. This why I ask you the output of `:CocList extensions`
2. The Python interpreter informations in your status line. coc-pyright doesn't show this
3. And the `python.setInterpreter` command

It's ok for this issue, glad to help you.

**Comment by farzadmf** [comment]
Hey @fannheyward , just wanted to thank you again for finding out the root issue

All this time, I was getting duplicate diagnostics etc and the reason I think was that I had both `coc-python` and `coc-pyright` installed. Today, I opened a Python file and it's much better.

I'm happy that I opened this issue :laughing:
