### ISSUE TITLE
Import my own module could not be resolved

### ISSUE THREAD

**Issue by Hungpro3112** [fannheyward/coc-pyright#594]
Output of `:CocCommand pyright.version`:

`[coc.nvim] coc-pyright 1.1.161 with Pyright 1.1.161`

Output of `:CocCommand workspace.showOutput Pyright`:

Workspace: C:\Users\MyPC
Using python from C:\Users\MyPC\AppData\Local\Programs\Python\Python39\python.EXE

```
[Warn  - 8:19:35 AM] Ignored rootPath C:\Users\MyPC of client "pyright"
[Info  - 8:19:35 AM] Pyright language server 1.1.161 starting
[Info  - 8:19:35 AM] Server root directory: C:\Users\MyPC\AppData\Local\coc\extensions\node_modules\coc-pyright\node_modules\pyright/dist/
[Info  - 8:19:35 AM] No pyproject.toml file found.
[Info  - 8:19:35 AM] Setting pythonPath for service "<default>": "C:\Users\MyPC\AppData\Local\Programs\Python\Python39\python.EXE"
[Warn  - 8:19:35 AM] stubPath typings is not a valid directory.
[Info  - 8:19:35 AM] Assuming Python version 3.9
[Info  - 8:19:35 AM] Assuming Python platform Windows
[Info  - 8:19:35 AM] Searching for source files
[Info  - 8:19:35 AM] No source files found.

```

Here is my python folder:
![image](https://user-images.githubusercontent.com/75968004/129822575-bdc36d7d-cbc9-4d0e-baf8-76343d917b6b.png)

However, when I import my module in the same directory:
![image](https://user-images.githubusercontent.com/75968004/129822694-d2c958a9-1c17-45ee-8b1a-076b6a059c73.png)

**Comment by fannheyward** [comment]
Looks like coc detects the wrong workspace root, it's should be `C:\Users\MyPC\Hello_world`. Do you have `.git` in your project root? Or put `pyproject.toml` file in your project root and try again.

**Comment by Hungpro3112** [comment]
> Looks like coc detects the wrong workspace root, it's should be `C:\Users\MyPC\Hello_world`. Do you have `.git` in your project root? Or put `pyproject.toml` file in your project root and try again.

I don't have `.git` in my project root. What do you mean when have `.git `in there?

If I have 2 Python projects, I must put `.git `in each root, right?

Can you explain in detail and easier 'cause ''m new with this

**Comment by Hungpro3112** [comment]
> Output of `:CocCommand pyright.version`:
> 
> `[coc.nvim] coc-pyright 1.1.161 with Pyright 1.1.161`
> 
> Output of `:CocCommand workspace.showOutput Pyright`:
> 
> Workspace: C:\Users\MyPC
> Using python from C:\Users\MyPC\AppData\Local\Programs\Python\Python39\python.EXE
> 
> ```
> [Warn  - 8:19:35 AM] Ignored rootPath C:\Users\MyPC of client "pyright"
> [Info  - 8:19:35 AM] Pyright language server 1.1.161 starting
> [Info  - 8:19:35 AM] Server root directory: C:\Users\MyPC\AppData\Local\coc\extensions\node_modules\coc-pyright\node_modules\pyright/dist/
> [Info  - 8:19:35 AM] No pyproject.toml file found.
> [Info  - 8:19:35 AM] Setting pythonPath for service "<default>": "C:\Users\MyPC\AppData\Local\Programs\Python\Python39\python.EXE"
> [Warn  - 8:19:35 AM] stubPath typings is not a valid directory.
> [Info  - 8:19:35 AM] Assuming Python version 3.9
> [Info  - 8:19:35 AM] Assuming Python platform Windows
> [Info  - 8:19:35 AM] Searching for source files
> [Info  - 8:19:35 AM] No source files found.
> ```
> 
> Here is my python folder:
> ![image](https://user-images.githubusercontent.com/75968004/129822575-bdc36d7d-cbc9-4d0e-baf8-76343d917b6b.png)
> 
> However, when I import my module in the same directory:
> ![image](https://user-images.githubusercontent.com/75968004/129822694-d2c958a9-1c17-45ee-8b1a-076b6a059c73.png)

It still runs this code and when I use relative import : 

`from .hello import number_repeated`

`pyright ` doesn't show red message but python has
![image](https://user-images.githubusercontent.com/75968004/129844166-a42e8a65-4834-4f1c-939e-2843c19bc146.png)

**Comment by fannheyward** [comment]
> What do you mean when have .git in there?

coc and Pyright need to detect your project root as workspace root to work. coc will auto detect the project if there is a `.git` folder exist in your project root, checkout https://github.com/fannheyward/coc-pyright/issues/521#issuecomment-858530052 and https://github.com/neoclide/coc.nvim/wiki/Using-workspaceFolders#resolve-workspace-folder

> Workspace: C:\Users\MyPC

This log means coc failed to find the project root.

**Comment by Hungpro3112** [comment]
I added this line in my _vimrc but has no effect

`autocmd FileType python let b:coc_root_patterns = ['.git', '.env', 'venv', '.venv', 'setup.cfg', 'setup.py', 'pyproject.toml', 'pyrightconfig.json']
`


![image](https://user-images.githubusercontent.com/75968004/129898510-2b0d305e-daee-4494-ba51-804b959a33fd.png)

`

**Comment by fannheyward** [comment]
@Hungpro3112 what't `Workspace` output from `:CocCommand workspace.showOutput Pyright`?

**Comment by Hungpro3112** [comment]
> @Hungpro3112 what't `Workspace` output from `:CocCommand workspace.showOutput Pyright`?

```
Workspace: C:\Users\MyPC
Using python from C:\Users\MyPC\trydjango\Scripts\python.exe

[Warn  - 2:03:39 PM] Ignored rootPath C:\Users\MyPC of client "pyright"
[Info  - 2:03:39 PM] Pyright language server 1.1.161 starting
[Info  - 2:03:39 PM] Server root directory: C:\Users\MyPC\AppData\Local\coc\extensions\node_modules\coc-pyright\node_modules\pyright/dist/
[Info  - 2:03:39 PM] No pyproject.toml file found.
[Info  - 2:03:39 PM] Setting pythonPath for service "<default>": "C:\Users\MyPC\trydjango\Scripts\python.exe"
[Warn  - 2:03:39 PM] stubPath typings is not a valid directory.
[Info  - 2:03:40 PM] Assuming Python version 3.9
[Info  - 2:03:40 PM] Assuming Python platform Windows
[Info  - 2:03:40 PM] Searching for source files
[Info  - 2:03:40 PM] No source files found.


```

**Comment by fannheyward** [comment]
> Workspace: C:\Users\MyPC

coc still can't find the correct project root. Do you start vim in your project root?

**Comment by Hungpro3112** [comment]
![bandicam 2021-08-19 20-37-47-278](https://user-images.githubusercontent.com/75968004/130078730-ca5b125e-6013-4c52-87fc-0ed0ba142eb2.gif)

**Comment by fannheyward** [comment]
Try to start your vim in your **project root**, not `C:\Users\MyPC`

**Comment by Hungpro3112** [comment]
> Try to start your vim in your **project root**, not `C:\Users\MyPC`

So every time open my vim it must be my project root? Any alternative way?
If I want to open something in `%userprofile%`, what should I do more efficiently?

**Comment by fannheyward** [comment]
Set `"workspace.bottomUpFiletypes": ["python"]` and try again.

**Comment by Hungpro3112** [comment]
> Set `"workspace.bottomUpFiletypes": ["python"]` and try again.

What this line is mean?
If I want to import in other languages I must open these in the root,  right?

**Comment by fannheyward** [comment]
The language server, here is Pyright, needs the workspace root to work, coc will try to detect the root by some patterns like `.git`, `pyproject.toml` and `b:coc_root_patterns`, that's why you need to open vim in your project root.

**Comment by Hungpro3112** [comment]
> The language server, here is Pyright, needs the workspace root to work, coc will try to detect the root by some patterns like `.git`, `pyproject.toml` and `b:coc_root_patterns`, that's why you need to open vim in your project root.

Thank you very much

**Comment by smthomas-sci** [comment]
In a slightly different issue, where I have pip installed my own module with `pip install -e`, the python environment finds it when it runs, but pyright fails on linting. This might have something to do with the fact that in site-packages it includes a redirect to the parent directory (not in the workspace dir, because it doesn't have to be via a pip install). The solution, which enables python the program to run, and pyright to find the module, is to create a symbolic link in the workspace folder with the same name as the module, and point it to the original location... Hopefully saves someone time.
