### ISSUE TITLE
Incorrect (and inconsistent) auto-import between completion and code action

### ISSUE THREAD

**Issue by smackesey** [fannheyward/coc-pyright#605]
When I reference a name defined in some standard library module (e.g. `reduce` in `functools`), then `coc-pyright` can properly auto-import it if I select it from the completion menu. Great!

However, if that is already in the text and there is a `Pyright: reportUndefinedVariable` diagnostic associated with it, then when I try to auto-import it with a code action, it's imported from the wrong place. Specifically, I am presented with these two options:

```
1. Add "import reduce"
2. Add "from _ import reduce"
```

Why don't these code actions have access to the same knowledge as the completion? Is there a way it needs to be configured? Thanks.

---

**What's the output of `:CocCommand pyright.version`**
version: [coc.nvim] coc-pyright 1.1.164 with Pyright 1.1.163

**What's the output of `:CocCommand workspace.showOutput Pyright`**
Workspace: /Users/smackesey
Using python from .venv/bin/python

[Info  - 2:32:08 PM] Pyright language server 1.1.163 starting
[Info  - 2:32:08 PM] Server root directory: /Users/smackesey/.cache/nvimplugin/coc-pyright/node_modules/pyright/dist/
[Info  - 2:32:08 PM] No configuration file found.
[Info  - 2:32:08 PM] No pyproject.toml file found.
[Info  - 2:32:08 PM] Setting pythonPath for service "mosaic": "/Users/smackesey/stm/code/lib/python/mosaic/.venv/bin/python"
[Warn  - 2:32:08 PM] stubPath /Users/smackesey/stm/code/lib/python/mosaic/typings is not a valid directory.
[Info  - 2:32:08 PM] Assuming Python version 3.9
[Info  - 2:32:08 PM] Assuming Python platform Darwin
[Info  - 2:32:09 PM] Searching for source files
[Info  - 2:32:09 PM] Auto-excluding /Users/smackesey/stm/code/lib/python/mosaic/.venv
[Info  - 2:32:09 PM] Found 142 source files

**Comment by fannheyward** [comment]
> auto-import it if I select it from the completion menu

This feature is provided by Pyright that it analyzes your Python project, returns the correct auto-import suggestions, Pyright does this smart and perfect.

> Why don't these code actions have access to the same knowledge as the completion

Pyright doesn't open the code actions of auto-import to non-VSCode client. These two code actions are from coc-pyright. If there's a `reportUndefinedVariable` diagnostic, coc-pyright provides two actions to do ___basic___ import with rope, they're not _smart_ as Pyright and may came from the wrong place.
