### ISSUE TITLE
Cannot format python source code: [coc.nvim] Formatting with autopep8/black failed: autopep8/black module is not installed.

### ISSUE THREAD

**Issue by robinchm** [fannheyward/coc-pyright#611]
**What's the output of `:CocCommand pyright.version`**
```
[coc.nvim] coc-pyright 1.1.164 with Pyright 1.1.165
```

**What's the output of `:CocCommand workspace.showOutput Pyright`**
```
Workspace: /home/****/Workspace/python
Using python from /home/****/Workspace/python/venv/bin/python

[Info  - 12:33:00 PM] Pyright language server 1.1.165 starting
[Info  - 12:33:00 PM] Server root directory: /home/****/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/
[Info  - 12:33:00 PM] No configuration file found.
[Info  - 12:33:00 PM] No pyproject.toml file found.
[Info  - 12:33:00 PM] Setting pythonPath for service "python": "/home/****/Workspace/python/venv/bin/python"
[Warn  - 12:33:00 PM] stubPath /home/****/Workspace/python/typings is not a valid directory.
[Info  - 12:33:00 PM] Assuming Python version 3.8
[Info  - 12:33:00 PM] Assuming Python platform Linux
[Warn  - 12:33:01 PM] Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Warn  - 12:33:01 PM] Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Info  - 12:33:01 PM] Searching for source files
[Info  - 12:33:01 PM] Auto-excluding /home/****/Workspace/python/venv
[Info  - 12:33:01 PM] Found 1 source file
```

My CocConfig:
```
{
    "coc.preferences.formatOnSaveFiletypes": [
        "go",
        "python",
        "json"
    ],
    "python.formatting.provider": "autopep8",
}

```

I am testing out coc.nvim with coc-pyright for python3 development in vim. In a virtual machine I installed fresh ubuntu20.04 with vim-gtk3. Then follow the instruction on coc.nvim to set up. Autocomplete, go-to-definition and so on all works great until I try to format the source file, then it complains:
```
[coc.nvim] Formatting with autopep8 failed: autopep8 module is not installed.
```
However I do have autopep8 installed and available on PATH. Running autopep8 in terminal gives me correct result.
I try to install autopep8 both via apt or in local virtualenv through pip, both give the same error.

Replacing autopep8 in the config (after installing black of course), simply changes the error to:
```
[coc.nvim] Formatting with black failed: black module is not installed.
```
However I do have black installed and available on PATH. Running black in terminal gives me correct result.

On the other hand, everything for golang works correctly (including formatting).

Can somebody help point out where the setup goes wrong? Many thanks.

**Comment by yaegassy** [comment]
@robinchm Add `python.formatting.autopep8Path` or `python.formatting.blackPath` settings, try to set the path of the tool that your environment

**e.g.**:

```jsonc
{
  // ...snip
  // autopep8
  "python.formatting.autopep8Path": "~/.local/bin/autopep8",
  // black
  "python.formatting.blackPath": "~/.local/bin/black",
  // ...snip
}
```

**Comment by robinchm** [comment]
@yaegassy That works!
Is there any reason why the location of the formatter binary is not resolved as how it is normally done via PATH? That way if we have installed a particular version of formatter in the current virtualenv it can automatically shadow the system one.
Anyway this is good enough for me, many thanks again.
