### ISSUE TITLE
Question: Understanding how to account for additional libraries / imports

### ISSUE THREAD

**Issue by DanielBarton446** [fannheyward/coc-pyright#612]
**What's the output of `:CocCommand pyright.version`**
[coc.nvim] coc-pyright 1.1.164 with Pyright 1.1.163

**What's the output of `:CocCommand workspace.showOutput Pyright`**
Workspace: /home/daniel/dev/school
Using python from /usr/bin/python

[Info  - 2:21:46 PM] Pyright language server 1.1.163 starting
[Info  - 2:21:46 PM] Server root directory: /home/daniel/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/
[Info  - 2:21:46 PM] No configuration file found.
[Info  - 2:21:46 PM] No pyproject.toml file found.
[Info  - 2:21:46 PM] Setting pythonPath for service "school": "/usr/bin/python"
[Warn  - 2:21:46 PM] stubPath /home/daniel/dev/school/typings is not a valid directory.
[Info  - 2:21:46 PM] Python version 2.7 from interpreter is unsupported
[Info  - 2:21:46 PM] Assuming Python platform Linux
[Info  - 2:21:46 PM] Searching for source files
[Info  - 2:21:46 PM] Found 3 source files

The issue I am running into is an issue of my lack of understanding.
Particularly, across multiple languages (Python, Java) I have utilized additional libraries or imports from the same directory (particularly libraries like numpy, matplotlib, etc). However, for each of these libraries that I have installed, or imports of files within the same folder as the current file I am editing, I run into an issue where a message along the lines of " Import "numpy" could not be resolved"

My understanding of this is that I don't know what I am doing, and I have not set something up properly. Note: I have done nothing with any configuration of the pyright config.

I figure that I need to do something with the config for pyright in order for these kinds of "errors" to be resolved and checked for.

Where do I go to for this kind of information?

Apologies for the nooby questions, I just don't know where to go.

Thank you a lot,
   Daniel

**Comment by fannheyward** [comment]
> Workspace: /home/daniel/dev/school
> Using python from /usr/bin/python

The logs shows you're using the Python from system, maybe you need to activate your Python virtual environment before launch vim.
