### ISSUE TITLE
Failing to sort imports with `isort`

### ISSUE THREAD

**Issue by hexcowboy** [fannheyward/coc-pyright#613]
<details>
  <summary><code>[coc.nvim] coc-pyright 1.1.164 with Pyright 1.1.165`</code></summary>

```
Workspace: /project
Using python from /project/venv/bin/python

[Info  - 2:26:57 PM] Pyright language server 1.1.165 starting
[Info  - 2:26:57 PM] Server root directory: /Users/user/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/
[Info  - 2:26:57 PM] No configuration file found.
[Info  - 2:26:57 PM] No pyproject.toml file found.
[Info  - 2:26:57 PM] Setting pythonPath for service "main": "/project/venv/bin/python"
[Warn  - 2:26:57 PM] stubPath /project/typings is not a valid directory.
[Info  - 2:26:57 PM] Assuming Python version 3.9
[Info  - 2:26:57 PM] Assuming Python platform Darwin
[Info  - 2:26:57 PM] Searching for source files
[Info  - 2:26:57 PM] Auto-excluding /project/venv
[Info  - 2:26:57 PM] Found 3 source files
########## isort Output ##########
Error from isort:
Traceback (most recent call last):
  File "/Users/user/.config/coc/extensions/node_modules/coc-pyright/pythonFiles/sortImports.py", line 11, in <module>
    import isort.main
ModuleNotFoundError: No module named 'isort'

########## isort Output ##########
Error from isort:
Traceback (most recent call last):
  File "/Users/user/.config/coc/extensions/node_modules/coc-pyright/pythonFiles/sortImports.py", line 11, in <module>
    import isort.main
ModuleNotFoundError: No module named 'isort'

########## isort Output ##########
Error from isort:
Traceback (most recent call last):
  File "/Users/user/.config/coc/extensions/node_modules/coc-pyright/pythonFiles/sortImports.py", line 11, in <module>
    import isort.main
ModuleNotFoundError: No module named 'isort'
```

</details>

Getting an error: `[coc.nvim] Failed to format import by isort` when running `:CocCommand python.sortImports`

The error is not expected because `isort` exists and works within the project's virtual environment:

```bash
$ which isort
/project/venv/bin/isort

$ isort .
Fixing /project/main.py
```

**Comment by hexcowboy** [comment]
Additionally, my `coc-settings.json` is as follows:

```json
{
  "python": {
    "analysis": {
      "typeCheckingMode": "off"
    },
    "formatting": {
      "provider": "black"
    }
  }
}
```

**Comment by yaegassy** [comment]
@hexcowboy To make `isort` work, you need to install `isort` in your "virtual environment" or set the path of the tool in `python.sortImports.path`. 

**e.g. coc-settings.json**:

```jsonc
{
  // ...snip
  "pyright.organizeimports.provider": "isort",
  "python.sortImports.path": "~/.local/bin/isort",
  // ...snip
}
```

**Comment by hexcowboy** [comment]
Thanks for responding, but the point is that `isort` *is* installed in the virtual environment. I think it may have something to do with this part of the logs:

```
[Info  - 2:26:57 PM] Auto-excluding /project/venv
```

But I don't know why it's excluding the venv.

**Comment by yaegassy** [comment]
@hexcowboy 

> [Info  - 2:26:57 PM] Auto-excluding /project/venv

Perhaps the "Auto-excluding ..." message has nothing to do with this problem.

I am not able to reproduce your problem in my environment. Does the isort load correctly when run with the module specified? 

**e.g. version**: `python3 -m isort --version`

**Comment by fannheyward** [comment]
@hexcowboy does `python -m isort --version` work in your virtual environment?

**Comment by hexcowboy** [comment]
@fannheyward @yaegassy yes, isort is working as expected in my virtual environment.

```bash
(venv) $ python -m isort --version
VERSION 5.9.3

(venv) $ isort .
Skipped 1 files
```

However, when I open NeoVim (with the venv active) I start getting errors relating to my virtual environment:

```
[Pyright reportMissingImports] [W] Import "rich" could not be resolved 
[coc.nvim] Failed to format import by isort
```

I will try to reproduce in a VM.

**Comment by yaegassy** [comment]
> [Info  - 2:26:57 PM] Setting pythonPath for service "main": "/project/venv/bin/python"

I'm curious about this log. `main`?

**Comment by fannheyward** [comment]
Here's my tests:

1. pwd `/Users/fannheyward/src/hello-pyright`, has `.venv` virtual environment
2. `which python`: `/Users/fannheyward/src/hello-pyright/.venv/bin/python`
3. `python -m isort --version`: 5.9.3
4. `:CocCommand python.sortImports` works as expected
5. set `"pyright.organizeimports.provider": "isort"` in coc-settings.json, fire `<Plug>(coc-codeaction-cursor)` and apply `Sort Imports by isort` action, works as expected too.

<img width="470" alt="截屏2021-09-06 下午12 26 49" src="https://user-images.githubusercontent.com/345274/132160584-45a481ba-704b-4559-9b63-5030c1055f9c.png">

**Comment by hexcowboy** [comment]
I reproduced this issue but not sure what exactly the problem was.

The issue appears to be my version of `isort==5.8.0` which needed to be upgraded to `isort==5.9.3`. This fixed my issues an `isort` is working now.

For anyone else running into this issue:

```bash
pip install 'isort>=5.9.3'
```

Thanks @yaegassy @fannheyward for looking into it.

**Comment by hexcowboy** [comment]
Reopening because this issue is still persisting and I was able to reproduce it in a VM.

Reproduce:
1. Fresh install `neovim` and [`vim-plug`](https://github.com/junegunn/vim-plug)
2. Create the `~/.config/init.vim` with the following contents
```vim
call plug#begin(stdpath('data') . '/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()
```
3. Run `:PlugInstall`
4. Install `coc-pyright` with `:CocInstall coc-pyright`
5. Write the following config to `~/.config/nvim/coc-settings.json`
```json
{
  "pyright.organizeimports.provider": "isort",
  "python.sortImports.args": "--profile black"
}
```
6. Create a virtual environment and activate it
```bash
$ python3 -m venv venv
$ source venv/bin/activate
(venv) $ pip install isort
(venv) $ python --version && isort --version
Python 3.9.7
isort 5.9.3
```
7.  Open NeoVim with a Python file (sample fiile)
```python
from typing import Literal
import os
```
8. Run `:CocCommand python.sortImports`
<img width="671" alt="Screen Shot 2021-09-07 at 2 52 32 PM" src="https://user-images.githubusercontent.com/8162609/132402841-16cf431f-f265-425d-96cd-791caf75d145.png">

**Comment by yaegassy** [comment]
@hexcowboy Please set the value of `python.sortImports.args` as `array`, **not** as "string".

```jsonc
{
  // ...snip
  "python.sortImports.args": ["--profile", "black"]
  // ...snip
}
```

**Comment by Andrew15-5** [comment]
I have a similar problem, but instead I want to use:

```json
"python.sortImports.args": ["--settings-path", "~/.isort.cfg"]
```

And it doesn't work. I have to specify an absolute path which isn't flexible, giving that it would contain the user's name. `$HOME` also didn't work. Is there a better solution for this?

**Comment by fannheyward** [comment]
@Andrew15-5 sorry for the late response, what's the output of `:CocCommand workspace.showOutput Pyright`?

**Comment by Andrew15-5** [comment]
I can't test it now. Maybe in a couple of days.
