### ISSUE TITLE
[feature request] coc-pyright does not take into account black errors

### ISSUE THREAD

**Issue by laurentS** [fannheyward/coc-pyright#614]
I struggled a bit with the problem described in #229 until I ran `black --diff --quiet <thefile>` outside of vim (but with the correct venv), and got an actual error message from black complaining about a typo in my pyproject.toml.
The error wasn't in `coc-pyright`, but it was still displaying "file formatted with black", which was misleading enough that I committed and pushed non-formatted code :see_no_evil: 

I would be nice if `coc-pyright` could check the exit code of `black` and show some sort of error message (either the one from black, or just a pointer to where to look for details) if something went wrong.

I'll take the opportunity to say thanks for a really nice piece of software :raised_hands: 

**What's the output of `:CocCommand pyright.version`**
`coc-pyright 1.1.166 with Pyright 1.1.167`

**What's the output of `:CocCommand workspace.showOutput Pyright`**
not relevant here

**Comment by fannheyward** [comment]
Is there any error logs in `:CocCommand workspace.showOutput coc-pyright-formatting`?

**Comment by laurentS** [comment]
Not really, if I understand the results correctly, this is the relevant part:
```
########## active formattor: black
execPath:   black
moduleName: black
args:       --diff,--quiet,/home/<edited>/src/cli/main.py.eeb4242ffea89591ab759a47e2a96bac.py

########## black output:
<just blank lines here>
```
if I run `black` directly on the command line (with the same args as above, but on the file itself, not a temp copy):
```
Error: Could not open file /home/<edited>/pyproject.toml: Error reading configuration file: Can not overwrite a value (at line 13, column 20)
```
(to reproduce, you can duplicate one of the dependencies in `pyproject.toml`, which makes it invalid).

**Comment by fannheyward** [comment]
The error message will be redirected to `:CocCommand workspace.showOutput coc-pyright-formatting`. Try v1.1.168 and feedbacks are welcome.

**Comment by laurentS** [comment]
Thanks for the super quick fix!
Yes, the error message does turn up in showOutput. But somehow, I don't really see much more than a flash of error in the message area in neovim. If I run `:messages` after saving my python file, I see this:
```
[coc.nvim] Formatting with black failed
[coc.nvim] Formatted with black
"src/cli/main.py" 183L, 5419C written
```
but the first 2 lines flash by so quickly that I can't see them. Is there a way to keep the error message visible? I feel like it shouldn't say "Formatted with black", since it didn't actually do it.

**Comment by fannheyward** [comment]
> I feel like it shouldn't say "Formatted with black", since it didn't actually do it.

This has been fixed already and will in next release.
