### ISSUE TITLE
coc-pyright failed to start

### ISSUE THREAD

**Issue by fannheyward** [fannheyward/coc-pyright#623]
https://github.com/neoclide/coc.nvim/issues/3379

**Comment by fannheyward** [comment]
@r2ri2 does `node.exe C:\Users\r2ri2\AppData\Local\coc\extensions\node_modules\coc-pyright\node_modules\pyright\langserver.index.js` work?

**Comment by yaegassy** [comment]
It seems to be fine on my Windows for checking operation (although I tried it with Vim8 instead of Neovim).

<img width="929" alt="vim8-coc-pyright-ok" src="https://user-images.githubusercontent.com/188642/133376346-9cac750b-30e5-42de-9625-7902c4dc98eb.png">

**Comment by r2ri2** [comment]
@fannheyward 

### The command doesn't work in terminal
![image](https://user-images.githubusercontent.com/84429399/133376479-96c6bf95-b904-4b2d-acb2-0cfec4ee7c84.png)

**Comment by fannheyward** [comment]
@r2ri2 try `node.exe C:\Users\r2ri2\AppData\Local\coc\extensions\node_modules\coc-pyright\node_modules\pyright\langserver.index.js --stdio`

**Comment by r2ri2** [comment]
@fannheyward 

![image](https://user-images.githubusercontent.com/84429399/133379721-ca33a04b-f055-4396-9bdb-13fd62012dff.png)

**Comment by fannheyward** [comment]
How about `node.exe C:\Users\r2ri2\AppData\Local\coc\extensions\node_modules\coc-pyright\node_modules\pyright\dist\pyright-langserver.js --stdio`?

Looks like it's Pyright's path issue https://github.com/microsoft/pyright/blob/main/packages/pyright/langserver.index.js

**Comment by fannheyward** [comment]
@yaegassy can you test on Windows for this:

1. `node.exe xxxx\AppData\Local\coc\extensions\node_modules\coc-pyright\node_modules\pyright\langserver.index.js --stdio`
2. `node.exe xxxx\AppData\Local\coc\extensions\node_modules\coc-pyright\node_modules\pyright\dist\pyright-langserver.js --stdio`

**Comment by r2ri2** [comment]
@fannheyward 

I been looking for path issues, but idk where should i look for

![image](https://user-images.githubusercontent.com/84429399/133382013-ed84a7e6-cfd1-4bc1-a87e-4b7ae97abcb7.png)
![image](https://user-images.githubusercontent.com/84429399/133383300-ea391118-b646-4489-85c7-bd762c91aeec.png)

**Comment by yaegassy** [comment]
@fannheyward Both seem to be fine in my environment.

<img width="928" alt="coc-pyright-issue632-2" src="https://user-images.githubusercontent.com/188642/133383459-52e9ddd0-abc4-4010-9dfe-557bf2f6d0ee.png">

**Comment by fannheyward** [comment]
@r2ri2 have no idea about this, do you use WSL?

**Comment by r2ri2** [comment]
@fannheyward nop i dont, i have Cygwin but i dont use it.

**Comment by yaegassy** [comment]
@r2ri2 What happens if I create an appropriate directory, install pyright on it, and run `langserver.index.js`?

Try to rewrite the path separator for Windows and run it.

```
mkdir example
cd example
npm init -y
npm i pyright
node node_modules/pyright/langserver.index.js --stdio
```

**Comment by r2ri2** [comment]
@yaegassy  ok i did and this is what i got

![image](https://user-images.githubusercontent.com/84429399/133473424-7bdcb707-5e52-4a90-8d25-dff2a7347e6e.png)
![image](https://user-images.githubusercontent.com/84429399/133473543-f88345c2-ad0c-4cf5-9045-f7fb62f9c095.png)
![image](https://user-images.githubusercontent.com/84429399/133474146-4ba2c540-7592-4cf7-b1d1-4fcd020a3ced.png)

**Comment by yaegassy** [comment]
@r2ri2 

> @fannheyward nop i dont, i have Cygwin but i dont use it.

I was curious about the word "Cygwin".

I use Mac and Linux all the time, and I'm not familiar with Windows, but cygwin might be affecting the permission error. Ref: https://github.com/npm/npm/issues/845

Isn't your `C:\Users\r2ri2\AppData\Local\coc\extensions` directory somehow created from the cygwin environment?

**Comment by r2ri2** [comment]
Not that directory, but I do not remember about another nvim or system one.
I removed Cygwin yesterday but there is still related files, I found a couple of python files that mention the word cygwin.

![image](https://user-images.githubusercontent.com/84429399/133482393-8004b920-cb78-4409-bf62-457f9a0178f4.png)

I will try to purge completely Cygwin and reinstall python in my system.

**Comment by r2ri2** [comment]
@yaegassy @fannheyward 

Ok finally, I solve this problem, it was about 'special permissions' in 'dist' folder, but the folder permissions can not be set directly, so I had to delete all the groups permissions and set them again.
Thank you guys for help

![image](https://user-images.githubusercontent.com/84429399/133718118-e6297322-522d-4c1a-956f-d9db00ca2770.png)

![image](https://user-images.githubusercontent.com/84429399/133717954-701571ac-58b6-47b2-acdc-4a044ff0b949.png)

before
![image](https://user-images.githubusercontent.com/84429399/133718036-24e4d8d9-a72f-4710-903c-e359ac421c01.png)

after
![image](https://user-images.githubusercontent.com/84429399/133717972-396e101f-cc7c-4b54-9a6d-30bd1c7fa4e4.png)

**Comment by yaegassy** [comment]
@r2ri2 I'm glad you got the problem solved.

If you see a similar issue reported on `coc-pyright` in the future, please comment to the user in trouble!

**Comment by r2ri2** [comment]
@yaegassy yes for sure
