### ISSUE TITLE
Use system's pyright version instead of the plugin's one

### ISSUE THREAD

**Issue by bellini666** [fannheyward/coc-pyright#625]
Would it be possible to use the system's pyright version somehow?

One problem that is happening from time to time is that pyright releases a new version and coc-pyright will take some time to update to it, which causes the output of pyright be different from what my editor is seeing.

**Comment by fannheyward** [comment]
Note: coc-pyright will still install the Pyright even pyright.server is configured.

**Comment by bellini666** [comment]
@fannheyward awesome, thanks for implementing this :)

Is there any "issues" that might arrive from using that approach?
