### ISSUE TITLE
Scipy will make coc-pyright crash.

### ISSUE THREAD

**Issue by pittcat** [fannheyward/coc-pyright#626]
**What's the output of `:CocCommand pyright.version`**
latest

**What's the output of `:CocCommand workspace.showOutput Pyright`**
Workspace: /home/pittcat/Projects/Playboard/python/pyenv_dot
Using python from /usr/bin/python

[Info  - 7:51:47 PM] Pyright language server 1.1.168 starting
[Info  - 7:51:47 PM] Server root directory: /home/pittcat/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/
[Info  - 7:51:47 PM] No configuration file found.
[Info  - 7:51:47 PM] No pyproject.toml file found.
[Info  - 7:51:47 PM] Setting pythonPath for service "pyenv_dot": "/usr/bin/python"
[Warn  - 7:51:47 PM] stubPath /home/pittcat/Projects/Playboard/python/pyenv_dot/typings is not a valid directory.
[Info  - 7:51:47 PM] Assuming Python version 3.9
[Info  - 7:51:47 PM] Assuming Python platform Linux
[Warn  - 7:51:47 PM] Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Warn  - 7:51:47 PM] Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Warn  - 7:51:47 PM] Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Warn  - 7:51:47 PM] Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Info  - 7:51:47 PM] Searching for source files
[Info  - 7:51:47 PM] Found 1 source file

**Comment by pittcat** [comment]
https://asciinema.org/a/TkwBN7GL3Ux6wUxdQ0ctItIYH

Code:
```
#!/usr/bin/env python
# -*- coding=utf-8 -*-

import numpy as np
from scipy import optimize as op
op.curve_fit()
```
No such situation will occur in Jedi-lsp(coc-jedi) and Pylance. I'm not sure if this bug belongs to coc-pyright.

**Comment by pittcat** [comment]
https://github.com/microsoft/pyright/issues/2324
Maybe the problem is reated to pyright. `pyright.createtypestub numpy` will stuck.

**Comment by fannheyward** [comment]
coc-pyright can do nothing about this, try https://github.com/microsoft/python-type-stubs/tree/main/scipy-stubs work or not.
