### ISSUE TITLE
Disable specific warnings

### ISSUE THREAD

**Issue by goffi-contrib** [fannheyward/coc-pyright#627]
Hello,

thanks for maintaining this, I'm new to CoC and CoC-PyRight and it is quite pleasant to use.

Would it be possible to add a way to disable a specific warning (by its message for instance)? I'm using double underscore `__` to mark a variable as unused (I'm not using single underscore as it is conflicting with the use of it for gettext), this is a common practice, and Coc-Pyright is showing a "not accessed" hint for that.

I know that there have been previous discussion (#107) pointing to `diagnostic.showUnused` but I want to keep unused variables hints, only disable it for this specific variable name.

Furthermore, Pyright is incorrectly marking some [Twisted](https://twistedmatrix.com) methods such as `reactor.listenTCP` or `reactor.listenSSL` as not existing, it would be useful to indicate that this must be ignored.

Thanks

**Comment by fannheyward** [comment]
> Pyright is incorrectly marking some Twisted methods 

Try to create typing files by `:CocCommand pyright.createtypestub twisted`.

You can put `# type: ignore` at the end of line to disable Pyright checking.

**Comment by goffi-contrib** [comment]
thanks for your feedback, I knew about the `# type: ignore` way but it's not nice and polluting the code to put this in many places. I guess this should be fixed on Twisted level has I've found other people having this issue (e.g. here: https://stackoverflow.com/questions/66850481/mypy-typing-errors-when-upgrading-to-twisted-21-2-0)

What about the double dash issue? It's a common way to mark a variable as ignored, and disabling completely the feature is not a good option.

**Comment by fannheyward** [comment]
> It's a common way to mark a variable as ignored

I don't find it's a common way, in most Python practices, we use `_` to suppress the unused var.

**Comment by goffi-contrib** [comment]
> > It's a common way to mark a variable as ignored
> 
> I don't find it's a common way, in most Python practices, we use `_` to suppress the unused var.

Except when it conflicts with the common use of assigning `_` to gettext.

After a quick search I can see several references to it:

- https://stackoverflow.com/q/32602902 (and a comment below says that PyCharm recognise double underscore)
- https://stackoverflow.com/a/13944314 (mention of the issue with gettext)
- https://softwareengineering.stackexchange.com/a/285304 (gettext mentioned in original question), double underscore in the comment
- https://stackoverflow.com/questions/24984349/is-two-underscores-favorable-over-a-single-underscore-for-a-dummy-varia

**Comment by fannheyward** [comment]
Try coc-pyright v1.1.171, coc-pyright will ignore `"__" is not accessed` diagnostics.

https://github.com/microsoft/pyright/issues/1931

**Comment by goffi-contrib** [comment]
Thanks!
