### ISSUE TITLE
Autoimport doesn't work when using the system's pyright version

### ISSUE THREAD

**Issue by bellini666** [fannheyward/coc-pyright#628]
Hi,

When using my system's pyright version (which atm is at the same version as this plugin) from this (https://github.com/fannheyward/coc-pyright/issues/625), the auto import feature doesn't seem to work.

If I remove the config to use the one from the plugin it starts working again.

Is that an expected side-effect of the change there?

**Comment by fannheyward** [comment]
> the auto import feature doesn't seem to work

<img width="545" alt="截屏2021-09-26 上午10 07 39" src="https://user-images.githubusercontent.com/345274/134790728-2bd91464-f034-40b3-b701-fdb534d83ff3.png">

Do you mean this auto-import? After `<CR>` confirm, Pyright will `import os` to use. Tested with local and system global Pyright, works as expected.

**Comment by bellini666** [comment]
@fannheyward ok, I see now what is going on. I think the global pyright config is not working... I thought it was because I first set it to `pyright` only to get it from my $PATH and got an error, then I set it to `"pyright.server": "/home/bellini/.nvm/versions/node/v16.8.0/bin/pyright"` and it seemed to work (I can see the process running on `ps aux`), but it is not actually doing anything...

Any way to enable some extra debug to attach here the logs?

**Comment by fannheyward** [comment]
There will be two command in `/home/bellini/.nvm/versions/node/v16.8.0/bin/`:

1. `pyright`, this is the CLI tool that runs Pyright and outputs results to stdout, this's NOT the language server.
2. `pyright-langserver`, the Pyright language server

You should use the `pyright-langserver`.

**Comment by fannheyward** [comment]
In next coc-pyright release, you can set `pyright.server` with related path like `$HOME/bin/pyright-langserver`.

**Comment by bellini666** [comment]
Hey @fannheyward ,

Thanks for the late reply. I see, using `pyright-langserver` did the trick :)

The change to be able to put `$HOME/bin/pyright-langserver` is a nice addition, but does't really solve my issue. I want to config it like `pyright-langserver` and it would retrieve from my $PATH, since the `/home/bellini/.nvm/versions/node/v16.8.0/bin/` path can change when I update the node version (i.e. install node v16.9.0)

Its a QOL and np if it can't be done, but it would be awesome if it could.

**Comment by yaegassy** [comment]
Hi, @bellini666 

The new feature added by fannheyward means that you can expand `environment variables` and `~`. For "nvm", I think it is available in `$NVM_BIN/pyright-langserver`. Please try it.

(I don't use nvm, so sorry if I'm wrong)

**Comment by fannheyward** [comment]
You can use `"pyright.server": "pyright-langserver"` in next coc-pyright release, coc-pyright will resolve it from $PATH.

**Comment by bellini666** [comment]
Awesome! That solves everything

Thank you so much @fannheyward
