### ISSUE TITLE
Enable isort on each format

### ISSUE THREAD

**Issue by randrej** [fannheyward/coc-pyright#629]
It'd be nice to have a switch in the config that enables triggering an import sort on every format. I have a habit of formatting with a keyboard shortcut, and I'd like to also reorder the imports at the same time.

**Comment by fannheyward** [comment]
Try something like this: `autocmd BufWritePre *.py :silent call CocAction('runCommand', 'editor.action.organizeImport')`.

You need to set `"pyright.organizeimports.provider": "isort"` first, I think you already have this.
