### ISSUE TITLE
[bug] codeaction 'ignore pyright check for current line' will repeat the last character

### ISSUE THREAD

**Issue by Freed-Wu** [fannheyward/coc-pyright#632]
test.py
```python
def init() -> None:
```

after codeaction ignore pyright typing check for current line:

```python
def init() -> None:  # type: ignore:
```

the last character `:` always be repeated.

**What's the output of `:CocCommand pyright.version`**

1.1.172

**What's the output of `:CocCommand workspace.showOutput Pyright`**

```
Workspace: /home/wzy/Desktop/computer-graphics-homework
Using python from /usr/bin/python

[Info  - 8:05:31 PM] Pyright language server 1.1.172 starting
[Info  - 8:05:31 PM] Server root directory: /home/wzy/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/
[Info  - 8:05:32 PM] No configuration file found.
[Info  - 8:05:32 PM] No pyproject.toml file found.
[Info  - 8:05:32 PM] Setting pythonPath for service "computer-graphics-homework": "/usr/bin/python"
[Warn  - 8:05:32 PM] stubPath /home/wzy/Desktop/computer-graphics-homework/typings is not a valid directory.
[Info  - 8:05:32 PM] Assuming Python version 3.9
[Info  - 8:05:32 PM] Assuming Python platform Linux
[Warn  - 8:05:32 PM] Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Warn  - 8:05:32 PM] Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Warn  - 8:05:32 PM] Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Warn  - 8:05:32 PM] Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Info  - 8:05:32 PM] Searching for source files
[Info  - 8:05:32 PM] Found 16 source files
[Info  - 8:05:37 PM] [FG] Long operation: checking: /home/wzy/Desktop/computer-graphics-homework/utils/ellipse.py (3392ms)
[Info  - 8:05:37 PM] [FG] Long operation: analyzing: /home/wzy/Desktop/computer-graphics-homework/utils/ellipse.py (4460ms)
```

**Comment by yaegassy** [comment]
Hi, @Freed-Wu 

When I tried it in my environment, I could not reproduce it. It's working fine.

https://user-images.githubusercontent.com/188642/135267981-69f1aac3-3331-4033-a75b-7fe4f1b39b5e.mp4

**Comment by Freed-Wu** [comment]
```vim
" $ uname -r
" 5.14.7-arch1-1
" $ has nvim
" ✓ nvim 0.5.0
" $ has python
" ✓ python 3.9.7
" $ cat test.vim
set runtimepath=$VIMRUNTIME
set runtimepath+=~/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release
nmap g. <Plug>(coc-codeaction-selected)
" $ vi -u test.vim test.py
```
![Screenshot from 2021-09-29 20-45-28](https://user-images.githubusercontent.com/32936898/135271168-00ea92e9-bfea-46e4-ae67-764205cbcba8.png)

press `g.$`
![Screenshot from 2021-09-29 20-46-15](https://user-images.githubusercontent.com/32936898/135271181-d017f0d7-c06e-4851-81a3-681a5fcbabd9.png)

press `2`
![Screenshot from 2021-09-29 20-46-23](https://user-images.githubusercontent.com/32936898/135271197-36192aa5-f4d4-45fa-a6f3-9bd2fbca2e84.png)

I guess it is because some coc-plugin not vim plugin, because I don't add any other vim plugins except coc.nvim in my test.vim.

Before test, I have deleted coc-setting.json, but `~/.config/coc` still exists.

**Comment by Freed-Wu** [comment]
I have modify my `~/.config/coc/extensions/package.json` to

```json
{
  "dependencies": {
    "coc-pyright": ">=1.1.172",
  }
}
```

In this situation, only one coc plugin is sourced.

![Screenshot from 2021-09-29 20-56-30](https://user-images.githubusercontent.com/32936898/135272677-6176d1d1-7e42-4350-9448-94c953927062.png)

I guess the bug cannot be reproduced maybe because environment? What is your environment?

BTW, my node version is 16.10.0.

**Comment by yaegassy** [comment]
I think the problem is caused by the use of `<Plug>(coc-codeaction-selected)`. Select it in visual mode, including `:`, and try to run it.

Or try using `<Plug>(coc-codeaction-line)`.

**Comment by fannheyward** [comment]
Yes, this is caused by `<Plug>(coc-codeaction-selected)` in normal `char` mode, coc.nvim will use `getpos('[')` and `getpos(']')` to do selection, returns range without the `:`, have no idea why this happened.

Try select it in visual mode first, or `<Plug>(coc-codeaction-line)`.

**Comment by Freed-Wu** [comment]
So it is coc.nvim's bug on `<plug>(coc-codeaction-selected)`? Should we report it to coc.nvim?
