### ISSUE TITLE
Import "test" could not be resolved

### ISSUE THREAD

**Issue by theniceboy** [fannheyward/coc-pyright#64]
coc-pyright is unable to resolve imports when importing a local file, such as
```python
# main.py
from test import *
```
(both `main.py` and `test.py` are in the same directory)

**Comment by fannheyward** [comment]
test.py:

```py
def greeting(name: str):
    print("Hello, " + name)
```

main.py:
```py
#!/usr/bin/env python3

from test import *

greeting('aa')
```

**Comment by theniceboy** [comment]
Are you able to reproduce the issues with these two files?

lab1.py:
```python
def greeting(name: str):
    print("Hello, " + name)
```
main.py:
```python
#!/usr/bin/env python3

from lab1 import *

greeting('aa')
```
With these two files, I get:
```
[Pyright (reportMissingImports)] [E] Import "lab1" could not be resolved
[Pyright (reportGeneralTypeIssues)] [E] "greeting" is not defined
```

**Comment by fannheyward** [comment]
Can't reproduce. You can test with VSCode + https://marketplace.visualstudio.com/items?itemName=ms-pyright.pyright.

**Comment by theniceboy** [comment]
I just tried it on another computer, can’t reproduce there. Thank you for looking at this.

**Comment by rodorgas** [comment]
I had the same issue. Since I was working in a subdirectory of an git repository, it seems that CoC will consider that parent dir was the root. Solved by following instructions here: https://github.com/neoclide/coc.nvim/wiki/Using-workspaceFolders

**Comment by 0xMH** [comment]
@rodorgas Is there a way to set the current directory as a root? That'll help a lot in case working on mono repos.

**Comment by alexzanderr** [comment]
> I had the same issue. Since I was working in a subdirectory of an git repository, it seems that CoC will consider that parent dir was the root. Solved by following instructions here: https://github.com/neoclide/coc.nvim/wiki/Using-workspaceFolders

yes, this works. setting accordingly the root of the project will automatically fix coc-pyright import errors.
