### ISSUE TITLE
The utf-8 string complete error.

### ISSUE THREAD

**Issue by traversalnat** [fannheyward/coc-pyright#640]
```
"work".capitalize()
the coc report that the startcol is 8

"工作".capicapitalize()
the coc report that the startcol is 10
```

**What's the output of `:CocCommand pyright.version`**
[coc.nvim] coc-pyright 1.1.172 with Pyright 1.1.175

**What's the output of `:CocCommand workspace.showOutput Pyright`**
Workspace: /Users/jackzhang/workspace/Python
Using python from /Users/jackzhang/workspace/Python/venv/bin/python

[Info  - 下午8:26:01] Pyright language server 1.1.175 starting
[Info  - 下午8:26:01] Server root directory: /Users/jackzhang/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/
[Info  - 下午8:26:01] No configuration file found.
[Info  - 下午8:26:01] No pyproject.toml file found.
[Info  - 下午8:26:01] Setting pythonPath for service "Python": "/Users/jackzhang/workspace/Python/venv/bin/python"
[Warn  - 下午8:26:01] stubPath /Users/jackzhang/workspace/Python/typings is not a valid directory.
dyld: Library not loaded: /usr/local/Cellar/python@3.8/3.8.3/Frameworks/Python.framework/Versions/3.8/Python
  Referenced from: /Users/jackzhang/workspace/Python/venv/bin/python
  Reason: image not found
[Info  - 下午8:26:01] Unable to get Python version from interpreter
[Info  - 下午8:26:01] Assuming Python platform Darwin
dyld: Library not loaded: /usr/local/Cellar/python@3.8/3.8.3/Frameworks/Python.framework/Versions/3.8/Python
  Referenced from: /Users/jackzhang/workspace/Python/venv/bin/python
  Reason: image not found
dyld: Library not loaded: /usr/local/Cellar/python@3.8/3.8.3/Frameworks/Python.framework/Versions/3.8/Python
  Referenced from: /Users/jackzhang/workspace/Python/venv/bin/python
  Reason: image not found
[Info  - 下午8:26:01] Searching for source files
[Info  - 下午8:26:01] Auto-excluding /Users/jackzhang/workspace/Python/python/venv
[Info  - 下午8:26:01] Auto-excluding /Users/jackzhang/workspace/Python/venv
[Info  - 下午8:26:01] Found 290 source files

**Comment by fannheyward** [comment]
Fixed on coc.nvim latest release.
