### ISSUE TITLE
"reportMissingImports, reportMissingModuleSource" issues

### ISSUE THREAD

**Issue by xvim64** [fannheyward/coc-pyright#644]
**What's the output of `:CocCommand pyright.version`**
[coc.nvim] coc-pyright 1.1.177 with Pyright 1.1.179

**What's the output of `:CocCommand workspace.showOutput Pyright`**
Workspace: d:\test
Using python from python

[Info  - AM 10:53:34] Pyright language server 1.1.179 starting
[Info  - AM 10:53:34] Server root directory: C:\home\xvim\\.neovim\coc\extensions\node_modules\coc-pyright\node_modules\pyright/dist/
[Info  - AM 10:53:34] No configuration file found.
[Info  - AM 10:53:34] No pyproject.toml file found.
[Warn  - AM 10:53:34] stubPath d:\test\typings is not a valid directory.
[Info  - AM 10:53:34] Assuming Python platform Windows
[Info  - AM 10:53:34] Searching for source files
[Info  - AM 10:53:34] Found 1 source file

OS : Windows 10 x64

Python : v3.9.7

vim : v8.2.3532

I installed the "keyboard", "pillow" python libraries. but the coc-pyright can not detect "keyboard", "pillow" python libraries in vim.

It seems that the coc-pyright can not detect the "site-packages" directory of the python in vim

![1](https://user-images.githubusercontent.com/83569599/137657888-d7017ca2-f597-44e3-8ff5-bfb8a3046edc.png)

![2](https://user-images.githubusercontent.com/83569599/137657893-223aa227-1fc4-40b0-95d8-f4107f27843b.png)

**Comment by fannheyward** [comment]
> Using python from python

Can you import these modules by `python -m keyboard`?

Try to activate the correct Python before enter vim.

**Comment by fannheyward** [comment]
Try to set `python.pythonPath` to your python3 in coc-settings.json.

**Comment by xvim64** [comment]
"python.pythonPath" in coc-settings.json can not fix the problem.

![3](https://user-images.githubusercontent.com/83569599/137820515-aaded073-4d09-4573-8641-6645244921b6.png)

![4](https://user-images.githubusercontent.com/83569599/137820519-c4efc2fb-c417-405c-890b-c88dd70c62a2.png)

**Comment by yaegassy** [comment]
@xvim64 Also, if it still does not work, try checking it in a virtual environment.

Create a virtual environment and "activate" the virtual environment. Install the `keyboard` and `pillow` in your activated python environment.

Do you experience the same problem in that environment?

```bash
mkdir example
cd example
python -m venv venv
.\venv\Scripts\activate
pip install keyboard pillow
vim sample.py
```
