### ISSUE TITLE
Cannot get conda 4.10.3 to find imports for venvs

### ISSUE THREAD

**Issue by iernstig** [fannheyward/coc-pyright#647]
You've probably heard this one before, but I cannot get it to work and it's driving me nuts so I'm hoping you might be able to sort out the problem. Everything works fine in my base environment, but as soon as I'm activating a venv, coc-pyright cannot resolve any of my imports. 

My conda version is 4.10.3

**What's the output of `:CocCommand pyright.version`**
`[coc.nvim] coc-pyright 1.1.180 with Pyright 1.1..180`

**What's the output of `:CocCommand workspace.showOutput Pyright`**
```
Workspace: /home/iernstig/tmp
Using python from /home/iernstig/miniconda3/envs/tmp/bin/python

[Info  - 8:24:20 PM] Pyright language server 1.1.180 starting
[Info  - 8:24:20 PM] Server root directory: /home/iernstig/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/
[Info  - 8:24:20 PM] Setting pythonPath for service "tmp": "/home/iernstig/miniconda3/envs/tmp/bin/python"
[Info  - 8:24:20 PM] Loading configuration file at /home/iernstig/tmp/pyrightconfig.json
[Info  - 8:24:20 PM] Unable to get Python version from interpreter
[Info  - 8:24:20 PM] Assuming Python platform Linux
[Info  - 8:24:20 PM] No include entries specified; assuming /home/iernstig/tmp
[Info  - 8:24:20 PM] Auto-excluding **/node_modules
[Info  - 8:24:20 PM] Auto-excluding **/__pycache__
[Info  - 8:24:20 PM] Auto-excluding .git
[Warn  - 8:24:20 PM] The venvPath has been specified in both the config file and the client settings. The value in the config file (/home/iernstig/miniconda3/) will take precedence
[Error  - 8:24:20 PM] venv tmp subdirectory not found in venv path /home/iernstig/miniconda3/.
[Error  - 8:24:20 PM] typeshedPath /home/iernstig/miniconda3/lib/python3.9/site-packages/mypy/typeshed is not a valid directory.
[Warn  - 8:24:20 PM] stubPath /home/iernstig/tmp/typings is not a valid directory.
[Info  - 8:24:20 PM] Unable to get Python version from interpreter
[Info  - 8:24:20 PM] Searching for source files
[Info  - 8:24:20 PM] Found 1 source file

```
my local pyrightconfig.json
```
{
"venvPath": "/home/iernstig/miniconda3/envs",
"venv": "tmp"
}
```

So it seems that pyright is looking for the env and a specific interpreter, but it does not work. Furthermore, doing as the instruction in the readme doesn't work either. What I've tried there is:
1. Create `phony.sh` in `/home/iernstig/miniconda3`
2. chmod +x phony.sh
3. add `"python.pythonPath": "/home/iernstig/miniconda3/phony.sh"` to my coc-config.json

This solution did not work for me either. Did anyobody else have better luck in getting coc-pyright working with a conda venv?

Best regards
Isak

**Comment by fannheyward** [comment]
Sorry I'm not conda user, will try this later.

Try the following steps:

1. remove `venvPath` and `venv` settings in pyrightconfig.json
2. make sure there's no venv related settings in your coc-settings.json
3. activate the venv first, run `which python` to make sure you're using the correct venv
4. run vim and checkout the `:CocCommand workspace.showOutput Pyright`

> venv tmp subdirectory not found in venv path /home/iernstig/miniconda3/

Maybe this is the root reason.
