### ISSUE TITLE
Need to know the function name when call coc-references

### ISSUE THREAD

**Issue by JunqiZhang0** [fannheyward/coc-pyright#650]
coc-pyright only show the line which contains the word, it would be better if it can also show the caller function name like what vscode does

**Comment by JunqiZhang0** [comment]
@fannheyward Sorry, vscode doesn't do it either...

**Comment by JunqiZhang0** [comment]
But it would be nice, if we can show caller name when we call coc-references

**Comment by fannheyward** [comment]
LSP references doesn't have caller name, Try `:CocCommand document.showIncomingCalls` on the called function.
