### ISSUE TITLE
Support for custom command line arguments for the linter

### ISSUE THREAD

**Issue by wthueb** [fannheyward/coc-pyright#651]
After flake8 has removed support for a global configuration file (https://github.com/pycqa/flake8/pull/1404), it would be nice to be able to specify command line arguments for the linter. Making a .flake8 file for every project seems counter productive, and their is a semblance of support for this already with being able to provide command line arguments to the formatter.

**Comment by fannheyward** [comment]
Does `python.linting.flake8Args` work for you?

**Comment by wthueb** [comment]
> Does `python.linting.flake8Args` work for you?

Ah, thank you! None of the linter argument options are documented in the README, however I guess I could have dug into it a little more.
