### ISSUE TITLE
black runs 4x slower in coc-pyright than by itself (and times out)

### ISSUE THREAD

**Issue by laurentS** [fannheyward/coc-pyright#661]
I keep having problems with a file that black does not format in vim/coc-pyright (so I commit/push it and CI fails :cry: ). The problem is that black gets cancelled by coc-pyright because it's too slow. This makes sense, but:
- I initially had `"coc.preferences.willSaveHandlerTimeout": 1000,` and increased to 2200, problem still happened
- `:CocCommand workspace.showOutput coc-pyright-formatting` shows the following:
```
Using python from xxxx/.venv/bin/python

########## active formattor: black
execPath:   black
moduleName: black
args:       --diff,--quiet,myfile.py.9ba5f3118fe63c2bafdf088feb5a188e.py

########## black output:

########## black formatting action is canceled.
```
- `:CocCommand workspace.showOutput Pyright` says
```
[Info  - 11:48:44] [FG] Long operation: checking: myfile.py (2440ms)
[Info  - 11:48:44] [FG] Long operation: analyzing: myfile.py (2445ms)
```
- running black directly takes about 600ms
```
$ time black myfile.py
reformatted myfile.py
All done! ✨ 🍰 ✨
1 file reformatted.

real    0m0.602s
user    0m0.569s
sys     0m0.029s
```

So there are a couple of issues here:
- coc-pyright takes 4 times the baseline time to run black and therefore cancels the run
- my file is not formatted, but I don't see any error message (`:messages` just shows "[coc-nvim] Formatted with black" which is not true. There is no mention of a timeout)

**What's the output of `:CocCommand pyright.version`**
`[coc-nvim] coc-pyright 1.1.168 with Pyright 1.1.186`

**What's the output of `:CocCommand workspace.showOutput Pyright`**
see above

**Comment by fannheyward** [comment]
> [Info  - 11:48:44] [FG] Long operation: checking: myfile.py (2440ms)

This log is not the time of coc-pyright to do formatting, it's Pyright analyze time.

Try `:call CocAction('format')`.

**Comment by ashwinmahantha** [comment]
@laurentS I had the exact same issue. I spent a whole day on this.
I solved it as below:
1. Don't use black and isort from inside coc. My coc-settings.json:
```
{
    "python.sortImports.path": "/usr/bin/isort",
    "coc.preferences.willSaveHandlerTimeout": 1000,
    // this is required. Else coc looks for autopep8
    "python.formatting.provider": "black",
    "python.formatting.blackPath": "/usr/bin/black",
    // removed python from below to run black and isort independently
    "coc.preferences.formatOnSaveFiletypes": [
        "json",
        "markdown"
    ],
    "coc.source.around.firstMatch": false,
    "pyright.enable": true,
    "python.pythonPath": "/usr/bin/python",
    "python.linting.pylintEnabled": false,
    "python.linting.flake8Enabled": true,
    "python.linting.flake8Path": "flake8",
    "python.linting.enabled": true
}
```
2. In init.vim:
```
call plug#begin('~/.vim/plugged')
Plug 'psf/black', { 'branch': 'main' }
Plug 'fisadev/vim-isort'
call plug#end()

" This triggers all formatting before coc linter is triggered
aug python
    au!
    autocmd BufWritePre *.py Isort
    autocmd BufWritePre *.py Black
aug END
```
