### ISSUE TITLE
pyright with conda virtual envs

### ISSUE THREAD

**Issue by thinker310** [fannheyward/coc-pyright#666]
Is there a way to set interpreter in conda envs by pyright? In coc-python, there is a command to set interpreter and it is very nice. I want to know if there is a similar way to do that. Thank you inadvance!

**Comment by fannheyward** [comment]
No. coc-pyright will auto detect the Python from $CONDA_PREFIX. You can `conda activate` first, open vim, coc-pyright should find and use the right interpreter.

**Comment by minrui-hust** [comment]
But it seems not working at all,
so many import missing as other issue mentioned, without a working solution!
