### ISSUE TITLE
Configuration to disable `python-import`

### ISSUE THREAD

**Issue by fannheyward** [fannheyward/coc-pyright#667]
>  like sys module will not be listed by python-import

@BoysHands reproduced, but have no idea about this because the results of `python-import` is came from Pyright too. I'll add an option to disable `python-import`.

_Originally posted by @fannheyward in https://github.com/fannheyward/coc-pyright/issues/665#issuecomment-979591166_

**Comment by BoysHands** [comment]
thank u, and i just open a issue to describe my problem.
