### ISSUE TITLE
python-import may confilict with pyright

### ISSUE THREAD

**Issue by BoysHands** [fannheyward/coc-pyright#668]
coc-pyright provides two sources, import-python[PY] and pyright[LS]. In my environment, these two sources may conflict.
on first time, when i input ` import `, i will get result from ` import-python `. And it may not get all my modules.
![pic1](https://user-images.githubusercontent.com/21166470/143514814-63e72c15-60e2-4101-9f02-82f4de8a526d.PNG)
when i delete sys, and type again, it will get result from pyright[LS]
![pic2](https://user-images.githubusercontent.com/21166470/143514938-300e7517-e14e-41f8-bb9a-a04558ded5d7.PNG)
and i can't  change priority or disable sources with "cocconfig".

**What's the output of `:CocCommand pyright.version`**
[coc.nvim] coc-pyright 1.1.190 with Pyright 1.1.190

**What's the output of `:CocCommand workspace.showOutput Pyright`**
[Info  - 上午9:13:30] Pyright language server 1.1.190 starting
[Info  - 上午9:13:30] Server root directory: /home/xuda/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/
[Info  - 上午9:13:30] No configuration file found.
[Info  - 上午9:13:30] No pyproject.toml file found.
[Info  - 上午9:13:30] Setting pythonPath for service "Projects": "/usr/bin/python"
[Warn  - 上午9:13:30] stubPath /home/xuda/Projects/typings is not a valid directory.
[Info  - 上午9:13:30] Assuming Python version 3.9
[Info  - 上午9:13:30] Assuming Python platform Linux
[Warn  - 上午9:13:31] Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursiv
[Warn  - 上午9:13:31] Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursiv
[Warn  - 上午9:13:31] Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursiv
[Warn  - 上午9:13:31] Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursiv
[Warn  - 上午9:13:31] Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursiv
[Info  - 上午9:13:31] Searching for source files
[Info  - 上午9:13:32] Found 1502 source files

**Comment by fannheyward** [comment]
Added `pyright.completion.importSupport`, will be available in next release.
