### ISSUE TITLE
coc-python signatureHelp stops working

### ISSUE THREAD

**Issue by oblitum** [fannheyward/coc-pyright#67]
I've configured `coc-pyright` with:

```vim
  call coc#config('pyright', {
  \   'disableLanguageServices': v:true
  \ })
```

Because I'm trying to use it with coc-python, but now I don't get signatureHelp from either place.

**Comment by fannheyward** [comment]
Yes, coc-yright has some conflict with coc-python.

**Comment by oblitum** [comment]
Pyright recommends to use `disableLanguageServices` to make it work with VSCode python extension: https://github.com/microsoft/pyright#using-pyright-with-vs-code-python-extension.

Do you think this is possible from coc.nvim side too?

**Comment by fannheyward** [comment]
Pyright has improved signatureHelp in latest version https://github.com/microsoft/pyright/releases/tag/1.1.58, it works great.

After Pylance released, MPLS will be deprecated.

**Comment by oblitum** [comment]
Holy moly, a third python language server by microsoft? Just unsure which one I should move to now. Any plans to have a coc-pylance?

**Comment by oblitum** [comment]
Ah okay, so pylance is a vscode extension that actually uses pyright.

**Comment by oblitum** [comment]
Looks like pyright is still missing a lot compare to MPLS. For example, while typing`import numpy`,`numpy.abs(`, MPLS will give so much more info.

**Comment by fannheyward** [comment]
>  pyright doesn't give any signature help for abs from numpy

The same.

**Comment by oblitum** [comment]
Just tested numpy from master and things will improve, see https://github.com/microsoft/pyright/issues/753.

I'm switching to coc-pyright, it seems the way forward.

Do you happen to know for what purpose is `venvPath`? README says:

> `python.venvPath`: Path to folder with a list of Virtual Environments, default: `""`

But what can I do with that? I didn't find any command that could, for example, list those virtual environments to switch to them.

I use pyenv and my current setup is:

```vim
  if !empty($PYENV_VIRTUAL_ENV)
    call coc#config('python', {
    \   'pythonPath': $PYENV_VIRTUAL_ENV . '/bin/python',
    \   'venvPath': glob('~/.pyenv/versions')
    \ })
  endif
```

This works to set the corrent python for the current virtualenv. I'm also setting `venvPath` there, but don't have any use for it, it seems.

**Comment by fannheyward** [comment]
> Just tested numpy from master and things will improve

👍 

To be honest, I don't know what `python.venvPath` means and used for what. I've never set it. My workflow:

1. create venv in my project: `python3 -m venv .venv`
2. `source .venv/bin/activate`
3. open py files in vim and work with Pyright.
4. `deactivate`

There is no any python/pyright related configurations in `coc-settings.json`.

**Comment by oblitum** [comment]
Thanks for the info on workflow, I'll consider it, though the pyenv workflow as I documented above is also okay if one is using it.

**Comment by oblitum** [comment]
Just [discovered](https://github.com/microsoft/pyright/issues/753#issuecomment-670631256) [data-science-types](https://github.com/predictive-analytics-lab/data-science-types), it's nice! Maybe worth recommended on coc-pyright README for now.

**Comment by fannheyward** [comment]
> Maybe worth recommended on coc-pyright README for now.

Added.

**Comment by oblitum** [comment]
@fannheyward sorry, I just discovered this, maybe this one is even more worthy mentioned, as it's more generic: https://github.com/typeddjango/awesome-python-typing.

**Comment by fannheyward** [comment]
@oblitum can you make a PR for this?

**Comment by jonatasleon** [comment]
@fannheyward wouldn't be better if add the workflow reported in https://github.com/fannheyward/coc-pyright/issues/67#issuecomment-670292342 in README.md?

**Comment by ECon87** [comment]
> @fannheyward wouldn't be better if add the workflow reported in [#67 (comment)](https://github.com/fannheyward/coc-pyright/issues/67#issuecomment-670292342) in README.md?

I second that. @fannheyward thank you for this package is amazing, but @jonatasleon has a point. I spent 1 hour trying figure out the equivalent of setInterpreter. Found a thread and followed 2 other linked threads to come here. Tried setting venvPath, and venv.

**Comment by fannheyward** [comment]
@jonatasleon @ECon87 sorry for the delay, added https://github.com/fannheyward/coc-pyright/commit/4598c854817d74ae19b8169c4a349cb2d9ea96f9
