### ISSUE TITLE
Add option for flake8 arguments

### ISSUE THREAD

**Issue by ItsDrike** [fannheyward/coc-pyright#674]
There is currently no way to define flake8 arguments. In the available configuration options, there is only the option to enable flake8 linting itself: `python.linting.flake8Enabled`, however there is no `python.linting.flake8Args`, which greatly limits the ability to meaningfully use it when you want to globally ignore some warnings.

**What's the output of `:CocCommand pyright.version`**
[coc.nvim] coc-pyright 1.1.172 with Pyright 1.1.173

**Comment by yaegassy** [comment]
`python.linting.flake8Args` is available. Try it out.

**e.g.**:

```jsonc
{
  // ...snip
  "python.linting.flake8Args": [
    "--max-line-length=80",
    "--ignore=F401,E203,W503,W504"
  ],
  // ...snip
}
```

Perhaps you thought it did not exist because it was not mentioned in the README.

**Comment by fannheyward** [comment]
https://github.com/fannheyward/coc-pyright/blob/1c7e1fe424ea8d834ebd930ee2b406c8ea09cada/package.json#L783-L791

**Comment by ItsDrike** [comment]
Oh, maybe you should mention that file in README so it's clear that there are some undocumented settings too, alternatively, add it to that readme list @fannheyward
