### ISSUE TITLE
Most of packages import are wrong

### ISSUE THREAD

**Issue by CranChen** [fannheyward/coc-pyright#677]
Hello, thanks for offering such great extension!

pyright cannot detect pandas and most of the packages, it said "import pandas cannot be resolved".

Is it the problem of PATH?
I don't use virtual environment since I just use the default system python interpreter.
How can I solve this problem? 
Thanks!

**Comment by fannheyward** [comment]
Does `pandas` module in your system python?

**Comment by CranChen** [comment]
>

**Comment by CranChen** [comment]
Yes.
I have three python: 
1) Download from python official website
2) Homebrew download
3) MacOS built-in 

I mainly use the 1) python official website one and download all python packages around this interpreter.

**Comment by CranChen** [comment]
with the output  `:CocCommand workspace.showOutput Pyright`

I might figure out the error as the it use python from /usr/bin/python, which is even a python2.
How can I change the python interpreter in pyright? 

Thanks!

**Comment by fannheyward** [comment]
Make sure `python` from PATH is the correct one, or use an virtual environment.

**Comment by CranChen** [comment]
I add all python path into my PATH environement variable, with the mainly-used python the fisrt one.

But, how can I use the python I want in pyright?

**Comment by fannheyward** [comment]
You can set `python.pythonPath` in your coc-settings.json.

**Comment by CranChen** [comment]
ok, got you!
Thanks for your reply, I appreciate it a lot.
I with you have a great day!
