### ISSUE TITLE
pyright with scipy.stats.norm

### ISSUE THREAD

**Issue by CranChen** [fannheyward/coc-pyright#678]
Hello!

Thanks for your patience and answer last time!

I found some unexpected error of pyright report:

1) pyright cannot detect scipy.stats.norm
I have to do "from scipy.stats._continuous_distns import norm" 

2) pyright report error on scipy.stats.norm.rvs
x = norm.rvs(size=1000)
x[1]  #pyright says [Pyright reportGeneralTypeIssues] [E] "__getitem__" method not defined on type "int"

Can you help me take a look at this?
Thanks!

**Comment by fannheyward** [comment]
It's Pyright's issue, maybe you need a stub for scipy.
