### ISSUE TITLE
General question for coc-pyright background process

### ISSUE THREAD

**Issue by ow0x** [fannheyward/coc-pyright#679]
Hi, greetings!

So lately I am observing this background process from coc-pyright on my ubuntu 20.04 VPS. It randomly occurs sometimes and roughly ends up taking roughly 300MiB+ of RAM which often slows down other running processes on my VPS since it only has 2GiB of RAM.

![2021-12-18_12-07-52](https://user-images.githubusercontent.com/24418520/146639871-35648755-7d08-4c38-a538-18a389f9d957.png)

I was unsure where to ask for help for this since I'm unsure if coc-pyright or coc.nvim or pyright server is auto spawning this background process, so I decided to ask here! Sorry for any inconvenience!

Do you know what could possibly start this background process? I have searched closed issues on this repo and my issue/question seems related to #322
I sometimes code on this VPS in vim from time to time.
Up until now, I would just SIGKILL/SIGTERM this process from htop to free up RAM and go on focusing on my daily tasks, but it has become more frequent lately so I decided to open an issue.
I would be really grateful if you can point me in right direction for why this is occurring or how to stop this background process from occurring if it is not important for coc-pyright?

----------------------------------

**What's the output of `:CocCommand pyright.version`**
```
[coc.nvim] coc-pyright 1.1.194 with Pyright 1.1.197
```

**What's the output of `:CocCommand workspace.showOutput Pyright`**
```
Workspace: /data/cogs/CogManager/cogs
Using python from /opt/env/bin/python

[Info  - 11:30:19 AM] Pyright language server 1.1.197 starting
[Info  - 11:30:19 AM] Server root directory: /home/ubuntu/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/
[Info  - 11:30:19 AM] No configuration file found.
[Info  - 11:30:19 AM] No pyproject.toml file found.
[Info  - 11:30:19 AM] Setting pythonPath for service "cogs": "/opt/env/bin/python"
[Warn  - 11:30:19 AM] stubPath /data/cogs/CogManager/cogs/typings is not a valid directory.
[Info  - 11:30:19 AM] Assuming Python version 3.9
[Info  - 11:30:19 AM] Assuming Python platform Linux
[Warn  - 11:30:20 AM] Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Warn  - 11:30:20 AM] Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Warn  - 11:30:20 AM] Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Info  - 11:30:20 AM] Searching for source files
[Info  - 11:30:20 AM] Found 193 source files
[Info  - 11:30:25 AM] [FG] Long operation: checking: /data/cogs/CogManager/cogs/mytools/mytools.py (4475ms)
[Info  - 11:30:25 AM] [FG] Long operation: analyzing: /data/cogs/CogManager/cogs/mytools/mytools.py (4969ms)
```

**Comment by fannheyward** [comment]
Sorry for the late response, do you have multiple vim instances running? From your screenshot, you've multiple `build/index.js` process. Each vim instance will launch a node process.

**Comment by ow0x** [comment]
Hi,

Thank you for the response!
I don't recall ever launching multiple vim instances, I always close vim after saving my work with `:wq`, although I haven't seen this background process in past one month ever since opening this issue, it just happens randomly.

I have also updated coc-pyright just now to:
```
[coc.nvim] coc-pyright 1.1.206 with Pyright 1.1.206
```

If I see the same background process again, I will update here.

P.S. Have a nice day!

**Comment by fannheyward** [comment]
Upgrade to coc.nvim latest release, if you see the same issue please post here, close for now.
