### ISSUE TITLE
coc-pyright could not find pyrightconfig.json

### ISSUE THREAD

**Issue by last-partizan** [fannheyward/coc-pyright#680]
I have following project structure:

```
.
├── src
│  ├── app
│  │  ├── assets
│  │  │  └── test.js
│  │  ├── core
│  │  │  └── test.py
│  │  ├── __init__.py
│  │  ├── package-lock.json
│  │  ├── package.json
│  │  └── package.json
│  └── manage.py
├── poetry.lock
├── pyproject.toml
├── pyrightconfig.json
└── README.md
```

To reproduce issue, you need to have `coc-tsserver` and `coc-pyright` installed.
Clone this example and open `src/app/assets/test.js`, and then `src/app/core/test.js`
https://github.com/last-partizan/coc-project-dir-issue

Looks like `coc-tsserver` adds `src/app` to workspaceFolders, and `coc-pyright` uses first entry to look for pyrightconfig.json.

**Output of `:CocCommand workspace.workspaceFolders`**
```
/tmp/test-project-dir/src/app
/tmp/test-project-dir
```

**What's the output of `:CocCommand pyright.version`**
```
[coc.nvim] coc-pyright 1.1.194 with Pyright 1.1.195
```

**What's the output of `:CocCommand workspace.showOutput Pyright`**
```
Workspace: /tmp/coc-project-dir-issue/src/app
Using python from /usr/bin/python

[Info  - 12:12:24 PM] Pyright language server 1.1.195 starting
[Info  - 12:12:24 PM] Server root directory: /home/serg/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/
[Info  - 12:12:24 PM] No configuration file found.
[Info  - 12:12:24 PM] No pyproject.toml file found.
[Info  - 12:12:24 PM] Setting pythonPath for service "app": "/usr/bin/python"
[Warn  - 12:12:24 PM] stubPath /tmp/coc-project-dir-issue/src/app/typings is not a valid directory.
[Info  - 12:12:24 PM] Assuming Python version 3.10
[Info  - 12:12:24 PM] Assuming Python platform Linux
[Warn  - 12:12:24 PM] Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Warn  - 12:12:24 PM] Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Warn  - 12:12:24 PM] Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Info  - 12:12:24 PM] Searching for source files
[Info  - 12:12:24 PM] Found 6 source files
[Info  - 12:12:24 PM] Setting pythonPath for service "coc-project-dir-issue": "/usr/bin/python"
[Info  - 12:12:24 PM] Loading configuration file at /tmp/coc-project-dir-issue/pyrightconfig.json
[Info  - 12:12:24 PM] Assuming Python version 3.10
[Info  - 12:12:24 PM] Assuming Python platform Linux
[Info  - 12:12:24 PM] No include entries specified; assuming /tmp/coc-project-dir-issue
[Info  - 12:12:24 PM] Auto-excluding **/node_modules
[Info  - 12:12:24 PM] Auto-excluding **/__pycache__
[Info  - 12:12:24 PM] Auto-excluding .git
[Warn  - 12:12:24 PM] stubPath /tmp/coc-project-dir-issue/typings is not a valid directory.
[Warn  - 12:12:24 PM] Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Warn  - 12:12:24 PM] Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Warn  - 12:12:24 PM] Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Info  - 12:12:24 PM] Searching for source files
[Info  - 12:12:24 PM] Found 7 source files
```

**Comment by fannheyward** [comment]
Set `"python.analysis.diagnosticMode": "workspace"` in your coc-settings.json.

**Comment by last-partizan** [comment]
Yes, it find configuration file just fine with "workspace" mode, but it will analyse all 2k files in real project.

https://github.com/fannheyward/coc-pyright/blob/207fd92de3e75744a16740804eb500a3c4174497/src/configSettings.ts#L27

I think, workspace root selection could be modified to resolve this issue.

If you have ideas how to do this properly, i could create PR with changes. Or i can try to solve this this myself, and maybe think of some clever solution.

**Comment by last-partizan** [comment]
I'm started to work on a fix, and i'm trying to understand this part of code:

```ts
export class PythonSettings implements IPythonSettings {
  private workspaceRoot: string;
  ...

  constructor() {
    this.workspaceRoot = workspace.root ? workspace.root : __dirname;
    this.initialize();
  }

  public static getInstance(): PythonSettings {
    const workspaceFolder = workspace.workspaceFolders.length > 0 ? workspace.workspaceFolders[0] : undefined;
    const workspaceFolderUri: Uri | undefined = workspaceFolder ? Uri.parse(workspaceFolder.uri) : undefined;
    const workspaceFolderKey = workspaceFolderUri ? workspaceFolderUri.fsPath : '';

    if (!PythonSettings.pythonSettings.has(workspaceFolderKey)) {
      const settings = new PythonSettings();
      PythonSettings.pythonSettings.set(workspaceFolderKey, settings);
    }
    return PythonSettings.pythonSettings.get(workspaceFolderKey)!;
  }
...

```

`getInstance` is caching settings, based on some key generated from first folder in workspace?

In my case `workspaceFolderKey` is `"."` just dot, current folder. And probably that's not good choice for cache key, but maybe i'm missing something.

Isn't it better to cache settings by workspaceRoot?

But, what i presume, this all is unrelated to this problem, as `workspaceRoot` is independent from this cache key. And looks like it provided by coc.nvim?

**Comment by fannheyward** [comment]
Sorry for the late response, I'll look into this issue in the weekend.

**Comment by fannheyward** [comment]
Sorry for the delay, I've tried some ways to fix this, as you said, the `workspaceRoot` is provided by coc.nvim:

1. `nvim src/app/assets/test.js`, coc will detect the workspace root, use `package.json` as root pattern to find, and  found `src/app` to use, and save `src/app` into a cached `workspaceFolders`
2. `nvim src/app/core/test.py`, coc also will detect the root, this time coc found `src/app/core/test.py` is under `src/app` folder, coc will find it from the cache and use `src/app` as root, without doing resolve again
3. this is the issue, coc uses the _cached_ folder to ignore duplicate resolving, but this may wrong
4. `nvim src/manage.py`, this time coc could find from the cache, coc will do resolving, found `./` as root, this is correct.

I'll look into the coc side to find any way to fix this.

**Comment by last-partizan** [comment]
Thank you.

If you need any assistance, i could try to help.

**Comment by rickyelopez** [comment]
Bump on this, I have a similar problem. I'm working out of a monorepo, and I would like to have a `pyproject.toml` file for a python project that is deep in the repo. I would really like for pyright to be able to find the pyproject file that is in that folder and use that, rather than having to make a pyproject file at the root of the monorepo.

I have
```
    "workspace.workspaceFolderCheckCwd": false,
    "workspace.bottomUpFiletypes": [
        "python"
    ],
```
but pyright is still not able to find the pyproject file that is in the project dir.

**Comment by fannheyward** [comment]
> coc uses the cached folder to ignore duplicate resolving

This has been removed in coc.nvim, always do resolving for document.
