### ISSUE TITLE
error/cant detect match case

### ISSUE THREAD

**Issue by AhmadNaruto** [fannheyward/coc-pyright#691]
**What's the output of `:CocCommand pyright.version`**

coc-pyright 1.1.208 with Pyright 1.1.209

**What's the output of `:CocCommand workspace.showOutput Pyright`**

using Neovim
if python code contain  "match"  case (python 3.10)
its always show error "formating with balck failed" 
not sure  its problem is from pyright or from black.

**Comment by yaegassy** [comment]
@AhmadNaruto Add setting `--target-version py310` to `python.formatting.blackArgs` and try it.

**coc-settings.json**:

```jsonc
{
  "python.formatting.blackArgs": ["--target-version", "py310"],
}
```

**See**:

- <https://github.com/psf/black/issues/2242#issuecomment-974832792>

**Comment by AhmadNaruto** [comment]
> @AhmadNaruto Add setting `--target-version py310` to `python.formatting.blackArgs` and try it.
> 
> **coc-settings.json**:
> 
> ```js
> {
>   "python.formatting.blackArgs": ["--target-version", "py310"],
> }
> ```
> 
> **See**:
> 
> * [Support Python 3.10 pattern matching syntax psf/black#2242 (comment)](https://github.com/psf/black/issues/2242#issuecomment-976101575)

nice... thanks. its work now
