### ISSUE TITLE
rename does not work in file without .py extension

### ISSUE THREAD

**Issue by chuan137** [fannheyward/coc-pyright#702]
I am editing a file without .py extension, but with filetype set in the inline vim settings. And I try to rename a variable: popup window is shown, edit the variable name, and hit enter. Then nothing happens. The variable remains as it was. I guess pyright does not play well with the inline filetype setting

**What's the output of `:CocCommand pyright.version`**
coc-pyright 1.1.215 with Pyright 1.1.217

**What's the output of `:CocCommand workspace.showOutput Pyright`**

**Comment by yaegassy** [comment]
@chuan137 Rename does not work with python files without extensions, which is probably a specification of the pyright's language server itself.

The same behavior is observed when using the pyright extension in VSCode.

If you feel it's a problem, please try to report the issue to pyright itself.

**Comment by chuan137** [comment]
@yaegassy thanks for the reply.  No it's not a big issue. However, imho, it's more a coc-pyright problem than VSCode. VSCode not getting the file type from vim's modeline is quite expected.
