### ISSUE TITLE
Bad order of suggestions

### ISSUE THREAD

**Issue by Rizhiy** [fannheyward/coc-pyright#704]
**What's the output of `:CocCommand pyright.version`**

`[coc.nvim] coc-pyright 1.1.215 with Pyright 1.1.218`

**What's the output of `:CocCommand workspace.showOutput Pyright`**
```
   22 Workspace: /home/rizhiy/projects/sp-earnings
   21 Using python from /home/rizhiy/miniconda3/envs/sp-earnings/bin/python
   20
   19 [Warn  - 3:34:49 AM] disableCompletion in the client options is deprecated. use disabledFeatures instead.
   18
   17     at new Zh (/home/rizhiy/.vim/plugged/coc.nvim/build/index.js:225:28036)
   16     at Object.activate (/home/rizhiy/.config/coc/extensions/node_modules/coc-pyright/lib/index.js:23470:18)
   15 [Warn  - 3:34:49 AM] disableDiagnostics in the client options is deprecated. use disabledFeatures instead.
   14
   13     at new Zh (/home/rizhiy/.vim/plugged/coc.nvim/build/index.js:225:28036)
   12     at Object.activate (/home/rizhiy/.config/coc/extensions/node_modules/coc-pyright/lib/index.js:23470:18)
   11 [Info  - 3:34:50 AM] Pyright language server 1.1.218 starting
   10 [Info  - 3:34:50 AM] Server root directory: /home/rizhiy/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/
    9 [Info  - 3:34:50 AM] No configuration file found.
    8 [Info  - 3:34:50 AM] pyproject.toml file found at /home/rizhiy/projects/sp-earnings.
    7 [Info  - 3:34:50 AM] Setting pythonPath for service "sp-earnings": "/home/rizhiy/miniconda3/envs/sp-earnings/bin/python"
    6 [Info  - 3:34:50 AM] Loading pyproject.toml file at /home/rizhiy/projects/sp-earnings/pyproject.toml
    5 [Error  - 3:34:50 AM] Pyproject file "/home/rizhiy/projects/sp-earnings/pyproject.toml" is missing "[tool.pyright]" section.
    4 [Warn  - 3:34:50 AM] stubPath /home/rizhiy/projects/sp-earnings/typings is not a valid directory.
    3 [Info  - 3:34:50 AM] Assuming Python version 3.9
    2 [Info  - 3:34:50 AM] Assuming Python platform Linux
    1 [Info  - 3:34:50 AM] Searching for source files
  23  [Info  - 3:34:50 AM] Found 663 source files
```

Suggestions produced by coc-pyright seem  to be in a strange order, for example:
![image](https://user-images.githubusercontent.com/5617397/152663730-6017a3e2-fb23-4473-8120-d2cea54e1d28.png)

As you can see `get_raw` which is a public method is after `__init__` and `__setitem__` which are dunder methods.

I would like to have my attributes to be in the following order:
1. Public
2. Private
3. Others

How can I accomplish this?

Extra info:
I tried using [AstroVim](https://github.com/kabinspace/AstroVim) and I believe it also uses `pyright` on the backend.
Suggestions given in its autocompletion are in correct order.

**Comment by fannheyward** [comment]
https://github.com/fannheyward/coc-pyright/pull/695 has improved this, please try v1.1.219.

**Comment by Rizhiy** [comment]
Hi, yes it is much better now. Although sorting once part of the name is given is still broken, e.g.:

![image](https://user-images.githubusercontent.com/5617397/152956897-3feeb6ed-05d0-4fb7-acd4-bd7520bcd437.png)
Here `_wrapped` should really be first one in the list.

![image](https://user-images.githubusercontent.com/5617397/152957149-95af914b-8bd9-4da3-ab40-1dfb43061d78.png)
Here `_set_register_base_class` should probably be ahead of dunder methods.

I will try make it work over the weekend, if no-one fixes it by then.

**Comment by tejasvi** [comment]
`_wrapped` case is due to #649. `_set_register_base_class` is interesting since #695 sorts by the number of leading underscores. For pyright's default ordering just remove below lines. https://github.com/fannheyward/coc-pyright/blob/929c5f69eb234b6037bdcc5d844fd42275ba3ea5/src/index.ts#L131-L133

**Comment by Rizhiy** [comment]
`v1.1.220` seems to work as desired, thank you.
