### ISSUE TITLE
pyright says correct code shows error

### ISSUE THREAD

**Issue by xiang-tao** [fannheyward/coc-pyright#712]
I am using nvim to edit python code, my python code file works fine, but opening the file with nvim shows the following error
```
[Pyright reportGeneralTypeIssues] [E] Operator "*" not supported for types
"Expression" and "Unknown | Inner"
Operator "*" not supported for types "Expression" and "Inner"
```
But my code can run normally and get the correct result, is there any way to make this error message disappear?

**Comment by fannheyward** [comment]
You can disable `reportGeneralTypeIssues` in your coc-settings.json by `python.analysis.diagnosticSeverityOverrides`, or from `pyrightconfig.json` https://github.com/microsoft/pyright/blob/main/docs/configuration.md.
