### ISSUE TITLE
Feature Request - Allow setting things like "python.analysis.extraPaths" in pyproject.toml

### ISSUE THREAD

**Issue by rickyelopez** [fannheyward/coc-pyright#725]
Right now, if I want to set `python.analysis.extraPaths`, I need to do it in `coc-settings.json` or `coc-local-settings.json`, but all the rest of my project settings can be set in `pyproject.toml`.

Would it be possible to add the capability to define settings like these to `pyproject.toml` as well?

**Comment by yaegassy** [comment]
`pyproject.toml` and `pyrightconfig.json` are available. Check the "pyright" documentation for details. <https://github.com/microsoft/pyright/blob/main/docs/configuration.md>

**Comment by rickyelopez** [comment]
`python.analysis.extraPaths` is not an option in pyright, unless I'm missing something?

**Comment by fannheyward** [comment]
Pyright can read configurations from `pyrightconfig.json` or `[tool.pyright]` section in `pyproject.toml`.

`extraPaths` in an option for Pyright, not Pylint.

You can set Pylint args in `[tool.pylint]` section in your `pyproject.toml`.

**Comment by rickyelopez** [comment]
Oh, cool, thanks!
