### ISSUE TITLE
Unique port per workspace for blackd

### ISSUE THREAD

**Issue by lithammer** [fannheyward/coc-pyright#726]
The listen address blackd binds to is currently hardcoded to `127.0.0.1:45484`:

https://github.com/fannheyward/coc-pyright/blob/29025c2681459a01e487b399c511bf557c30b47c/src/formatters/blackd.ts#L28

This means that unless you configure `python.formatting.blackdHTTPURL` a per project basis (which is kind of a hassle), only one instance can run at a time.

It would be nice if picked a random port on a per project basis. However you would still have to ensure they don't conflict (like bookkeep used ports or just retry random ports until it works).

**Comment by fannheyward** [comment]
You can use a single blackd for multiple projects.

**Comment by lithammer** [comment]
Right. But different projects can have different versions of Black. Granted now that Black is no longer in beta, a slight version difference probably won't cause issues.

But I suspect blackd doesn't handle the case when different projects have different configuration (e.g. project A has a line length 80 but project B has 100).

**Comment by lithammer** [comment]
Thanks! 🥳

**Comment by fannheyward** [comment]
This will be available in next release.

**Comment by fannheyward** [comment]
@lithammer v1.1.229 is released, give it a try

**Comment by lithammer** [comment]
Works great! Thank you very much!
