### ISSUE TITLE
UnhandledRejection: request error nvim_call_function - Vim:E117: Unknown function: coc#util#echo_line

### ISSUE THREAD

**Issue by SkyLeachWork** [fannheyward/coc-pyright#727]
## Summary

Error pops up most often when formatting or editing long lines of python code such as static iterables (tuple, list, dictionary)/function arguments (*args)/function keyword arguments (**kwargs) or long lines (stacked generators).  I tend to use syntax-based style editors (gqq or visual-mode '=') to format the long lines at 80c width.

**What's the output of `:CocCommand pyright.version`**

`[coc.nvim] coc-pyright 1.1.223 with Pyright 1.1.225`

**What's the output of `:CocCommand workspace.showOutput Pyright`**
```text

Workspace: c:\Users\mattg\src\***\***
Using python from \Users\mattg\Envs\srs\Scripts\python.exe

[Info  - 12:56:11 PM] Pyright language server 1.1.225 starting
[Info  - 12:56:11 PM] Server root directory: C:\Users\mattg\AppData\Local\coc\extensions\node_modules\coc-pyright\node_modules\pyright/dist/
```

Errors in messages (from first error to restart):

```text
[coc.nvim]: UnhandledRejection: request error nvim_call_function - Vim:E117: Unknown function: coc#util#echo_line
[coc.nvim]: Uncaught exception: process.exit() is not allowed in extension sandbox
client coc abnormal exit with: 7

"~/src/caregility/reporting_lite/srs/api/__init__.py" [unix] 68L, 2076C written
client coc not running.
starting coc.nvim service

```

Note: the stacktrace isn't in messages and I don't know how to bring it back up.

**Comment by SkyLeachWork** [comment]
Just happened again and I grabbed a screenshot (this time it was on a long docstring)

![image](https://user-images.githubusercontent.com/98411760/158032436-2aafa139-1b59-4b0d-88da-50be96f99fe9.png)

**Comment by fannheyward** [comment]
> \Users\mattg AppData\Local\coclextensions\node_modules\coc-python\lib\index.js

You're using `coc-python`, not `coc-pyright`.

**Comment by SkyLeachWork** [comment]
nice catch, I uninstalled coc-python to see if pyright by itself works better.
