### ISSUE TITLE
Format on save with black does not work on FreeBSD

### ISSUE THREAD

**Issue by ivan-volnov** [fannheyward/coc-pyright#738]
Hello,

Format on save feature does not work on FreeBSD.

I suppose it's because of `The feature watch recursively is unavailable on the current platform, which is being used to run Node.js`

Although this config perfectly works on Mac.

Is there any workaround to make it working?

```
{
    "coc.preferences.formatOnSaveFiletypes": [
        "json",
        "python"
    ],
    "coc.preferences.messageLevel": "error",
    "suggest.snippetIndicator": "",
    "suggest.noselect": false,
    "coc.preferences.currentFunctionSymbolAutoUpdate": true,
    "python.pythonPath": "python3",
    "python.formatting.provider": "black",
    "python.linting.pylintEnabled": false,
    "python.linting.flake8Enabled": true,
    "python.linting.flake8Args": [
        "--ignore=E501"
    ]
}
```

```
❯ black --version
black, 22.1.0 (compiled: no)
```

```
:CocCommand workspace.showOutput coc-pyright-formatting
Using python from /usr/local/bin/python3

########## active formattor: black
execPath:   black
moduleName: black
args:       --diff,--quiet,/path/to/the/file.py.5c8659fd677c6db9b43d8c8a093c4ebf.py
########## black formatting action is canceled.
```

**What's the output of `:CocCommand pyright.version`**

nothing prints

but :CocUpdate says:
`- ✓ coc-pyright Current version 1.1.232 is up to date.`

**What's the output of `:CocCommand workspace.showOutput Pyright`**
```
Workspace: /path/to/the/file
Using python from /usr/local/bin/python3

[Info  - 9:57:12 PM] Pyright language server 1.1.235 starting
[Info  - 9:57:12 PM] Server root directory: <HOME>/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/
[Info  - 9:57:12 PM] No configuration file found.
[Info  - 9:57:12 PM] No pyproject.toml file found.
[Info  - 9:57:12 PM] Setting pythonPath for service "python": "/usr/local/bin/python3"
[Warn  - 9:57:12 PM] stubPath /path/to/the/file/typings is not a valid directory.
[Info  - 9:57:12 PM] Assuming Python version 3.8
[Warn  - 9:57:12 PM] Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Warn  - 9:57:12 PM] Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Warn  - 9:57:12 PM] Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Info  - 9:57:12 PM] Searching for source files
[Info  - 9:57:12 PM] Found 6 source files

```

**Comment by fannheyward** [comment]
Does `:call CocAction('format')` work for your?

From the first logs, `black formatting action is canceled.`, coc will cancel the formatting action in 500ms by default, increase `coc.preferences.willSaveHandlerTimeout` and try again.

**Comment by ivan-volnov** [comment]
@fannheyward Thanks for the answer!

Yes, `:call CocAction('format')` works.

Tried to set `coc.preferences.willSaveHandlerTimeout` to 5000. No luck(

**Comment by fannheyward** [comment]
@ivan-volnov try v1.1.235, I've added more logs in `:CocCommand workspace.showOutput coc-pyright-formatting`.

**Comment by ivan-volnov** [comment]
Ok, done. Looks ok, but still no formatting on save

```
Using python from /usr/local/bin/python3

########## active formattor: black
execPath:   black
moduleName: black
args:       --diff,--quiet,/path/to/the/file.5c8659fd677c6db9b43d8c8a093c4ebf.py

########## black output:

<here is a valid black output diff, I have cut>

########## black formatting action is canceled on success

```

**Comment by fannheyward** [comment]
The formatting steps:

1. coc.nvim sends a formatting request, from `:call CocAction('format')` or on-save event
2. coc-pyright runs black to do formatting, parses the result and returns to coc.nvim
3. coc.nvim applies the changes to document.

From your logs, you've got the black diff result, this means the black did finished formatting. But at this time, a cancel formatting request came, coc-pyright won't return the diff result to coc.nvim to apply.

I can't reproduce this in my tests, try minimal vimrc, just coc.nvim + coc-pyright only.
