### ISSUE TITLE
not autocompleting dlib library

### ISSUE THREAD

**Issue by randallwc** [fannheyward/coc-pyright#739]
**What's the output of `:CocCommand pyright.version`**
```
[coc.nvim] coc-pyright 1.1.231 with Pyright 1.1.232
```

**What's the output of `:CocCommand workspace.showOutput Pyright`**
```
Workspace: /Users/william/Downloads
Using python from /opt/homebrew/Caskroom/miniconda/base/bin/python
```

Specs:

- Mac M1 Pro
- Dlib installed with conda (also tried pip3 and it gave the same results)
- vscode and coc.nvim using pyright (both using the same language server)
- python 3.9.12

```python
import dlib
dlib.get_frontal_face_detector()
```

Currently, when I run the above script with python, **it works** with no hiccups, but when I try to autocomplete the modules of dlib in vim **it will not autocomplete** the modules of `dlib`.

[link to my StackOverflow question about the same issue](https://stackoverflow.com/questions/71811674/pyright-not-autocompleting-dlib-for-python)

**Comment by fannheyward** [comment]
Does the autocompletion work on VS Code + Pyright? It's Pyright's issue, coc-pyright can do nothing about this.
