### ISSUE TITLE
Error description is blank 

### ISSUE THREAD

**Issue by MakonnenMak** [fannheyward/coc-pyright#740]
Similar to the example in the readme. How can I debug further? 
![image](https://user-images.githubusercontent.com/25201013/164357881-09eb8361-a25d-453e-a25b-f8a143a6c1d6.png)

**Comment by fannheyward** [comment]
Try minimal vimrc, looks like it's colorscheme related.

**Comment by MakonnenMak** [comment]
Oh brother , you're right. I just saw the darker red on my phone when pulling up this issue, was nearly impossible on my monitor. Closing this, ty!
