### ISSUE TITLE
[Question] How did you get that speed with find references?

### ISSUE THREAD

**Issue by amaksymov** [fannheyward/coc-pyright#763]
Thanks for your work, extension is awesome!
But I have question, how you get it?
I working on a large codebase and use [AstroNvim](https://github.com/AstroNvim/AstroNvim)(before I created my own config, but astro has all it in the box) but i had a problem with references search speed, I installed pyright with vim-lsp-installer, and but search speed was low. 
How does this extension work faster?

**Comment by fannheyward** [comment]
It's Pyright and coc.nvim's power.
