### ISSUE TITLE
Text-objects do not include last line

### ISSUE THREAD

**Issue by sabah-AB** [fannheyward/coc-pyright#765]
**What's the output of `:CocCommand pyright.version`**

coc-pyright 1.1.253 with Pyright 1.1.253

**What's the output of `:CocCommand workspace.showOutput Pyright`**

Workspace: /Users/sabah/Desktop/test
Using python from /Users/sabah/Desktop/test/venv/bin/python

[Info  - 12:18:12] Pyright language server 1.1.253 starting
[Info  - 12:18:12] Server root directory: /Users/sabah/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/
[Info  - 12:18:12] No configuration file found.
[Info  - 12:18:12] No pyproject.toml file found.
[Info  - 12:18:12] Setting pythonPath for service "test": "/Users/sabah/Desktop/test/venv/bin/python"
[Warn  - 12:18:12] stubPath /Users/sabah/Desktop/test/typings is not a valid directory.
[Info  - 12:18:12] Assuming Python version 3.7
[Info  - 12:18:12] Assuming Python platform Darwin
[Info  - 12:18:12] Searching for source files
[Info  - 12:18:12] Auto-excluding /Users/sabah/Desktop/test/venv
[Info  - 12:18:12] Found 1 source file

Function and Class inner text-objects do not include last line.

![Screenshot 2022-06-10 at 12 21 06](https://user-images.githubusercontent.com/105719608/173054703-5783b1e1-d2e3-4c94-87f0-96bd5ec0916d.png)

**Comment by fannheyward** [comment]
Reproduced.

**Comment by fannheyward** [comment]
Related https://github.com/neoclide/coc.nvim/issues/1847
