### ISSUE TITLE
How to use `python.venvPath` for Pipenv support

### ISSUE THREAD

**Issue by dr-costas** [fannheyward/coc-pyright#767]
**What's the output of `:CocCommand pyright.version`**
`[coc.nvim] coc-pyroght 1.1.255 with Pyright 1.1.255

Hi, 

I saw the argument `python.venvPath` and I'm wondering how I can use it for activating Pipenv venvs with Pyright. Or, how can I use that argument? 

For example, if I use the root dir of the vens dir from Pipenv, then Pyright will scan all created venvs? Or do I have to use the root dir of the current venv?

Thnx!

**Comment by fannheyward** [comment]
You didn't need to set `python.venvPath`, just `activate` the venv for your project, then vim your Python files.

**Comment by dr-costas** [comment]
Great! Thank you,

**Comment by dr-costas** [comment]
Hi, 

Sorry for bringing up this again. I have install coc-pyright but it seems that the venv is not taken into account by Vim. I activate the venv (which is at the `.venv` dir in the project) but inside Vim the Python command is not the one from the venv.

**Comment by fannheyward** [comment]
Check `:CocCommand workspace.showOutput Pyright` to make sure you're using the correct Python for your project.

**Comment by dr-costas** [comment]
This command gives me nothing as an output.

**Comment by fannheyward** [comment]
Open your Python files, then run `:CocCommand workspace.showOutput Pyright`.

**Comment by dr-costas** [comment]
@fannheyward 

Yes, the proper Python executable is **not** used. Any help on that?

**Comment by oblitum** [comment]
@dr-costas I don't use or need [this setting](https://codeberg.org/oblitum/dotfiles/commit/35ea46641251bece27a64980cad2dbddbb34fbda) anymore, but it may be useful for you: https://github.com/fannheyward/coc-pyright/issues/67#issuecomment-670286861.

**Comment by fannheyward** [comment]
@dr-costas coc-pyright will try to detect the Python in your project from `.venv` to use, maybe it failed. You can `activate` the correct Python before open vim.
