### ISSUE TITLE
Disable organizing and sorting imports.

### ISSUE THREAD

**Issue by mahdikooshkbaghi** [fannheyward/coc-pyright#777]
Hi all,
I want to disable both sorting and organizing imports. Can you give the corresponding options I need to put in `coc-setting.json` file.
Thanks.

**What's the output of `:CocCommand pyright.version`**
`[coc.nvim] coc-pyright 1.1.255 with Pyright 1.1.256`

**Comment by fannheyward** [comment]
By default, coc-pyright won't do sorting and organizing imports. How to reproduce your issue?

**Comment by mahdikooshkbaghi** [comment]
> By default, coc-pyright won't do sorting and organizing imports. How to reproduce your issue?

Thanks. That's true. I have a format on save in my `.vimrc` which seems do all the `autopep8` formatting when I save my `.py` file.
Here is the format on save part of my .vimrc, using the plugin `'sbdchd/neoformat'`

```
" Auto-format on save
augroup fmt
  autocmd!
  autocmd BufWritePre *.py undojoin | Neoformat
augroup END
```
