### ISSUE TITLE
add some arguments with flake8

### ISSUE THREAD

**Issue by liuyug** [fannheyward/coc-pyright#778]
such as:
flake8_args = "--ignore=E128,E402,E501,F401,C901"

How do I config it?

**Comment by yaegassy** [comment]
Set `python.linting.flake8Args` in `coc-settings.json`. REF: <https://github.com/fannheyward/coc-pyright/blob/master/package.json#L861-L869>

**Example**:

```
{
  // ...snip
  "python.linting.flake8Args": [
    "--ignore",
    "E128",
    "E402",
    "E501",
    "F401",
    "C901"
  ],
  // ...snip
}
```

Or you can have a flake8 config file (`setup.cfg`, `tox.ini`, or `.flake8`)in your project root. coc-pyright respects the flake8 config file.
