### ISSUE TITLE
Loading bar pop up every time I make a modification

### ISSUE THREAD

**Issue by liamattard** [fannheyward/coc-pyright#779]
**What's the output of `:CocCommand pyright.version`**

[coc.nvim] coc-pyright 1.1.262 with Pyright 1.1.263

**What's the output of `:CocCommand workspace.showOutput Pyright`**

Workspace: /home/liamattard/Documents/Masters/torch-med-rec-sys
Using python from /home/liamattard/miniconda3/envs/medRecSys/bin/python

[Info  - 15:41:46] Pyright language server 1.1.263 starting
[Info  - 15:41:46] Server root directory: /home/liamattard/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/
[Info  - 15:41:46] Starting service instance "torch-med-rec-sys"
[Info  - 15:41:46] No configuration file found.
[Info  - 15:41:46] No pyproject.toml file found.
[Info  - 15:41:46] Setting pythonPath for service "torch-med-rec-sys": "/home/liamattard/miniconda3/envs/medRecSys/bin/python"
[Warn  - 15:41:46] stubPath /home/liamattard/Documents/Masters/torch-med-rec-sys/typings is not a valid directory.
[Info  - 15:41:46] Assuming Python version 3.9
[Info  - 15:41:46] Assuming Python platform Linux
[Info  - 15:41:46] Searching for source files
[Info  - 15:41:46] Found 13 source files
[Info  - 15:41:48] [FG] Long operation: analyzing: /home/liamattard/Documents/Masters/torch-med-rec-sys/src/data_handler/modelDataBuilder.py (2187ms)

### Issue

Every time I make a slight change to a python file, I get the following loading bar on the screen. Most of the time, the bar is on the text that I am typing, making it difficult to see what I am typing. This lasts around a second every time I type a word sometimes it contains the text 1 file to analyse, sometimes it merges with the text beneath it, and sometimes it contains no text at all. 

![image](https://user-images.githubusercontent.com/21961804/180651502-d000c919-051f-431c-baf2-0a247c2936f8.png)

![image](https://user-images.githubusercontent.com/21961804/180651507-890a5bd1-cc8f-4453-92c0-44d4bcfee307.png)

![image](https://user-images.githubusercontent.com/21961804/180651353-bae46eb5-2482-4722-944a-24879adcbb31.png)

**Comment by fannheyward** [comment]
You can disable it with `pyright.disableProgressNotifications`.
