### ISSUE TITLE
coc-pyright shows error that CLI pyright does not

### ISSUE THREAD

**Issue by meangrape** [fannheyward/coc-pyright#780]
**What's the output of `:CocCommand pyright.version`**
coc-pyright 1.1.260 with Pyright 1.1.262

**What's the output of `:CocCommand workspace.showOutput Pyright`**
```python
Workspace: /Users/jayed/repos/create_cluster
Using python from /Users/jayed/Library/Caches/pypoetry/virtualenvs/create-cluster-PmxHvHbg-py3.10/bin/python

[Info  - 1:45:55 PM] Pyright language server 1.1.262 starting
[Info  - 1:45:55 PM] Server root directory: /Users/jayed/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/
[Info  - 1:45:55 PM] Setting pythonPath for service "create_cluster": "/Users/jayed/Library/Caches/pypoetry/virtualenvs/create-cluster-PmxHvHbg-py3.10/bin/python"
[Info  - 1:45:55 PM] Loading configuration file at /Users/jayed/repos/create_cluster/pyrightconfig.json
[Info  - 1:45:55 PM] Assuming Python version 3.10
[Info  - 1:45:55 PM] Assuming Python platform Darwin
[Info  - 1:45:55 PM] No include entries specified; assuming /Users/jayed/repos/create_cluster
[Info  - 1:45:55 PM] Auto-excluding **/node_modules
[Info  - 1:45:55 PM] Auto-excluding **/__pycache__
[Info  - 1:45:55 PM] Auto-excluding **/.*
[Warn  - 1:45:55 PM] The venvPath has been specified in both the config file and the client settings. The value in the config file (/Users/jayed/Library/Caches/pypoetry/virtualenvs) will take precedence
[Warn  - 1:45:55 PM] stubPath /Users/jayed/repos/create_cluster/typings is not a valid directory.
[Info  - 1:45:55 PM] Searching for source files
[Info  - 1:45:55 PM] Found 7 source files
[Info  - 1:45:57 PM] [FG] Long operation: checking: /Users/jayed/repos/create_cluster/src/create_cluster.py (2248ms)
[Info  - 1:45:57 PM] [FG] Long operation: analyzing: /Users/jayed/repos/create_cluster/src/create_cluster.py (2330ms)
[Info  - 1:46:24 PM] [FG] Long operation: checking: /Users/jayed/repos/create_cluster/src/create_cluster.py (2191ms)
[Info  - 1:46:24 PM] [FG] Long operation: analyzing: /Users/jayed/repos/create_cluster/src/create_cluster.py (2262ms)
```

**code**
```python
from google.iam.v1 import iam_policy_pb2
request = iam_policy_pb2.GetIamPolicyRequest()
request.resource = f"projects/{project}"
```

**error**
```
[Pyright reportGeneralTypeIssues] [E] Cannot assign member "resource" for
return policy  type "GetIamPolicyRequest"
Member "resource" is unknown
```

**coc-settings**
```json
      "pyright.disableCompletion": true,
      "pyright.enable": true,
      "python.formatting.blackPath": "black",
      "python.formatting.provider": "black",
      "python.linting.enabled": true,
      "python.linting.mypyEnabled": true,
      "python.linting.pylintEnabled": true,
      "python.linting.pydocstyleEnabled": true,
      "python.linting.banditEnabled": false,
      "python.linting.flake8Enabled": false,
      "python.linting.prospectorEnabled": false,
      "python.linting.pycodestyleEnabled": false,
      "python.linting.pylamaEnabled": false,
      "python.linting.pytypeEnabled": false,
      "python.venvPath": "/Users/jayed/Library/Caches/pypoetry/virtualenvs",
```

**pyrightconfig.json**
```json
{
  "venvPath": "/Users/jayed/Library/Caches/pypoetry/virtualenvs",
  "venv": "create-cluster-PmxHvHbg-py3.10"
}
```

As we can see above, `coc-pyright` detects a general type error that `pyright` does not. My assumption is there might be an issue with finding the correct virtual env; however, both are using the same venvPath from the config file so I'm not sure how that would be the case. I have dozens of these errors.

**Comment by meangrape** [comment]
**pyright --verbose**
```python
Loading configuration file at /Users/jayed/repos/create_cluster/pyrightconfig.json
Assuming Python version 3.10
Assuming Python platform Darwin
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding **/.*
stubPath /Users/jayed/repos/create_cluster/typings is not a valid directory.
Search paths for /Users/jayed/repos/create_cluster
  /Users/jayed/.npm/_npx/6f75558c21262cab/node_modules/pyright/dist/typeshed-fallback/stdlib
  /Users/jayed/repos/create_cluster
  /Users/jayed/repos/create_cluster/typings
  /Users/jayed/.npm/_npx/6f75558c21262cab/node_modules/pyright/dist/typeshed-fallback/stubs/...
  /Users/jayed/Library/Caches/pypoetry/virtualenvs/create-cluster-PmxHvHbg-py3.10/lib/python3.10/site-packages
  /Users/jayed/repos/create_cluster
Searching for source files
Found 1 source file
pyright 1.1.263
/Users/jayed/repos/create_cluster/src/create_cluster.py
  /Users/jayed/repos/create_cluster/src/create_cluster.py:328:22 - error: Could not access item in TypedDict
    "name" is not a required key in "ServiceAccount", so access may result in runtime exception (reportTypedDictNotRequiredAccess)
  /Users/jayed/repos/create_cluster/src/create_cluster.py:331:13 - error: Could not access item in TypedDict
    "privateKeyData" is not a required key in "ServiceAccountKey", so access may result in runtime exception (reportTypedDictNotRequiredAccess)
  /Users/jayed/repos/create_cluster/src/create_cluster.py:336:28 - error: Could not access item in TypedDict
    "name" is not a required key in "ServiceAccount", so access may result in runtime exception (reportTypedDictNotRequiredAccess)
3 errors, 0 warnings, 0 informations
Completed in 2.175sec
```

**Comment by fannheyward** [comment]
Reinstall coc-pyright, `:CocUninstall coc-pyright` and `:CocInstall coc-pyright`, this will install Pyright 1.1.263, and try again.

**Comment by fannheyward** [comment]
<img width="552" alt="截屏2022-07-26 16 08 26" src="https://user-images.githubusercontent.com/345274/180956509-50092d81-1a67-4e12-bedf-9552e617de5a.png">

I think it's Pyright's issue, tested with Pylance, same error reported.

**Comment by meangrape** [comment]
Upgrading `coc-pyright` to the latest version with pyright `1.1.263` seems to have fixed that.

Here's another example that shows an error in `coc-pyright` but not in pylance or the cli.

**code**
```python
from google.cloud import kms_v1
request = kms_v1.CreateKeyRingRequest()
request.parent = "test"
request.key_ring_id = "test"
request.key_ring = kms_v1.KeyRing()
```

<img width="438" alt="Screen Shot 2022-07-26 at 10 13 32 AM" src="https://user-images.githubusercontent.com/9083/181027570-31a41108-9ff9-431e-af6e-95a9be2188c5.png">

<img width="1124" alt="Screen Shot 2022-07-26 at 10 13 00 AM" src="https://user-images.githubusercontent.com/9083/181027447-223a3147-433f-4bbb-943f-17aae6bc8005.png">

**pyright output**
Loading configuration file at /Users/jayed/repos/create_cluster/pyrightconfig.json
Assuming Python version 3.10
Assuming Python platform Darwin
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding **/.*
stubPath /Users/jayed/repos/create_cluster/typings is not a valid directory.
Searching for source files
Found 1 source file
pyright 1.1.263
/Users/jayed/repos/create_cluster/src/create_cluster.py
  /Users/jayed/repos/create_cluster/src/create_cluster.py:328:22 - error: Could not access item in TypedDict
    "name" is not a required key in "ServiceAccount", so access may result in runtime exception (reportTypedDictNotRequiredAccess)
  /Users/jayed/repos/create_cluster/src/create_cluster.py:331:13 - error: Could not access item in TypedDict
    "privateKeyData" is not a required key in "ServiceAccountKey", so access may result in runtime exception (reportTypedDictNotRequiredAccess)
  /Users/jayed/repos/create_cluster/src/create_cluster.py:336:28 - error: Could not access item in TypedDict
    "name" is not a required key in "ServiceAccount", so access may result in runtime exception (reportTypedDictNotRequiredAccess)
3 errors, 0 warnings, 0 informations
Completed in 2.082sec

**Comment by meangrape** [comment]
nvm that last comment. It was a pylance setting that stopped it from appearing. Thanks for all your help! Thanks for coc-pyright!
