### ISSUE TITLE
Autoimport usability improvements (suggestion ordering, auto-aliases)

### ISSUE THREAD

**Issue by Kache** [fannheyward/coc-pyright#789]
**What's the output of `:CocCommand pyright.version`** `[coc.nvim] coc-pyright 1.1.260 with Pyright 1.1.260`

**What's the output of `:CocCommand workspace.showOutput Pyright`**

```
Workspace: /Users/kevincheng/carrot/customers/airflow-task-runners/customers-airflow-task-runner-acquisition
Using python from /Users/kevincheng/carrot/customers/airflow-task-runners/customers-airflow-task-runner-acquisition/.venv/bin/python

[Info  - 1:23:41 PM] Pyright language server 1.1.260 starting
[Info  - 1:23:41 PM] Server root directory: /<REDACTED_VIM_DIR>/plugged/coc-pyright/node_modules/pyright/dist/
[Info  - 1:23:41 PM] No configuration file found.
[Info  - 1:23:41 PM] pyproject.toml file found at <REDACTED_PROJ_ROOT>.
[Info  - 1:23:41 PM] Setting pythonPath for service "<REDACTED_PROJ_NAME>": "<REDACTED_PROJ_ROOT>/.venv/bin/python"
[Info  - 1:23:41 PM] Loading pyproject.toml file at <REDACTED_PROJ_ROOT>/pyproject.toml
[Info  - 1:23:41 PM] Assuming Python version 3.7
[Info  - 1:23:41 PM] Assuming Python platform Darwin
[Info  - 1:23:41 PM] No include entries specified; assuming <REDACTED_PROJ_ROOT>
[Info  - 1:23:41 PM] Auto-excluding **/node_modules
[Info  - 1:23:41 PM] Auto-excluding **/__pycache__
[Info  - 1:23:41 PM] Auto-excluding **/.*
[Warn  - 1:23:41 PM] stubPath <REDACTED_PROJ_ROOT>/typings is not a valid directory.
[Info  - 1:23:41 PM] Searching for source files
[Info  - 1:23:41 PM] Found 262 source files
[Info  - 1:23:43 PM] [FG] Long operation: analyzing: <REDACTED_PROJ_ROOT>/<PATH_TO_PY_FILE> (2234ms)
```

### Auto-import suggestion ordering

Ordering is inconsistent. First popup:

<img width="296" alt="image" src="https://user-images.githubusercontent.com/133218/182190097-7ff3c4d5-5132-444a-a345-7f67d71ad735.png">

Then immediately trigger auto-import suggestion again:

<img width="293" alt="image" src="https://user-images.githubusercontent.com/133218/182190169-f60a4faf-725f-4151-84f4-6510138a9d85.png">

I think some ordering consistency would be nice -- perhaps by natural sort to bring stdlib imports to the top? This would be especially helpful when the suggestion list is long.

### Auto import aliasing

Would like to have auto-import make suggestions for import aliases, e.g.:

| Alias | import |
| --- | --- |
| it | import itertools as it |
| ft | import functools as ft |
| np | import numpy as np |

I wouldn't mind manually defining such a mapping table just once in configuration, in order to support custom aliases for internal modules as well. Defining popular aliases for popular/stdlib modules by default would just be a bonus.

**Comment by fannheyward** [comment]
> auto-import suggestion ordering

The ordering is came from Pyright

auto-import aliasing

You can use `snippet` to define this.

**Comment by Kache** [comment]
FYI for any future readers, it is indeed possible to auto-aliased-import via snippet functionality, but it takes a bit of doing.

I managed to accomplish it via Ultisnips + coc-ultisnips, with a custom snippet like:

```snippet
global !p
def upsert_import(impt):
    # bunch of code adapted from https://github.com/SirVer/ultisnips/issues/635#issuecomment-170956110
endglobal

pre_expand "upsert_import('functools as ft')"
snippet ft "Auto-import functools"
ft
endsnippet
```
