### ISSUE TITLE
code is unreachable

### ISSUE THREAD

**Issue by r4vanan** [fannheyward/coc-pyright#791]
my coc-pyright updated to latest version but it showing like this error and in grey color
![2022-08-05-213752_1366x768_scrot](https://user-images.githubusercontent.com/35825039/183117519-033e94cf-078c-4e6e-bfa6-485270bac8f5.png)

**Comment by fannheyward** [comment]
Pyright reported your code is unreachable, which means these three lines code won't run, coc marked them gray.
