### ISSUE TITLE
How to config pyright and python-language-server

### ISSUE THREAD

**Issue by YuCao16** [fannheyward/coc-pyright#792]
Hi,

I'm using the latest `coc-pyright`, and at the same time, I also use `python-language-server`, and my config for `python-language-server` is [here](https://github.com/neoclide/coc.nvim/wiki/Language-servers#python:~:text=//%20be%20careful%20not,%7D%0A%20%20%7D%0A%7D)
I've noticed that sometimes the `pyright` documents are displayed not too useful, highlight and variable type hint are great features. For example:
`pyright`:
![iShot_2022-08-05_22 49 58](https://user-images.githubusercontent.com/62466929/183253668-8e2c2fa0-9ec6-48b8-8a53-4d8507482224.jpg)
`python-language-server`:
![iShot_2022-08-05_22 50 09](https://user-images.githubusercontent.com/62466929/183253684-24d7ac7d-5832-4795-8504-71791363808d.jpg)
1. python-language-server has not been updated for a long time. I would like to use just `coc-pyright` plugin, so does `coc-pyright` has any plans to improve the document display?
2. And I don't know why, but the documentation from `python-language-server` doesn't always appear. Sometimes the same code  only the documentation from `pyright` will appear. How can I debug it or, how can I fix it?

**Comment by fannheyward** [comment]
> does coc-pyright has any plans to improve the document display

The documentation is came from Pyright, you need to ask Pyright to improve the document

> documentation from python-language-server doesn't always appear

Have no idea about this.
