### ISSUE TITLE
Is there an option to disable definitionhover from pyright?

### ISSUE THREAD

**Issue by YuCao16** [fannheyward/coc-pyright#793]
I'm using `coc-pyright` and `coc-jedi` at the same time.
<img width="956" alt="image" src="https://user-images.githubusercontent.com/62466929/183313827-7b5c7693-976e-43fb-a8cd-a08799447c71.png">
Now the document from `cocAction('doHover')` is duplicated, I think the first one the from `coc-pyright` and the second one from `coc-jedi`.  They are pretty much the same, but `coc-jedi's` document is more readable.

**Comment by fannheyward** [comment]
You can use `pyright.disableDocumentation` to disable document form Pyright.
