### ISSUE TITLE
I can't get linting to run at all

### ISSUE THREAD

**Issue by ipsod** [fannheyward/coc-pyright#794]
Running `:CocCommand python.runLinting` seems to do nothing.  I tried it with a minimal config (fresh vimrc with only coc.nvim recommended lines) with the same result.

Auto-completion, go-to-definition, etc., are all working well, though.

**relevant config?**
    "python.linting.enabled": true,
    "python.linting.pylintEnabled": true,
    "python.linting.flake8Enabled": true,
    "python.linting.pylintUseMinimalCheckers": false,

**What's the output of `:CocCommand pyright.version`**
[coc.nvim] coc-pyright 1.1.266 with Pyright 1.1.267

**What's the output of `:CocCommand workspace.showOutput Pyright`**
Workspace: /home/zero/rockbox/gk/robots/myFluidNC
Using python from /home/zero/.virtualenvs/image_w/bin/python

[Info  - 9:07:31 AM] Pyright language server 1.1.267 starting
[Info  - 9:07:31 AM] Server root directory: /home/zero/rockbox/dot/config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/
[Info  - 9:07:31 AM] Starting service instance "myFluidNC"
[Info  - 9:07:31 AM] No configuration file found.
[Info  - 9:07:31 AM] No pyproject.toml file found.
[Info  - 9:07:31 AM] Setting pythonPath for service "myFluidNC": "/home/zero/.virtualenvs/image_w/bin/python"
[Warn  - 9:07:31 AM] stubPath /home/zero/rockbox/gk/robots/myFluidNC/typings is not a valid directory.
[Info  - 9:07:31 AM] Assuming Python version 3.9
[Info  - 9:07:31 AM] Assuming Python platform Linux
[Info  - 9:07:31 AM] Searching for source files
[Info  - 9:07:31 AM] Found 106 source files

**Comment by fannheyward** [comment]
Do you have `pylint` and `flake8` installed?

**Comment by ipsod** [comment]
No, they weren't.  That fixed it.  Thank you!

**Comment by ipsod** [comment]
Oops.  It still isn't fixed.  I had Syntastic running, and it was doing linting.  I disabled that, and am still getting no linting from coc-pyright.  Tried again with a minimal config, and still no luck.

**Comment by ipsod** [comment]
nevermind - removed some lines from my Coc config and it works.
