### ISSUE TITLE
Refactor/Rename snake_case variables bug

### ISSUE THREAD

**Issue by 3ddiddE** [fannheyward/coc-pyright#795]
**What's the output of `:CocCommand pyright.version`**
coc-pyright 1.1.266 with Pyright 1.1.266

**What's the output of `:CocCommand workspace.showOutput Pyright`**
[Info  - 4:00:15 PM] Pyright language server 1.1.266 starting
[Info  - 4:00:15 PM] Server root directory: /home/user/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/
[Info  - 4:00:15 PM] Starting service instance "camera_calibration"
[Info  - 4:00:15 PM] No configuration file found.
[Info  - 4:00:15 PM] No pyproject.toml file found.
[Info  - 4:00:15 PM] Setting pythonPath for service "camera_calibration": "/home/user/.local/share/virtualenvs/camera_calibration-Ev9BhSTv/bin/python"
[Warn  - 4:00:15 PM] stubPath /home/user/camera_calibration/typings is not a valid directory.
[Info  - 4:00:15 PM] Unable to get Python version from interpreter
[Info  - 4:00:15 PM] Assuming Python platform Linux
[Info  - 4:00:15 PM] Searching for source files
[Info  - 4:00:15 PM] Found 1 source file

When I want to replace/rename/refactor a snake_case variable via `ciw`, it will not work with coc-refactor.
coc-rename is working, but obviously would not allow me to use commands like `ciw` to replace the whole variable.
Replacing within coc-refactor works flawlessly (e.g. by `R` or `r`)

**Comment by 3ddiddE** [comment]
This behavior also seems to be the case with camelCase variables

**Comment by fannheyward** [comment]
Can you post an example code to reproduce this issue? In my tests, `coc-refactor` works with `ciw` on snake_case var.

**Comment by 3ddiddE** [comment]
Well... that is strange. Now the issue seems to be resolved
now with coc-pyright and Pyright: 1.1.269
