### ISSUE TITLE
weird "&nbsp;" characters in help definition popup menu

### ISSUE THREAD

**Issue by ow0x** [fannheyward/coc-pyright#796]
**What's the output of `:CocCommand pyright.version`**
![image](https://user-images.githubusercontent.com/24418520/186223759-cfaf115e-2fab-45d3-a41a-6504542ff4cf.png)

**What's the output of `:CocCommand workspace.showOutput Pyright`**
![image](https://user-images.githubusercontent.com/24418520/186224807-837e1d4c-1826-4b3b-9832-64c988fe1531.png)

----------------------------------

Hi,

I am seeing these weird `&nbsp;` characters/entities since a while when vim offers the helpdoc popup menu for properties/functions/methods/classes etc. (not sure what the proper term for this is, apologies 😅  )
![image](https://user-images.githubusercontent.com/24418520/186223194-d72714f4-90da-4e64-9b75-4cc94e5d926b.png)

I searched for this on internet first and came across very old issue and could not find any other sources:
https://github.com/microsoft/python-language-server/issues/422

I am not sure if coc-pyright causes this; though I doubt it but I did not know where to seek help for this. Sincere apologies if this issue doesnt belong in this repo. Thank you for your valuable time. I would be grateful if you can guide or educate me in right direction to solve this issue.

**Comment by fannheyward** [comment]
<img width="698" alt="截屏2022-08-25 10 35 34" src="https://user-images.githubusercontent.com/345274/186561200-144e312a-b5fb-4c2c-80a8-7dd6e90afff0.png">

Pyright returns docs with `&nbsp;`, coc-pyright will replace `&nbsp;` to `' '`, have no idea why your docs can't be replaced. Can you post a code example?

**Comment by fannheyward** [comment]
Reproduced. The first is hover doc, the second is help signature. Will check it ASAP.

**Comment by fannheyward** [comment]
Fixed, will be available in next release.

**Comment by fannheyward** [comment]
Released in v1.1.269
