### ISSUE TITLE
Where the stub file generated?

### ISSUE THREAD

**Issue by fred214** [fannheyward/coc-pyright#798]
Hi,
I used command to generated stub files:
```
:CocCommand pyright.createtypestub kubernetes
```
The effect is not very good, then I found https://github.com/MaterializeInc/kubernetes-stubs
When I install it, I found completion still show "This type stub file was generated by pyright", even I reinstall the coc-pyright.
where the stub file generated? or can provider a command to clean the generated stub file?
Thanks a lot

**Comment by fannheyward** [comment]
It's `typings` folder in your project root.
