### ISSUE TITLE
workspaceSymbols

### ISSUE THREAD

**Issue by fdschmidt93** [fannheyward/coc-pyright#80]
Hi!

Pyright added support for workspaceSymbols (e.g. CocList symbols), though only "outline" is available from within coc. Otherwise I find that coc-pyright already quite suitably can replace coc-python, especially since the LSP starts a lot faster :)

Many thanks for your work on the plugin and consideration!

**Comment by fannheyward** [comment]
`CocList symbols` works in INTERACTIVE mode, you need to input your search query.

**Comment by fdschmidt93** [comment]
Okay thank you, seems like interactive mode does not work out of the box with coc-fzf, I'll see if there is a fitting workaround for me.
