### ISSUE TITLE
Code formating

### ISSUE THREAD

**Issue by Maswor** [fannheyward/coc-pyright#81]
`coc-pyright` at the moment doesn't support formatting. From what I understand, `pyright` itself doesn't support formatting, but `pylance` does using `vscode-python`. Maybe you can take a look and see if it's possible to implement the functionality in `coc-pyright`. Thank you!

**Comment by eelkeh** [comment]
Also looking for this! What's the recommend setup right now if you need to use a formatter (i.e. Black) ?

**Comment by Maswor** [comment]
If I can use `Pylint`, it would be great!

**Comment by jaapz** [comment]
> Also looking for this! What's the recommend setup right now if you need to use a formatter (i.e. Black) ?

If you use black, I recommend you install the official Black vim plugin https://github.com/psf/black/blob/master/docs/editor_integration.md#vim

**Comment by bbkane** [comment]
It looks like the official black plugin doesn't support NeoVim - installing it and running `:Black` results in:

```
![image](https://user-images.githubusercontent.com/6081085/92957219-0a2a6180-f41d-11ea-8154-5fb1bac3cd41.png)
```

**Comment by bbkane** [comment]
Ooh, It looks like Ale can do it: https://www.vimfromscratch.com/articles/vim-for-python/

```
let g:ale_fixers = {
      \    'python': ['black'],
      \}
nmap <F10> :ALEFix<CR>
let g:ale_fix_on_save = 1
```

^ works for me

**Comment by GertBurger** [comment]
> It looks like the official black plugin doesn't support NeoVim - installing it and running `:Black` results in:
> 
> ```
> The black.vim plugin requires vim7.0+ with Python 3.6 support.
> ```
> 
> ![image](https://user-images.githubusercontent.com/6081085/92957219-0a2a6180-f41d-11ea-8154-5fb1bac3cd41.png)
> 
> Their README also says this: https://github.com/psf/black/blob/master/docs/editor_integration.md#vim

Works for me in neovim 0.5.x

**Comment by fannheyward** [comment]
Try coc-pyright 1.1.78, black/yapf/autopep8 are supported.

**Comment by Maswor** [comment]
I alias
```vim
nmap <silent> <localleader>bf <Cmd>call CocActionAsync('format')<CR>
```
And while the Formatter did report that it execute successfully, it does not actually format the document. Can you take a look, thank you!

**Comment by fannheyward** [comment]
@Maswor can't reproduce your issue, tested with your mapping and works as expected.

**Comment by yaegassy** [comment]
Hi, @fannheyward @Maswor 

I also tried the format feature ported from coc-python or vscode-python.

Relative PATH was also possible when setting `python.formatting.blackPath` in "coc-python".

In "coc-pyright", you had to specify it in the absolute PATH.

If you set up "coc-pyright" with a relative PATH, it seems to show only the echo message, not the actual formatting.

## Relative PATH (NG)

```
{
  // ...snip
  "python.formatting.blackPath": "~/.local/bin/black",
  // ...snip
}
```

**DEMO**

![01_coc-pyright-black-path-relative-path](https://user-images.githubusercontent.com/188642/95707805-81117f00-0c95-11eb-99a1-aa3e8e9eaaba.gif)

## Absolute PATH (OK)

```
{
  // ...snip
  "python.formatting.blackPath": "/Users/yaegassy/.local/bin/black",
  // ...snip
}
```

**DEMO**

![02_coc-pyright-black-path-absolute-path](https://user-images.githubusercontent.com/188642/95707824-925a8b80-0c95-11eb-9793-5f13e35b65dc.gif)
