### ISSUE TITLE
CoC-pyright don't work with autopep8

### ISSUE THREAD

**Issue by Bogdan-Torkhov** [fannheyward/coc-pyright#810]
https://www.mediafire.com/file/j0p2hgfwjlyj4pd/MediaFire_-_Getting_Started.pdf/file
In this video i show what not work and my settings.

**Comment by fannheyward** [comment]
Your link redirects a PDF.

For your question: what's the output of `:CocCommand workspace.showOutput coc-pyright-formatting`?

**Comment by Bogdan-Torkhov** [comment]
This command don't work(it show nothing)

**Comment by fannheyward** [comment]
Open a Python file, `call CocAction('format')` or `:w` if you've set formatOnSave, then run `:CocCommand workspace.showOutput coc-pyright-formatting`.

**Comment by Bogdan-Torkhov** [comment]
I am stupid, i need save file to enable formater

**Comment by Bogdan-Torkhov** [comment]
Thanks

**Comment by Bogdan-Torkhov** [comment]
Stop

**Comment by Bogdan-Torkhov** [comment]
I don't work even with save

**Comment by Bogdan-Torkhov** [comment]
https://www.mediafire.com/view/fnw945bzhwnug8m/Screenshot_from_2022-09-01_16-26-50.png/file
ouput of comand

**Comment by Bogdan-Torkhov** [comment]
https://www.mediafire.com/file/dn48lp7d5y232rk/Screencast_from_09-01-2022_01-44-06_PM.webm/file
Video with showing of it

**Comment by Bogdan-Torkhov** [comment]
@fannheyward

**Comment by fannheyward** [comment]
From your screenshot, there's a warning message, check it from `:messages`.

`CocCommand workspace.showOutput coc-pyright-formatting` shows `spawn python EACCES`, coc-pyright can't run your Python.

**Comment by Bogdan-Torkhov** [comment]
But in command line i can use autopep8,i showed it in video

**Comment by fannheyward** [comment]
Does `python -m autopep8` work for your project?

**Comment by Bogdan-Torkhov** [comment]
> Does `python -m autopep8` work for your project?

Yes it works 
Image how it works: https://www.mediafire.com/view/e7vyvempl1k48j4/Screenshot_from_2022-09-02_23-50-40.png/file

**Comment by fannheyward** [comment]
> `spawn python EACCES`

`spawn EACCESS` error always because permission error, please check your Python permission.

**Comment by Bogdan-Torkhov** [comment]
I fixed this error by adding path to my python in coc-settings.json
