### ISSUE TITLE
Linting completely breaks when asked to confim a substitution with inccommand turned on.

### ISSUE THREAD

**Issue by avalonv** [fannheyward/coc-pyright#811]
Starting a substitution with `:%s:::c` while `inccommand` is set to either split or nosplit completely messes up linting and highlighting. Replacements don't have to actually be confirmed, simply initiating a substitute command causes problems.

Replacing items without the `c` flag in the substitution, or with `set inccommand=` behaves as expected.

Video which demonstrates the issue:
https://imgur.com/a/WOa4N6W

Screenshot:
![image](https://user-images.githubusercontent.com/29720696/188031327-9614250b-ec73-4f1d-bdfe-802b04f62169.png)

**What's the output of `:CocCommand pyright.version`**
coc-pyright 1.1.265 with Pyright 1.1.265

**What's the output of `:CocCommand workspace.showOutput Pyright`**
```
Workspace: /home/satsu/Documents/cursewordle
Using python from /usr/bin/python

[Info  - 8:32:23 PM] Pyright language server 1.1.265 starting
[Info  - 8:32:23 PM] Server root directory: /home/satsu/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/
[Info  - 8:32:23 PM] Starting service instance "cursewordle"
[Info  - 8:32:23 PM] No configuration file found.
[Info  - 8:32:23 PM] No pyproject.toml file found.
[Info  - 8:32:23 PM] Setting pythonPath for service "cursewordle": "/usr/bin/python"
[Warn  - 8:32:23 PM] stubPath /home/satsu/Documents/cursewordle/typings is not a valid directory.
[Info  - 8:32:23 PM] Assuming Python version 3.10
[Info  - 8:32:23 PM] Assuming Python platform Linux
[Info  - 8:32:23 PM] Searching for source files
[Info  - 8:32:23 PM] Found 6 source files
```

**Comment by avalonv** [comment]
I suspect this could be an issue with inccommand's implementation more broadly, but I'm not entirely sure how to test that.

**Comment by fannheyward** [comment]
`inccommand` is `nosplit` by default, check `:h inccommand`. I can't reproduce your issue.

**Comment by avalonv** [comment]
> `inccommand` is `nosplit` by default, check `:h inccommand`. I can't reproduce your issue.

You're right, I just assumed it was off by default. 

Updated title, seems to be specifically triggered by the confirm flag in a substitution command.

I tried with a minimal `init.vim` with just the following, largely identical to the standard coc-config: 

https://gist.github.com/avalonv/a01f6a0feec2dd287350d3ebd72a70c7

Typing `:%s:::c` in a python file will mess up linting regardless of whether type enter or <esc>. No substitutions have to take place for this to occur.

**Comment by avalonv** [comment]
@fannheyward have you been able to replicate this? I tested it in another machine but I'm still wondering if it might have something to do with my configuration.

**Comment by fannheyward** [comment]
Can't reproduce this.

**Comment by fannheyward** [comment]
Test code:

```
def foo(bar: int = None):
    print(bar)
```

1. `:set inccommand=nosplit`
2. search `bar`
3. `:%s::c`

<img width="298" alt="截屏2022-09-15 16 17 57" src="https://user-images.githubusercontent.com/345274/190352582-13828479-67f8-4ff6-9a7a-add5669b21d8.png">

`<cr>` to accept, or `<esc>` to roll back.

**Comment by avalonv** [comment]
Hi, the example doesn't really apply.

I'm not trying to replace bar with `c`, `c` in this case is the confirm flag for the substitute command, not the replacement string.

The command should be `:%s:::c` (three `:` in the middle)

Made another video which should be clearer to read: https://imgur.com/a/aBsa82E

**Comment by fannheyward** [comment]
Sorry for the `:::` issue, I made it wrong with two sign.

Here's my test.

mini.vim

```
set nocompatible
set runtimepath^=/Users/fannheyward/.local/share/nvim/plugged/coc.nvim
filetype plugin indent on
syntax on

set runtimepath^=~/src/coc-pyright
```

test code foo.py:

```
def foo(bar: int = None):
    bar = 1
```

steps:

1. nvim -u mini.vim foo.py
2. search `bar`
3. `:%s:::c`, without `<cr>` to confirm

<img width="415" alt="截屏2022-09-15 18 42 39" src="https://user-images.githubusercontent.com/345274/190384040-7482ef98-c8a9-4d0b-b139-329129208fca.png">

two `bar` are removed. `<cr>` to confirm:

<img width="437" alt="截屏2022-09-15 18 42 57" src="https://user-images.githubusercontent.com/345274/190384100-2f5ea725-3d23-4904-a77d-97ef3fbecd25.png">

press `n` twice, no errors.

`:set inccommand=nosplit`, and `:%s:::c` again, press `<cr>` to confirm and `n` twice, no errors.
