### ISSUE TITLE
Please, help! How to disable this "Literal[5] and list[Unknown] popup?

### ISSUE THREAD

**Issue by acidx27x** [fannheyward/coc-pyright#814]
![image](https://user-images.githubusercontent.com/97349653/188227088-4389f570-db04-4be9-b975-b36af3bc4fd8.png)

**Comment by fannheyward** [comment]
You can disable it by `pyright.inlayHints.enable`.

**Comment by ykamikawa** [comment]
How to change the text color?

**Comment by vishalwadhwa13** [comment]
+1 How to change the colour? I want to fade/grey it out.

**Comment by fannheyward** [comment]
The hi group is `CocInlayHint`. Check `:h coc-inlayHint`.

**Comment by bulletmark** [comment]
These inlay hints have reappeared again and are splattered all over my code. I still have `"pyright.inlayHints.enable": false` and have changed nothing other than updating my plugins. Any hint how to fix it now?

**Comment by bulletmark** [comment]
Don't worry, just found this commit 35028975a074e0f0d574970a21efa5e41ccee505.

**Comment by fannheyward** [comment]
Use `inlayHint.enable`, same configuration option as coc.nvim, sorry for the breaking 😞.

**Comment by jonashaag** [comment]
Is there a way to disable only the `Literal[x]` hints? They really are useless
