### ISSUE TITLE
Fails to lint multiple line commands using backslash

### ISSUE THREAD

**Issue by thomasnal** [fannheyward/coc-pyright#816]
Issue in the screenshot. This fails on every multi-line command split using backslash
![image](https://user-images.githubusercontent.com/17355467/188287428-893b4734-4353-4f5d-ba1a-0e8876e778f9.png)

**What's the output of `:CocCommand pyright.version`**
[coc.nvim] coc-pyright 1.1.269 with Pyright 1.1.269

**What's the output of `:CocCommand workspace.showOutput Pyright`**
[Info  - 22:41:48] Pyright language server 1.1.269 starting
[Info  - 22:41:48] Server root directory: /userhome/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/
[Info  - 22:41:48] Starting service instance "trading-system"
[Info  - 22:41:48] Setting pythonPath for service "trading-system": "/proj.pyenv/bin/python"
[Info  - 22:41:48] Loading configuration file at /proj/pyrightconfig.json
Config "reportUnknownParameterType" entry must be true, false, "error", "warning", "information" or "none".
[Info  - 22:41:48] Assuming Python version 3.7
[Info  - 22:41:48] Assuming Python platform Darwin
[Info  - 22:41:48] No include entries specified; assuming /proj
[Info  - 22:41:48] Auto-excluding **/node_modules
[Info  - 22:41:48] Auto-excluding **/__pycache__
[Info  - 22:41:48] Auto-excluding **/.*
[Warn  - 22:41:48] stubPath /proj/typings is not a valid directory.
[Info  - 22:41:48] Searching for source files
[Info  - 22:41:49] Found 222 source files
[Info  - 22:42:34] Setting pythonPath for service "trading-system": "/proj.pyenv/bin/python"
[Info  - 22:42:34] Loading configuration file at /proj/pyrightconfig.json
Config "reportUnknownParameterType" entry must be true, false, "error", "warning", "information" or "none".
[Info  - 22:42:34] Assuming Python version 3.7
[Info  - 22:42:34] Assuming Python platform Darwin
[Info  - 22:42:34] No include entries specified; assuming /proj
[Info  - 22:42:34] Auto-excluding **/node_modules
[Info  - 22:42:34] Auto-excluding **/__pycache__
[Info  - 22:42:34] Auto-excluding **/.*
[Warn  - 22:42:34] stubPath /proj/typings is not a valid directory.
[Info  - 22:42:34] Searching for source files
[Info  - 22:42:35] Found 222 source files

**Comment by fannheyward** [comment]
Looks like it's Pyright's issue, does it work correctly with VSCode + Pylance?

**Comment by thomasnal** [comment]
I cannot say since I don't use those editors.

**Comment by thomasnal** [comment]
I just learned about stubs. This break on pandas.
```python
import pandas as pd

def main():
    greetings = pd.read_parquet('a.parquet')
    print(greetings)
```
With `pandas-stub` installed or `:CocCommand pyright.createtypstub pandas` the unreachable code hint goes away.

What is the recommended way to manage the stubs especially when dependencies version change?
