### ISSUE TITLE
pyright can not work, using :CocInfo exerts an error

### ISSUE THREAD

**Issue by cybaol** [fannheyward/coc-pyright#82]
## versions

vim version: NVIM v0.5.0-610-g326b87feb
node version: v14.5.0
coc.nvim version: 0.0.78-0ff42027ff
coc.nvim directory: /home/kino/.cache/dein/repos/github.com/neoclide/coc.nvim_release
term: xterm-256color
platform: linux

## Output channel: Pyright

[Info  - 8:45:28 AM] Pyright language server 1.1.60 starting
[Info  - 8:45:28 AM] Server root directory: /home/kino/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/
[Error  - 8:45:28 AM] stubPath typings is not a valid directory.

**Comment by fannheyward** [comment]
What do you mean not work? No definition hover and no completion item suggestion?

> stubPath typings is not a valid directory.

Pyright uses `typings` folder in your project root as `stubPath`, there is no such folder,  so comes this message, you can ignore it.

**Comment by fannheyward** [comment]
@DedSecer looks like coc can't resolve your workspace root, checkout https://github.com/neoclide/coc.nvim/wiki/Using-workspaceFolders#resolve-workspace-folder

**Comment by DedSecer** [comment]
@fannheyward
So this mean coc-pyright only work when python file is in workspace folder?
If so,I think it's inconvenient that when I want test a py script(`nvim /tmp/test.py`) I cannot get coc-pyright work.

**Comment by fannheyward** [comment]
No, I can `nvim /tmp/test.py` with coc-pyright works.

**Comment by DedSecer** [comment]
@fannheyward 
I've added `coc.preferences.rootPatterns = ['*']` to coc-settings.json and it seem that it could make my coc-pyright work.Will it have  impact for coc.nvim?

**Comment by fannheyward** [comment]
@DedSecer I don't need to change `coc.preferences.rootPatterns` to make pyright works. Can you reproduce this issue with a minimal vimrc?

**Comment by DedSecer** [comment]
* install neovim in a new deepin linux(without doing any other things), and install the lastest neovim(version 0.4.4) to my linux.
* install node.js(version 14.8.0) to my linux.
* download vim-plug
* edit ~/.config/nvim/init.vim:
```
call plug#begin('~/.config/nvim/plugged')
    Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()
```

* type `PlugInstall` and `CocInstall coc-pyright`.
* and try nvim /tmp/test.py,pyright still not work.
