### ISSUE TITLE
method drodown list has too many "noises"

### ISSUE THREAD

**Issue by laoshaw** [fannheyward/coc-pyright#831]
**What's the output of `:CocCommand pyright.version`**

coc-pyright 1.1.272 with Pyright 1.1.273

**What's the output of `:CocCommand workspace.showOutput Pyright`**

```
[Info  - 8:40:16 AM] Pyright language server 1.1.273 starting
[Info  - 8:40:16 AM] Server root directory: /home/testx/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/
[Info  - 8:40:17 AM] Starting service instance "code"
[Info  - 8:40:21 AM] No configuration file found.
[Info  - 8:40:21 AM] No pyproject.toml file found.
[Info  - 8:40:21 AM] Setting pythonPath for service "code": "/home/testx/python/code/.venv/bin/python"
[Warn  - 8:40:21 AM] stubPath /home/testx/python/code/typings is not a valid directory.
[Info  - 8:40:21 AM] Assuming Python version 3.10
[Info  - 8:40:21 AM] Assuming Python platform Linux
[Info  - 8:40:21 AM] Searching for source files
[Info  - 8:40:21 AM] Found 126 source files
```
when I want to see a dropdown list of methods, coc-pyright gave me lots of options and many of them are not useful, see the screenshot, what I really need is just the "f", not "v".

![image](https://user-images.githubusercontent.com/18351761/194710610-f2bbd921-66d7-4e23-827f-dd902d727ba6.png)

as a comparison to my c++ code, only useful methods are shown up in the dropdown list:

![image](https://user-images.githubusercontent.com/18351761/194710713-21266e22-410b-45b3-9b92-d6889873079c.png)

so is typescript:
![image](https://user-images.githubusercontent.com/18351761/194710745-183acc90-c15b-4750-be65-ed5ad4d13a78.png)

**Comment by fannheyward** [comment]
Change `suggest.defaultSortMethod` to give a try, but the completion items and orders are came from language server, here is Pyright.
