### ISSUE TITLE
Cannot turn off inlay hints

### ISSUE THREAD

**Issue by cterdam** [fannheyward/coc-pyright#835]
**What's the output of `:CocCommand pyright.version`**
[coc.nvim] coc-pyright 1.1.275 with Pyright 1.1.275

**What's the output of `:CocCommand workspace.showOutput Pyright`**
Workspace: /Users/sterdam/cterdam/11785                                                                                 
Using python from /opt/homebrew/Caskroom/miniforge/base/envs/785hwp1/bin/python  
                                                                                   
[Info  - 2:29:32 PM] Pyright language server 1.1.275 starting                    
[Info  - 2:29:32 PM] Server root directory: /Users/sterdam/.config/coc/extensions/node_modules/coc-pyright/node_modules/     ↳pyright/dist/
[Info  - 2:29:32 PM] Starting service instance "11785"                           
[Info  - 2:29:32 PM] No configuration file found.                                
[Info  - 2:29:32 PM] No pyproject.toml file found.                               
[Info  - 2:29:32 PM] Setting pythonPath for service "11785": "/opt/homebrew/Caskroom/miniforge/base/envs/785hwp1/bin/python" 
[Warn  - 2:29:32 PM] stubPath /Users/sterdam/cterdam/11785/typings is not a valid directory.
[Info  - 2:29:32 PM] Assuming Python version 3.7                                  
[Info  - 2:29:32 PM] Assuming Python platform Darwin                             
[Info  - 2:29:33 PM] Searching for source files                                  
[Info  - 2:29:33 PM] Found 28 source files

**Problem**
pyright creates in-line type annotations that look like this:
<img width="765" alt="Screen Shot 2022-10-19 at 14 33 15" src="https://user-images.githubusercontent.com/36314639/196775344-9986d397-9bab-4f49-abc0-f49ffd3f2b54.png">

I tried to turn it off by adding `pyright.inlayHints.enable: false` in `:CocConfig`, but it seems to have no effect.

**How to reproduce**
With COC and coc-pyright of the specified version, open any python file and you will see the in line type annotations.

**Comment by fannheyward** [comment]
Use `inlayHint.enable`, same configuration option as coc.nvim, sorry for the breaking.
