### ISSUE TITLE
hide variable types

### ISSUE THREAD

**Issue by yongbinkim-chemist** [fannheyward/coc-pyright#836]
**What's the output of `:CocCommand pyright.version`**
[coc.nvim] coc-pyright 1.1.275 with Pyright 1.1.277

**What's the output of `:CocCommand workspace.showOutput Pyright`**
<img width="1326" alt="2" src="https://user-images.githubusercontent.com/80072270/198182598-313bd20b-9c76-4733-af45-0662f139cd10.png">

I am wondering if I could hide the variable types right next to the variable declaration.
<img width="964" alt="1" src="https://user-images.githubusercontent.com/80072270/198182992-86a00ff2-a5df-40f7-81b5-40170cb41fd3.png">

**Comment by fannheyward** [comment]
Check `:h coc-inalyHint`.

**Comment by yongbinkim-chemist** [comment]
I am sorry, I didn't understand properly.
I tried that command on my vim, but nothing happened.

<img width="326" alt="3" src="https://user-images.githubusercontent.com/80072270/198185897-b3737755-e189-4cd1-96de-18f45419629f.png">
<img width="477" alt="4" src="https://user-images.githubusercontent.com/80072270/198185907-4ad43536-71f6-469d-913e-446ebc27c196.png">

**Comment by yaegassy** [comment]
@yongbinkim-chemist Please try. `:h coc-inalyHint` -> `:h coc-inlayHint`.

**Comment by fannheyward** [comment]
@yongbinkim-chemist sorry for the typo. It's `coc-inlayHint`.

**Comment by yaegassy** [comment]
To disable this feature, set `inlayHint.enable` to false in `coc-settings.json`.

```jsonc
{
  "inlayHint.enable": false
}
```

**Comment by yongbinkim-chemist** [comment]
It is now working perfectly. Thanks for your quick answer, and please forgive my ignorance.
