### ISSUE TITLE
No Code actions

### ISSUE THREAD

**Issue by matheusfillipe** [fannheyward/coc-pyright#843]
**What's the output of `:CocCommand pyright.version`**
```
[coc.nvim] coc-pyright 1.1.275 with Pyright 1.1.278
```

**What's the output of `:CocCommand workspace.showOutput Pyright`**
```
Workspace: /home/matheus/tmp
Using python from /usr/bin/python

[Info  - 7:16:32 PM] Pyright language server 1.1.278 starting
[Info  - 7:16:33 PM] Server root directory: /home/matheus/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/
[Info  - 7:16:33 PM] Starting service instance "tmp"
[Info  - 7:16:33 PM] No configuration file found.
[Info  - 7:16:33 PM] No pyproject.toml file found.
[Info  - 7:16:33 PM] Setting pythonPath for service "tmp": "/usr/bin/python"
[Warn  - 7:16:33 PM] stubPath /home/matheus/tmp/typings is not a valid directory.
[Info  - 7:16:33 PM] Assuming Python version 3.10
[Info  - 7:16:33 PM] Assuming Python platform Linux
[Info  - 7:16:33 PM] Searching for source files
[Info  - 7:16:33 PM] Found 85 source files
[Error - 7:16:34 PM] Sending request textDocument/completion failed.
  Message: request cancelled
  Code: -32800 
[Info  - 7:16:48 PM] [FG] Long operation: completion at /home/matheus/tmp/project.py:0:5 (9790ms)
[Error - 7:16:48 PM] Sending request textDocument/completion failed.
  Message: request cancelled
  Code: -32800 
[Error - 7:16:48 PM] Sending request textDocument/completion failed.
  Message: request cancelled
  Code: -32800 
[Error - 7:16:48 PM] Sending request textDocument/completion failed.
  Message: request cancelled
  Code: -32800 
[Error - 7:16:48 PM] Sending request textDocument/completion failed.
  Message: request cancelled
  Code: -32800 
[Error - 7:16:48 PM] Sending request textDocument/completion failed.
  Message: request cancelled
  Code: -32800 
[Error - 7:16:48 PM] Sending request textDocument/completion failed.
  Message: request cancelled
  Code: -32800 
```

**Problem description**

![image](https://user-images.githubusercontent.com/24435787/199614803-e3558340-b0c0-4c68-aa54-857a0d9c1c85.png)

I've created a single `project.py` file and opened it with nvim and added the code that can be seen. `<Plug>(coc-codeaction-selected)` shows only 2 possibilities and that seems to be always the case for every issue it detected, and I am sure it can do more.

![image](https://user-images.githubusercontent.com/24435787/199614811-8b9a8044-92d8-4e48-9add-53dd3f747ef0.png)

Also while I'm typing it seems to show a completion but that doesn't automatically import the module. I am doing tab auto-completion with coc like this:

```
inoremap <silent><expr> <TAB>
      \ coc#pum#visible() ? coc#pum#next(1):
      \ CheckBackspace() ? "\<Tab>" :
      \ coc#refresh()

inoremap <silent><expr> <C-j>
      \ coc#pum#visible() ? coc#pum#next(1):
      \ CheckBackspace() ? "\<C-j>" :
      \ coc#refresh()

inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"
inoremap <expr><C-k> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"

```
Here is my full very messy init.vim: https://github.com/matheusfillipe/dotfiles/blob/master/nvim/init.vim

**Comment by fannheyward** [comment]
> show a completion but that doesn't automatically import the module

Do you have a `<cr>` mapping?  I'm using this:

`inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm() : "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"`

**Comment by matheusfillipe** [comment]
Thanks @fannheyward, I was missing that binding and now the completion works. What about the actions list? Shouldn't it also show that option? It always only have those two options.

**Comment by fannheyward** [comment]
Try `<Plug>(coc-codeaction-cursor)`?

**Comment by matheusfillipe** [comment]
Thanks @fannheyward, that gives more options:
![image](https://user-images.githubusercontent.com/24435787/200098441-5f45603b-4251-4be4-bbb3-762e55c9070a.png)

But then it says rope is not installed:

![image](https://user-images.githubusercontent.com/24435787/200098459-e3b70f54-7533-40e9-90fc-52c4ab99638d.png)

I have `pip install rope` and also have the `python-rope` system package installed. I am not in a venv.

**Comment by fannheyward** [comment]
Does `python3 -c "import rope"` report any errors?

**Comment by matheusfillipe** [comment]
@fannheyward  It works now for some random reason. Not sure what was wrong before. 

Shouldn't it suggest: `from typing import Optional` though? I know this is wither pyright's or rope's fault but maybe you know whats wrong. Maybe it is just not that capable yet.

![image](https://user-images.githubusercontent.com/24435787/200436691-0840fadb-28f3-44eb-8216-f65a305bb375.png)

**Comment by matheusfillipe** [comment]
Anyway this issue can be closed, is not coc-pyright's fault that there aren't more options there.
