### ISSUE TITLE
Is there a way to use mypy *instead of* pyright for type checking?

### ISSUE THREAD

**Issue by hjwp** [fannheyward/coc-pyright#848]
I'm really enjoying coc-pyright as a source of autocompletions, and quite like the inline type overlays too.

but for actual type checking, i would rather use mypy (pyright is not very good at dealing with numpy for example, or pydantic).  is there a way to do that?

I've tried setting `"python.linting.mypyEnabled": true` but i'm still seeing pyright type errors.

**Comment by fannheyward** [comment]
You can disable Pyright's diagnostics by set `pyright.disableDiagnostics` to true.

**Comment by hjwp** [comment]
sorry, answered my own question.  pyright's type checking can be disabled by setting typeCheckingMode to "off"

```json
   // disable pyright type checker and use mypy instead
   "python.analysis.typeCheckingMode": "off"
   "python.linting.mypyEnabled": true,

```

**Comment by hjwp** [comment]
thanks @fannheyward !  sounds like that'll work too.  with the typeCheckingMode=off i'm still getting _some_ pyright diagnostics, which i think i quite like:

![image](https://user-images.githubusercontent.com/769730/202432497-84da02c6-463f-45a2-9cb1-84c02a87c3a1.png)
