### ISSUE TITLE
Disable coc-pyright definitions inside code

### ISSUE THREAD

**Issue by DiegoCostas97** [fannheyward/coc-pyright#849]
Hi all!

I was wondering if it is normal to have these weird definitions inside the code:

![Captura de Pantalla 2022-11-17 a las 18 33 24](https://user-images.githubusercontent.com/67594492/202517023-ddd7f18e-8a7c-4415-af54-77b3acbdb025.png)

For me are quite annoying and I would really appreciate if you can help me remove them.

My installation process was just the recommended. I installed coc-nvim via vim-plug using
`Plug 'neoclide/coc.nvim', {'branch': 'release'}`

Then, I installed coc-pyright with
`:CocInstall coc-pyright`

Thanks in advance!

P.S.: Is it possible to use TAB for suggestion completion? When I press TAB it just scrolls down the suggestions and for selecting the one I want I have to hit Enter. Thanks again.

**Comment by fannheyward** [comment]
Set `inlayHint.enable` to fale in your coc-settings.json, check `:h coc-inlayHint` for more.

> use TAB for suggestion completion

Setup mapping for your TAB, check coc.nvim README or help doc.
