### ISSUE TITLE
Error with subplots

### ISSUE THREAD

**Issue by DiegoCostas97** [fannheyward/coc-pyright#850]
Hello again,

I was wondering if you could help me understand the next error, because I do not find it anywhere.

![Captura de Pantalla 2022-11-18 a las 18 28 54](https://user-images.githubusercontent.com/67594492/202766061-109f550a-b72c-45e1-b906-ee2d28b4430e.png)

Thank you very much!

**Comment by fannheyward** [comment]
https://github.com/fannheyward/coc-pyright#python-typing-and-stub-files

Pyright needs packages to be type annotated and/or have stub files, looks like pyplot didn't provide type stubs. You can clone https://github.com/microsoft/python-type-stubs/tree/main/matplotlib and setup `python.analysis.typeshedPaths` to use.

**Comment by DiegoCostas97** [comment]
Thanks for the response, but sadly I do not understood you very well.

I do not where should I clone the matplotlib repo, and how to setup the `python.analysis.typeshedPaths`

I would really appreciate if you could explain it to me a little more in detail.

Thanks again.

**Comment by fannheyward** [comment]
Sorry I made a mistake, you should use `python.analysis.stubPath`.

For example, you clone `https://github.com/microsoft/python-type-stubs` to your local src dir `~/src/python-type-stubs`, then `"python.analysis.stubPath": "~/src/python-type-stubs"` to your coc-settings.json, you can open it with `:CocConfig`.

<img width="755" alt="截屏2022-11-19 20 24 40" src="https://user-images.githubusercontent.com/345274/202850680-d28c535d-0527-42e1-b4a2-44dcbaba0674.png">

**Comment by DiegoCostas97** [comment]
Thank you very much, it works perfectly now!
