### ISSUE TITLE
How do I remove the type and return hints on suggestion?

### ISSUE THREAD

**Issue by LrnzDC3696** [fannheyward/coc-pyright#852]
What I do
```py
def __<enter>
```
Expected Output
```py
def __init__(self):
    pass
```
Actual Output
```py
def __init__(self) -> None:
    pass
```

**Comment by fannheyward** [comment]
The completion item is came from Pyright with type hint, have no idea whether Pyright support this or not.

**Comment by fannheyward** [comment]
Maybe we can add this support in coc-pyright side, will look into this.

**Comment by LrnzDC3696** [comment]
alright thanks!
