### ISSUE TITLE
Pyright suggests incorrect type hint.

### ISSUE THREAD

**Issue by ZachVec** [fannheyward/coc-pyright#856]
**What's the output of `:CocCommand pyright.version`**
[coc.nvim] coc-pyright 1.1.275 with Pyright 1.1.279

**What's the output of `:CocCommand workspace.showOutput Pyright`**
Workspace: /home/vector/test
Using python from /usr/bin/python

[Info  - 11:08:01 PM] Pyright language server 1.1.279 starting
[Info  - 11:08:01 PM] Server root directory: /home/vector/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/
[Info  - 11:08:01 PM] Starting service instance "test"
[Info  - 11:08:01 PM] No configuration file found.
[Info  - 11:08:01 PM] No pyproject.toml file found.
[Info  - 11:08:01 PM] Setting pythonPath for service "test": "/usr/bin/python"
[Warn  - 11:08:01 PM] stubPath /home/vector/test/typings is not a valid directory.
[Info  - 11:08:01 PM] Assuming Python version 3.8
[Info  - 11:08:01 PM] Assuming Python platform Linux
[Info  - 11:08:01 PM] Searching for source files
[Info  - 11:08:01 PM] Found 1 source file

```python
class Dog:
    def __init__(self, name: str) -> None:
        self._name: str  = name

    def greeting(self, name: str) -> str:
        return f"{self._name} says hello to {name}"

if __name__ == "__main__":
    greeting: (name  = Dog("Charlie").greeting
```

the greeting variable is suggested incorrect type `(name`. 

![image](https://user-images.githubusercontent.com/75198239/204836651-fc29d5fe-5370-4fe0-968d-687f8a22ac93.png)

**Comment by lithammer** [comment]
If you perform the hover action on `greeting` it will reveal the type as `(name: str) -> str` (which is the notation for a callable/function). So for some reason it seems to be cutting of everything after `:`.
