### ISSUE TITLE
How show indent tips like the readme.md?

### ISSUE THREAD

**Issue by HCY-ASLEEP** [fannheyward/coc-pyright#862]
I want to show these indent symbols like this:
![image](https://user-images.githubusercontent.com/76894615/204993416-fcc14d6d-e966-4d37-b8b0-8a0905332602.png)

I use inlayHint.enable in my coc-settings.json, but it seems that it didn't work as I wish.
![image](https://user-images.githubusercontent.com/76894615/204994083-fa203c87-441c-457f-9ca5-96814a86656d.png)
![image](https://user-images.githubusercontent.com/76894615/204994173-c4947eb2-427c-4ddf-be04-e0302a22bb8a.png)

Can anyone tell me how to show indent symbols or indent lines?

**Comment by fannheyward** [comment]
`set list listchars=tab:\|\ ,trail:·,eol:¬,leadmultispace:---+`

**Comment by HCY-ASLEEP** [comment]
Thank you very much!
