### ISSUE TITLE
Use of 'flake8Args' 

### ISSUE THREAD

**Issue by steakhutzeee** [fannheyward/coc-pyright#864]
Hello,

I started using coc-pyright and was looking for a way to set the flake8 args. Looking at the Vscode linting section I found the value:

python.linting.flake8Args

and it's working fine in my coc-settings.json

What is not clear to me is, is this the right way to do this? The command I used has nothing to do with this extension as per it's not documented?

Thank you in advance!

**Comment by fannheyward** [comment]
Yes, there's `python.linting.flake8Args` https://github.com/fannheyward/coc-pyright/blob/096218b6f5301945f381e62c715a18d81fab334d/package.json#L884-L892.

I'll improve the document.
