### ISSUE TITLE
Can't Disable Hint messages with coc-settings.json

### ISSUE THREAD

**Issue by miguel-a-tamayo** [fannheyward/coc-pyright#865]
Hello! Thank you for putting this together. I'm having issues disabling hints and some gray messages next to my code lines (as seen below). 

<img width="539" alt="image" src="https://user-images.githubusercontent.com/83749938/210112812-88eb0dc0-5fff-46c4-a173-38b0e7368d87.png">

I read issue #271 and followed the steps by adding 
`"diagnostic.showUnused": false` and `"diagnostic.level": "information",` to my coc-settings.json file but I'm not sure if the file is being ignored.

The settings file is located in ~/.config/nvim

Any help or tips are appreciated!!!

**Comment by half0wl** [comment]
These are inlay hint messages. You can toggle them via the `pyright.inlayHints.functionReturnTypes` and `pyright.inlayHints.variableTypes` flags.

To disable them completely, add these to your coc config file:

```json
{
    "pyright.inlayHints.functionReturnTypes": false,
    "pyright.inlayHints.variableTypes": false
}
```

For anyone coming here after updating `pyright`/`coc-pyright` (like me), yes this seems to be a relatively new addition that is enabled by default.

---

@miguel-a-tamayo :

> but I'm not sure if the file is being ignored.

To be sure, open the config file via `:CocConfig` in neovim :-)
