### ISSUE TITLE
Feature request: configure linter args

### ISSUE THREAD

**Issue by GuillaumeDesforges** [fannheyward/coc-pyright#871]
Like in VSCode, I would like to pass some args to my linter (in my case flake8) to adjust it, e.g. set the path to the configuration file (in my case `../../tox.ini`).

In VSCode settings I would add
```
    "python.linting.flake8Args": [ "--config=${workspaceFolder}/../../tox.ini" ],
```

See https://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-config

**What's the output of `:CocCommand pyright.version`**

`[coc.nvim] coc-pyright 1.1.282 with Pyright 1.1.282`

**What's the output of `:CocCommand workspace.showOutput Pyright`**

(redacted)
```
Workspace: /home/me/somerepo
Using python from /home/me/somerepo/libs/somelib/.venv/bin/python
```

**Comment by fannheyward** [comment]
> python.linting.flake8Args

Same configuration option can be used in coc-settings.json.
