### ISSUE TITLE
Flake8 errors disappear immediately on inserting text, only re-appear on save

### ISSUE THREAD

**Issue by ntaylorwss** [fannheyward/coc-pyright#873]
**What's the output of `:CocCommand pyright.version`**
`[coc.nvim] coc-pyright 1.1.284 with Pyright 1.1.288

**What's the output of `:CocCommand workspace.showOutput Pyright`**
```
Workspace: /home/me/test
Using python from /home/me/test/.venv/bin/python

[Info  - 11:41:39.054] Pyright language server 1.1.288 starting
[Info  - 11:41:39.054] Server root directory: /home/me/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/
[Info  - 11:41:39.058] Starting service instance "test"
[Info  - 11:41:39.072] No configuration file found.
[Info  - 11:41:39.072] No pyproject.toml file found.
[Info  - 11:41:39.072] Setting pythonPath for service "test": "/home/me/test/.venv/bin/python"
[Warn  - 11:41:39.076] stubPath /home/me/test/typings is not a valid directory.
[Info  - 11:41:39.096] Assuming Python version 3.10
[Info  - 11:41:39.097] Assuming Python platform Linux
[Info  - 11:41:39.151] Searching for source files
[Info  - 11:41:39.154] Found 1 source file
```

## Issue

With flake8 enabled as the linter, errors appear on opening the file, but entering insert mode and adding any text makes them disappear, and they do not re-appear until I save the file.

## Desired Behaviour

I would like flake8 to be continuously linting the file, such that errors are updated each time I return to normal mode from insert mode. I've recently transitioned from using ALE, and that was how ALE behaved.

## Details

I use flake8 as my linter, and prefer to disable pyright diagnostics, because I have a number of flake8 extensions enabled. However, this issue makes it very difficult to use.

Here's a simple one-line file with screenshots to demonstrate.

1. Open a file `nvim test.py`, add `import glob` on the first line, save and close.
2. Re-open `nvim test.py`:

![2023-01-16-11:45:37-screenshot](https://user-images.githubusercontent.com/14324416/212755395-9ac88c8b-f610-4511-8041-cc6c203c3437.png)

3. `i` to enter insert mode, `A` to append to the line, type `s`. The line now reads `import globs`.
4. The error immediately disappears from the sign column:
![2023-01-16-11:48:18-screenshot](https://user-images.githubusercontent.com/14324416/212755740-a2d62d7f-7f20-4dee-8115-310f187912e6.png)

## Environment

The behaviour can be reproduced with only this `coc-settings.json`:

```
{"python.linting.flake8Enabled": true, "pyright.disableDiagnostics": true}
```

In an environment configured like so:

```
~> mkdir test && cd test
~> python -m venv .venv
~> source .venv/bin/activate
~> pip install flake8
```

**Comment by fannheyward** [comment]
This is expected as coc-pyright runs `flake8 xxx.py`on opening and saving only.

Maybe we can improve this with stdin, this will work on input mode.

**Comment by fannheyward** [comment]
coc-pyright v1.1.291 has added linting from stdin, will run flake8 on file changing, without saving.

Note that coc-pyright will clear diagnostics when vim enter insert mode.
