### ISSUE TITLE
Bumping on microsoft/pyright dependency

### ISSUE THREAD

**Issue by fvdnabee** [fannheyward/coc-pyright#874]
coc-pyright currently depends on microsoft/pyright 1.1.284, while 1.1.291 was released yesterday. [Sometimes](https://github.com/fannheyward/coc-pyright/pull/870) dependabot will suggest to bump pyright but it hasn't done so for the last seven releases. It's unclear why dependabot isn't more pro-active about bumping pyright. A more 'aggresive' dependabot could help to follow microsoft/pyright more closely. Is this something we have control over?

edit: this seems relevant https://github.com/dependabot/dependabot-core/issues/2980#issuecomment-760586879; but 'Dependabot' is missing from this repo's Dependency Graph for me and this still requires a manual intervention.

**Comment by fannheyward** [comment]
I've set Dependabot to bump monthly https://github.com/fannheyward/coc-pyright/blob/master/.github/dependabot.yml

The coc-pyright is released manually, you can `:CocUninstall coc-pyright` and `:CocInstall coc-pyright` again to install new Pyright release.
