### ISSUE TITLE
CodeActions for auto-import not showing up.

### ISSUE THREAD

**Issue by iago-lito** [fannheyward/coc-pyright#876]
I have read through #90 and #843, set up `"python.analysis.diagnosticMode": "workspace",`, checked that `python3 -c 'import rope; import autoimport` run well (+same for `python3.11`), but I still get no autoimport code action in the following situation, no matter whether I use `(coc-codeaction)`, `(coc-codeaction-cursor)`, `(coc-codeaction-selected)` or `(coc-codeaction-line)`:

```
a = 5
Optional
 ^╭Choose action ─────────────────────────────────╮
  │1. Ignore Pyright typing check for current line│
  │2. Extract Method                              │
  │3. Extract Variable                            │
  ╰───────────────────────────────────────────────╯

```

What could be wrong in the setup? How can I get `4. Add "from typing import Optional"` ?

```
:CocCommand pyright.version
[coc.nvim] coc-pyright 1.1.291 with Pyright 1.1.291

:CocCommand workspace.showOutput Pyright
Workspace: /home/iago-lito/python_test
Using python from /usr/bin/python3.11

[Info  - 19:39:38.815] Pyright language server 1.1.291 starting
[Info  - 19:39:38.815] Server root directory: /home/iago-lito/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/
[Info  - 19:39:38.820] Starting service instance "python_test"
[Info  - 19:39:38.841] No configuration file found.
[Info  - 19:39:38.841] No pyproject.toml file found.
[Info  - 19:39:38.841] Setting pythonPath for service "python_test": "/usr/bin/python3.11"
[Warn  - 19:39:38.845] stubPath /home/iago-lito/python_test/typings is not a valid directory.
[Info  - 19:39:38.872] Assuming Python version 3.11
[Info  - 19:39:38.873] Assuming Python platform Linux
[Info  - 19:39:38.945] Searching for source files
[Info  - 19:39:38.949] Found 2 source files
```

**Comment by yaegassy** [comment]
@iago-lito The commit on the coc.nvim itself seems to be affected.

- <https://github.com/neoclide/coc.nvim/commit/0b570284045f328663e5446f179322e0c06a3607>

Currently, I think that the target action will be displayed if `<Plug>(coc-codeaction-source)` is mapped and used.

If there is a problem, please report the issue to coc.nvim itself.

**Comment by fannheyward** [comment]
The import code action kind has changed to `quickfix`, same as VSCode Python/Pylance.

For Q2, coc-pyright can do nothing for this.

**Comment by yaegassy** [comment]
The code action for "organize imports" also seems to be in a situation where it can only be called by `coc-codeaction-source` https://github.com/fannheyward/coc-pyright/blob/master/src/features/codeAction.ts#L19-L3

**Comment by fannheyward** [comment]
Yes, I kept its kind remains `SourceOrganizeImports` because this can be called by `editor.action.organizeImport`. What do you think?

**Comment by yaegassy** [comment]
@fannheyward I checked because there may be similar issue report. I myself have no problem with it as I basically run it by command.
