### ISSUE TITLE
help signature for `getattr` method does not show

### ISSUE THREAD

**Issue by o-wo** [fannheyward/coc-pyright#884]
**What's the output of `:CocCommand pyright.version`**
v1.1.292
![image](https://user-images.githubusercontent.com/24418520/216821717-61b7b45c-ea58-43aa-adb1-d18f11818ad1.png)

**What's the output of `:CocCommand workspace.showOutput Pyright`**
![image](https://user-images.githubusercontent.com/24418520/216821961-d6b0c4db-29bf-4a47-a655-7fae805d17b6.png)

----------------------------------------
Greetings,

I have observed lately that help signature popup does not show up for python's built-in `getattr` method but it does show up for `hasattr` and `setattr` and all other methods. Is it a bug with the current version of coc-pyright?

I faintly remember coc-pyright used to show help signature popup few months ago for `getattr` too; the last time I used this method, but I dont use this built-in method alot so I can't say for sure which was the last coc-pyright version it was. I have added a video below for reproduction example. Thank you for reading and apologies for any inconvenience.

https://user-images.githubusercontent.com/24418520/216823505-a0ca7278-9e10-4fa1-8ab3-69e29ed83257.mp4

**Comment by fannheyward** [comment]
Set `"signature.triggerSignatureWait": 1000` in your coc-settings.json.

By default, the wait limit is `500ms`, coc will cancel the signature request when limit reach out. In my env, Pyright returns `hasattr` signature in 25ms, `setattr` in34ms , but `getattr` in 773ms, that's why you can't get help signature.
