### ISSUE TITLE
[Feature] Support ruff auto fix and sort import on save

### ISSUE THREAD

**Issue by pierrejeambrun** [fannheyward/coc-pyright#886]
Hello all,

Thanks for this amazing project :tada: 

**coc-pyright version:** 1.1.291

### Context
Lately I swapped my python linter from [flake8](https://github.com/PyCQA/flake8) to [ruff](https://github.com/charliermarsh/ruff). Ruff has some isort capabilities embedded in it that are run when doing autofix. This yields slightly different results than isort. I have deactivated my `isort` on save, and would like to enable something similar with ruff.

**The goal would be to mimic what I had before, but using ruff**:
```
autocmd BufWrite *.py :silent call CocAction('runCommand', 'python.sortImports')
```

To sort import with ruff we can run the following command:
```
ruff --fix --no-update-check --force-exclude --fixable I001
```
I tried adding that to an `autocmd BufWrite` as above, but it didn't feel great (swp + file reloading issue, and the command wasn't run at the correct time (on old file content), maybe you have an idea on how to achieve this)

### Describe the solution you'd like
Maybe something like:
```
  "python.sortImports.path": "ruff --fix --no-update-check --force-exclude --fixable I001",
```
Or a way to specify ruff for `sortImports`.

### Describe alternatives you've considered
- Maybe something similar to eslint autofix on save, but for python:
```
eslint.executeAutofix
```
- An autocmd would be fine as well

**Comment by pierrejeambrun** [comment]
Thank you for your answer

Indeed that would be great if coc-pyright could also support ruff for `python.sortImports`.

Thank you for pointing out `coc-ruff` project, I didn't know about it. I'm going to give it a try :)

**Comment by pierrejeambrun** [comment]
`coc-ruff` is working perfectly for my use case, thanks 🎉 

Feel free to close the issue unless you plan on adding extra support for ruff on coc-pyright :)

**Comment by fannheyward** [comment]
https://github.com/fannheyward/coc-pyright/commit/102b534767634c83460eebc0a3a1a8fe0dff9469

`python.sortImports` supports `Pyright`, `ruff`, `isort` now.
