### ISSUE TITLE
Package installed in the anaconda environment cannot be detected.

### ISSUE THREAD

**Issue by hatute** [fannheyward/coc-pyright#89]
Coc-pyright cannot resolve a package from the anaconda envirment
![屏幕快照 2020-09-06 上午12 35 39](https://user-images.githubusercontent.com/15870636/92318369-68001900-efd9-11ea-9439-6f3b3f503646.png)
under the rightly chosen python interpreter,
![屏幕快照 2020-09-06 上午12 36 16](https://user-images.githubusercontent.com/15870636/92318382-a72e6a00-efd9-11ea-8ee9-d1b94ca56e14.png)

while I have added the env-related setting into the coc config file.
![屏幕快照 2020-09-06 上午12 42 36](https://user-images.githubusercontent.com/15870636/92318407-f83e5e00-efd9-11ea-9f99-b4bf8a84eca5.png)

**Comment by fannheyward** [comment]
Try to use full path of conda in config, not `$HOME`.

**Comment by hatute** [comment]
Sorry for late response.
I have reviewed the document again and tried to change the `python.condaPath` to `"~/anaconda3/bin/conda"`. But unfortunately, it still does not work for me.
Could I have more clues for solving this? Like related configurations.
Appreciated!

**Comment by hatute** [comment]
Hi fannheyward,
I found that if I switch to the target conda environment in the terminal before launch neovim, the coc-pyright can work well. However if neovim work on the default conda environment (like 'base' in my anaconda config), the coc-pyright cannot resolve the import although choose the target conda environment by coc-python.

**Comment by fannheyward** [comment]
This is expected.
