### ISSUE TITLE
Would it be ok to contribute the pyright JSON schema to schemastore.org?

### ISSUE THREAD

**Issue by JonathanPlasse** [fannheyward/coc-pyright#890]
Hi,
I would love that the pyright JSON schema be available for all via [schemastore.org](https://www.schemastore.org/json/).
Would it be ok with you?

**Comment by fannheyward** [comment]
The schema is defined by Pyright https://github.com/microsoft/pyright/blob/main/packages/vscode-pyright/schemas/pyrightconfig.schema.json
