### ISSUE TITLE
Formatting with autopep8 in virtual environment does not work out-of-the-box

### ISSUE THREAD

**Issue by cosmoswafer** [fannheyward/coc-pyright#891]
What is your recommended workflow to develop python scripts in virtual environment?

I found out that coc-pyright will try to run autopep8 module not the command by default. I need to set the absolute path in the coc-settings.json. If I'm working within a virtual environment, I need to install the autopep8 within that environment otherwise it will show errors about module is not installed. Is it possible to tell coc-pyright to use the command rather than module? And search the $PATH not giving a absolute path?

**What's the output of `:CocCommand pyright.version`**
`[coc.nvim] coc-pyright 1.1.293 with Pyright 1.1.294`

**What's the output of `:CocCommand workspace.showOutput Pyright`**
_Doesn't matter for this issue_

**Comment by fannheyward** [comment]
Try coc-pyright v1.1.295

**Comment by cosmoswafer** [comment]
It works now! Thank you very much!
