### ISSUE TITLE
coc-pyright runs linter for every input in insert mode

### ISSUE THREAD

**Issue by fvdnabee** [fannheyward/coc-pyright#893]
In 1.1.295 coc-pyright spawns a linter process (pylint) for every keystroke in insert mode. This is problematic for python modules where pylint takes >5 seconds to complete. I have a module where pylint takes ~8 seconds and in 1.1.295, my system regularly hits 100% CPU:
![image](https://user-images.githubusercontent.com/1157936/221601831-e9c74ab1-f667-4ecb-9d03-e090e1d5e8ef.png)

In 1.1.284, the linter is only spawned once when the file is saved. Even when I edit the buffer and save the file multiple times in rapid succession, I only find 1 linter process active.

As I don't see much value in linting for every keystroke in insert mode for modules with long linter run times, I would propose to add a config option to opt-out from linting on stdin change. Those with long runtimes can opt-out, those with short runtimes can continue to lint from stdin.  An alternative is to run the linter whenever vim exists insert mode, not whenever the buffer is changed (if that is feasible). If providing an opt-out config setting, then a-per linter setting would be nice; as I assume not all linters suffer from such long run times. Something similar to:
```json
{
	"python.linting.enabled": true,
	"python.linting.pylintEnabled": true,
	"python.linting.pylintStdin": false
}
```

Note #889 might be related.

**What's the output of `:CocCommand pyright.version`**
[coc.nvim] coc-pyright 1.1.295 with Pyright 1.1.295

**What's the output of `:CocCommand workspace.showOutput Pyright`**
Not relevant.

**Comment by fannheyward** [comment]
Thank you for your feedback, will improve this in next release.

**Comment by fannheyward** [comment]
`python.linting.pylintStdin` is added.

**Comment by fvdnabee** [comment]
Just tested coc-pyright v1.1.296 and only see once linter process now. Thanks a bunch Fann :+1: !
