### ISSUE TITLE
Is a SemanticTokenProvider technically possible?

### ISSUE THREAD

**Issue by alexpw** [fannheyward/coc-pyright#899]
Is it feasible to write a `SemanticTokenProvider()` for coc-pyright, similar to other features, like`TypeInlayHintProvider()`?  Has it been attempted, or is a plan for it in the works?

From a naive glance by an outsider, it might be possible to write it.

I'm aware that Pyright does not provide semantic tokens for us, or at least appears not to; however, Pyright also does not provide inlay hints, but coc-pyright ***does***, like Pylance, by leveraging Pyright to build it itself.

Thanks!

**Comment by fannheyward** [comment]
Yes, WIP.

**Comment by fannheyward** [comment]
| Before | After |
|--------|--------|
| <img width="474" alt="截屏2023-04-26 16 04 56" src="https://user-images.githubusercontent.com/345274/234510772-7ea3ce48-d93d-4666-a196-c5883629c839.png"> | <img width="445" alt="截屏2023-04-26 16 06 05" src="https://user-images.githubusercontent.com/345274/234511063-a5d2261e-c5f8-4e7a-adf5-b4637f306f93.png"> |

**Comment by fannheyward** [comment]
`:CocCommand semanticTokens.checkCurrent` to list additional token hi name.
