### ISSUE TITLE
How to use pyright's auto import feature?

### ISSUE THREAD

**Issue by xulongwu4** [fannheyward/coc-pyright#90]
Can you give a bit instruction on how to use pyright's auto import feature with coc-pyright?

**Comment by xulongwu4** [comment]
For anyone coming to this issue, I found [a very good illustration](https://ibb.co/B6MJDBM) of the auto-import behavior in vscode. Some very relevant discussions are [here](https://github.com/microsoft/pylance-release/issues/28).

**Comment by roblevy** [comment]
I still don't know how to use the auto-import feature, after watching the gif and reading the discussion you posted. Is it actually possible to get auto-import?

**Comment by jeanlucthumm** [comment]
Can we reopen this

**Comment by fannheyward** [comment]
Set `"python.analysis.diagnosticMode": "workspace"` in your coc-settings.json, you will get auto-import suggestions.

**Comment by davidonlaptop** [comment]
YMMV but it seems that the default indexing isn't deep enough for auto-import to work when the function or class you import is not at the root level, so here's what I had to put in my settings.json for it to work properly:

```json
{
  "python.analysis.autoImportCompletions": true,
  "python.analysis.indexing": true,
  "python.analysis.packageIndexDepths": [
    {
      "name": "",
      "depth": 3
    },
    
    ]
}
```
