### ISSUE TITLE
coc-pyright is using buffers irresponsibly

### ISSUE THREAD

**Issue by jmbeck15** [fannheyward/coc-pyright#905]
I've been noticing that my buffer number increases really fast without me even using them. I rely on buffers quite a lot to switch between files, and it's really annoying when I open a second file and it's loaded into buffer 603.

I finally tracked down the issue to coc-pyright. When I disable the plugin, the buffers behave as I expect. I can't figure out why this plugin is increasing the buffers so quickly, but it seems like every time there's a window of information displayed, it uses and destroys a buffer to do so. Is there any way to avoid this behavior?

I'm using nvim 0.7.2.

**What's the output of `:CocCommand pyright.version`**
```
[coc.nvim] coc-pyright 1.1.298 with Pyright 1.1.300
```

**What's the output of `:CocCommand workspace.showOutput Pyright`**
```
Workspace: /Users/jmbeck/development
Using python from /usr/local/bin/python

[Info  - 7:37:53 PM] Pyright language server 1.1.300 starting
[Info  - 7:37:53 PM] Server root directory: /Users/jmbeck/.config/coc/extensions/node_modules/coc-pyright/n
[Info  - 7:37:53 PM] Starting service instance "development"
[Info  - 7:37:53 PM] No configuration file found.
[Info  - 7:37:53 PM] No pyproject.toml file found.
[Info  - 7:37:53 PM] Setting pythonPath for service "development": "/usr/local/bin/python"
[Warn  - 7:37:53 PM] stubPath /Users/jmbeck/development/typings is not a valid directory.
[Info  - 7:37:53 PM] Assuming Python version 3.10
[Info  - 7:37:53 PM] Assuming Python platform Darwin
[Info  - 7:37:53 PM] Searching for source files
[Info  - 7:37:54 PM] Found 173 source files
```

**Comment by fannheyward** [comment]
> every time there's a window of information displayed, it uses and destroys a buffer to do so

Can you post a screenshot? Maybe the progress notifications, try `notification.statusLineProgress` to `true` in your coc-settings.json.

**Comment by jmbeck15** [comment]
I'm not sure what to show here. In the steps below, I opened an empty file `example.py`.

This image is the "window of information" that I see pop up; I'm guessing this is rendered in a buffer, but I have no idea.
<img width="331" alt="image" src="https://user-images.githubusercontent.com/3802179/229277064-d362f4e1-346d-4cd5-b525-c18604255a94.png">

Next, I open another file with `:e test.py`, and list the buffers with `:ls`.
<img width="362" alt="image" src="https://user-images.githubusercontent.com/3802179/229276780-8a563258-1ccf-4213-8be3-c7826312d54d.png">

The `test.py` file shouldn't be loaded in to 4, it should be loaded into 2. That's why I'm assuming buffers are being used in the background.

I tried writing `"notification.statusLineProgress": true` into the file opened by `:CocConfig`, but it didn't change behavior.

**Comment by kylemacfarlane** [comment]
I have the same problem and this is the only Google result. I have also narrowed it down to Pyright but I don't use coc-pyright, I'm using nvim-lspconfig.

If I do `:buffers!` I can see there's loads of random Python files open in unlisted buffers.

I use telescope.nvim as my fuzzy finder and I think the preview feature in Telescope is causing Pyright to run but disabling the preview doesn't fix it so I'm not sure. I also find that if I wait a few seconds before hitting enter in Telescope then the problem never occurs, which maybe implies it's some async background task that gets cancelled before it's cleaned up.

Are you also using telescope.nvim?

**Comment by kylemacfarlane** [comment]
I fixed my problem by setting `diagnosticMode` to `openFilesOnly` in nvm-lspconfig but it looks like coc-pyright defaults to that already?

When run in `workspace` mode it seems like Pyright will open any .py files with errors into an unlisted buffer.

**Comment by fannheyward** [comment]
@jmbeck15 with `  "notification.statusLineProgress": true` in my coc-settings.json, I can't reproduce this

<img width="317" alt="截屏2023-04-03 15 34 39" src="https://user-images.githubusercontent.com/345274/229441967-d93274c7-ab34-416b-b76d-7aef73505df5.png">

**Comment by fannheyward** [comment]
I think I found the issue.

After some floating windows opens, the buffer number is increased. Many plugins use floating/popup windows to work, for example coc.nvim uses floating to show hover document, completion suggestions, telescope-nvim uses them for files browsing.

I think it's not coc-pyright or coc.nvim's issue, but nvim/vim, because vim treats these floating window as buffers and assign a buffer number to theme.

**Comment by jmbeck15** [comment]
@fannheyward thanks for looking into this so quickly. I'll ping the Neovim people.

Is there a way to disable floating windows? I tried `"coc.preferences.floatActions": false` in my CocConfig file, but it didn't help.
