### ISSUE TITLE
 How can we set the `pyright.inlayHints` color?

### ISSUE THREAD

**Issue by joamatab** [fannheyward/coc-pyright#922]
at the moment the inliay hints have the same color as my text, so it's hard to distinguish them from the actual code

How can we set the `pyright.inlayHints` color?

**Comment by fannheyward** [comment]
Check `:h coc-inlayHint`, you can change the hi group:

Change highlight group:~

- CocInlayHint
- CocInlayHintType
- CocInlayHintParameter
