### ISSUE TITLE
How to use local configuration to override global coc-settings for python formatting?

### ISSUE THREAD

**Issue by gwjulian** [fannheyward/coc-pyright#923]
I have a flask project where imports should not be sorted.
I solved this by setting
```
{
  "python.formatting.autopep8Args": ["--ignore", "E402"]
}
```
on `coc-settings.json`, but, this disables the import sorting globally, and I need to disable it only on the current flask project

**What's the output of `:CocCommand pyright.version`**

coc-pyright 1.1.304 with Pyright 1.1.304
**What's the output of `:CocCommand workspace.showOutput Pyright`**

Workspace: d:\Universidad\Semestre 13\virtus\projects\bps
Using python from C:\Users\Julian\AppData\Local\Programs\Python\Python310\python.EXE

[Info  - 20:41:38.866] Pyright language server 1.1.304 starting
[Info  - 20:41:38.866] Server root directory: C:\Users\Julian\AppData\Local\coc\extensions\node_modules\coc-pyright\node_modules\pyright/dist/
[Info  - 20:41:38.869] Starting service instance "bps"
[Info  - 20:41:38.882] Setting pythonPath for service "bps": "C:\Users\Julian\AppData\Local\Programs\Python\Python310\python.EXE"
[Info  - 20:41:38.882] Loading configuration file at d:\Universidad\Semestre 13\virtus\projects\bps\pyrightconfig.json
[Info  - 20:41:38.924] Assuming Python version 3.10
[Info  - 20:41:38.924] No include entries specified; assuming d:\Universidad\Semestre 13\virtus\projects\bps
[Info  - 20:41:38.927] Auto-excluding **/node_modules
[Info  - 20:41:38.927] Auto-excluding **/__pycache__
[Info  - 20:41:38.928] Auto-excluding **/.*
[Warn  - 20:41:38.928] stubPath d:\Universidad\Semestre 13\virtus\projects\bps\typings is not a valid directory.
[Info  - 20:41:39.040] Found 6 source files

**Comment by yaegassy** [comment]
You can apply settings on a project basis (workspace). Try writing settings in the `.vim/coc-settings.json` file created when you run the `:CocLocalConfig` command.
