### ISSUE TITLE
Does coc-pyright support global configuration path?

### ISSUE THREAD

**Issue by fred214** [fannheyward/coc-pyright#937]
I want to suppress some diagnostics, I cannot find a global path for `pyrightconfig.json` in [configuration.md](https://github.com/microsoft/pyright/blob/main/docs/configuration.md).

Does `coc-pyright` support global configuration path, such like `~/.config/pyrightconfig.json` ?

Thanks

**Comment by fannheyward** [comment]
You can set them with `python.analysis.diagnosticSeverityOverrides` in coc-settings.json.
