### ISSUE TITLE
leader ac import error

### ISSUE THREAD

**Issue by THtianhao** [fannheyward/coc-pyright#949]
**What's the output of `:CocCommand pyright.version`**
coc-pyright 1.1.310 with Pyright 1.1.311

**What's the output of `:CocCommand workspace.showOutput Pyright`**

Workspace: /Users/toto/Project/MyProject/ai_video_generate
Using python from /Users/toto/Project/MyProject/ai_video_generate/venv/bin/python

```
[Info  - 17:23:45.722] Pyright language server 1.1.311 starting
[Info  - 17:23:45.722] Server root directory: /Users/toto/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/
[Info  - 17:23:45.727] Starting service instance "ai_video_generate"
[Info  - 17:23:45.741] Setting pythonPath for service "ai_video_generate": "/Users/toto/Project/MyProject/ai_video_generate/venv/bin/python"
[Warn  - 17:23:45.747] stubPath /Users/toto/Project/MyProject/ai_video_generate/typings is not a valid directory.
[Info  - 17:23:45.792] Assuming Python version 3.10
[Info  - 17:23:45.905] Auto-excluding /Users/toto/Project/MyProject/ai_video_generate/venv
[Info  - 17:23:45.906] Found 2 source files
```
when I type <leader> ac ,show follow hint
![image](https://github.com/fannheyward/coc-pyright/assets/7608485/4c6f9c99-6c8b-49e5-a72c-73e207885189)
and occur [coc.nvim] Module rope not installed
how do i fix this import error

**Comment by THtianhao** [comment]
哥我才发现你是中国人，交流方便多了，
1.我看他们说自动补全的时候可以自动import，但是我没有。
2.还有就是cocrunaction的时候老是提示repo没安装，但是我在虚拟环境中已经安装了，是不是需要做其他的配置呢？

**Comment by fannheyward** [comment]
1. Pyright 是支持补全时自动 import 的，比如你输入 `redis` 自动补全会有。但并不是全部 module，比如 os 就没有
2. coc-pyright 是通过 `rope` 做的~半自动~补全，效果没那么智能。需要在你当前项目的 python 环境中安装。你看看 `/Users/toto/Project/MyProject/ai_video_generate/venv/bin/python -c "import rope"` 是否OK

<img width="844" alt="image" src="https://github.com/fannheyward/coc-pyright/assets/345274/952f7655-6ac6-47ef-9e31-6c2aafd24c49">

**Comment by fannheyward** [comment]
`rope` 找不到应该是环境不一致 https://github.com/fannheyward/coc-pyright/issues/901

**Comment by THtianhao** [comment]
太激动了，感谢哥的回复！你看哥我pip是安装上的，但是import就找不到，我是哪弄错了吗？
![image](https://github.com/fannheyward/coc-pyright/assets/7608485/14540b39-a839-45a7-a068-2aa3d9a3ff7f)

**Comment by fannheyward** [comment]
<img width="182" alt="image" src="https://github.com/fannheyward/coc-pyright/assets/345274/c63f2bf9-1038-49e6-b184-59eb0bc250b5">

你安装错了，`rope`, 不是 `repo`

**Comment by THtianhao** [comment]
谢谢哥，这种低级错误真的是没脸见人了= =
