### ISSUE TITLE
Unable to handle compilation

### ISSUE THREAD

**Issue by THtianhao** [fannheyward/coc-pyright#950]
哥我又来了
第一行总是出现这个提示（没有写代码也会出现），这个我不确定是不是lsp的问题，请指教哥。
I'm here again
The first line always appears
![image](https://github.com/fannheyward/coc-pyright/assets/7608485/4858d409-c9ab-4e69-bb86-d804871c536f)

**Comment by fannheyward** [comment]
不是 coc-pyright 产生的，目测和 clang 相关，最小化配置排查一下。

**Comment by THtianhao** [comment]
哥我解决了，是因为我再:CocConfig中的languageserver中配置了clang的lsp出错的。谢谢哥
