### ISSUE TITLE
Is there a way to set colors for the hint?

### ISSUE THREAD

**Issue by weishenl6y6n** [fannheyward/coc-pyright#96]

**Comment by yaegassy** [comment]
@weishenl6y6n Hi,

This is possible by adding and adjusting `CocHintSign` settings in `.vimrc/init.vim`.

Please refer to the `coc.nvim` documentation. https://github.com/neoclide/coc.nvim/blob/master/doc/coc.txt

```
CocHintSign						*CocHintSign*

  Default: `hi CocHintSign ctermfg=Blue guifg=#15aabf`

  The highlight used for hint signs.
```
