### ISSUE TITLE
pyright not detecting venv despite setting python.venvPath

### ISSUE THREAD

**Issue by barbarjan** [fannheyward/coc-pyright#966]
**What's the output of `:CocCommand pyright.version`**
[coc.nvim] coc-pyright 1.1.316 with Pyright 1.1.319

**What's the output of `:CocCommand workspace.showOutput Pyright`**
Workspace: /home/jan/Isadre/isadre/testsite
Using python from /home/jan/Isadre/bin/python

[Info  - 8:21:39 AM] Pyright language server 1.1.319 starting
[Info  - 8:21:39 AM] Server root directory: /home/jan/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/
[Info  - 8:21:39 AM] Starting service instance "testsite"
[Info  - 8:21:39 AM] Setting pythonPath for service "testsite": "/home/jan/Isadre/bin/python"
[Warn  - 8:21:39 AM] stubPath /home/jan/Isadre/isadre/testsite/typings is not a valid directory.
[Info  - 8:21:39 AM] Assuming Python version 3.11
[Info  - 8:21:39 AM] Found 37 source files

Hello, despite setting the venv path as in the docs

`{
  "snippets.ultisnips.pythonPrompt": false,
  "python.venvPath": "~/"
}
`

pyright still doesn't detect the packages from the venv. I'm not sure whats going on because the python path points to the venv. (Even after starting nvim from an activated venv terminal)

![image](https://github.com/fannheyward/coc-pyright/assets/76540587/2db9224d-6cd8-4c5e-a5a2-365fbaa69848)

The venv is in my ~ directory:

![image](https://github.com/fannheyward/coc-pyright/assets/76540587/0379fffd-153e-4724-81b4-390bcfcecc40)

I would appreciate your help on the subject, thank you in advance!

**Comment by fannheyward** [comment]
> Using python from /home/jan/Isadre/bin/python

coc-pyright already uses the venv python.

**Comment by barbarjan** [comment]
Hey, thank you for the reply

Yes I see it uses the python from the correct venv, so I don't understand why it says `unable to import selenium` despite it being installed in the venv.

![image](https://github.com/fannheyward/coc-pyright/assets/76540587/dc34e509-aadf-4a5b-b473-3be799f2efb0)

**Comment by fannheyward** [comment]
What's the output of `/home/jan/Isadre/bin/python -c "import selenium"`?

Remove `python.venvPath` in your coc-settings.json and try again.

**Comment by fannheyward** [comment]
Close for now.
