### ISSUE TITLE
Where to place the package

### ISSUE THREAD

**Issue by btobab** [fannheyward/coc-pyright#975]
Environment: win11, vim90
pyright version: 1.1.320
I try to install coc-pyright, but when I type "CocInstall coc-pyright", vim always display downloading sth from https://registry.npmjs.org/coc-pyright/-/coc-pyright-1.1.320.tgz. like this
<img width="722" alt="image" src="https://github.com/fannheyward/coc-pyright/assets/66876429/d5f35966-d927-440b-b487-b6e2361b9374">
Then I try to download the package from browser, and the structure of package is like below:
<img width="453" alt="image" src="https://github.com/fannheyward/coc-pyright/assets/66876429/147ae4bb-e7a6-49b9-ab01-087db99fd52b">
but then I don't know where to place the package, I beg an answer= =

**Comment by fannheyward** [comment]
You don't need to place the extension manually, `:CocInstall coc-pyright` will handle it.

The downloaded package will be located to `~/AppData/Local/coc/extensions`.
