### ISSUE TITLE
Pyright is not using specified formatting provider

### ISSUE THREAD

**Issue by drdavella** [fannheyward/coc-pyright#976]
I am trying to use `black` as my formatting provider but the configuration does not appear to take effect. Instead, it appears that `coc-pyright` is attempting to use `yapf`, which is not installed.

Here's my configuration:
```json
{
    "python.formatting.provider": "black",
    "coc.preferences.formatOnSave": true
}
```

**What's the output of `:CocCommand pyright.version`**
<img width="671" alt="image" src="https://github.com/fannheyward/coc-pyright/assets/2458487/524361df-c43b-4000-a721-52f8663a660e">

**What's the output of `:CocCommand workspace.showOutput Pyright`**
```
Using python from /Users/danieldavella/miniconda3/envs/python-codemod/bin/python

########## active formattor: yapf
execPath:   yapf
moduleName: yapf
args:       --diff,/Users/danieldavella/codemodder-python/codemodder/semgrep.py.ab41782fe9cf7c889ab506746513d5c9.py
########## Formatting with yapf failed
Module 'yapf' not installed.
```

I'm using neovim:
```
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.1/share/nvim"
```

**Comment by fannheyward** [comment]
Can't reproduce, how do you config this? By `:CocConfig`? or `:CocLocalConfig`? Looks like the configurations were overrides. 

Check `:echo CocAction('getConfig', 'python.formatting')`, the `provider` value.

**Comment by drdavella** [comment]
I showed you the result of `:CocConfig` but my `:CocLocalConig` had `yapf` configured. I have no idea how that got there, but thank you so much for the quick response!
