### ISSUE TITLE
Can we have a CocComman `python.setInterpreter` like coc-python does?

### ISSUE THREAD

**Issue by Congee** [fannheyward/coc-pyright#99]
coc-pyright is faaaaaaaaaar better than coc-python speaking of the language server pyright. I really miss the `python.setInterpreter` feature from coc-python. Without it, I have to currently set an absolute python path to the config "python.pythonPath".

**Comment by fannheyward** [comment]
`python.setInterpreter` is ported from vscode-python, it's quit complex, https://github.com/neoclide/coc-python/issues/55, I wouldn't like to add `python.setInterpreter` to coc-pyright.

Instead, coc-pyright will pick the first python interpreter found by `which python`, you can also custom it by `python.pythonPath`.

**Comment by oblitum** [comment]
You can use `coc#config()` to set coc conf dynamically, for example, for coc-pyright I have set this as I use `pyenv`:

```vim
  if !empty($PYENV_VIRTUAL_ENV)
    call coc#config('python', {
    \   'pythonPath': $PYENV_VIRTUAL_ENV . '/bin/python'
    \ })
  endif
```
