### ISSUE TITLE
Cannot perform addImport using selected element(s)

### ISSUE THREAD

**Issue by fannheyward** [fannheyward/coc-pyright#991]
Hi, I'm receiving errors using this functionality in vim 9.0.

Pyright version:
```
[coc.nvim] coc- pyright 1.1.325 with Pyright 1.1.327
```
On the cursor position,  I use the `<Plug>(coc-codeaction-cursor)` command, and receive the expected options:

![image](https://github.com/fannheyward/coc-pyright/assets/22935226/77612a83-5c10-4d42-b02a-633a26e8206e)

However, if I select 1, I get the following error:

```
[coc.nvim] Cannot perform addImport using selected element(s).
```

Could you tell me why its not adding in the import when it correctly identifies the missing module?

_Originally posted by @SuryaThiru in https://github.com/fannheyward/coc-pyright/issues/419#issuecomment-1720433123_

**Comment by fannheyward** [comment]
@SuryaThiru what's the output of `:CocCommand workspace.showOutput Pyright`, some error logs will go here.

**Comment by SuryaThiru** [comment]
Thank you for sharing that command, seems there issue was an unrelated syntax error above the code. I was looking for errors in the `CocOpenLog` and couldn't find any info. Missed the command above in the docs.
